### ISSUE TITLE
Merchant Plant "Single Value" price option does not work

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1004]
### Describe the bug

For the Merchant Plant model, the "Single Value" option for entering price data results in no revenue. Note that the "Hourly" option does work.

![image](https://user-images.githubusercontent.com/27711933/163649476-9013620d-e1c8-4856-a96a-99f9c2074d0d.png)

See workaround solution in this forum post: https://sam.nrel.gov/forum/forum-general/3809

Issue also reported here: https://sam.nrel.gov/forum/forum-general/3068

### To Reproduce

Use the following file for testing. It has two cases, "single value price" with price set to $10/MWh single price that results in no energy market revenue in cash flow, and "hourly prices" with hourly prices set to $10/MWh that results in annual energy market revenue.

[merchant-single-value-bug.zip](https://github.com/NREL/SAM/files/8498788/merchant-single-value-bug.zip)

Both of these cases should result in the same revenue.

### Operating System and Version

Tested in SAM 2021.12.02 r1 on Windows

**Comment by cpaulgilman** [comment]
@sjanzou and @brtietz, can one of you take this one?

**Comment by sjanzou** [comment]
Fixed in ssc pull request https://github.com/NREL/ssc/pull/823

Test file
[SAM_1004.zip](https://github.com/NREL/SAM/files/8778305/SAM_1004.zip)


Note that if percentage of generation exceeds 100 of all enabled revenue streams, then the cleared capacity exceeds the system generation...

**Comment by sjanzou** [comment]
Closed with ssc pull request https://github.com/NREL/ssc/pull/823
