### ISSUE TITLE
Opening 2017.9.5 SAM file in develop results in module inconsistencies

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#101]
[pv_shading.zip](https://github.com/NREL/SAM/files/2447167/pv_shading.zip)

When the attached file is opened in the development version of SAM, it goes through the version upgrade progress.  When you click on the `Module` page, you get the following error:

![image](https://user-images.githubusercontent.com/5658281/46488479-0701b200-c7c0-11e8-8ce1-837da568c176.png)

But, if you search for that module, the `SunPower SPR-X21-335-BLK`, you'll see it in the list:

![image](https://user-images.githubusercontent.com/5658281/46488549-33b5c980-c7c0-11e8-9d20-52d75ec7e53a.png)

The problem is, it doesn't match the properties for the `SunPower SPR-X21-335-BLK` module in SAM 2017.9.5
![image](https://user-images.githubusercontent.com/5658281/46488585-521bc500-c7c0-11e8-8a07-6886fc649573.png)

I believe there are two issues here:
1. Issue with detection of valid module in CEC Library
2. Issue with numerical precision or changes in 6par coefficient calculator.

**Comment by dguittet** [comment]
The new version of the CEC module library lists the module as Sunpower rather than SunPower. Since there are several modules listed as Sunpower, the Library's FindEntry function was modified to use case-insensitive comparison.

**Comment by dguittet** [comment]
It would actually be better to enforce case consistency for names between different versions of the CEC module library.
