### ISSUE TITLE
Upgrade SAM development to visual studio 2022

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1013]
While visual studio 2019 is still supported, there are a number of features from visual studio 2022 we'd like to use in SAM development. Upgrade the build pipeline prior to the fall release. This likely includes updating CMake files and similar.

**Comment by cpaulgilman** [comment]
Windows build instructions as of this commit are for Visual Studio Community 2022: https://github.com/NREL/SAM/wiki/Windows-Build-Instructions/ebcbfb953e955211f104e78908f1baf0f00afa49

The only change required in my testing was this one: https://github.com/NREL/ssc/pull/852

We can close this issue once the team has had a chance to review the new Windows build instructions

**Comment by sjanzou** [comment]
> Windows build instructions as of this commit are for Visual Studio Community 2022: https://github.com/NREL/SAM/wiki/Windows-Build-Instructions/ebcbfb953e955211f104e78908f1baf0f00afa49
> 
> The only change required in my testing was this one: [NREL/ssc#852](https://github.com/NREL/ssc/pull/852) (also requires changing GTest Windows environment variables as per the instructions).
> 
> We can close this issue once the team has had a chance to review the new Windows build instructions

This update fails to build the debug version of the Test project and the instructions mentioned only build the Release version of wxWidgets which prevents the building of the debug version of SAM using Visual Studio per mixing of different versions of the CRT (C Runtime Library) per https://stackoverflow.com/questions/14714877/mismatch-detected-for-runtimelibrary

**Comment by brtietz** [comment]
@sjanzou Why did we bump the cmake version? What is the _minimum_ version required by whatever is driving the upgrade? wxWidgets only requires 3.0 https://github.com/wxWidgets/wxWidgets/blob/e9d299d92ccd9688b81a13b13ca17e53fce32fbd/CMakeLists.txt#L10 and googletest 3.5.

It looks like 3.24 is a release candidate at the moment, is there a reason 3.23 doesn't work?

**Comment by brtietz** [comment]
> @brtietz @sjanzou It looks like GitHub Actions assumes the latest version of CMake unless you explicitly specify a CMake version: https://github.com/marketplace/actions/actions-setup-cmake

Good find, I'm glad someone automated that, I was just installing them in the runners using apt-get. I'll push the changes to GH Actions to these branches. It might take 2 or 3 attempts to get it to work.

**Comment by cpaulgilman** [comment]
@brtietz, @sjanzou I think this issue is ready to close. Any objections?

**Comment by sjanzou** [comment]
> @brtietz, @sjanzou I think this issue is ready to close. Any objections?

I have tested and built wxWidgets-3.2.0 on CentOS 7 and MacOS 12.5; so, no objections from me…. Please close at your convenience.

**Comment by cpaulgilman** [comment]
Windows build instructions are updated for Visual Studio 2022 Community: https://github.com/NREL/SAM/wiki/Windows-Build-Instructions
