### ISSUE TITLE
SolarAnywhere timestamps in file converter macro - minute at beginning instead middle of interval

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1016]
### Describe the bug

The solar resource file converter macro pulls minute values from the SolarAnywhere weather file (e.g., minute value of "00" for a row with original timestamp "01/01/2021 11:00") and uses that to populate the resulting SAM weather file. 

For 60 minute interval SolarAnywhere data, this results in a SAM-formatted weather file with a minute column full of zeros. My understanding of the solar position calculations in SAM, and what is represented in SolarAnywhere data [1], is that it would be better to either leave the minutes column out for 60 minute interval data, or to calculate the minute that is the midpoint of the interval (e.g., 30 for 60 minute interval data).

This same issue should apply to sub-hourly SolarAnywhere as well. Calculating the midpoint minute should be a more robust solution. 

Tagging @kwagnercpr, as they submitted a recent issue related to Clean Power Research SolarAnywhere data.

Here is the relevant code, I think:

https://github.com/NREL/SAM/blob/062a09e263f34b32846c5d801ae23619f60092d9/deploy/runtime/macros/Solar%20Resource%20File%20Converter.lk#L523-L550

### Additional context

[1] https://www.solaranywhere.com/support/data-fields/resolution/#data-averaging

**Comment by williamhobbs** [comment]
I'll Add that I think this issue could apply to pvgis files as well, as minutes appear to be generated similarly in the macro, but I haven't worked with pvgis files before.

**Comment by KWagnerCPR** [comment]
What Will reported here is correct. 

Using the example of “01/01/2021 11:00”, SAM would be using the sun position at 11:00 based on the converted SolarAnywhere file, where the sun position at 10:30 would be more representative of the average irradiance condition over the hour. I like Will's suggestion to remove the "minute" column from the converted SolarAnywhere files. 

Thanks!

@cpaulgilman

**Comment by cpaulgilman** [comment]
@KWagnerCPR, @williamhobbs Thanks for this contribution!

I like Will's approach of explicitly setting the Minute value to 30 for hourly data. This makes it clear what timestamp SAM will use for the sun position calculation. By default, for data with no Minute column, SAM's weather file reader code does [set the Minute value to the midpoint of the time step](https://github.com/NREL/ssc/blob/b130bde3f3fbe8a825891bc994983b8339bc2c91/shared/lib_weatherfile.cpp#L1452), but the only way to know that is to read the SAM documentation or explore the code.

One question for Kristin: Can you confirm that for subhourly SolarAnywhere data, replacing the minute value with the midpoint of the time step is correct?

**Comment by KWagnerCPR** [comment]
Thank you @cpaulgilman. I can confirm that for sub-hourly SolarAnywhere data, replacing the minute value with the midpoint of the time step is correct. 

I.e. Using the example of 11:15:00, the minutes should actually be 07:30.

**Comment by williamhobbs** [comment]
@KWagnerCPR - Just to clarify your example, you're referring to the original SolarAnywhere format timestamp of 11:15:00, which would be converted to 11:00:00 in the current version of the SAM file converter macro, should instead be converted to 11:07:30 for use in SAM. Is that correct?

**Comment by KWagnerCPR** [comment]
@williamhobbs With Solaranywhere 15-min resolution data, the timestamp of 11:15:00 would currently be converted to hour: 11, minute: 15, seconds: 00. It should be converted to hour: 11, minute: 7, seconds: 30.

**Comment by williamhobbs** [comment]
I think this was closed with https://github.com/NREL/SAM/pull/1019. Should I close this issue out?
