### ISSUE TITLE
vdcmax from the CEC inverter list is not the inverter maximum DC voltage

### ISSUE THREAD

**Issue by cwhanse** [NREL/SAM#1020]
### Describe the bug

The CEC grid supporter list includes a field titled "Voltage Maximum". This quantity is the maximum DC voltage at which inverter efficiency is measured, which is not the same as the maximum input DC voltage. For example, for inverter "SMA America STP 33-US-41 [480V]", Voltage Maximum is given as 800Vdc, but the inverter maximum DC input voltage is 1000 Vdc, per the [datasheet](https://d3g1qce46u5dao.cloudfront.net/data_sheet/stpcore1_dus182619w.pdf).

Private communication with SMA America informs that the inverter maximum DC input voltage is not requested by the CEC.

The problem is with how SAM uses "Voltage Maximum" to suggest and check string length. For example, [this line](https://github.com/NREL/SAM/blob/3d14fb9fe5bf367ba51041e639e64195185793df/deploy/runtime/macros/Flat%20Plate%20PV/System%20Sizing.lk#L550)

```
modules_per_string_max = floor( inverter.vdcmax / voc_max_design );
```

An alternative is to assume that the maximum DC input voltage is 125% of "Voltage Maximum" (private communication with SMA) but I don't know if this rule of thumb works for all inverters. Another alternative is to remove the string length calculations.

**Comment by cpaulgilman** [comment]
Thanks @cwhanse, this is helpful information.

When we build SAM's inverter library from the [CEC Inverter Workbook](https://solarequipment.energy.ca.gov/Home/DownloadtoExcel?filename=InvertersList), we interpret the "Voltage Minimum" and "Voltage Maximum" from the workbook as Vmppt_min and Vmppt_max. We also set Vmppt_max = Vdc_max.

As you point out, these are the  voltages at which the efficiencies reported in the workbook are measured and may be different from the input voltage range ratings reported on the manufacturer datasheet.

In the SAM user interface (and sizing macro that you reference above), Vmppt_max is used to suggest a number of strings when the user chooses the automatic sizing option ("Estimate Subarray 1 configuration" on the System Design page).

In SSC, Vmppt_min and Vmppt_max are used to limit the inverter input voltage and calculate inverter voltage clipping losses.

I looked at a few other inverters, and do not see a consistent relationship between the maximum voltage in the CEC workbook and Vmppt_max reported on the datasheet. I think the best solution for now would be to make the MPPT voltage range editable in SAM. We could use the 125% of Vdcmax rule of thumb as you suggest, or continue using our current approach, but make it possible for the user to enter the correct value from the datasheet.

**Comment by williamhobbs** [comment]
@cpaulgilman, is it exceeding Vmppt_max that triggers this warning?

![image](https://user-images.githubusercontent.com/45701090/165760084-d6c8f608-da04-47d9-9690-e3900635020d.png)

If so, I suggest changing the warning message to something like "Subarray 1 string voltage exceeds the inverter maximum MPPT voltage at reference conditions. Consider using fewer modules per string."

Unrelated to this issue, I just noticed that the GCR footnote should probably be above the "Electrical Sizing Information" section break and at the bottom of the "Tracking and Orientation" section.

**Comment by williamhobbs** [comment]
@cwhanse, shouldn't Vmppt_max also be considered in string length calculations? Vdc_max should always be a hard constraint, but a simple sizing calculation (like what is done the the GUI) is probably best done with Vmppt_max. A more rigorous optimization with timeseries analysis _could_ evaluate string lengths that exceed Vmppt_max at reference conditions but still stay below Vdc_max as appropriate.

**Comment by cwhanse** [comment]
> shouldn't Vmppt_max also be considered in string length calculations? 

Yes, it's a factor and I'm not saying it shouldn't play a role. The problem is that Vdc_max is not equal to Vmppt_max as SAM is currently assuming.

**Comment by williamhobbs** [comment]
Understood. I agree (on all points). 

I thought you were suggesting that _only_ the editable maximum DC input voltage (editable Vdc_max) be used for string length calculations. 

Thanks for clarifying for me.

**Comment by adriesse** [comment]
This just popped up on my github notifications, so sorry if my comments are a bit late.

Vmax is related to safety rather than performance.  Therefore, I believe the warning should appear when Voc exceeds Vmax.
