### ISSUE TITLE
NSRDB advanced download sets time zone to 0 for full-disc and typical year

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1022]
### Describe the bug

When downloading weather through the advanced download, typical year files (TGY, TMY, TDY) and fill-disc files have time zones of GMT 0 instead of the local time zone.

### To Reproduce

1. Go to the advanced download tool in the detailed PV model
2. Find a location
3. Select a full-disc weather file and/or a typical year weather file and download them
4. See that the resulting time zone is GMT 0

### Expected behavior

I expected the time zone to match the local time zone offset, as it does for other weather file types through the standard and advanced download tools.

### Operating System and Version

 - OS: Windows 10
 - Version: SAM 2021.12.02 and 2021.12.02r1

### Additional context

- Downloading the default TMY file through the standard download tool (not the advanced one) works as expected. 
- It looks like the issue should have been fixed in [#609](https://github.com/NREL/SAM/pull/609)? 
- Maybe the issue for full-disc was fixed in [#950](https://github.com/NREL/SAM/pull/950)?

**Comment by brtietz** [comment]
Thanks for reporting! This was fixed in #950 and will be released with patch 2 in May. I don't think there's an easy way to manually patch the nsrdb calls since in a cpp file instead of an lk file.

Closing this since it's a duplicate.

**Comment by brtietz** [comment]
Upon further investigation, this is solved for full-disc but not psm-tmy. Reopening and adding to patch.
