### ISSUE TITLE
AC capacity factor for PV

### ISSUE THREAD

**Issue by n8blair** [NREL/SAM#103]
Sarah Kurtz and other users would benefit from an additional output which calculates the PV capacity factor (by year) based on the AC capacity of the system.  Currently, it's based on DC capacity and some analysts want it based on AC capacity to be aligned with other technologies.

**Comment by nickdiorio** [comment]
Submitted pull request: https://github.com/NREL/ssc/pull/199

**Comment by janinefreeman** [comment]
Merged pull request
