### ISSUE TITLE
Receiving ITC over multiple years

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1038]
There are a number of use cases where a user might want to receive the ITC in years in addition to the first year of the project.

Behind the meter cases are discussed here: https://www.energy.gov/sites/default/files/2021/02/f82/Guide%20to%20Federal%20Tax%20Credit%20for%20Residential%20Solar%20PV%20-%202021.pdf

Front of the meter here: https://sam.nrel.gov/forum/forum-general/3368-itc-normalization.html

Create an additional input option that allows the user to cap the amount of the ITC received in a given year, with additional values spread across additional years (potentially also subject to a cap).

Also consider making direct cash incentives like IBI, CBI, available on an annual basis: https://sam.nrel.gov/forum/forum-general/4031

**Comment by brtietz** [comment]
SETO webinar 9/27 confirmed this is still relevant post IRA. Homeowners still need sufficient tax liability and are not eligible for direct pay like businesses.

**Comment by sjanzou** [comment]
@cpaulgilman, @brtietz Please review the following assumptions for implementation based on inputs:
1. we are not checking that the user enters 10 years of ITC distribution but then has 5 year macrs and then only first five years reduces depreciable basis if checked.
2. checking that the sum of all the schedule entries is less than 100% for the ITC percentage
3. Max value only on percentatage and not on fixed amount option.

**Comment by brtietz** [comment]
I agree with 1 & 2. For (3) - will the units of the maximum continue to be in $? If so then that seems fine to me. Note that the maximum could vary year to year if household income changes.

**Comment by cpaulgilman** [comment]
This seems fine to me.

I think the maximum limit for the Percentage (%) option should continue to be in dollars.

**Comment by sjanzou** [comment]
Input variable changes addressed in ssc pull request https://github.com/NREL/ssc/pull/901 and SAM pull request https://github.com/NREL/SAM/pull/1206
