### ISSUE TITLE
Add Ability to Input Measured Cell Temperature

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#106]
We'd like to add the ability for users to directly input measured cell temperature into the PV performance model and bypass the cell temperature models that are included in SAM.

**Comment by cpaulgilman** [comment]
A related request is to allow users to specify a custom cell temperature equation, such as one for floating PV arrays. Quoting from https://sam.nrel.gov/node/80657:

```
I'm trying to use SAM to model a floating PV system and I wanted to change the equation SAM uses to calculate cell temperature. The equation found in the literature is rather simple and considers ambient temperature, irradiance and wind speed something between the lines of tcell = a*ambient temperature + b*irradiance + c*wind speed.

Is there a way to modify the way it is calculated to a user input equation?
```

**Comment by adriesse** [comment]
I was just about to give this issue a thumbs-up, :+1: but then discovered I couldn't because I had already done so!

**Comment by mjprilliman** [comment]
This has been implemented in ssc for PySAM/SDK usage for the upcoming release. Leaving this issue open and updating the milestone for future UI implementation

**Comment by mjprilliman** [comment]
Closing per https://github.com/NREL/ssc/pull/1071, outstanding work moved to #850
