### ISSUE TITLE
Grid interconnection limit doesn't impact monthly_energy

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1064]
### Describe the bug

Monthly energy (`monthly_energy`, AC energy (kWh/mo)) is not affected by setting a grid interconnection limit. It appears that this output is a gross value, but is not labeled as such. 

### To Reproduce

1. Run a model without an interconnection limit. 
2. Enable an interconnection limit that is lower than peak output of the system
3. Compare results.

(see screenshot below)

### Expected behavior

Following naming convention of AC energy outputs, I would expect the monthly AC energy to be _after_ the interconnect limit has been applied. 

### Screenshots

![image](https://user-images.githubusercontent.com/45701090/171745726-1256ae1b-c54c-488d-b9e9-d0c9eea81560.png)

### Operating System and Version

 - OS: Windows
 - Version: SAM 2021.12.2r1

**Comment by brtietz** [comment]
Short term fix in https://github.com/NREL/ssc/pull/983

To truly fix this, we have to add monthly_energy to cmod_grid as an inout, and that's a release-only change. Additional considerations from Paul:

> Related to this is the confusion that labels for time series outputs like "system power before grid curtailment" and "system power before grid interconnect" cause: It might be best to report a gross and net value, and report the losses as kW values instead of reporting progressively smaller system power values. To do that we would have to decide what "gross" means for each technology, e.g., before or after AC and other transformer losses for a PV system.

**Comment by brtietz** [comment]
Note for future reference: we implemented the curtailment with the progressively smaller system values in order to support the financial calculations for curtailment revenue.
