### ISSUE TITLE
Tooltips for PV Uncertainty 

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#1080]
Detailed tooltips needed for PV Uncertainty form for PVWatts and Detailed PV configurations
![image](https://user-images.githubusercontent.com/6498311/175008321-55b6e4e2-f740-4749-a147-15a287eed64a.png)

Update in SAM repo pvuncertainty.cpp lines 101-113
![image](https://user-images.githubusercontent.com/6498311/175008632-2041f472-9e6e-4dd8-b6e1-800d6ffbc85c.png)

**Comment by cpaulgilman** [comment]
Use code similar to setting the simulation buttons based on technology:

```
case 4:
     if ((m_case->GetTechnology()=="PVWatts") || (m_case->GetTechnology()=="Flat Plate PV"))
          id ="pvuncertainty"
     else
          id = "p50p90"
```
