### ISSUE TITLE
Sign (negative) ignored for 1 axis tilt

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1087]
### Describe the bug

If a user assigns a negative tilt for a 1 axis tracking system it appears to be treated as a positive tilt. 

### To Reproduce

1. Start a detailed PV model
2. In System Design, select "1 Axis" and assign a negative tilt value (e.g., -10)
3. Simulate
4. See the notice that describes the tilt as positive
5. Compare results (energy, surface tilt and surface azimuth) with a similar case using a positive tilt and see that results are identical.

### Expected behavior

One of the following, or similar:
- Issue an error message about negative values being invalid
- Issue a notice message about negative values automatically being converted to positive
- Model the system with the described geometry but with a notice (e.g., model tilt = -10 and azimuth =180 as tilt = 10 and azimuth = 0)

### Screenshots

Notice that occurs when assigning a _negative_ tilt (note that tilt angle in the notice is _positive_):
![image](https://user-images.githubusercontent.com/45701090/177576466-11d0128f-cc32-48df-88f0-6d2efbe341f2.png)

Results with tilt = 10, azimuth = 180:
![image](https://user-images.githubusercontent.com/45701090/177575730-b40cb34c-1c91-4b5f-b0d1-7d0b8b8b1544.png)

Results with tilt = -10, azimuth = 180 (same as above, not what I expected):
![image](https://user-images.githubusercontent.com/45701090/177575878-14bf2ff6-be54-4071-ba9e-603cb6df52a9.png)

Results with tilt = 10, azimuth = 0 (what I expected -10, 180 to look like):
![image](https://user-images.githubusercontent.com/45701090/177576016-f337bcf2-261d-4da0-b508-7d74113c9e4e.png)

Inputs browser for reference:
![image](https://user-images.githubusercontent.com/45701090/177576154-466483b6-654b-4615-b0e8-43fbe781e354.png)

### Operating System and Version

 - OS: Windows
 - Version: SAM 2021.12.2 r2 [e.g. SAM 2020.2.29 r3]

Tagging @kanderso-nrel and @kurt-rhee, since they brought up this issue here https://github.com/pvlib/pvlib-python/issues/1471.

**Comment by kanderso-nrel** [comment]
Thanks @williamhobbs, I was just looking into this myself.  I believe this is the relevant line of code in SSC: https://github.com/NREL/ssc/blob/1ed56222b4f4a5991eaef697dac2af7a929401c3/shared/lib_pv_io_manager.cpp#L339

```cpp
        if (cm->is_assigned(prefix + "tilt")) tiltDegrees = fabs(cm->as_double(prefix + "tilt"));
```

As far as "expected behavior", I'd favor the first of @williamhobbs's suggestions (Issue an error message about negative values being invalid).  This would also be consistent with the constraint `"MIN=0,MAX=90"` listed in `_cm_vtab_pvsamv1` for `subarrayN_tilt`.

**Comment by williamhobbs** [comment]
The error message is also my preferred solution. Changing user inputs to give them either result, even with a notice, seems problematic.
