### ISSUE TITLE
Ground interference occuring for 1-axis bifacial

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/SAM#1088]
The default value for the bifacial input "Ground clearance height" (for the spe, cec, 6par and mlm models), result in negative ground clearance heights during simulation (e.g., at 45 deg tilt)

Changing from the current default of 1 m to 2 m would give a ground clearance of 0.34 m at 90 deg tilt (vertical), for example.

1. If a bifacial module, should there be a check in the UI Callbacks for ground interference at vertical orientation?
2. Should the "Ground clearance height" just be automatically increased so the ground clearance equals zero at vertical if it would be less than zero?
3. If a bifacial module, should an error be raised (in lib_pv_io_manager.cpp?) if there's ground interference at vertical?

**Comment by Matthew-Boyd** [comment]
@janinefreeman Should this be a group discussion? Or do you just want to make a decision?

**Comment by mjprilliman** [comment]
@Matthew-Boyd I might advocate for handling it in the same way as wind turbine ground interference. There's red warning text that appears if the rotor diameter causes interference with the specified hub height, but the simulation still runs. @cpaulgilman @janinefreeman might have different ideas though. 

![image](https://user-images.githubusercontent.com/54449384/177822734-6dc42df2-eccf-4a78-bebe-7a8e6524b853.png)

**Comment by cpaulgilman** [comment]
For the wind power model, I can't think of a situation where you'd want the hub height to be less than the blade length -- seems like an SSC error would be appropriate in addition to the red UI text. This NREL [publication from 2009](https://www.nrel.gov/docs/fy09osti/44439.pdf) lists some county ordinances with minimum ground clearance requirements of either 25 or 75 feet. This [2019 European study](https://www.researchgate.net/publication/334173853_Impact_of_Ground_Clearance_on_Wind_Farm_Performance) explores modeling of ground clearance effect on turbulence.
