### ISSUE TITLE
Stand Alone Battery UI form bugs

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1099]
### Describe the bug

Several dispatch methods for the stand alone battery allow you to choose "discharge to grid" when the algorithm that doesn't support it.

### Expected behavior

Discharge to grid behavior should match PV for BTM algorithms.

### Screenshots

![image](https://user-images.githubusercontent.com/5530592/180494608-1dacdc7d-127e-4b44-9a8a-98c9b262bff2.png)

### Operating System and Version

 - Version 2021.12.02 - at least r2, maybe earlier.

**Comment by brtietz** [comment]
Second bug, installation cost box is blue when it shouldn't be:

![image](https://user-images.githubusercontent.com/5530592/180503746-f0b8207f-5195-4bf7-b99c-df866543de04.png)

**Comment by mjprilliman** [comment]
Noticed the second bug when working on marine energy, will carry over the fix. Will dig into the first bug as well.
