### ISSUE TITLE
Link to 2021 Cambium Data

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1104]
The merchant plant defaults to calling the 2020 cambium data. 2021 provides additional scenarios, such as 95% renewables by 2035. Add this to the data download options.

Also consider including "busbar" data in addition to "end use" data.

Update LK sample scripts with any changes to Cambium API calls in SAM.

**Comment by cpaulgilman** [comment]
@brtietz The [Cambium Scenario Viewer](https://scenarioviewer.nrel.gov/?mode=browse) now provides access to the Cambium 2020, 2021, and 2022 projects. A couple of options:

1. Update to Cambium 2022.
2. Provide access to all three projects (assuming they all use the same structure, which initial tests suggest they do).

Do you have a preference?

I don't think there is a way to automatically get a list of available projects, so we would have to update this manually with each SAM release.

**Comment by brtietz** [comment]
I have a slight preference for (1). This encourages people to use the most up-to-date data, and folks can always manually work around it if they need the older data for some reason.
