### ISSUE TITLE
Equations error on develop

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1114]
Opening any detailed PV or PV+Battery configuration in the SAM-private config on develop generates the following equations error:

![image](https://user-images.githubusercontent.com/5530592/182201380-132df72a-3bba-4c99-a9d5-51e4669e2fdf.png)

Not on patch/2021.12.02r2, works fine in SAM OS

**Comment by sjanzou** [comment]
@brtietz , could you please clean and rebuild SAM from Develop? I just built and ran PV-Battery / commercial and Photovoltaic / Merchant Plant without issue from VS2022 and from the \SAM-private\build_windows\deploy\x64 folder directly:
![image](https://user-images.githubusercontent.com/6498311/182326331-774730bb-4952-4943-9174-85380d97c781.png)

**Comment by sjanzou** [comment]
@brtietz , if you ran from SAM-private\deploy\x64, then that is an old build and that folder is no longer created. 
Could you please test a clean clone and build? thanks!

**Comment by brtietz** [comment]
Yes, deleting and re-cloning sam-private worked. I missed that in the upgrade instructions.
