### ISSUE TITLE
Generic system no financial fails in release branch

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#112]
The Generic System - No Financial Model fails in the current release branch:

![image](https://user-images.githubusercontent.com/5658281/47168223-95485e80-d2bd-11e8-8a54-b5690216bd58.png)

![image](https://user-images.githubusercontent.com/5658281/47168258-abeeb580-d2bd-11e8-8c85-3396b33216e0.png)

**Comment by janinefreeman** [comment]
Did a merge into the release branch fail? Some of these bugs are looking familiar... but maybe I'm remembering wrong!

**Comment by nickdiorio** [comment]
This was slightly different.  There were some issues with some defaults, and some outstanding issues that were caused by not checking if the system was lifetime or not with no-financial.  Should be fixed now, though the defaults all need to be updated.
