### ISSUE TITLE
Loss diagram is cut-off at right side

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/SAM#1122]
The "Losses" diagram cuts-off long label text at the right side. The allowable width of the diagram needs to be increased. This is especially a problem with the new bifacial losses.

**Comment by sjanzou** [comment]
@Matthew-Boyd, could you please provide a screenshot or a SAM project file to illustrate the issue? Thanks!

**Comment by Matthew-Boyd** [comment]
You can start to see it here. I've changed the shown bifacial losses so I don't have a better example at the moment, but I think I have seen more of a cut-off with larger systems (wider arrows). Since I've changed the shown losses, this might not be as much of a priority anymore. Thanks for taking a look!
![image](https://user-images.githubusercontent.com/30417543/183094645-2e748dad-55ab-4616-9c70-f9faedf8c629.png)

**Comment by sjanzou** [comment]
Project file that demonstrates issue SAM_1122.sam 
[SAM_1122.zip](https://github.com/NREL/SAM/files/9437827/SAM_1122.zip)

![image](https://user-images.githubusercontent.com/6498311/187027717-b89e9d74-3336-47c0-b339-3f5ed9de7b57.png)

**Comment by sjanzou** [comment]
Updated and fixed text width max in SAM pull request #1139 

![image](https://user-images.githubusercontent.com/6498311/187028930-f8cf12ba-fab8-4019-ac0a-2f1f1e5ae7a9.png)
