### ISSUE TITLE
Change Price Signals Dispatch to Utility Rate Dispatch

### ISSUE THREAD

**Issue by n8blair** [NREL/SAM#1123]
### Is your feature request related to a problem? Please describe.

The term "price signals" is confusing.  It could be BTM utiltiy rate signals (which it is) or it could be from real-time or day-ahead market data if front of meter. 

### Describe the solution you'd like

I think we could change the title to "Utility Rate" dispatch option which is specific and less confusing.

### Describe alternatives you've considered

discussion of other options and how it links to other dispatch options to make sure nothing else is confusing.

### Additional context

discussed at SAM meeting on 8/8/22

**Comment by cpaulgilman** [comment]
Consider "retail electricity rate".
