### ISSUE TITLE
Hard crash of CSP linear Fresnel molten salt in release branch

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#113]
When you build and run the ssc and SAM release branches, the default CSP linear Fresnel molten salt - Commercial case hard crashes when you click Simulate.

**Comment by Matthew-Boyd** [comment]
Addressed with commit [826bdb9](https://github.com/NREL/SAM/commit/826bdb90e1cb6a232f68917dd1f7dadce2c2ab85)
