### ISSUE TITLE
Battery not charging from fuel cell during grid outage

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1130]
### Describe the bug

The battery does not appear to charge from the fuel cell during grid outages. Seems similar to https://github.com/NREL/SAM/issues/977. 

### To Reproduce

1. Create a new _Fuel Cell, Commercial_ case
2. Change fuel cell unit nameplate to 50 kW
3. Enable the battery
4. Set battery dispatch to "input grid power targets" with monthly values all set to 0
5. Enable "battery can charge from fuel cell"
6. Simulate
7. View "Electricity to battery from fuel cell (kW)" output:
![image](https://user-images.githubusercontent.com/45701090/184934590-55214a87-874c-4a10-80c5-56fb84a5a9a9.png)

8. Go to Grid Outage, set "Critical load percent of electric load" to 100%
9. Set the Grid outage array to 1 in all 8760 time steps.
10. Simulate, and compare new "Electricity to battery from fuel cell (kW)" output with previous (note Y-axis is very small): 
![image](https://user-images.githubusercontent.com/45701090/184935138-02c47ff3-f237-40a1-957f-081c87b3f759.png)
11. Also note that the fuel cell operates continuously, despite electricity appearing to not go to the grid, load, or battery: 
![image](https://user-images.githubusercontent.com/45701090/184935636-89c6bec4-982d-463c-8a40-fb4b16582889.png)

### Expected behavior

The battery should be able to charge from the fuel cell during grid outages. Results should be similar to a grid power target of 0 and no outage.

### Operating System and Version

 - OS: Windows
 - Version: 2021.12.2 r2

**Comment by brtietz** [comment]
@williamhobbs We don't recommend running the grid outage code with PVWatts, since we prefer for people to use the losses code in detailed PV. This means that the fuel cell code is currently not tied to the grid outage code in any meaningful way. Based on your description in "expected behavior" I'm going to change this to "enhancement."

**Comment by williamhobbs** [comment]
Ah, good to know. In that case, would it make sense to remove the "grid outage" tab from the Fuel Cell case? Or produce a warning/notice for the user if they use the grid outage features in a Fuel Cell case?
