### ISSUE TITLE
Consider local implementation of REopt to replace web API call

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1135]
The current implementation of REopt in the SAM user interface uses the REopt web API at https://developer.nrel.gov/docs/energy-optimization/reopt/.

REopt has a new Julia package under development: https://github.com/NREL/REopt.jl.

When the Julia package is ready, it would be possible for SAM to run REopt locally. This would potentially be faster and more reliable than the web API calls.

Also consider new version of REopt and "stable" endpoint.

**Comment by brtietz** [comment]
Julia integrations with other languages are harder when we thought when we opened this issue. Closing until we can find a rock solid C++ - Julia interface.
