### ISSUE TITLE
Update land use calculations for consistency and industry rules of thumb

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1143]
### Describe the bug

The papers and podcast episode below suggest that average land use per MW should be more like 5 - 10 acres/MW, where as detailed PV suggests 3 acres/MW, and PVWatts suggests 9.4

https://www.nrel.gov/docs/fy13osti/56290.pdf
https://xenetwork.org/ets/episodes/episode-175-community-support-and-opposition/
https://emp.lbl.gov/publications/land-requirements-utility-scale-pv

#### To Reproduce

1. Open default cases as described above
2. Change DC system size to 1 MW
3. See error

#### Expected behavior

Land use calculations should lead to results consistent with the above resources, and be consistent between models

### Total Module Area

Consider using same convention for PVWatts and Detailed PV: PVWatts "Estimated total module area" and Detailed PV "Total module area" shown on System Design page should be total of all module areas rather than total module area projected onto ground, i.e., not be affected by GCR. GCR should only affect land area in acres/ha on PV Land Area form. 

* Verify that this approach is consistent with all uses of GCR: Self shading, backtracking, and land area for both Detailed PV and PVWatts models. 

* Note module area on Detailed PV Module and Shading and Layout page: Total module area on system design page should be area of single module times total number of modules.

**Comment by mjprilliman** [comment]
From meeting with James:

-Look into adding acre/MW input toggle for different way of specifying land area.
-Wide range of acre/MW values in literature, most developers focused on total land purchased (large acreage where PV is not deployed in some areas)
-No objections to GCR land acreage calculation approach.
