### ISSUE TITLE
sCO2 macros did not finish.

### ISSUE THREAD

**Issue by freddyUC** [NREL/SAM#1149]
When I want to use the sCO2 model provided by: https://github.com/NREL/SAM/tree/develop/samples/CSP/sco2_analysis_python_V2

### I followed these Instructions
1. Create a new CSP-PTMS-Single Owner project
2. Go to Macros located below Simulate bottom
3. Choose sCO2 Cycle Integration
4. Run the Python sCO2 Power Cycle model from the GitHub link to generate the .json file. 
5. Click Run macro above and follow the prompts to: 
    - Import data from the JSON file created by the script. 
    - Change variables in the user interface? Yes

I expected to get a message like: Done or successful macros file

![Sin título](https://user-images.githubusercontent.com/112201218/189937201-ce3156cf-7779-4fc2-9a9b-4497f43a0b83.png)

Instead, when I open .json file, the message I receive is
Macro did not finish.
[114] operand to sizeof must be an array, string, or table type.

### Operating System and Version

 - OS: Windows 10
 - Version SAM 2021.12.2

I don't have problems with python scripts to generate all the data, but SAM doesn't read it as I expected.

**Comment by cpaulgilman** [comment]
@tyneises, @qualand Is this a known issue before I investigate further? Line 114 in the SAM macro sets `n_rows_udpc = #udpc_table`, so the error seems likely caused by `udpc_table` not being read or being read incorrectly from the JSON file.

**Comment by tyneises** [comment]
@freddyUC can you attach the json you are trying to load?

**Comment by freddyUC** [comment]
@tyneises I attach the files I used to generate the .json

The .py compile with no problems, but .json doesn´t work in SAM caused by
line [114]
[image: image.png]

Waiting for your reply

Best regards
Freddy

**Comment by cpaulgilman** [comment]
@freddyUC We are not seeing any attached files. Could you please try attaching them again?

**Comment by tyneises** [comment]
The Python file that you ran only simulates a few off-design cases to demonstrate the off-design model. The SAM macro loads off-design into the User Defined Power Cycle model, which in turn requires a certain combination of off-design results. This file demonstrates how to generate data for the macro and User Defined Power Cycle model: https://github.com/NREL/SAM/blob/develop/samples/CSP/sco2_analysis_python_V2/example/mspt_default_generate_sco2_udpc.py

A few notes:
- The dictionary at the top of the file defines default parameters
- Line 117 adjusts the convergence tolerance to 1%. This enables the code to run relatively quickly, but there is some noise in the off-design response that you can see in the plots that the Python code generates
- If you adjust the tolerance to 0.1% (0.001), then the results have less noise, but the simulation will require a significant time to solve. I am developing some options to increase the simulation speed, but those won't be available for a few months
