### ISSUE TITLE
Large differences in output between detailed PV and PVWatts for vertical bifacial

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1151]
### Describe the bug

When simulating vertical bifacial panels (tilt 90, azumith 270) the detailed PV model estimates 36% more energy production from the detailed PV system. The difference between the two models for lower tilt angles is within 10%

### To Reproduce

1. Run both cases in the attached SAM file: 
[detailed_pv_vs_pvwatts_vertical_bifacial.zip](https://github.com/NREL/SAM/files/9561366/detailed_pv_vs_pvwatts_vertical_bifacial.zip)
2. View the difference between the simulations

### Expected behavior
Expect smaller differences between the models

### Operating System and Version
 - Version 2021.12.02 r2 and develop

Can't compare to the PVWatts website since that code predates the PVWatts bifacial model

**Comment by cpaulgilman** [comment]
Similar issue reported for detailed PV model: https://sam.nrel.gov/forum/forum-general/4017

Note that bifacial model is based on test data for modules with up to 45 degree tilt angles: https://sam.nrel.gov/component/kunena/forum-general/3468

**Comment by janinefreeman** [comment]
@sjanzou do you have time to take a look at this? Even if the model itself wasn't validated for 90 deg tilts, I would expect the two implementations (pvwatts and pvsamv1) to give similar results.

**Comment by sjanzou** [comment]
> @sjanzou do you have time to take a look at this? Even if the model itself wasn't validated for 90 deg tilts, I would expect the two implementations (pvwatts and pvsamv1) to give similar results.

Working on it...
