### ISSUE TITLE
Battery type error

### ISSUE THREAD

**Issue by diegolinhares** [NREL/SAM#1158]
### Describe the bug

I tried to edit the battery type for a Generic Battery case and it's only possible if setting the value 2-3 times. Without the show_page setting, the value also didn't work.

```
      show_page("Battery Cell and System");
      set('batt_type', 0);
      set('batt_type', 0);
      set('batt_type', 0);
```

### To Reproduce

1. Create a new script using this code:
 ```
      show_page("Battery Cell and System");
      set('batt_type', 0);
```

2. Click on simulate.
3. See error

### Expected behavior

Try to set the batt_type only one time and without be need to use show_page command.

### Operating System and Version

 - OS: Windows
 - Version 2021-12-02-r1

**Comment by cpaulgilman** [comment]
@diegolinhares 

This behavior is as intended.

When you change the **Battery type** choice by hand using the list on the Battery Cell and System page, SAM prompts you asking if you want to replace inputs with default values:

![image](https://user-images.githubusercontent.com/27711933/192901743-1de2d7b7-25ea-427c-9829-2aa1ce872945.png)

When you change the value of `batt_type` in an LK script, the window with the prompt appears, and you have to click **OK** to proceed with changing the battery type. It is not possible to override this behavior from an LK script.

One workaround might be to create a SAM file with a separate case for each battery type. Then you can use `active_case()` to change cases when you want to change the battery type.

Another approach, if you know Python, is to use NREL's PySAM package, which includes some pre-written functions for working with the battery model, including for changing the battery type: https://nrel-pysam.readthedocs.io/en/master/helper-tools.html#battery-tools. The source code in Python for those functions is here: https://github.com/NREL/pysam/blob/master/files/BatteryTools.py.
