### ISSUE TITLE
Autonomy Autographs for Fuel Cell Configurations

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1168]
Consider adding autonomy autographs for this Fuel Cell configuration: 
![image](https://user-images.githubusercontent.com/54449384/193660372-f02849b9-3410-4fd6-83fa-6e5437358941.png)

_Originally posted by @mjprilliman in https://github.com/NREL/ssc/pull/880#pullrequestreview-1128897353_

**Comment by mjprilliman** [comment]
Let's also look at Generic Battery, Standalone Battery
