### ISSUE TITLE
New bifacial graphs, outputs showing for monofacial systems

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1177]
### Describe the bug

-Autographs and output metrics for rear and ground POA between rows showing up for monofacial systems. 

### To Reproduce

1. Go to Detailed PV case
2. Simulate
3. Look at Autographs on summary page, data tables

### Expected behavior

Rear POA metrics should only show up when bifacial option is checked

### Operating System and Version

 - OS: [Windows, macOS, Linux]
 - Version [e.g. SAM 2020.2.29 r3]

**Comment by Matthew-Boyd** [comment]
Ground irradiance is valid for agrivoltaics, and rear irradiance is useful for back sheet degradation research ([example paper](https://www.sciencedirect.com/science/article/pii/S1364032122000880)). Thoughts @cpaulgilman and @janinefreeman ?

**Comment by cpaulgilman** [comment]
I gather that those graphs are on the Summary page because the agraph() heat map is the only way we have to graph a time series matrix. The summary page is intended to have a few key graphs to help users do an initial evaluation of results, and I think we should avoid cluttering it.

Could we modify the plot on the Heat Map tab to be able to handle these graphs?

**Comment by Matthew-Boyd** [comment]
> Could we modify the plot on the Heat Map tab to be able to handle these graphs?

@sjanzou Do you know how difficult this would be?

**Comment by sjanzou** [comment]
@mjprilliman, what is the error? That the following plots showing up for monfacial and not bifacial only?
![image](https://user-images.githubusercontent.com/6498311/195040321-b2c1f944-ac5b-45e1-befc-20a76d157b0e.png)

**Comment by sjanzou** [comment]
> > Could we modify the plot on the Heat Map tab to be able to handle these graphs?
> 
> @sjanzou Do you know how difficult this would be?

What graphs specifically? I did not see any in the "example paper" link.

**Comment by Matthew-Boyd** [comment]
> > > Could we modify the plot on the Heat Map tab to be able to handle these graphs?
> > 
> > 
> > @sjanzou Do you know how difficult this would be?
> 
> What graphs specifically? I did not see any in the "example paper" link.

I think another option is to add the capability of plotting matrix data on the "Heat map" tab, so we can move the two new heat maps shown on the right off the main Summary page. This may necessitate adding a new "Heat maps" tab to the SAM Development Environment (Ctrl-F7) to allow customization like that afforded on the Autographs tab.

Another option is to add heat maps to the Graphs tab for plotting Matrix data.

**Comment by Matthew-Boyd** [comment]
Adding plots to a new Spatial tab, regardless of monofacial/bifacial. Also adding a heatmap for the albedo, but only if using spatial albedos.
