### ISSUE TITLE
PV land area acre/MW input

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1185]
From meeting with James:

-Look into adding acre/MW input toggle for different way of specifying land area. (Particularly useful in PVWatts)
-Wide range of acre/MW values in literature, most developers focused on total land purchased (large acreage where PV is not deployed in some areas)
-No objections to GCR land acreage calculation approach.

_Originally posted by @mjprilliman in https://github.com/NREL/SAM/issues/1143#issuecomment-1275169114_

**Comment by cpaulgilman** [comment]
Looks good. This will be a useful option. 

I changed the check box to radio buttons to make it explicit to the user what the options are, and added a UI variable showing the AC capacity for reference:

![image](https://user-images.githubusercontent.com/27711933/196751424-421cf075-21f4-49a6-a7c2-a3b4d6f23498.png)

This does not have any checks on whether the user-entered acres/MWac results in a land area that is much smaller or much bigger than the module area, so we are leaving it up to the user to compare the total module area in acres to the total estimated land area.

Also note that the new extra row included in the automatic calculation, when GCR = 0.999 the area projected onto ground is greater than the module area -- just a reminder to myself that this is the intended behavior.
