### ISSUE TITLE
Weather file downloads broken for solar and wind

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1186]
Weather file download returns geocode error:

- For wind, works OK if you provide lat/lon, but not location name or street address.
- For solar, does not work for either.
- Marine energy wave works OK.

See easycurl.cpp in WEX. Solution is to use a JSON reader instead of attempting to parse the JSON response by splitting the returned JSON by commas into an array:
 
https://github.com/NREL/wex/blob/28c2fe6c840cdd5f28d5a189927012edadfa78b3/src/easycurl.cpp#L629

LK script for testing geocode function (requires copying and pasting keys from private.h):

[geocode-tests-no-keys.zip](https://github.com/NREL/SAM/files/9778279/geocode-tests-no-keys.zip)

Note RapidJSON implementation in https://github.com/NREL/SAM/issues/486

**Comment by ghazi-git** [comment]
@cpaulgilman we're having an issue with weather files as well while using pysam to generate a solar valuation.

The error we're seeing is this:
```
exec fail(pvwattsv7): first two header lines must have same number of columns
```
We're using pysam 2.2.4 and it was reported only today.
Here's the weather file in question
[nsrdb_38.81_-77.26_psm3-tmy_60_tmy_zpexne.csv](https://github.com/NREL/SAM/files/9831783/nsrdb_38.81_-77.26_psm3-tmy_60_tmy_zpexne.csv)

**Comment by cpaulgilman** [comment]
@ghazi-git I just noticed this as well. The issue I discovered is that some files from the NSRDB are being returned with a "Version" column in the header (Row 1), but no version number in Row 2. SAM's weather file reader requires that the first two header rows have the same number of columns. A workaround solution for now might be to edit the header rows before using the weather file -- adding a comma to Row 2 should do the trick.

This is an issue that we either need to fix in SAM's weather file reader, or see if the NSRDB team can ensure that all weather files are returned with a version number.

Here is where the weather file reader makes that check: https://github.com/NREL/ssc/blob/9766fe9b54161f13d1fad26e465c7882877e52c3/shared/lib_weatherfile.cpp#L790.

**Comment by ghazi-git** [comment]
Thank you @cpaulgilman, the issue is fixed when adding an extra comma to the second row. However, I chose to set the missing version value as "3.2.0" since both rows already have the same number of columns which is 20 (setting the version to any value fixes the issue as well).

**Comment by williamhobbs** [comment]
I found this regarding NSRDB version numbers: https://github.com/NREL/developer.nrel.gov/issues/281. It sounds like that issue has been fixed, but I haven't tested it in the context mentioned here.
