### ISSUE TITLE
BTM Battery peak shaving does not dispatch for small battery

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1208]
### Describe the bug

For a BTM battery that is very small compared to the load, peak shaving never dispatches the battery because of 3% safety factor on grid power target to account for AC/DC conversion issues when setting the target: https://github.com/NREL/ssc/blob/80651e1e3593f4179b9411f35c70978f05e91710/shared/lib_battery_dispatch_automatic_btm.cpp#L511

Given recent changes with better modeling of AC/DC conversions in other parts of the code, revisit this safety factor. 

### To Reproduce

1. Create a default PV Battery / Commercial case.
2. On the Electric Load page, set scaling factor to >30.
3. Run a simulation, note battery does not discharge.

Original user case had 600 kWdc PV, 500 kW / 2h battery, 66,000 kW /  270,000,000 kWh load

**Comment by cpaulgilman** [comment]
Example file: https://github.com/NREL/SAM/files/9931300/btm-peak-shaving-large-load.zip

**Comment by brtietz** [comment]
A comment near the safety factor reads "set safety factor in case voltage differences make it impossible to achieve target without violated minimum SOC"

I tested replacing the safety factor with a charging efficiency on branch https://github.com/NREL/ssc/tree/SAM_1208_revisit_safety_factor Lithium Ion and Lead Acid chemistries performed just fine in the commercial case with relaxed charging constraints, but vanadium flow violated the SOC constraints:

![image](https://user-images.githubusercontent.com/5530592/206811795-db3d3e02-a975-4f5e-8c89-81f15ce8d60f.png)

I suspect solving https://github.com/NREL/ssc/issues/831 and/or https://github.com/NREL/ssc/issues/569 prior to this issue will solve the underlying problem. Both of those issues are already scheduled for patch 1.

**Comment by brtietz** [comment]
It looks like some of the reporting around the grid power target might be ignoring the safety factor. See this case: automated dispatch in march reports a target of 47 kW, but manually entering a target of 50 kW produces the same grid use: 
[power_targets_bug.zip](https://github.com/NREL/SAM/files/12654017/power_targets_bug.zip)
