### ISSUE TITLE
SAM UI pages may move when collapsible windows are collapsed

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#121]
To recreate this behavior:
1. Create a Wind/Residential case.
2. Go to the Electricity Rates page.
3. Collapse the "Demand Charges" pane.
4. The top of the UI page moves down and the "Demand Charges" collapsible header disappears.

The current workaround is to click on another UI page, go back to the Electricity Rates page, and the demand charge header reappears, so not an urgent issue, but worth looking into.

**Comment by cpaulgilman** [comment]
@janinefreeman I think this may have been fixed for https://github.com/NREL/SAM/issues/405. Would you mind testing and closing this issue if it is working properly now? (I was not able to replicate in SAM 2020.11.29 r1.)

**Comment by janinefreeman** [comment]
Thanks Paul, I agree this seems to have been fixed!
