### ISSUE TITLE
Results' Time series display error after Simulate() called in LK script

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#122]
After running Simulate() from an LK script or Macro, since the default value for Update UI is false, the Results Viewer should not change. But the data for the Time Series Viewer is gone and results in either crashes or nonsensical results when trying to view data.

The Simulate() function with update UI false should leave Time Series Viewer data intact.

**Comment by cpaulgilman** [comment]
See also https://github.com/NREL/SAM/issues/579
