### ISSUE TITLE
Add std prefix to abs() and isnan() (and others?) in NREL SAM code

### ISSUE THREAD

**Issue by tyneises** [NREL/SAM#1223]
Some of our code uses abs() instead of std::abs() or fabs(). Abs() can return an integer instead of double in some contexts when compiled with gcc.

**Comment by sjanzou** [comment]
Issue addressed in lk repo in pull request 37 https://github.com/NREL/lk/pull/37

**Comment by sjanzou** [comment]
Issue addressed in wex repo in pull request 149 https://github.com/NREL/wex/pull/149

**Comment by sjanzou** [comment]
Two pull requests to close this issue
https://github.com/NREL/ssc/pull/931
https://github.com/NREL/SAM/pull/1250
