### ISSUE TITLE
Battery peak shaving for very large load compared to system/battery size

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1231]
### Describe the bug

BTM battery with large load compared to battery and system size does not dispatch due to 3% safety factor.

[btm-peak-shaving-large-load.zip](https://github.com/NREL/SAM/files/9931300/btm-peak-shaving-large-load.zip)

The peak shaving algorithm uses a 3% safety factor on the grid power target to account for AC/DC conversion issues when setting the target: https://github.com/NREL/ssc/blob/80651e1e3593f4179b9411f35c70978f05e91710/shared/lib_battery_dispatch_automatic_btm.cpp#L511

Since this governed by the grid usage, in the attached file it ends up being ~1200 kW on the first day in January. Since this is larger than the battery system, the system never discharges.

Workaround is to use “Input grid power targets” for this case and use automated dispatch to inform his choice of targets, maybe specifying a target 3-5% lower than the peak target at the end of each month.

We’ve gotten more sophisticated about AC/DC conversions in other parts of the code now, so it might be worth revisiting this safety factor.

**Comment by brtietz** [comment]
Isn't this a duplicate of https://github.com/NREL/SAM/issues/1208?

**Comment by cpaulgilman** [comment]
Oops. Yes a duplicate. Closing after attaching sample file to other issue.
