### ISSUE TITLE
Condense "Out of range albedo" errors

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#1232]
When a weather file has a column that consists entirely of bad albedo values, should we consider reporting them as one error "Weather file contained X bad albedo values, monthly value was used", sort of like we do for bad values in the snow model? "SRRL weather data with fixed snow and fake POA" in the sam-documentation repo can be used to see the current behavior, which is a separate warning for every single timestep.

Not urgent, and welcome opinions to the contrary.

**Comment by sjanzou** [comment]
Detailed PV update:
![image](https://user-images.githubusercontent.com/6498311/219645759-53003e69-d847-47fe-839a-c087537f4c22.png)

PVWattsv8 update for consistent results:
![image](https://user-images.githubusercontent.com/6498311/219645886-74523d5d-1cc8-4a9c-a013-c9cf7fb2e58c.png)
