### ISSUE TITLE
Combine cases crashes when case generates simulation error

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1238]
### Describe the bug

For the Generic System model with **Calculate generation profiles and nameplate capacity from open cases** on the Power Plant page, when one of the cases being combined generates an SSC simulation error, clicking **Select cases** causes SAM to crash.

### To Reproduce

1. Download and open the the "st helena.sam" file attachment to https://sam.nrel.gov/forum/forum-general/4066-combine-cases-shuts-down-sam.html.
2. Go to the "New WT" case and run a simulation to see the SSC error "exec fail(windpower): failed to read local weather file".
3. Go to the "All Wind" case.
4. On the Power Plant page, click **Select cases**.
5. SAM crashes.

Update: SAM crashes for this file even when there is no SSC simulation error.

### Expected behavior

Clicking **Select cases** should not cause SAM to crash.

If one or more of the cases being combined generates an error, clicking Select Cases should inform the user there is a problem with one of the cases, perhaps in a message box, like "Simulation for case [case name] failed with error: [SSC error]".

**Comment by mjprilliman** [comment]
The issue with this file is that the 2 wind cases were built with LCOE calculator financial model, which forgoes the assignment of system_use_lifetime_output. The combine cases function doesn't know what to do when this variable is not assigned. What is the intended behavior @Matthew-Boyd @cpaulgilman ?

**Comment by cpaulgilman** [comment]
@mjprilliman Thanks for investigating. Would it work to assume one year of gen data if `system_use_lifetime_output` is not assigned? Or, perhaps it should be assigned in the LCOE calculator model. The intended behavior is that it should be possible to combine cases that use the LCOE calculator financial model.
