### ISSUE TITLE
Custom depreciation schedules not handled in Single Owner with equations

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#124]
Custom schedule for depreciation not handled in Single owner workbook with equations.
To replicate,
1) run PV for India Wizard 
2) go to the results page and send to Excel with equations
3) LCOE does not match - Federal depreciation missing from the workbook
4) SAM case has 100% custom schedule depreciation that is missing from depreciation schedule sheet in the workbook

**Comment by cpaulgilman** [comment]
I've updated the spreadsheet to account for custom depreciation schedules. Running some tests now and will commit when I finish.
