### ISSUE TITLE
REopt API call fails for PVWatts cases

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1290]
See https://sam.nrel.gov/forum/forum-general/4085

To replicate:

1. Create a default PVWatts-Battery / Commercial case.
2. On the System Design page, click **Get battery size and dispatch from REopt**.
3. See UI callback error.

```
Could not evaluate callback function:call_reopt->on_change
[30]: error in call to 'reopt_size_battery()': Invalid inputs. See 'input_errors'.
[ Invalid length for prod_factor_series_kw. Samples must be hourly (8,760 samples), 30 minute (17,520 samples), or 15 minute (35,040 samples) ][11]: eval error in statement list
```

**Comment by cpaulgilman** [comment]
@brtietz Did this PR break "simple" REopt call for PVWatts-Battery: https://github.com/NREL/ssc/pull/925?

**Comment by brtietz** [comment]
Yes, that seems likely, though it's not clear why. I can add it to my list for the first patch.
