### ISSUE TITLE
groundClearanceHeight definition for Sandia module model

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1296]
### Describe the bug

-SAM detailed PV model. 
-Mike Wagner: I’m trying to run the default case with the only change being selection of the Sandia module performance model, and using the default panel type. When running in debug mode only, the model hangs up. In debugging, I found that this occurs because the module variable ‘groundClearancHeight’ is not set for the Sandia model, and defaults to some NaN that is a very large negative number. The calculation of shading uses a while loop based on this value, and it ends up hanging. The screenshots below give a bit of context. 

### Screenshots

![image](https://user-images.githubusercontent.com/54449384/205396930-b58ece39-b87c-4f76-9df0-e2a306630b42.png)

### Operating System and Version

 - OS: [Windows, macOS, Linux]
 - Version [e.g. SAM 2020.2.29 r3]

### Additional context

-Only happening in debug?

**Comment by mjprilliman** [comment]
![image](https://user-images.githubusercontent.com/54449384/205397128-2230a114-2c33-4ef8-84cd-c108d02fa9c9.png)

**Comment by mjprilliman** [comment]
FYI @mjwagner2 @tyneises

**Comment by mjprilliman** [comment]
@cpaulgilman with the spatial albedo calculations the Sandia module model needs a clearance height definition even though there is no bifacial option. Thoughts on hard coding a value for now (1 meter for example) vs adding a new input? Is adding bifacial capabilities to the Sandia model another potential pathway?

**Comment by cpaulgilman** [comment]
@mjprilliman I think adding a hard-coded value would be fine for now (with a comment explaining why it's there.):

* Would it make sense to report the ground clearance height as an output for all module models so users can tell what value is being used for the spatial albedo outputs?
* I assume that this value does not affect the Sandia model outputs themselves.

Another option would be to disable the spatial albedo option for the Sandia model. 

We don't have any plans to modify the Sandia model that I am aware of.
