### ISSUE TITLE
Error saving & loading "Time of Day" schedules and factors

### ISSUE THREAD

**Issue by dylanjmcconnell** [NREL/SAM#13]
Hi there - There seems to be an issue with loading and saving schedule data (specifically in the 'Time of Delivery Factors' tab).

Recieve a popup message, which appears to be generated by SAM:
>"Data load failed" 

Or
>"Data save failed"

And  another popup message, that seems to be system generated:
> "can't open file '/path/to/csvfile.csv' (error 2: No such file or directory).

(Files definitely exist)

Using SAM on Linux (Version 2017.1.17, 64 bit, updated to revision 4)
SSC Version 174: Linux 64 bit GNU/C++ Jun 19 2017 05:06:12
wxWidgets 3.1.0 on Linux 4.10.0-32-generic x86_64
Internet connection method: default

**Comment by nickdiorio** [comment]
Thanks for reporting the issue, I've confirmed the behavior as well.  We'll take a look and get it fixed.  
Best regards,
Nick

**Comment by nickdiorio** [comment]
Were you trying to upload a time-series file using the Save/Load buttons?  That option is actually specified using a drop down menu:
![image](https://user-images.githubusercontent.com/5658281/29541082-253e025a-868f-11e7-96fb-ceeae0aa60fd.png)
This is confusing, so we're going to redesign the page to be more obvious.  The Save/Load data buttons you were using use a different file format than just a straight time series (simply click "Save data to file" to see what it looks like).

**Comment by dylanjmcconnell** [comment]
Hi Nick - no, no time series - just trying to save (and load) manually input schedule. See mock-up below:
 
![screengrab](https://user-images.githubusercontent.com/18433446/29541453-7f0b6bdc-8717-11e7-98f4-97edfaa3fadd.png)

**Comment by nickdiorio** [comment]
Dylan, ah, I think I see.  This looks like possibly a Linux specific issue, we'll investigate.  My apologies for the confusion.

**Comment by nickdiorio** [comment]
This still appears to be broken, when I save TOD schedule data to a file, the file is empy

**Comment by sjanzou** [comment]
Issue was that group name for variables on the form was changed but the callback function were not updated. 
![image](https://user-images.githubusercontent.com/6498311/56952181-eea80a80-6af6-11e9-976e-47c167831902.png)

**Comment by sjanzou** [comment]
Updated and tested in develop and patch branches
