### ISSUE TITLE
PVWatts No financial Advanced Inputs callback error

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#1310]
With 2022.11.21 release:
1. Create PVWatts / No Financial Model case
2. System Design->Advanced Inputs->Edit shading...
3. Enable one or more shading options
4. Simulate
5. Click on System Design page

Receive callback error
![image](https://user-images.githubusercontent.com/6498311/210514720-de1c9433-1da6-4405-99a3-f6b417ab61be.png)

**Comment by cpaulgilman** [comment]
This is a duplicate of https://github.com/NREL/SAM/issues/1305
