### ISSUE TITLE
ETES System Design UI callback error

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1311]
### Describe the bug

Calculated values do not update on ETES System Design page in SAM 2022.11.21.

Note error in IDE script editor:

![etes-callback-error](https://user-images.githubusercontent.com/27711933/210639840-4a286597-5f72-491d-ad6a-d2d1dd1ccc98.png)

Workaround is to use SAM 2021.12.02 r2.

**Comment by tyneises** [comment]
@cpaulgilman I recommend still using SAM 2022.11.21. The calculated values in the UI do not update, but the simulation will still properly handle user inputs.

**Comment by tyneises** [comment]
@sjanzou I accidentally added an errant '0' to the end of the Equations code in the ETES System Design ui page. Paul's screenshot above shows that the IDE editor complains, but when I open the ETES technology model in SAM, the UI ignores the equations window without reporting the syntax error. Is there a way for the UI to catch and report this type of error?

https://github.com/NREL/SAM/commit/3027feebfdf3f8d794b9be8ad9b11fee1c110200

**Comment by tyneises** [comment]
> @sjanzou I accidentally added an errant '0' to the end of the Equations code in the ETES System Design ui page. Paul's screenshot above shows that the IDE editor complains, but when I open the ETES technology model in SAM, the UI ignores the equations window without reporting the syntax error. Is there a way for the UI to catch and report this type of error?
> 
> [3027fee](https://github.com/NREL/SAM/commit/3027feebfdf3f8d794b9be8ad9b11fee1c110200)

It looks like the text file will have a 0 at the end, but the bug was that there was a space after the end of the equations code? I'm not quite sure how this works, but the commits appear to fix the issue.

**Comment by sjanzou** [comment]
> > @sjanzou I accidentally added an errant '0' to the end of the Equations code in the ETES System Design ui page. Paul's screenshot above shows that the IDE editor complains, but when I open the ETES technology model in SAM, the UI ignores the equations window without reporting the syntax error. Is there a way for the UI to catch and report this type of error?
> > [3027fee](https://github.com/NREL/SAM/commit/3027feebfdf3f8d794b9be8ad9b11fee1c110200)
> 
> It looks like the text file will have a 0 at the end, but the bug was that there was a space after the end of the equations code? I'm not quite sure how this works, but the commits appear to fix the issue.

@tyneises, all of the uiforms are currently written as text files in main.cpp InputPageData::Write_text which includes the callbacks and equations. The way everything is written now is character by character. I think the 0 that got added was misinterpreted as a \0 (end of file marker and caused the callback syntax error but not picked up by the parser.

We are moving to JSON for the UI forms soon ((like the defaults), so these mysterious fixes and bugs should be minimized.

Your pull request 1312 seems to close this issue as far as I can tell. I will let you or @cpaulgilman do the official closing of this issue.

**Comment by tyneises** [comment]
> > > @sjanzou I accidentally added an errant '0' to the end of the Equations code in the ETES System Design ui page. Paul's screenshot above shows that the IDE editor complains, but when I open the ETES technology model in SAM, the UI ignores the equations window without reporting the syntax error. Is there a way for the UI to catch and report this type of error?
> > > [3027fee](https://github.com/NREL/SAM/commit/3027feebfdf3f8d794b9be8ad9b11fee1c110200)
> > 
> > 
> > It looks like the text file will have a 0 at the end, but the bug was that there was a space after the end of the equations code? I'm not quite sure how this works, but the commits appear to fix the issue.
> 
> @tyneises, all of the uiforms are currently written as text files in main.cpp InputPageData::Write_text which includes the callbacks and equations. The way everything is written now is character by character. I think the 0 that got added was misinterpreted as a \0 (end of file marker and caused the callback syntax error but not picked up by the parser.
> 
> We are moving to JSON for the UI forms soon ((like the defaults), so these mysterious fixes and bugs should be minimized. #504
> 
> Your pull request 1312 seems to close this issue as far as I can tell. I will let you or @cpaulgilman do the official closing of this issue.

Thanks, Steve. The JSON format for UI forms will be nice - it was tricky trying to auto-merge the UI page change into the mspt_no_finance branch...
