### ISSUE TITLE
Add PTES Design Point Dialog Widget

### ISSUE THREAD

**Issue by taylorbrown75** [NREL/SAM#1317]
### Is your feature request related to a problem? Please describe.

Some of the PTES inputs (such as heat pump COP) are non-intuitive and design point properties need to be calculated to run the SAM simulation. 

### Describe the solution you'd like

A button launches a PTES design point dialog widget, where users enter cycle information and returns design point results. 

### Describe alternatives you've considered

There is currently a macro to run a Matlab script and import the design point data.

**Comment by cpaulgilman** [comment]
Fixed in https://github.com/NREL/SAM/pull/1318
