### ISSUE TITLE
CSP Physical Trough flips SCA and HCE labels

### ISSUE THREAD

**Issue by taylorbrown75** [NREL/SAM#1319]
### Describe the bug

For the csp physical trough model, the SCA and HCE types assigned on the Solar Field tab are not shown correctly on the Collector's and Receiver's tab. The Collector's tab lists the HCE types and the Receiver's tab lists the SCA types on the field labeled "Collector types in loop configuration."

### To Reproduce

1. Go to 'CSP->Parabolic Trough - Physical'
2. Go to Solar Field tab
3. Scroll down and change the first SCA to type 2
4. Go to Collectors tab and see that the collector types are all type 1.
5. Go to Receivers tab and see that the first receiver is type 2.

### Expected behavior

The collectors and receivers tabs should list the same type configuration as shown on the solar field tab.

### Screenshots
![image](https://user-images.githubusercontent.com/60201147/212142090-3e56fa2c-fe03-4279-9ec8-e1cee5ed5eca.png)

![image](https://user-images.githubusercontent.com/60201147/212142164-21fc50e9-4b5c-4eb8-acb5-ff8785287484.png)

![image](https://user-images.githubusercontent.com/60201147/212142207-c3326707-cc79-4745-b7f9-5b06b5243564.png)

### Operating System and Version

 - OS: [Windows]
 - Version [e.g. SAM 2022.11.21]

**Comment by tyneises** [comment]
@Matthew-Boyd This seems related to how SSC Equations interprets "trough_loop_control". Can you please take a look?

**Comment by Matthew-Boyd** [comment]
@tyneises Taylor and I met yesterday and I think he's on the right track.

@taylorbrown75 If the issue you found in the UI Equations isn't the main problem, you may want to check out Sca_info_array() in cmod_csp_common_eqns.cpp and ensure the returned values to the call in cmod_csp_trough_eqns.cpp make sense. Feel free to reach out again if you need some help.
