### ISSUE TITLE
Generic system / PPA single owner configuration fails with subhourly generation profile

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#135]

**Comment by sjanzou** [comment]
Please note that i am able to run the simulation with hourly input, i.e Hourly.Sam, however if i change the time step, i.e 15 min.SAM, and run the same simulation SAM becomes not responding as shown in the figure 
![image](https://user-images.githubusercontent.com/6498311/50052111-4c096500-00dc-11e9-8694-958011497e40.png)

**Comment by sjanzou** [comment]
Fixed in ssc patch branch commit https://github.com/NREL/ssc/commit/9a0db4f657a25a7557e347e40ba0348dad2e05ea
