### ISSUE TITLE
Mismatched array length between critical load and load equation error

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1371]
### Describe the bug

-If critical load array length does not match load array length when crit_load_type is switched to 'Use time series critical load data', a equation error occurs. 
-Array length cannot be changed unitl crit_load_type is set to 1, so error will always occur if load is different length than default hourly critical load time series
-Occurs when load data is set before grid outages (low priority)
-

### To Reproduce

1. Go to PV Battery Commercial
2. Choose 15 minute weather file
3. Set load increment to 15 minutes on Electric Load page
4. Go to Grid Outage, select 'Use time series critical load data'
5. See equation error (line 51 of Electric Load Data)

### Expected behavior

Somehow avoiding an equation error popping up would be preferred

**Comment by cpaulgilman** [comment]
I fixed the UI issue in https://github.com/NREL/SAM/tree/critical-load-ui-callback so that a message box is displayed when the load and critical load data have different time steps.

However, the simulation runs under this condition. @brtietz, should SSC throw a simulation error when the `load` and `crit_load` arrays have different lengths?

**Comment by brtietz** [comment]
> I fixed the UI issue in https://github.com/NREL/SAM/tree/critical-load-ui-callback so that a message box is displayed when the load and critical load data have different time steps.
> 
> However, the simulation runs under this condition. @brtietz, should SSC throw a simulation error when the `load` and `crit_load` arrays have different lengths?

We don't support lifetime load at the moment, right? I could imagine a valid case where someone specified 25 years of load, but used an escalation factor for critical load. However, it seems like currently different array lengths would indicated different timesteps, which seems like it should throw a simulation error.

**Comment by cpaulgilman** [comment]
> > I fixed the UI issue in https://github.com/NREL/SAM/tree/critical-load-ui-callback so that a message box is displayed when the load and critical load data have different time steps.
> > However, the simulation runs under this condition. @brtietz, should SSC throw a simulation error when the `load` and `crit_load` arrays have different lengths?
> 
> We don't support lifetime load at the moment, right? I could imagine a valid case where someone specified 25 years of load, but used an escalation factor for critical load. However, it seems like currently different array lengths would indicated different timesteps, which seems like it should throw a simulation error.

Right, I wasn't clear -- I meant that SSC seems to run when the critical load and load have different time steps. (There is an SSC check that the grid outage time step is correct, but not one for critical load.) The SAM UI is supposed to do a pre-check before running the simulation that is broken -- the UI callback error prevents the simulation from running when load and crit_load have different time steps, so you can't test this condition in the release version, but in my branch that fixes the UI callback error, it is possible for crit_load and load to have different lengths and SSC doesn't complain. We can rely on the SAM UI to prevent that, but I think an SSC check would be good for SDK/PySAM users.
