### ISSUE TITLE
Geothermal plant capital cost equation error

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1378]
### Describe the bug

-Equation error for geothermal capital cost automatic calculation caused by introduction of resource temperature upper bound introduced in patch 1. 

### To Reproduce

1. Go to Geothermal Case
2. Click on Installation Costs
3. Check Automatically estimate the plant cost per kW

**Comment by cpaulgilman** [comment]
https://sam.nrel.gov/forum/forum-general/4179
