### ISSUE TITLE
SAM code generator shading inputs for PySAM Pvsamv1

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1395]
### Describe the bug

Code generator exports shading variables for Detailed PV cases with shading enabled with the different variable name to JSON for PySAM than PySAM expects.

Details and workaround solution here: https://sam.nrel.gov/forum/forum-sdk/3630

**Comment by sjanzou** [comment]
Why???
![image](https://github.com/NREL/SAM/assets/6498311/cf8b4666-1f8d-4754-90a5-20f11d9157dc)

**Comment by sjanzou** [comment]
The "JSON for inputs" currently exports as desired
![image](https://github.com/NREL/SAM/assets/6498311/a9236f8c-30c2-46b4-ae5a-098dbbe945b0)

**Comment by sjanzou** [comment]
From the latest patch branches, the PySAM JSON generates the expected names from https://sam.nrel.gov/forum/forum-sdk/3630-importing-json-input-files-into-pvsamv1.html?start=6 
![image](https://github.com/NREL/SAM/assets/6498311/985965b5-0286-458f-a386-2614768a11fa)
