### ISSUE TITLE
Solar Resource Interpolation Macro doesn't work with new format

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#140]
The output of the solar resource interpolation macro on library and NSRDB-downloaded weather files does not allow for valid simulations.

**Comment by nickdiorio** [comment]
The solar resource interpolation macro is also really slow.  I'm wondering if we could speed it up by adding some memory allocations (using alloc()) and see where else we could speed things up.

**Comment by dguittet** [comment]
The reason I reported it as not working was because the macro set the irradiance components to zero when calculated sun position is not over the horizon. I forgot that this was a feature instead of a bug. 

I changed to alloc() for the output data but it's still slow. Might be due to the sun position calculations?

Added 1 min option.
