### ISSUE TITLE
Evalutaion of deploy/libraries/CEC Modules.csv

### ISSUE THREAD

**Issue by tommasogallingani** [NREL/SAM#1400]
How does this file in produced and fitted and how does the following parameters are evaluated?

    I_L_ref : float
        The light-generated current (or photocurrent) at reference
        conditions [A]
    I_o_ref : float
        The dark or diode reverse saturation current at reference
        conditions [A]
    R_s : float
        The series resistance at reference conditions, in ohms.
    R_sh_ref : float
        The shunt resistance at reference conditions, in ohms.
    a_ref : float
        The product of the usual diode ideality factor ``n`` (unitless),
        number of cells in series ``Ns``, and cell thermal voltage at
        reference conditions [V]
    Adjust : float

**Comment by cwhanse** [comment]
@tommasogallingani the parameter values are determined by fitting the CEC model equations (described [here](https://doi.org/10.1115/1.4005759)) to the IV curve at STC and temperature coefficients. The idea is that CEC model requires only datasheet information to be fit. The procedure is available through PySAM (and pvlib, which it appears you may be using; see `pvlib.ivtools.sdm.fit_cec_sam`). The SAM team occasionally updates the `CEC Modules.csv` file by processing the database of modules found [here](https://solarequipment.energy.ca.gov/Home/PVModuleList); you can download the Excel file to see the full data set. There is some human quality control on the results.

**Comment by cpaulgilman** [comment]
@tommasogallingani, @cwhanse

The `CEC Modules.csv` file that we package with the SAM software is available here: https://github.com/NREL/SAM/tree/patch/deploy/libraries

The PySAM module SixParsolve is equivalent to the SSC module 6parsolve.

The inputs and outputs to SixParsolve are described here: https://nrel-pysam.readthedocs.io/en/main/modules/SixParsolve.html

The SSC source code for 6parsolve is here: https://github.com/NREL/ssc/blob/patch/ssc/cmod_6parsolve.cpp, with libraries here: https://github.com/NREL/ssc/tree/patch/shared

**Comment by tommasogallingani** [comment]
thanks @cpaulgilman and @cwhanse!
I saw that with respect to the database published by CEC, the pvlib.ivtools.sdm.fit_cec_sam function wants temperature coefficient in A/C and V/C and that the number of cells is series is actually the product of the CEC database columns N_s * N_p that represent not the series and parallel but rows and columns of the PV module.
Just to make sure that everything is correct, there's no need to correct the value in [unit]/K from [unit]/C since the delta of the two temperature scale is the same, is that correct?

**Comment by cpaulgilman** [comment]
@tommasogallingani I would recommend using correct units (&deg;C) to avoid any potential problems. For SSC, the 6parsolve module converts temperature values from Celsius to Kelvin, for example here: https://github.com/NREL/ssc/blob/f8d64af67c238172afd4d6bac3f559f6c61341bf/shared/lib_cec6par.cpp#L167.
