### ISSUE TITLE
LCOE real for PV + Storage discrepancy in the cash flow 'send to Excel with equations' workbook.

### ISSUE THREAD

**Issue by TheMakiran** [NREL/SAM#1403]
### Describe the bug

We noted a difference in the LCOE real as reported in the Summary tab compared to the cash flow workbook created with 'send to Excel with equations'. The values are equivalent when modelling PV only, but when modelling Storage only or PV + Storage, the discrepancy occurs. For our PV + Storage model, the Summary report shows a real LCOE is 16.91 R / kWh. In the excel workbook, the real LCOE is R 2.86. When I model the PV only system with a higher installation cost that matches the cost of the PV + Storage, the real LCOE is 2.53 R/kWh in both the summary report and the excel workbook. The 16.91 R / kWh seems much too high for the PV + storage. 

### To Reproduce

1. Create a 'PV-Battery, Commercial' model
2. Simulate
3. Note the real LCOE on the Summary Tab
4. Click on the 'Cash Flow' tab
5. 'Send to Excel with equations'
6. Note the real LCOE on the 'Inputs and Outputs' tab

### Expected behavior

I expect the reported real LCOE to be similar, maybe with 5% due to the limited functionality of the excel workbook model, not 5x or so as noted. 

### Screenshots

See attachments. Note the values are in Rand-cents, not USD-cents

### Operating System and Version

 - OS: Windows 10 Enterprise, version 10.0.19045 19045
 - SAM Version 2022.11.21, 64 bit, updated to revision 1

### Additional context
![pv_storage_summary_report](https://github.com/NREL/SAM/assets/26845062/2bf8c5d3-430b-4208-9cc5-d4eb83e83b64)
[20230510 S8_pv_storage.xlsx](https://github.com/NREL/SAM/files/11484723/20230510.S8_pv_storage.xlsx)

I attached the summary report and the excel workbook for the PV + storage project.

**Comment by TheMakiran** [comment]
This discrepancy only seems to occur when I include a 'grid outage' profile profile.

**Comment by cpaulgilman** [comment]
@TheMakiran Thank you for reporting this issue. We'll need to check that the Excel workbook for SAM's "Send to Excel with Equations" feature is working correctly with grid outage data from SAM. In this special case (battery storage with grid outage), the Excel workbook is not replicating SAM's cash flow calculations correctly.

**Comment by cpaulgilman** [comment]
Also note issue with BTM battery O&M costs in Excel spreadsheet (need to check for Fuel Cell and other techs as well): https://sam.nrel.gov/forum/forum-general/4240

**Comment by cpaulgilman** [comment]
Also:

When using Detailed PV-battery model, in SAM cashflow includes battery operating expenses and information about energy discharged annualy:

![thumbnail_image](https://github.com/NREL/SAM/assets/27711933/8c9b5e40-e2b4-4db6-8d36-46db7ca04d44)

But spreadsheet generated with your default file do not.

![thumbnail_image-1](https://github.com/NREL/SAM/assets/27711933/3fd1f4f4-1ad0-43f3-a0ae-1b2ab834116c)

When using merchant model the are present:

![thumbnail_image](https://github.com/NREL/SAM/assets/27711933/42d8af1c-2eba-4632-a419-050646e4d625)
