### ISSUE TITLE
p50/p90 results table doesn't export row or column headings

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#141]
It is possible to export the P50/P90 results table by selecting the table and using ctrl-C/ctrl-V but that copies and pastes the data without headings.

Maybe consider an Export button or other method to export data. Also consider allowing user to choose variables to display.

**Comment by jforbess** [comment]
Hi, I am writing to second this request, because it is quite frustrating to have a table without labels.

**Comment by tuppenyb** [comment]
Me Three

**Comment by tuppenyb** [comment]
thank you - meanwhile - I figured out how to load the headings from the graphics export to excel and have created a one sub array spreadsheet - interested parties can copy and add for additional arrays and adjust heading if different special probability is chosen
[P90_P50 template.xlsx](https://github.com/NREL/SAM/files/6125026/P90_P50.template.xlsx)
