### ISSUE TITLE
Installation issue for Windows 10 and Windows Defender

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#142]
Some organizations' Windows Defender settings prevent SAM 2018.11.11 from installing. In this case, a user is unable to install SAM on a work computer and is using SAM 2017.9.5 instead:

![image](https://user-images.githubusercontent.com/27711933/50606798-d2170100-0e7b-11e9-8f68-2ee582f46f76.png)

**Comment by sjanzou** [comment]
Created new installation for Windows 10 for testing at:

https://sam.nrel.gov/sites/default/files/content/public_releases/sam-windows-2018-11-11-r1_win10.exe

**Comment by brtietz** [comment]
Did this get resolved?

**Comment by cpaulgilman** [comment]
We have not gotten any reports of this issue for SAM 2020.2.29.
