### ISSUE TITLE
Code generation for c#

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#1427]
The generated code calls to the c sharp function bool Log has float instead of the required double declaration for the time argument  which causes an error
<img width="381" alt="image" src="https://github.com/NREL/SAM/assets/6498311/e7363790-b7a2-4e6a-b947-3e168c00553d">

If changed to double, there is no error and the code runs and matches SAM

The generated code should have extension .cs instead of .cpp (both work with csc.exe command line compiler)

Details in attached document
[UserSupportForum2023.8.7_issue_4329.docx](https://github.com/NREL/SAM/files/12289471/UserSupportForum2023.8.7_issue_4329.docx)

**Comment by cpaulgilman** [comment]
https://sam.nrel.gov/forum/forum-sdk/4329
