### ISSUE TITLE
Cell temperature equals ambient temperature when using weather file POA 

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1428]
### Describe the bug

I have a custom weather file with measured POA data. If I use the heat transfer method (CEC module model) for temperature, cell temperature is being calculated as equal to ambient temperature. 

### Expected behavior

I would expect cell temperature to be different from ambient temperature in most daytime hours.

### Screenshots

![image](https://github.com/NREL/SAM/assets/45701090/52bd213f-6706-4c79-84f9-863d030335c0)
![image](https://github.com/NREL/SAM/assets/45701090/1484f766-d27d-4ae0-a6a3-334a2d8a2fbf)

### Operating System and Version

 - OS: Windows
 - Version: SAM 2022.11.21 r3

### Additional context

Temperature seems ok when using the NOCT method.

**Comment by cpaulgilman** [comment]
@williamhobbs Could you share an example of a weather file that causes this results? I was not able to replicate this using our test POA weather file.

**Comment by williamhobbs** [comment]
Here you go. It's reformatted from "Phase1_meteo_hourly.xlsx" here https://pvpmc.sandia.gov/resources-and-events/2023-blind-modeling-comparisons/. It seems to work ok otherwise, so I _think_ I got the formatting correct. 

[Phase1_meteo_hourly_sam.csv](https://github.com/NREL/SAM/files/12318007/Phase1_meteo_hourly_sam.csv)

**Comment by cpaulgilman** [comment]
Thanks for sharing the file. The Heat Transfer method requires atmospheric pressure and wet-bulb temperature data (see the note in the "Heat transfer method" section of the Module Help topic).

To fix this issue, we will:

* Add a simulation error when the heat transfer method is selected and those weather data elements are missing from the file.
* Revise the "Weather Data Elements" topic to mention this requirement.
