### ISSUE TITLE
in CEC Modules.csv: "Sunny International Power SPM-190SB105" got truncated

### ISSUE THREAD

**Issue by tobias-loew** [NREL/SAM#1438]
### Describe the bug

in CEC Modules.csv: the entry "Sunny International Power SPM-190SB105" got truncated with commit d582dbc78e56f4e8504a0ef477b7d27cb513e51f

**Comment by tobias-loew** [comment]
https://github.com/NREL/SAM/pull/1439 will fix this issue

**Comment by cpaulgilman** [comment]
Thank you for pointing out this issue and for proposing a fix.

We will double-check module library test results for negative performance ratios when we prepare the module library for future versions. We plan to release the next version of SAM this fall.
