### ISSUE TITLE
Apply clearsky outputs to other solar models. 

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1449]
To consider after merging:

* Consider a more informative name than "Subhourly clipping".
* Add clear sky irradiance outputs to other solar models (CSP, solar water heating, etc.) ?

_Originally posted by @cpaulgilman in https://github.com/NREL/SAM/pull/1447#pullrequestreview-1627802516_

**Comment by mjprilliman** [comment]
@tyneises is there anything you would use clear sky DNI for in the near-term? Otherwise this might get pushed to a later patch or release. https://github.com/NREL/ssc/issues/151#event-10388841471 for original context

**Comment by tyneises** [comment]
> @tyneises is there anything you would use clear sky DNI for in the near-term? Otherwise this might get pushed to a later patch or release. [NREL/ssc#151 (comment)](https://github.com/NREL/ssc/issues/151#event-10388841471) for original context

We have a few clear sky DNI models in the molten salt power tower code, so I don't think we need anything new in the near term. Ideally, we would replace or complement our local calcs with the pending centralized clear sky calcs (from the weather file reader?). @jannamartinek please correct / elaborate if necessary

**Comment by mjprilliman** [comment]
Pushing to a patch for now.
