### ISSUE TITLE
PV Uncertanty module crashes on develop

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1458]
### Describe the bug

While uncertainty was left out of the hybrids modules, it crashes for detailed PV.

### To Reproduce

1. Open a detailed PV case
2. Click on the uncertainty module
3. Select a folder with weather files
4. Click "run uncertainty simulations"
5. SAM crashes

### Expected behavior

Uncertainty module should run like the release 

### Operating System and Version

 - OS: Windows
 - Version 2023.9.19/develop

**Comment by sjanzou** [comment]
Issue traced to sim->Override call with m_overrides size=0
<img width="571" alt="image" src="https://github.com/NREL/SAM/assets/6498311/be5cf1c9-ec26-4e33-9ed8-ffffb8ae28fc">
