### ISSUE TITLE
Wind Hybrids is Missing "Balance of System" Inputs

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1470]
### Describe the bug

PV-Wind-Battery hybrids is missing the balance of system inputs

### To Reproduce

1. Open a wind hybrids case on develop
2. Click on Wind Installation Costs
3. Click on "Go to balance of system cost inputs"

### Expected behavior

Cost inputs should match stand alone wind.

### Screenshots

Hybrids:
![image](https://github.com/NREL/SAM/assets/5530592/0941f0b0-6d8e-4083-b3aa-ac78f711c347)

Stand Alone Wind:
![image](https://github.com/NREL/SAM/assets/5530592/f7f385ac-7cfa-4561-b798-4274fc58b3f7)

**Comment by mjprilliman** [comment]
hide button, remove UI forms if not easily fixable
