### ISSUE TITLE
Production Based Incentive references wrong cell for generation in send to excel with eqns for host-developer

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1473]
### Describe the bug

Host-developer's send to excel w/equations references cell C10 for energy production for the production based incentive, whereas cell C7 is likely more appropriate.

### To Reproduce

1. Compare cash flow in SAM vs send to excel to equations in attached zip: 
[send_to_excel_host_developer.zip](https://github.com/NREL/SAM/files/12753653/send_to_excel_host_developer.zip)

### Expected behavior

PBI should reference gross generation or net energy to grid, not the cell for a technology that is not implemented.

### Operating System and Version

 - Version 2022.11.21, develop

**Comment by cpaulgilman** [comment]
Also use this opportunity to disable Send to Excel to Equations for new IPH Single Owner configs because of electricity purchases.

**Comment by cpaulgilman** [comment]
In SSC, all financial models calculate the following from `CF_energy_sales`:

* O&M production-based expense (`CF_energy_sales` or `CF_energy_without_battery`), except Community Solar
* PBI
* PTC
* LCOE

These are currently calculated from `CF_energy_net` and should be changed to `CF_energy_sales`:

* TPO Host / Developer agreement cost
* Community Solar O&M production-based expense (CF_energy_net or CF_energy_without_battery)
* Community Solar recurring cost by generation
* Community Solar subscription revenue from generation

This should be removed (see #732):
 
* Community Solar return on equity (should this be removed?)
