### ISSUE TITLE
Fuel cell model does not report monthly energy

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1474]
For hybrid configurations, need monthly electricity from fuel cell for monthly energy autograph.

Fuel cell model reports "Fuel cell annual energy discharged" `fuelcell_annual_energy_discharged` and "Electricity from fuel cell" `fuelcell_power`. Would be useful to also have monthly energy discharged.

**Comment by sjanzou** [comment]
see https://github.com/NREL/ssc/issues/1056 and #1509
