### ISSUE TITLE
Update ITC and incentives interactions for host developer market only per test file

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1477]
Based on this article from SETO: https://www.energy.gov/eere/solar/homeowners-guide-federal-tax-credit-solar-photovoltaics, SAM's calculate ITC percentage inputs reduces the ITC basis by too much for a taxable incentive. Update the effects of "taxable" and "reduces basis" checkboxes to align with the guidance in the above article.

**Comment by sjanzou** [comment]
SETO article for residential and there is not basis reduction for ITC
![image](https://github.com/NREL/SAM/assets/6498311/8232e8cd-f2eb-4bba-8989-c43c3bd1551b)

Is there a specific SAM case/project file that shows what "effects" of the ITC percentage calculation is incorrect and for what markets?

**Comment by brtietz** [comment]
Whoops. This is the correct article: https://www.energy.gov/eere/solar/federal-solar-tax-credits-businesses

This SAM file shows a case where the ITC basis is reduced by a taxable investment based incentive: 
[ITC_basis_reduction.zip](https://github.com/NREL/SAM/files/14423022/ITC_basis_reduction.zip) The ITC credit should remain at $284,459 in this case (same as IBI)

This would also apply to CBI and PBI as well, assuming the taxable box is checked and the reduces bases box is unchecked.

**Comment by sjanzou** [comment]
> Whoops. This is the correct article: https://www.energy.gov/eere/solar/federal-solar-tax-credits-businesses
> 
> This SAM file shows a case where the ITC basis is reduced by a taxable investment based incentive: [ITC_basis_reduction.zip](https://github.com/NREL/SAM/files/14423022/ITC_basis_reduction.zip) The ITC credit should remain at $284,459 in this case (same as IBI)
> 
> This would also apply to CBI and PBI as well, assuming the taxable box is checked and the reduces bases box is unchecked.
> 
> I agree we should be consulting the rules for residences for the residential case. I believe the rules for businesses above apply to every other case.

In digging through the code, I think the disconnect is the updated installed cost based on any IBI or CBI applied as:
![image](https://github.com/NREL/SAM/assets/6498311/ebd38062-5f71-4ebb-b320-ddbf7f1d5ee2)

This value affects the ITC percentage as it is based on the installed cost and the Investments and Capacity based incentives act to reduce the installed cost BEFORE the ITC is applied.

So, do we want to rework that equation so that the ITC is always based on the installed cost before IBI and CBI are applied?

The proforma was constructed so that IBI and CBI are applied in year 0 and the ITC was applied in year 1
![image](https://github.com/NREL/SAM/assets/6498311/ad769e3e-7ad8-46f5-8e3d-0a6dfcdbb32b)

I am not sure how to proceed here...

**Comment by brtietz** [comment]
> Are you saying that the cost_installed in the code above should only be reduced if the IBI and CBI are not taxable?

Yes. Given the checkboxes in the UI, the default of "taxable" and "does not reduce basis" should not run this code. If taxable is not checked, or if reduces basis is checked, then this code should run. Alternatively, we could simplify the code to only run if "reduces basis" is checked, and solve the inter-dependency between the two checkboxes in the GUI/help.

**Comment by sjanzou** [comment]
Breaking this into separate issues for each financial market with this issue specific to hots developer and others will be updated accordingly.

**Comment by cpaulgilman** [comment]
I'm not sure exactly what the issue is here:

1. Is the goal for a IBI and ITC incentive to be the same, i.e., a 30% ITC for a commercial business and 30% direct pay incentive (IBI) for a tax-exempt entity should a) be the same dollar amount, and/or b) have the same effect on the cash flow? If this is true, then I think our test file should compare two cases, one with a 30% ITC and one with a 30% IBI, not a single case with both.

2. Under what conditions would you have both a 30% IBI and a 30% ITC?

3. Where in the [SETO article](https://www.energy.gov/eere/solar/federal-solar-tax-credits-businesses) does it explain the effect of an IBI or other cash incentive on the ITC basis?

**Comment by brtietz** [comment]
1. The goal of the test file is to show that the IBI and ITC should be the same in this case.
2. We encountered this case on PR-ERF, depending on how the incentive is structured.
3. See this discussion on tax basis, which indicated an error in the current behavior (reducing the ITC for taxable incentives):
![image](https://github.com/NREL/SAM/assets/5530592/02539eef-b8b3-4ac5-b512-1e2b7b1c6117)

**Comment by cpaulgilman** [comment]
@brtietz Thanks for the clarification.

Note the comment about the exception for PV at a residence: SAM's Host / Developer model may be used for a sytem installed on either a residential or commercial property, so we'll need to consider how to handle that correctly.

**Comment by brtietz** [comment]
Thanks. I think in that case the user could check the "reduces basis" box under my "alternatively" scenario above.

**Comment by brtietz** [comment]
I mocked up the first example (taxable with no basis reduction) below:

[SAM Financials.zip](https://github.com/user-attachments/files/15517172/SAM.Financials.zip)

The key distinction seems to be whether the incentive is taxable income (the case developed here) or a rebate considered reduction in sale price, which would result in a reduction in basis (see "decreases to basis" on https://www.irs.gov/publications/p551).

I think this requires a new variable. Net capital cost needs to remain as is for other cash flow calculations. 

@sjanzou and @cpaulgilman Does this approach make sense to you? If so I'll outline the next batch of cases (basis reduction, credit+ITC more than cost) and look for some reviewers within NREL.

**Comment by sjanzou** [comment]
> I mocked up the first example (taxable with no basis reduction) below:
> 
> [SAM Financials.zip](https://github.com/user-attachments/files/15517172/SAM.Financials.zip)
> 
> The key distinction seems to be whether the incentive is taxable income (the case developed here) or a rebate considered reduction in sale price, which would result in a reduction in basis (see "decreases to basis" on https://www.irs.gov/publications/p551).
> 
> I think this requires a new variable. Net capital cost needs to remain as is for other cash flow calculations.
> 
> @sjanzou and @cpaulgilman Does this approach make sense to you? If so I'll outline the next batch of cases (basis reduction, credit+ITC more than cost) and look for some reviewers within NREL.

@brtietz , what is the new variable and how does it affect the depreciation and ITC basis table:
![image](https://github.com/NREL/SAM/assets/6498311/aa223e2a-4dc8-436a-9557-73aef3b4ce08)

One of the key changes that has switched back and forth is the "issuance_of_equity" and the "purchase_of_property" and the "cost_installed" that have changed, e.g. host developer:
![image](https://github.com/NREL/SAM/assets/6498311/9f2198c8-ae6a-451c-858e-93017f687dd8)

My suggestion would to be to come up with more current terms and be consistent through all the financial models and to use as many IRS publications (or other citable publications) as reference going forward.

Maybe we should add another output table to breakdown the cost_installed and issuance_of_equity and purchase_of_property values use throughout the pro-forma for clarity?

**Comment by brtietz** [comment]
Apologies for not writing that up in more detail. The new variable is the sum of the negative cash flows from investing activities (i.e. without CBI or IBI):

![image](https://github.com/NREL/SAM/assets/5530592/3fb07709-90a5-494e-828d-20fa6a5f724f)

issuance_of_equity, purchase_of_property, and cost_installed should not change relative to patch, but the depreciation allocations and ITC basis should refer to this new variable (as I've set up in Excel in your screenshot).

Thoughts on naming the new variable? "gross_tax_basis"?

I'm a fan of "trace precedents" and "trace dependents" for creating that breakdown, but happy to create a short form.

**Comment by brtietz** [comment]
I think the only existing use of cost_installed that needs to change is: https://github.com/NREL/ssc/blob/6825d95b3263d0f1f3aa23a9661f646cd874ac0d/ssc/cmod_host_developer.cpp#L2285

where it should change to cost_prefinancing + cost_financing. I'd favor reporting that variable out in the cash flow, so it's more than a one line change.
