### ISSUE TITLE
solar_resource on_change callback not working

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/SAM#149]
In the patch branch, I get the following notice when starting any kind of project:

Could not evaluate callback function:solar_resource->on_change
[23]: reference to unassigned variable:librarygetnumbermatches
[23]: error: _s
[22]: eval error in statement list

Might be related to commit c6a802f59

**Comment by cpaulgilman** [comment]
There is a new set of LK functions including librarygetnumbermatches() to access information from the library widget. This issue may have been caused by building SAM with out-of-date WEX or LK library.
