### ISSUE TITLE
Nested input tables don't allow easy navigation back to results

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1505]
### Describe the bug

On develop, the view results graphic isn't always clickable after a simulation

### To Reproduce

1. Open a hybrids simulation on develop
2. Run the simulation
3. Click back to a general input, clicking to results is possible
4. Click back to an input under a technology model (battery life or similar)
5. One has to run the simulation again in order to get results

### Expected behavior

After running a simulation, the results icon should always be clickable

### Screenshots
Behavior as of step 3. Dark blue means it's clickable:
![image](https://github.com/NREL/SAM/assets/5530592/15ecfe18-aa69-4c8d-8345-841fc9b36f0f)

Behavior as of step 4:

![image](https://github.com/NREL/SAM/assets/5530592/85b9a20e-b1af-49e2-b948-ba3967755de4)

### Operating System and Version

 - OS: Windows
 - Version: Develop

**Comment by cpaulgilman** [comment]
Pretty sure this is a duplicate of https://github.com/NREL/SAM/issues/1485

**Comment by brtietz** [comment]
Sure is! Sorry that I missed that one,
