### ISSUE TITLE
Typo in PVWatts help docs

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1508]
### Describe the bug

The help documentation for PVWatts includes a link to a description of the physical model for IAM. The link is:

https://pvpmc.sandia.gov/modeling-steps/1-weather-design-inputs/shading-soiling-and-reflection-losses/incident-angle-reflection-losses/physical-model-of-iam/

which does not work. I think it should be:

https://pvpmc.sandia.gov/modeling-steps/1-weather-design-inputs/shading-soiling-and-reflection-losses/incident-angle-reflection-losses/physical-iam-model/

### Screenshots

<img width="613" alt="image" src="https://github.com/NREL/SAM/assets/45701090/e1e9321c-d665-4854-a901-c6ef30a776d9">

![image](https://github.com/NREL/SAM/assets/45701090/05216bf6-d853-4dda-b4ee-685f9d2d8ca8)

**Comment by janinefreeman** [comment]
Thank you for the bug report and the correct link!

**Comment by cpaulgilman** [comment]
The link is fixed in the working draft of Help and will be included in Fall 2023 release.
