### ISSUE TITLE
Fuel cell output not included in hybrid cashflow

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1509]
### Describe the bug

The fuel cell's power output is not registering in the cash flow for PPA sales

### To Reproduce

1. Run attached SAM case 
[fuel_cell_not_in_cashflow.zip](https://github.com/NREL/SAM/files/13034373/fuel_cell_not_in_cashflow.zip)

2. Fuel cell is running in one situation but not the other
3. Cash flow is the same, but it should be different

### Expected behavior

Fuel cell output should be included in cash flow

**Comment by sjanzou** [comment]
See https://github.com/NREL/ssc/issues/1056 and #1474
