### ISSUE TITLE
JSON code generation for hybrids

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#1515]
The code generation for hybrids needs to be updated.

For example, the JSON for inputs for the Generic PVWatts Wind Fuel Cell Battery Single Owner produces
<img width="1149" alt="image" src="https://github.com/NREL/SAM/assets/6498311/6c603229-b566-4eb9-b206-271dc7eef7d1">

The generated inputs should be able to be processed by cmod_hybrids and be structured like the defaults
<img width="675" alt="image" src="https://github.com/NREL/SAM/assets/6498311/eebe0de8-2d26-46cf-b046-a090f0363cdc">

**Comment by sjanzou** [comment]
Issue 1515 has been updated to JSON generation only for hybrids and the other languages have been moved to Patch 2 in Issue https://github.com/NREL/SAM/issues/1717 per the 2/27/2024 SAM meeting

**Comment by dguittet** [comment]
@sjanzou The hybrid Pvsamv1 JSON generation has UI variables, but the original Pvsamv1 JSON generation doesn't. Are the UI variables meant to be part of "JSON for inputs"?

**Comment by sjanzou** [comment]
> @sjanzou The hybrid Pvsamv1 JSON generation has UI variables, but the original Pvsamv1 JSON generation doesn't. Are the UI variables meant to be part of "JSON for inputs"?

Restored branch and not limited to compute module inputs only... the ssc test no longer runs for the patch branch and SAM_1515 branch of ssc since the additional inputs for costs and o and m are not included. Hopefully, this will work with the pysam_hybrids branch of ssc. 

Please test changes to codegenrator.cpp from SAM branch SAM_1515 with your ssc branch and let me know. Thanks!
