### ISSUE TITLE
UI callback error on System Design page for PV Battery configurations

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1520]
### Describe the bug

![image](https://github.com/NREL/SAM/assets/27711933/a710d990-a385-486d-8fc6-8b921b5666c5)

### To Reproduce

1. Create a PV Battery / Single Owner case.
2. Go to System Design page.

### Operating System and Version

 - OS: Windows 10
 - Version SAM Dev build

**Comment by cpaulgilman** [comment]
May be related to https://github.com/NREL/SAM/issues/1523

**Comment by sjanzou** [comment]
Note that #1548 does not fix this issue.

However, clicking on the Inverter page does fix the error
