### ISSUE TITLE
Documentation is vague about PVWatts temperature model

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1521]
### Describe the bug

The help docs does not clarify which temperature model is used by PVWatts (v8). It could be NOCT or Heat Transfer method, as far as I can tell.

<img width="916" alt="image" src="https://github.com/NREL/SAM/assets/45701090/fa0d5752-c42c-40e8-99d0-ca86f2b27eb2">

**Comment by cpaulgilman** [comment]
PVWatts V8 uses "NOCT method" to calculate cell temperature:

[Cell temperature model definition](https://github.com/NREL/ssc/blob/6c9fda04a7253385ed90b55dab5c3b2788b718d3/ssc/cmod_pvwattsv8.cpp#L442):

![image](https://github.com/NREL/SAM/assets/27711933/8f585245-0d98-4b51-8b62-b8cd0adf5dfb)

[Value of T_noct depends on array type](https://github.com/NREL/ssc/blob/6c9fda04a7253385ed90b55dab5c3b2788b718d3/ssc/cmod_pvwattsv8.cpp#L592)

![image](https://github.com/NREL/SAM/assets/27711933/68fa3e2b-f046-48a3-9118-213d14b64b7b)

Description in Help will be updated for Fall 2023 release.

**Comment by cpaulgilman** [comment]
PVWatts model description updated in Help database.
