### ISSUE TITLE
NSRDB geocoding issue

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1526]
### Describe the bug

Using the main "Download Weather Files" interface, I seem to be having issues with geocoding not working right. If I enter [lat], [lon], like "40.5137, -108.5449", the actually API query location is notably off (by 0.1 to 0.3 degreed). 

See the screenshot below:

<img width="862" alt="image" src="https://github.com/NREL/SAM/assets/45701090/63de93c9-b089-4dbc-b161-0025b8440f59">

When querying the same lat, lon through the NSRDB developer API, I get something closer to the desired location:

<img width="376" alt="image" src="https://github.com/NREL/SAM/assets/45701090/5a5db118-d7ff-4c78-bca3-0b52396b918e">

**Comment by cpaulgilman** [comment]
LK script for testing:

```
x = geocode('45.5,-120.3');
outln(x);
```

Note lat/lon in result are different than in request:

```
{ lat=45.3781 tz=-8 lon=-120.211 ok=1 }
```

**Comment by cpaulgilman** [comment]
Until we fix this, a workaround is to use the "Advanced download" option:

1. On Location and Resource page, check **Advanced download**.

    ![image](https://github.com/NREL/SAM/assets/27711933/a33ae6fc-888d-40cf-b572-75962a6a9d3f)

2. Type lat, lon values and choose TMY file (or other files as needed):

    ![image](https://github.com/NREL/SAM/assets/27711933/52b0a879-6e12-4379-98fe-af6bce380454)

3. After the file downloads, select it in the library list:

    ![image](https://github.com/NREL/SAM/assets/27711933/7553a022-5e83-4b1f-b686-956333486cbf)

4. Verify that the latitude and longitude in the downloaded file is correct:

    ![image](https://github.com/NREL/SAM/assets/27711933/9522ec06-5ce0-41e4-85cf-0ff5dcab1f7f)

**Comment by cpaulgilman** [comment]
See https://github.com/NREL/SAM/issues/1426
