### ISSUE TITLE
UI inputs for system design SDK features

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1543]
### Is your feature request related to a problem? Please describe.

-Add inputs for user input cell temperature arrays
-Add inputs for user input tracker rotation angles

### Describe the solution you'd like

-UI design that fits these inputs into the system design page

### Describe alternatives you've considered

-Previously SDK only

### Additional context

#850 , #106

**Comment by williamhobbs** [comment]
These features would be very nice to have!
