### ISSUE TITLE
Battery can charge from fuel cell dispatch option not available for hybrid with fuel cell

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1560]
### Describe the bug

On Battery Dispatch page for BTM hybrid configurations with fuel cells, **Battery can charge from fuel cell** option is not available.

### To Reproduce

1. Create a case with fuel cell hybrid.
2. Go to Battery Dispatch page.
3. Note missing option. (Compare to Fuel Cell - PV - Battery configuration.

### Expected behavior

Battery can charge from fuel cell should be available for all BTM configurations with battery and fuel cell.

**Comment by mjprilliman** [comment]
@cpaulgilman @brtietz A couple questions here: 

1. Should we be able to charge from fuel cell in hybrids for FOM and BTM?
2. Why are we using standalone battery dispatch pages for FOM but not BTM?

![image](https://github.com/NREL/SAM/assets/54449384/1ce53603-2b6f-435c-a781-643f5c073e35)

**Comment by cpaulgilman** [comment]
Note that the hybrid configurations with fuel cell do not use the `setup_pages_standalone_battery_dispatch_btm()` function.

> Why are we using standalone battery dispatch pages for FOM but not BTM?

Maybe for the new Self Consumption option? The `setup_pages_standalone_battery_dispatch_btm()` function excludes the Self Consumption option.

> Should we be able to charge from fuel cell in hybrids for FOM and BTM?

I think so.
