### ISSUE TITLE
Small UI Fixes for Fall 2023 Release

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1561]
This issue is to track small UI label, size, and alignment issues for the Fall 2023 release:

* Battery Dispatch BTM "Weather file for price signal forecast" should be "Weather file for retail rate dispatch."

**Comment by sjanzou** [comment]
Hybrid fuel cell cost per capacity is zero (capacity missing from calculation)
![image](https://github.com/NREL/SAM/assets/6498311/d5a6e387-d0c4-4830-b908-bdd889058264)

**Comment by cpaulgilman** [comment]
> Hybrid fuel cell cost per capacity is zero (capacity missing from calculation) ![image](https://user-images.githubusercontent.com/6498311/282039834-d5a6e387-d0c4-4830-b908-bdd889058264.png)

This is fixed by https://github.com/NREL/SAM/pull/1564

**Comment by mjprilliman** [comment]
![image](https://github.com/NREL/SAM/assets/54449384/e542ea97-436c-4f3e-8d70-51663c4d0d40)
Standalone battery capacity factor will always be zero as currently calculated ("capacity_factor" isn't provided to cmod_battery.cpp, so nameplate_in is set to its initialized value of zero, leading to Inf. Should we take it out of the table or come up with a capacity factor for standalone battery?

**Comment by cpaulgilman** [comment]
> Standalone battery capacity factor will always be infinity as currently calculated ("capacity_factor" isn't provided to cmod_battery.cpp, so nameplate_in is set to its initialized value of zero, leading to Inf. Should we take it out of the table or come up with a capacity factor for standalone battery?

1. I think we should remove capacity factor for Standalone battery configurations. 
2. It also seems like "Battery charge energy from system" will always be zero, so maybe that should be replaced by battery charge energy from grid, if there is such a metric.

**Comment by mjprilliman** [comment]
> > Standalone battery capacity factor will always be infinity as currently calculated ("capacity_factor" isn't provided to cmod_battery.cpp, so nameplate_in is set to its initialized value of zero, leading to Inf. Should we take it out of the table or come up with a capacity factor for standalone battery?
> 
> 1. I think we should remove capacity factor for Standalone battery configurations.
> 2. It also seems like "Battery charge energy from system" will always be zero, so maybe that should be replaced by battery charge energy from grid, if there is such a metric.

We don't have the charge energy from grid metrics set up in ssc currently, will probably have to be done in a patch.

**Comment by cpaulgilman** [comment]
These are all fixed in Develop as of 11/28/2023.
