### ISSUE TITLE
Remove "hybrid" from names in configuration tree

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1569]
All hybrids in the configuration tree have the word "hybrid" which does not add useful information since they appear under the "Hybrid" bin name.

However, the configuration tree uses "hybrid" to identify hybrid technologies. Removing it requires reworking how hybrids are implemented in the user interface.

**Comment by mjprilliman** [comment]
![image](https://github.com/NREL/SAM/assets/54449384/9e1aa744-7ec2-49f1-964c-f0d2c60d40ae)
Widget error when selecting 'Enable partial shading model'

**Comment by janinefreeman** [comment]
@cpaulgilman any objections to moving this to the fall release? If so, please undo my change.

**Comment by sjanzou** [comment]
> ![image](https://private-user-images.githubusercontent.com/54449384/283537039-9e1aa744-7ec2-49f1-964c-f0d2c60d40ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzM4MDksIm5iZiI6MTcyODYzMzUwOSwicGF0aCI6Ii81NDQ0OTM4NC8yODM1MzcwMzktOWUxYWE3NDQtN2VjMi00OWYxLTk2NGMtZjBkMmM2MGQ0MGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMDA4NzhiYTcyNWE5YjdiYTBiODk0MDMxNWU1ZGI4ZDZiMjNiNDgxYjI5YjUwZTMzZmVjMGE4NmU1YWY4OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u3MYtrNOuCE2zmFvSXM8lV5bvR9jJ7rOhdg8eeWCUUU) Widget error when selecting 'Enable partial shading model'

Tested with latest develop branches and SAM_1569 branch of SAM
![image](https://github.com/user-attachments/assets/5da67b4b-a20f-4c80-89ce-8764c8d20d0c)
