### ISSUE TITLE
Send to Excel with Equations issues

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1582]
### Describe the bug

-Send to Excel with Equations for Merchant Plant (maybe others) not populating years at top of Cash Flow table, showing analysis period of 0 years
-Misalignment of community solar revenue generation shares in Excel equations. 

### Expected behavior
-Analysis period should be copied from SAM
-Excel equations should align with the different classes of community solar subscribers

### Screenshots
![image](https://github.com/NREL/SAM/assets/54449384/d1c77ea3-6d66-4f36-a8d4-edfad678aad6)

[pvwatts_cs.xlsx](https://github.com/NREL/SAM/files/13384597/pvwatts_cs.xlsx)
[wind_mp.xlsx](https://github.com/NREL/SAM/files/13384598/wind_mp.xlsx)

**Comment by cpaulgilman** [comment]
@mjprilliman The analysis period issue may be related to #1563 where some data intermittently does not get passed from SAM to Excel.

1. Is the analysis period cell on the Inputs sheet always zero, or does it sometimes get set to the correct value? If you try a few times does it ever work correctly?
2. Do you get an OLE Automation Error when the analysis period value is incorrect?

**Comment by cpaulgilman** [comment]
@mjprilliman I fixed the community solar issue in the `SAM/fix-send-excel-cs-mp` branch -- thanks for finding that. However, I can't replicate the analysis period issue in SAM 2023.12.17. Could you test again, and if you are able to replicate it, attach an example .sam file? Thanks!
