### ISSUE TITLE
Set up battery charge from grid metrics for summary page of standalone battery

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1589]
> Standalone battery capacity factor will always be infinity as currently calculated ("capacity_factor" isn't provided to cmod_battery.cpp, so nameplate_in is set to its initialized value of zero, leading to Inf. Should we take it out of the table or come up with a capacity factor for standalone battery?

1. I think we should remove capacity factor for Standalone battery configurations. 
2. It also seems like "Battery charge energy from system" will always be zero, so maybe that should be replaced by battery charge energy from grid, if there is such a metric.

_Originally posted by @cpaulgilman in https://github.com/NREL/SAM/issues/1561#issuecomment-1815573904_

**Comment by cpaulgilman** [comment]
Item 1 is fixed, so only need to address Item 2 for this.

**Comment by mjprilliman** [comment]
@cpaulgilman I added this metric as I think it could potentially be helpful in other models, but the percentage will always be 100% for standalone batteries so maybe not so useful in the summary page. I suppose we can either put the kWh number in the summary page rather than the percentage, or rethink the metric table here for Standalone Battery.

**Comment by cpaulgilman** [comment]
I think replacing the current battery energy charge from system (%) with battery energy charge from grid (kWh) for standalone battery is a good solution.

One consideration is time frame: For PV battery, Help says the battery roundtrip efficiency (%) is over the analysis period. Energy charge from grid (kWh) would probably make sense as a Year 1 value to be consistent with annual energy for other technologies. Not sure if it's potentially confusing to have % over life and kWh for Year 1 in the same table.
