### ISSUE TITLE
PV and PVWatts sun angle calculations at high latitudes

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#159]
For latitudes above about about 61 degrees N (e.g., north of Anchorage AK) -- 
[northern_latitude_ak_weather_files.zip](https://github.com/NREL/SAM/files/2853387/northern_latitude_ak_weather_files.zip), SAM reports -999 for daytime sun angle values during summer months so that POA irradiance and system power generated goes to zero:

![image](https://user-images.githubusercontent.com/27711933/52599867-b570d000-2e0e-11e9-9198-a6ddd31a783b.png)

**Comment by janinefreeman** [comment]
Fixed with commit NREL/ssc@d8b2338de33ba8755606a39ee974adaf6d82f820
