### ISSUE TITLE
Parametrics import function doesn't work

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#1594]
The import function in parametrics is broken.

Steps to reproduce:
1. Open a case (I've tested with Detailed PV + Battery/Commercial and PVWatts/None)
2. Create a parametrics table (as simple as can be)
3. Export the table as a CSV
4. Attempt to import the CSV table
5. SAM hard crashes

The import function is broken in the current release as well, but gives an error message "Error: could not identify parametric variable run" rather than crashing. Given that we haven't gotten complaints about this so far, I'm going to give it a lower priority and assign it to the patch.

**Comment by janinefreeman** [comment]
I'm going to list this here because I'm guessing this is related: when you upgrade a file from a previous SAM version that has parametrics saved into it, it doesn't import the parametrics correctly and hard crashes if you try to simulate anyways:

1. Open the attached PVWatts 2022.11.21 case in the latest SAM develop build.
[pvwattsparametrics.zip](https://github.com/NREL/SAM/files/13398135/pvwattsparametrics.zip)
2. Go to parametrics and see that the "Tilt" input column no longer has a label:
![image](https://github.com/NREL/SAM/assets/12733546/b26c1a2f-5103-4e0f-affd-2889992ebd75)
3. Click "Run simulations" - SAM hard crashes.

**Comment by janinefreeman** [comment]
Update- this causes the MiniGrid wizard to crash because it uses the "parametric_import" lk function. Moving it back to the release.

**Comment by sjanzou** [comment]
> I'm going to list this here because I'm guessing this is related: when you upgrade a file from a previous SAM version that has parametrics saved into it, it doesn't import the parametrics correctly and hard crashes if you try to simulate anyways:
> 
> 1. Open the attached PVWatts 2022.11.21 case in the latest SAM develop build.
>    [pvwattsparametrics.zip](https://github.com/NREL/SAM/files/13398135/pvwattsparametrics.zip)
> 2. Go to parametrics and see that the "Tilt" input column no longer has a label:
>    ![image](https://private-user-images.githubusercontent.com/12733546/283952147-b26c1a2f-5103-4e0f-affd-2889992ebd75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzc0MTIsIm5iZiI6MTcwMTA3NzExMiwicGF0aCI6Ii8xMjczMzU0Ni8yODM5NTIxNDctYjI2YzFhMmYtNTEwMy00ZTBmLWFmZmQtMjg4OTk5MmViZDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA5MjUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZGJhMmM1NDFjNjRlYWVmNWRlYzNjNTcxMmY0OThmNjc2YWQyYzNhMWZmNjdiMGJjYTY2ZTgzNmZhODJlZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vzL24tKJo60qFcaoLsm12rPg1tdxNnhPA8rOHcOI5mQ)
> 3. Click "Run simulations" - SAM hard crashes.

Fixed with https://github.com/NREL/SAM/commit/6da195222ed3bca45fba6278ef2322978a25bf65

**Comment by sjanzou** [comment]
Import /Export working for non-hybrids with commit  https://github.com/NREL/SAM/issues/1594
