### ISSUE TITLE
Electricity bill calculation improvements

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#16]
* Apply end-of-year credit to following year for California NEM: https://sam.nrel.gov/forum/forum-general/1159

* Change month for end-of-year kWh rollover credit
For Residential and Commercial financial models, SAM applies any kWh rollover credits remaining in December 31 to the December electricity bill. Some states specify a different month, for example Maryland is end of April. Request is to add an input to specify the month for the "end of year" credit: https://sam.nrel.gov/forum/forum-general/1824. Duke Energy NC "resets accumulated excess on May 31" https://sam.nrel.gov/forum/forum-general/2170

* Allow separate TOU schedules for Saturday and Sunday per NamPower rates in Namibia: https://www.nampower.com.na/Page.aspx?p=178, and also as typical in South Africa: https://sam.nrel.gov/forum/forum-general/2969

**Comment by brtietz** [comment]
"Change month for end-of-year kWh rollover credit" is merged in to develop.

"Apply end-of-year credit to following year for California NEM" is partially implemented, the current implementation effectively delays the check by a month. See comments in https://github.com/NREL/ssc/pull/382 for how to improve the model.

Would recommend either implementing those comments or removing the checkbox prior to the 2021 release.

**Comment by sjanzou** [comment]
@brtietz, is the UI list of months enabled for all metering options?

**Comment by brtietz** [comment]
Yes
