### ISSUE TITLE
some rows in CEC Inverters library have garbage over 100 characters long

### ISSUE THREAD

**Issue by mikofski** [NREL/SAM#160]
in the latest [`CEC Inverters.csv`](https://raw.githubusercontent.com/NREL/SAM/develop/deploy/libraries/CEC%20Inverters.csv) bc0b83f098c394b97c9864449b03494476d44e55 :

    Canadian Solar Incorporated : CSI-50KTL-GS [480V]ÃÂÃÂ¢ÃÂÃÂÃÂÃÂÃÂÃÂ¢ÃÂÃÂÃÂÃÂ 480V [CEC 2018],480,70.467972,50083,50885.01172,650,-1.46E-07,-6.68E-06,-0.00007,0.001392,1,720,78.284633,580,720
    Canadian Solar Incorporated : CSI-50KTL-GS-FL [480V]ÃÂÃÂ¢ÃÂÃÂÃÂÃÂ 480V [CEC 2018],480,42.721951,50084,50863.50781,650,-8.06E-08,-2.35E-06,0.00449,0.011896,1,720,78.25155,580,720

There are more rows with garbage apparently characters.

Seems like this started in older [`CEC Inverters.csv`](https://raw.githubusercontent.com/NREL/SAM/3f11df28228984864c3869d9821ad75b3ce061af/deploy/libraries/CEC%20Inverters.csv) commit 3f11df28228984864c3869d9821ad75b3ce061af:

    Canadian Solar Incorporated : CSI-50KTL-GS [480V]ââ 480V [CEC 2018],480,70.467972,50083,50885.01172,650,-1.46E-07,-0.00007,-6.68E-06,0.001392,1,720,78.284633,580,720
    Canadian Solar Incorporated : CSI-50KTL-GS-FL [480V]â 480V [CEC 2018],480,42.721951,50084,50863.50781,650,-8.06E-08,0.00449,-2.35E-06,0.011896,1,720,78.25155,580,720

The names are inconsistent, and the garbage characters are growing longer

**Comment by cpaulgilman** [comment]
It looks like there are some hidden characters in the Excel workbook from the CEC that we didn't notice. We'll do some more processing to remove those so they don't end up in the SAM library file. Thanks for pointing this out.

**Comment by mikofski** [comment]
FYI: I uploaded the new files (not `-old`) for certain modules, inverters, and sapm modules from the SAM 2018.11.11 library to [pvfree](https://pvfree.herokuapp.com)

**Comment by cpaulgilman** [comment]
Fixed in aa60bc3b4262838faad759926cc9ee1876fc0f6a.

SAM's inverter library now only has data from current CEC database (dated 3/1/2019 for this update). We have removed the data accumulated from older databases.
