### ISSUE TITLE
Stochastic simulations for array inputs

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#161]
Some input variables like PV degradation are arrays that the SAM user interface allows you to enter either as single value or an array of values. A stochastic simulation does not work for an array of values because the algorithm determines a distribution for a single value. However, if the array only has a single value, stochastic simulations should be possible.

**Comment by janinefreeman** [comment]
Closed in e165953336ff254bd3ad5142a80f58d30f2b7bc8
