### ISSUE TITLE
Upgrading "adjust" variable doesn't work

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#1611]
"Custom periods" in the `adjust` variable are not upgrading correctly. The current version upgrade script on the version-upgrade-updates branch has a debugging msgbox showing the issue. There seems to be an issue switching between different matrix types, [ [x,y,z] ] and [ [x], [y], [z] ] for the `adjust_periods` variable.

Using the attached .sam file (created in SAM 2022.11.21), see that the "custom periods" loss is not upgraded correctly.
[upgrade.zip](https://github.com/NREL/SAM/files/13506608/upgrade.zip)

Once this is fixed, code needs to be updated in the version upgrader script in 3 places, currently lines 71, 104, and 114, which is all the places that the `adjust_periods` variable is set.

**Comment by cpaulgilman** [comment]
`adjust_periods` is not converted correctly for some files. To replicate:

1. Open test .sam file: [adjust-test-2022-11-21.zip](https://github.com/NREL/SAM/files/14843295/adjust-test-2022-11-21.zip)
2. Run simulation.
3. See error

```
adjust_periods:fail(adjust_periods, cols=3): 1
Simulation pvsamv1 failed :adjust_periods:fail(adjust_periods, cols=3): 1
gen not assigned
Simulation grid failed :gen not assigned
```
