### ISSUE TITLE
Marine Tidal resource default time series library not working

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1625]
### Describe the bug

1. On Marine Tidal model's Tidal Resource page, switching from **Frequency of occurrence** to **Time series** results in UI error messages:

```
Could not find library: TidalResourceData
```

```
Error 'COD0911' is not available in the library. Choose a different item.
```

2. When Frequency of Occurrence option is selected after switching to Time Series mode, simulation fails with SSC message:

```
Could not locate referenced library: TidalResourceData
Error preparing simulation.
```

### To Reproduce

1. Create a Tidal Resource / LCOE Calculator case.
2. On Tidal Resource page, click **Time series**.
3. See UI errors.
4. Click **Frequency of occurrence**.
5. Click **Simulate**.
6. See simulation error.

### Expected behavior

Time series tidal resource library should load correctly with a valid default file selected, and Frequency of Occurrence option should run regardless of state of Time Series option.

### Operating System and Version

 - Windows 10
 - Version 2023.12.1 rc

**Comment by mjprilliman** [comment]
Something is still missing in sam-private because the resource folder tidal_resource isn't in the release candidate build. @sjanzou any help on this?

**Comment by mjprilliman** [comment]
@cpaulgilman for the library load error could you try running this script, deleting TidalResourceData.csv, and restarting? I changed the columns for the data storage so it may be reading wrong if you've already had the library build on your machine. 

[Librarymetdataload.zip](https://github.com/NREL/SAM/files/13551827/Librarymetdataload.zip)

**Comment by cpaulgilman** [comment]
> @cpaulgilman for the library load error could you try running this script, deleting TidalResourceData.csv, and restarting? I changed the columns for the data storage so it may be reading wrong if you've already had the library build on your machine.
> 
> [Librarymetdataload.zip](https://github.com/NREL/SAM/files/13551827/Librarymetdataload.zip)

@mjprilliman Deleting the library file and restarting fixes the problem -- tested in a SAM-private build off of Develop.

**Comment by mjprilliman** [comment]
> > @cpaulgilman for the library load error could you try running this script, deleting TidalResourceData.csv, and restarting? I changed the columns for the data storage so it may be reading wrong if you've already had the library build on your machine.
> > [Librarymetdataload.zip](https://github.com/NREL/SAM/files/13551827/Librarymetdataload.zip)
> 
> @mjprilliman Deleting the library file and restarting fixes the problem -- tested in a SAM-private build off of Develop.

And on my side it seemed like https://github.com/NREL/SAM-private/pull/100 in sam-private build off of develop worked to fix the default error, but I'm not 100% sure that translates to what gets built for the rc.
