### ISSUE TITLE
"Photovoltaic" label missing in Hybrid Cashflows on energy line

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#1627]
First line annual energy values are correct, but label is missing "Photovoltaic" prepend in cashflow (see image). The "wind" prepend is there. The "photovoltaic" prepend is there for O&M costs, it is only missing for the PV annual energy. Missing in both the Single Owner and Host/Developer financial models. All hybrids that use PVWatts have the PVWatts annual energy correctly named. To replicate, run the default PV-Wind-Battery case with either SO or Host/Developer financial models, and look at the cashflow labels.

![Capture](https://github.com/NREL/SAM/assets/12733546/95a0238c-e0bb-449b-8e20-35b5f90fe4ef)

**Comment by mjprilliman** [comment]
![image](https://github.com/NREL/SAM/assets/54449384/197c6740-aaf5-48be-869b-4e2bd5dc8ede)

lowercase "annual" and uppercase "Energy" reads a bit weird in the metrics table, may be something for later. simulation.cpp line 1230.

**Comment by mjprilliman** [comment]
> First line annual energy values are correct, but label is missing "Photovoltaic" prepend in cashflow (see image). The "wind" prepend is there. The "photovoltaic" prepend is there for O&M costs, it is only missing for the PV annual energy. Missing in both the Single Owner and Host/Developer financial models. All hybrids that use PVWatts have the PVWatts annual energy correctly named. To replicate, run the default PV-Wind-Battery case with either SO or Host/Developer financial models, and look at the cashflow labels.
> 
> ![Capture](https://private-user-images.githubusercontent.com/12733546/288124618-95a0238c-e0bb-449b-8e20-35b5f90fe4ef.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDUwODQsIm5iZiI6MTcwMTgwNDc4NCwicGF0aCI6Ii8xMjczMzU0Ni8yODgxMjQ2MTgtOTVhMDIzOGMtZTBiYi00NDliLThlMjAtMzViNWY5MGZlNGVmLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE5MzMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MjUxMTA2Y2RjMTA0Y2VjMDVlMjcwNzEwNTU1ZWJjNzA2YTBmMzc0YmExNzE5NzIwM2U5MTdlZmFkNTU0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MYsUQ-f0aGNUbYuGbsE4xvnl3-gk7V7ri9tQjrThg48)

This is keying off of cf_energy_net in vtab_hybrid_tech_om vartable in common.cpp, still haven't identified why "Photovoltaic" isn't being carried over as prepend. It also shows up in Data Tables
![image](https://github.com/NREL/SAM/assets/54449384/bdaab62a-3716-4996-877b-2da591674b8c)

**Comment by mjprilliman** [comment]
![image](https://github.com/NREL/SAM/assets/54449384/77dfb146-c621-4ad1-b11b-029c4a077feb)
What is the purpose of comparing the length of the label and the prepend name on 1224? Seems like photovoltaic_ is == "annual_energy" so it's skipping that step.

**Comment by mjprilliman** [comment]
![image](https://github.com/NREL/SAM/assets/54449384/d216ba72-bfe2-41b6-9f1b-0c647e37ccd9)
'cEC' and 'pOA'
