### ISSUE TITLE
Inputs Browsers not working for some technology models

### ISSUE THREAD

**Issue by tyneises** [NREL/SAM#1630]
E.g. CSP, Marine:
![image](https://github.com/NREL/SAM/assets/27820293/372d463a-c244-4857-96f6-4f1b94110676)

**Comment by tyneises** [comment]
Inputs Browser still not working for Case Comparison *across technologies*. Except common inputs between Trough and Tower to show up in Different or Equal values. E.g. "ppa_price_input"
Show Different Values:
![image](https://github.com/NREL/SAM/assets/27820293/f0897318-d7c1-436e-ba26-4f2f3ff6fb11)

Show Equal Values:
![image](https://github.com/NREL/SAM/assets/27820293/a05416f2-7cc7-4071-b79c-69b1aa99d1c1)

Show All Values:
![image](https://github.com/NREL/SAM/assets/27820293/c955bf7f-e3be-411e-98c7-20604a822266)

![image](https://github.com/NREL/SAM/assets/27820293/179f273f-8098-4ed6-9560-e8dcea72338d)

**Comment by sjanzou** [comment]
> Inputs Browser still not working for Case Comparison _across technologies_. Expect common inputs between Trough and Tower to show up in Different or Equal values. E.g. "ppa_price_input" Show Different Values: ![image](https://private-user-images.githubusercontent.com/27820293/289115314-f0897318-d7c1-436e-ba26-4f2f3ff6fb11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU1NzMsIm5iZiI6MTcwMjE5NTI3MywicGF0aCI6Ii8yNzgyMDI5My8yODkxMTUzMTQtZjA4OTczMTgtZDdjMS00MzZlLWJhMjYtNGYyZjNmZjZmYjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA4MDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MzdmZTEyY2IwNTdmNjU1ZDBmMWIwMTExZmZmMGQ5MzM2ODg5NTk3Yjg1OTRhZDY5NjFmNDVmZjI5OGM5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RySmWFAP4jHHu25fmPvho4esb44TYRjzlrc3PJP3nv8)
> 
> Show Equal Values: ![image](https://private-user-images.githubusercontent.com/27820293/289116296-a05416f2-7cc7-4071-b79c-69b1aa99d1c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU1NzMsIm5iZiI6MTcwMjE5NTI3MywicGF0aCI6Ii8yNzgyMDI5My8yODkxMTYyOTYtYTA1NDE2ZjItN2NjNy00MDcxLWI3OWMtNjliMWFhOTlkMWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA4MDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NmU1NGFhODg0MmI5Y2EwMGIwZDRjNWI4YWJhZjdlY2MyODUyNzgyMGEzOTgzMmIyODdhY2RjNmI3YmIzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gsIHjd4fZAeVBhu4LmDCoEavr1tIjLHX0EwilBn96JQ)
> 
> Show All Values: ![image](https://private-user-images.githubusercontent.com/27820293/289115524-c955bf7f-e3be-411e-98c7-20604a822266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU1NzMsIm5iZiI6MTcwMjE5NTI3MywicGF0aCI6Ii8yNzgyMDI5My8yODkxMTU1MjQtYzk1NWJmN2YtZTNiZS00MTFlLTk4YzctMjA2MDRhODIyMjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA4MDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNjk1ZDU4Y2EwNTQ2NjEwZTJlNmQ2MWJmOTkxY2NhZWFmNTVmNDc0NjFlOGFlODk2ZTZhOWNiOGIxNjFlZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WG05oyJ6GnECz5Lf9Vj-LK9dhxYO4YcrngK5E7q65jY)
> 
> ![image](https://private-user-images.githubusercontent.com/27820293/289115875-179f273f-8098-4ed6-9560-e8dcea72338d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxOTU1NzMsIm5iZiI6MTcwMjE5NTI3MywicGF0aCI6Ii8yNzgyMDI5My8yODkxMTU4NzUtMTc5ZjI3M2YtODA5OC00ZWQ2LTk1NjAtZThkY2VhNzIzMzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA4MDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NDJjYzlmNDU3NDAwMDQyOGM3YTgzN2RlOGRlYzYwMGFiMDhhZGNlN2RlNTg1Y2VjMjAwNDNlNzJjZWViMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VILg-1Nh4i85cgxlndESJePIEugw0AZELBh7fNm2bLk)

@tyneises , closing this issue and working through input browser functionality in #1656
