### ISSUE TITLE
Inverter CEC upgrade script trips on existing inverters

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1647]
### Describe the bug

The version upgrade script is supposed to check to see if an inverter has been removed from the CEC library and make the user choose a new inverter if their project's inverter is no longer in the library. However, this appears to be happening for all inverters.

### To Reproduce

1. Open the attached SAM file in 2023.12.01 (or develop)
[inverter_upgrade_test.zip](https://github.com/NREL/SAM/files/13618618/inverter_upgrade_test.zip)
2. The version upgrade script forces choosing a new inverter when the inverter exists in the library.

### Expected behavior

The version upgrade script should skip the inverter replacement for this file.

### Screenshots
![image](https://github.com/NREL/SAM/assets/5530592/bf89f426-63a2-45f3-afdb-d0ab09aef7aa)

### Operating System and Version

 - OS: Windows
 - Version 2023.12.01/develop

**Comment by mjprilliman** [comment]
I'll take a look at this.

**Comment by mjprilliman** [comment]
Still looking into this. The right hand side of the  '?@' command on line 135 of version.lk has a m_type of 36, while the right hand side has m_type of 35. 

![image](https://github.com/NREL/SAM/assets/54449384/7224eeff-82fb-4644-84b1-7c96c56ace6b)
