### ISSUE TITLE
Unable to download wind data using the "Download a wind resource file from the online NREL WIND Toolkit" option

### ISSUE THREAD

**Issue by srikanthmadala** [NREL/SAM#165]
I am encountering the following error: 

"Retrieving data at lattitude = 39.74 and longitude = -104.99
Downloading data for 60m hub height.
Failed to read downloaded weather file C:\Users\smadala/SAM Downloaded Weather Files/lat39.74_lon-104.99__2013."

Any guidance on how to proceed is much appreciated. Thank you!

**Comment by cpaulgilman** [comment]
This is an issue with the NREL WIND Toolkit web service and not a SAM issue. The web service issue has been resolved, so the wind data downloads should work in SAM. For a discussion on the SAM support forum: https://sam.nrel.gov/node/80878
