### ISSUE TITLE
SAM_AdjustmentFactors missing variables required for PySAM

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#1661]
**Describe the bug**
Currently the AdjustmentFactors module is manually maintained, not regenerated by export_config. This was done because adjust used to have names with ":" that conflicted with the libSAMapi interface. Adjustment factors have since been modified and new variables have been added, but SAM_AdjustmentFactors and the PySAM adjustment factors haven't been modified to follow those changes.

The automatic generation is not possible with the code as-is for the following reason. In order to use hourly, period, or timeindex adjustment factors, the enabling variable is required, such as "adjust_en_hourly". These variables are however commented out: https://github.com/NREL/ssc/blob/75b4b1778d88234149bbb693d72914c2293ee721/ssc/common.cpp#L524

So they wouldn't make it to the PySAM interface.

**Expected behavior**
Adjustment factors need to have all the variables required for its use. 

Propose manually modifying the SAM_AdjustmentFactors and PySAM files for now.

**Comment by brtietz** [comment]
@dguittet should this be closed based on #1826 ?
