### ISSUE TITLE
REopt API call crashes SAM for weather file with subhourly data

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1671]
Clicking **Get size and dispatch** on Battery Cell and System page should check weather file time step and display UI message instead of proceeding with API call.

Tested with 15-minute data from NSRDB.

**Comment by brtietz** [comment]
The REopt documentation suggests it should work with 30 and 15 minute data. While we should add a UI message for other subhourly timesteps, the fact that 15 minute data fails suggests a bug in how SSC sets up the API call.

**Comment by cpaulgilman** [comment]
> The REopt documentation suggests it should work with 30 and 15 minute data. While we should add a UI message for other subhourly timesteps, the fact that 15 minute data fails suggests a bug in how SSC sets up the API call.

Agreed. Here are files for testing: [reopt-subhourly-tests.zip](https://github.com/NREL/SAM/files/13922517/reopt-subhourly-tests.zip)

* Two versions of the same .sam file, one for SAM 2022.11.21 and one for SAM 2023.12.17.
* 15-minute and 60-minute NSRDB weather files for same location and year.
