### ISSUE TITLE
Electricity bill with system changes for same inputs, different simulations

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1676]
### Describe the bug

For the BTM financial models, running multiple simulations without changing inputs results in different bill with system.

Issue as reported on SAM forum for PV-Battery / TPO Host-Developer with self-consumption dispatch (includes example file): https://sam.nrel.gov/forum/forum-general/4493-pv-battery-bill-savings-results-change-every-time-i-click-simulate.html

### To Reproduce

1. Create a default PV-Battery / Residential case.
2. Run simulation and note Year 1 electricity bill with system on Summary tab.
3. Run another simulation without changing inputs and note different bill with system.

### Expected behavior

Bill with system should not change when rerunning simulations for PV-Battery with TPO-Host Developer, TPO Host, Residential, or Commercial financial models.

### Operating System and Version

 - OS: Windows 11
 - Version: SAM 2023.12.17

**Comment by brtietz** [comment]
I had also noticed that some of the electricity to/from grid outputs from the utility rate code didn't match the ones from the battery, but hadn't had time to nail it down and file a bug yet. May be related to this.

**Comment by cpaulgilman** [comment]
This only seems to be an issue for battery systems. For example, PV / Residential does not exhibit this behavior.

**Comment by cpaulgilman** [comment]
Possibly related is difference between "Electricity load (year 1)" and "Lifetime electricity load." For example see these results for default PV-Battery / Commercial case:

SAM 2022.11.21, year 1 load and lifetime load are the same:

![image](https://github.com/NREL/SAM/assets/27711933/0ceb2b53-d81e-4707-b2b6-915da417bcfb)

SAM 2023.12.17, year 1 and lifetime load are different:

![image](https://github.com/NREL/SAM/assets/27711933/521d73c6-e5ff-4556-962a-a4747411c3c4)
