### ISSUE TITLE
Request to add a new solar manel (Amerisolar AS-7M120-HC-460W)

### ISSUE THREAD

**Issue by SebaNahuel** [NREL/SAM#1677]
Hello
We are from the National University of Hurlingham Argentina
And in the photovoltaic configuration we are working with, we have the "Amerisolar AS-7M120-HC" solar panel which is not found in the CSV
We wanted to know if you could add it.
We have the manufacturer's Datasheet, but there is data that we do not have.
It would be of great help for our project if the panel we are working with could be added to the CSV.
From already thank you very much.

[http://www.weamerisolar.com/d/file/english/product/pro11555/2021/06-25/846a2b1a34a6d37873fc465434d46b08.pdf](url)

**Comment by cpaulgilman** [comment]
@SebaNahuel Please see this post on the SAM forum for information about modules and inverters that are not in SAM's libraries: https://sam.nrel.gov/forum/forum-general/2768-pv-modules-and-inverters-not-in-database.html

We create the libraries with data from the California Energy Commission (CEC) Solar Equipment Lists: https://www.energy.ca.gov/programs-and-topics/programs/solar-equipment-lists
