### ISSUE TITLE
P50/P90 simulations do not work for wind

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1681]
P50/P90 simulations is checking for solar resource files instead of wind resource files.

```
Invalid File P50/P90 simulations do not work with the file extension. Only csv, srw, smw, epw amnd tm2 file extensions are supported. please remove any files with invalid extensions from the weather file folder.
```

See https://sam.nrel.gov/forum/forum-general/4503-p50-p90-simulation-error for description and set of wind resource files for testing.

**Comment by cpaulgilman** [comment]
May be related to https://github.com/NREL/SAM/issues/1734

**Comment by sjanzou** [comment]
Zip file of weather resources not available at https://sam.nrel.gov/forum/forum-general/4503-p50-p90-simulation-error.html#12846
