### ISSUE TITLE
Fix PV land area calculations

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1682]
There are several issues with PV land area calculations:

* Land area calculation is inconsistent for different shading options
* Variable labels are misleading
* Documentation is incorrect

See https://sam.nrel.gov/forum/forum-general/4494-land-area-tilt-and-ground-coverage-ratio.

**Comment by cpaulgilman** [comment]
PVWatts land area calculations are still incorrect: For default PVWatts / Single owner, I expect ground area to be total module area / GCR or 130.055 / 0.3 = 433.517:

![image](https://github.com/NREL/SAM/assets/27711933/dcd03bb2-38b0-407f-a5d0-bcd1f7c52fc5)

Here are the correct equations:

Module Area (m2) = Nameplate Capacity (kWdc) / Module Efficiency / (1kW/m2)
Module Area (acres) = Module Area (m2) / 4046.86 (m2/acre)
Ground Area (acres) = Module Area (acres) / GCR * Land Area Multiplier
Land Area (acres) = Grond Area (acres) + Additional Land Area (acres)

**Comment by mjprilliman** [comment]
Looks my changes to the PVWatts calculations didn't get saved in the land area form in the PR.

**Comment by cpaulgilman** [comment]
@mjprilliman Yeah, I'm not sure what happened there -- I'll create a new PR for your review.
