### ISSUE TITLE
Detailed PV and PV-Battery hourly and hourly lifetime discrepancy

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1684]
### Describe the bug

For the Detailed PV and PV-Battery (pvsamv1) model, outputs reported as "hourly" and "hourly lifetime" have different values for some time steps. Attempting to reconcile hourly "electricity to x from y" with hourly lifetime variables like "System power generated" and "Electricity to/from grid AC" makes it unclear to users what data SAM is using for bill calculations, battery dispatch, electricity to/from grid, etc.

See attached .sam files and Excel workbook: [test-hourly-vs-lifetime.zip](https://github.com/NREL/SAM/files/14059146/test-hourly-vs-lifetime.zip)

Tested on Windows 11 with SAM 2023.12.17 and SAM 2022.11.21.

**Comment by brtietz** [comment]
Electricity to/from grid for lifetime is calculated by the battery, whereas for hourly (non-lifetime) it is calculated by utility rate 5. I suspect https://github.com/NREL/SAM/issues/1676 is also the cause of this issue.

In the battery code, we have lines that round anything less than 0.002 kW to zero. If we want these to align perfectly we should add similar lines to the hourly (non-lifetime) computations.
