### ISSUE TITLE
Add $/kW for battery replacements to be consistent

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#169]
Currently, battery replacements are specified on a $/kWh basis, while battery costs on the System Costs page are $/kW and/or $/kWh.

**Comment by cpaulgilman** [comment]
See also https://github.com/NREL/SAM/issues/355

**Comment by cpaulgilman** [comment]
Closing duplicate issue (see #355)

**Comment by n8blair** [comment]
OK, my comment on this is that we likely should leave the replacement cost as $/kwh.  While a full new storage system includes battery packs, containers, installation, a ariety of soft costs, etc. it is safe to envision that a replacement in 10 years (particuarlly for large systems) will be (1) cheaper and (2) likely to just replace the battery pack and not require all the same interconnection, soft csots, etc.  Therefore, those issues combined wtih the uncertainty of future costs and the ATB having both future $/kW and $/kwh costs, it would be confusing if we implied that the entire battery needs to be replaced including all of the support structures and inverter, etc.
