### ISSUE TITLE
Add error checks for database specs

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#17]
NREL doesn't maintain the CEC module and inverter databases, but sometimes the specifications in the CEC databases are wrong. We encourage users to report the issues directly to the CEC; however, it might be nice to also have a few simple mechanisms in place to alert the user that the specs for the component they've chosen look suspicious.

For both the inverter and the modules, we could display some warnings (probably in the UI?) when specs are either not physical (negative or zero voltages, etc) or not self-consistent (voltage and current don't multiply to the same order of magnitude as power, etc). More thought is needed to figure out what we could check for, and how to best display it.

**Comment by cpaulgilman** [comment]
Hi Allen,

Thanks for offering to help!

The process we use to build SAM's module and inverter libraries from the data in the CEC lists is:

1. Download the appropriate Excel file (.xlsx) from the [CEC Solar Equipment Lists](https://www.energy.ca.gov/programs-and-topics/programs/solar-equipment-lists) website.

2. Manually process the Excel file to remove unneeded rows information and clean up some things like extraneous Greek characters, and tabs, commas and line breaks within cells.

3. Save the cleaned-up Excel file as CSV.

4. Run a script to convert the data in the CSV file to SAM's library format. This involves running code for each module or inverter to calculate model input coefficients from the datasheet parameters in the CEC data that are in SAM's library file but not included in the CEC data. (For example, the module coefficient generator calculates coefficients for the 6-parameter single diode module model like light current and reverse saturation current.)

5. Run a test script to identify any modules and inverters that cause simulation problems and manually remove them from the list. In this step, we do some checks on the inverter data to try to identify suspicious ones.

I am happy to share the scripts we use and more details of the process.

We have been wanting to convert these scripts from SAM's LK scripting language to Python with the PySAM package, but have not had time to do that.

One other note is that the CEC Solar Equipment Lists website mentions that they are changing the format of the equipment lists after October 31, 2021, so we will likely need to update our process to work with the new format: https://www.energy.ca.gov/programs-and-topics/programs/solar-equipment-lists.

Thanks,
Paul.

**Comment by cwhanse** [comment]
@allenlawrence94 pvlib includes a function showing how to access the SDK functions to run the parameter estimation code.. See `fit_cec_sam` [here](https://github.com/pvlib/pvlib-python/blob/master/pvlib/ivtools/sdm.py); maybe helpful for this effort.

A few years back @janinefreeman and I had some discussion about rehosting the parameter generation capability outside of SAM, and to smooth over some of the cracks between the SAM parameter files and other applications making use of those files. Some of that conversation is in this [thread](https://github.com/pvlib/pvlib-python/issues/761#issuecomment-523610210).  We set up a project [here](https://github.com/pvlib/pvmodules) to contain a parameter generation engine but didn't get past that point. For my part I'm happy to help build and maintain that engine.

It is my opinion that a separate open-source engine translating the CEC database to model parameters would benefit the modeling community, including SAM developers and users.

**Comment by allenlawrence94** [comment]
@cwhanse - I think having a separate open source engine for this is an awesome idea! I'm mid-way through a prototype script for pv modules. Once I get in working order, how about I open a PR to pvlib/pvmodules?

Thanks for the guidance and support.

**Comment by cpaulgilman** [comment]
@cwhanse The SSC code (C++) that calculates the inverter model parameters ("coefficient generator" or "cg" in SAM lingo) is here: https://github.com/NREL/ssc/blob/develop/ssc/cmod_inv_cec_cg.cpp

The SSC code that calculates module model parameters for SAM's 6-parameter single-diode module model is here: https://github.com/NREL/ssc/blob/develop/ssc/cmod_6parsolve.cpp

These are SSC compute modules, so they can be accessed using any of the following methods:

* In SAM, using the ssc_exec() function in SAM's LK scripting language.
* In a Python script using the [PySAM package](https://sam.nrel.gov/software-development-kit-sdk/pysam.html)
* In any of the languages for which there is a wrapper in the [SAM SDK](https://sam.nrel.gov/software-development-kit-sdk.html)

**Comment by allenlawrence94** [comment]
Sorry for the radio silence @cpaulgilman! @kanderso-nrel for visibility (thanks for reminding me about this).

I have a simple (and messy) notebook that generates coefficients for the CEC modules dataset using PySAM, but I never figured out how to handle all the missing/erroneous data. I've had to shift focus away from this, but I'll clean up and push what I currently have to [pvmodules](https://github.com/pvlib/pvmodules) in case someone else can pick up my slack before I come back to this.

**Comment by allenlawrence94** [comment]
PR here: https://github.com/pvlib/pvmodules/pull/11

**Comment by cpaulgilman** [comment]
Scripts and instructions for the process NREL uses to generate module and inverter library CSV files from CEC Excel workbooks are here: https://github.com/NREL/SAM/tree/develop/samples/CEC%20Module%20and%20Inverter%20Libraries
