### ISSUE TITLE
Trough loop configuration does not update on SCA/HCE input pages

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1703]
### Describe the bug

For the Physical Trough model, the loop configuration representation on the Collectors (SCAs) page does not update to match the "Single Loop Configuration" on the Solar Field page:

![image](https://github.com/NREL/SAM/assets/27711933/e1c73ec4-ed07-4631-81a1-eeb63e8be809)

![image](https://github.com/NREL/SAM/assets/27711933/2f202691-7156-4c7b-af1e-3144a3b33648)

Note that the representation on the Receivers (HCEs) page does update correctly:

![image](https://github.com/NREL/SAM/assets/27711933/3f9596bb-0ca6-4406-8c4f-9550f450f246)

Reported on SAM forum: https://sam.nrel.gov/forum/forum-general/4526

### To Reproduce

1. Create a Physical Trough / Single Owner case.
2. On the Solar Field page, edit the Single Loop Configuration diagram so that there are at least two SCA types.
3. Note the representation on the Collectors (SCAs) page.

### Operating System and Version

SAM 2023.12.17 for Windows

**Comment by tyneises** [comment]
@taylorbrown75 can you please investigate?
