### ISSUE TITLE
SAM 2023.12.17 r1 release candidate doesn't start on Linux

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1728]
After installing SAM 2023.12.17 r1 on Linux, starting SAM results in:

```
undefined symbol tidal_turbine_calculate_powercurve
```

![linux-run-error](https://github.com/NREL/SAM/assets/27711933/48970155-87c7-4c6f-b4b7-097d20ee7be7)

**Comment by sjanzou** [comment]
Hmmm... downloads and starts fine on RHEL 8
![image](https://github.com/NREL/SAM/assets/6498311/264d27ac-d60f-487e-889b-8d90ab0ea733)

**Comment by sjanzou** [comment]
> After installing SAM 2023.12.17 r1 on Linux, starting SAM results in:
> 
> ```
> undefined symbol tidal_turbine_calculate_powercurve
> ```
> 
> ![linux-run-error](https://private-user-images.githubusercontent.com/27711933/309831080-48970155-87c7-4c6f-b4b7-097d20ee7be7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTc0NDMsIm5iZiI6MTcwOTYxNzE0MywicGF0aCI6Ii8yNzcxMTkzMy8zMDk4MzEwODAtNDg5NzAxNTUtODdjNy00YzZmLWI0YjctMDk3ZDIwZWU3YmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA1MzkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YTIwMmExZmRlNmMwNDM4NWQ3NzhjNDA4NmEwOTFiNmIyOWRiZDRlODNkOWFjMjVhMGE1OTQxYzc5Yzc5MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9vXiwW6WnqL9ZFnqsVZk0m0_zu5csTvo2T0z-EaR17A)

The "tidal_turbine_calculate_powercurve" is an equation defined in ssc/ssc_equations.h
![image](https://github.com/NREL/SAM/assets/6498311/bef24b20-4c1c-41c6-9919-d1edf22bfa62)

Is there another ssc.dylib somewhere on your path on the Linux machine that could be conflicting with the 2023.12.17.r1 installation?

**Comment by sjanzou** [comment]
Setup a clean Ubuntu 20.04.6 desktop and download and install sam-linux-2023-12-17-r1.run
![image](https://github.com/NREL/SAM/assets/6498311/7015be59-8bb2-461d-8b52-559242d8eafe)

registers and runs without issue
![image](https://github.com/NREL/SAM/assets/6498311/38dbd551-e973-48a1-b0b4-576632ead983)

METidal
![image](https://github.com/NREL/SAM/assets/6498311/21000ad4-1951-4e17-bada-1e7d1f2a8574)

**Comment by brtietz** [comment]
@sjanzou I get the same (successful) results as you on an Ubuntu 20.04 VM, including METidal running.

@cpaulgilman Please let us know if Steve's suggestions turn anything up. For what it's worth, `which ssc.so` returns nothing on my VM.

**Comment by cpaulgilman** [comment]
`which ssc.so` returns nothing like @brtietz.

![Screenshot from 2024-03-05 12-31-34](https://github.com/NREL/SAM/assets/27711933/8f0e3cde-c6f4-495e-bdd0-9847a31cafb0)

**Comment by cpaulgilman** [comment]
![Screenshot from 2024-03-05 12-47-37](https://github.com/NREL/SAM/assets/27711933/0acecebb-30b3-42c5-819e-9c31140cdc23)

**Comment by sjanzou** [comment]
> ![Screenshot from 2024-03-05 12-47-37](https://private-user-images.githubusercontent.com/27711933/310274426-0acecebb-30b3-42c5-819e-9c31140cdc23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzIzNTYsIm5iZiI6MTcwOTY3MjA1NiwicGF0aCI6Ii8yNzcxMTkzMy8zMTAyNzQ0MjYtMGFjZWNlYmItMzBiMy00MmM1LTgxOWUtOWMzMTE0MGNkYzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIwNTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MTZkNTE2OGUxOWZiYWJlYTJhNGRhY2RiYmNhMTYzMGFhZjg0N2I4NzdmZWQwMzBlZTEwMzIyYTZhMzAwNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZeEI7OClUEALOzrrn8BmjnfXhhVYT5DFO4LqMIF7cuw)

@cpaulgilman , please delete or rename the ssc.co in usr/local/lib - that is probably a different version causing the issue.

**Comment by cpaulgilman** [comment]
Solution was to edit my bash configuration file (`bashrc`). It had `export LD_LIBRARY_PATH=/home/paul/SAM/2023.11.1/linux_64` (pointing to a previous internal version) so SDKtool would work. Either deleting that line or changing the version number to `2023.12.17` fixed the problem.

**Comment by cpaulgilman** [comment]
Fixed by editing bash config file.
