### ISSUE TITLE
Simulation fails from Federal straight line depreciation check even when it is disabled

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1733]
### Describe the bug

The `cashloan` module generates a simulation error about Federal straight line depreciation not being positive even though it is not enabled:

![image](https://github.com/NREL/SAM/assets/27711933/936cde81-e00f-44d7-ad51-b6a55d1e913d)

Simulation error:

```
depr_fed_sl_years:fail(depr_fed_sl_years, positive): 0
Simulation cashloan failed :depr_fed_sl_years:fail(depr_fed_sl_years, positive): 0
```

### Workaround

Workaround is to set Federal straight line depreciation to a positive number like 1, even when Federal straight line depreciation is not enabled.

### To Reproduce

1. Create a default PVWatts / Commercial case.
2. On the Finanical Parameters page, set Federal depreciation to **No depreciation**.
3. Set Straight line to 0.
4. Click **Simulate**.
5. See error.

### Expected behavior

If Federal or State depreciation is not set to the straight line option, SAM should not check the value of straight line depreciation.

### Operating System and Version

 - SAM 2023.12.17 r1 (also SAM 2023.12.17)
 - Windows 11

**Comment by sjanzou** [comment]
Note that this is now the expected behavior due to https://github.com/NREL/SAM/issues/1184
