### ISSUE TITLE
REopt API call for default PV Battery / Commercial returns battery size of zero

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1742]
For the default PV Battery / Commercial case, clicking **Get size and dispatch** on the Battery Cell and System page intermittently returns an optimal battery size of zero. 

![image](https://github.com/NREL/SAM/assets/27711933/0a0bd050-eb17-4b7c-97ce-126266f10a52)

After trying three times:

![image](https://github.com/NREL/SAM/assets/27711933/58c6a2c3-35bc-4d3b-a313-f46cc22cab08)

**Comment by brtietz** [comment]
As of 4/17, this has changed to:

![image](https://github.com/NREL/SAM/assets/5530592/c4abd7ab-fda5-4753-8b91-450574f570d9)

Given that the default case has net metering, we may need to assess implementing some of what is discussed here: https://github.com/NREL/REopt-Analysis-Scripts/discussions/149 for the SAM API call.

**Comment by brtietz** [comment]
Notes from the REopt team:

- If trying to specify a fixed PV size, don't supply both existing and max kW - this could lead to double the PV onsite
- Set net_metering_limit_kw to the generator size if the system will receive net metering credits at that system size.
