### ISSUE TITLE
Snow loss reported incorrectly

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#176]
Hourly DC snow loss value is incorrectly reported. This issue appears to have been introduced in SAM version 2018.11.11 (SSC 198).
For example for default PV/No Financials case using Fargo, ND MTS 1 weather file with snow enabled, 
SAM 2017.9.5 reports total snow loss of 11%/yr, and SAM 2018.11.11 r3 reports 0.82%.
See [snow_issue.zip](https://github.com/NREL/SAM/files/3133388/snow_issue.zip) for sample files and details.

**Comment by sjanzou** [comment]
Fixed in patch 6b322b36b6081449cde23f83b87093f2cea53400 and develop 6e6bc3c6b5726886c9eebac093a7aec0abc29f16 branches of ssc commits and have 11% per year and match with 2017.9.5 snow loss 
![image](https://user-images.githubusercontent.com/6498311/57014029-69425a00-6bcb-11e9-882f-ace7ccb63085.png)
