### ISSUE TITLE
Application window text unreadable

### ISSUE THREAD

**Issue by lukolszewski** [NREL/SAM#1771]
### Describe the bug

Upon opening the app window GUI elements have weird sizes. Text does not appear to fit and once a new project is started the main window text is unreadable.

### To Reproduce

1. Run SAM installtion. Go to the folder. Run the app.
2. Skip registration
3. Click start a new project, choose Photovoltaic, Detailed PV Model, No Financial Model and press OK
4. The main window text is all on top of eachother/ 

### Expected behavior

Text and GUI elements that make use of the entire window and are not bunched up in the corner all on top of eachother.

### Screenshots

![image](https://github.com/NREL/SAM/assets/43611481/0e0ea7a6-2744-4a9e-aa08-b54836787a33)

### Operating System and Version

Debian bookworm,

### Additional context
 Nvidia GPU proprietary driver, 4K screen. GNOME desktop set to 168DPI, text size set to 1.5.

**Comment by cpaulgilman** [comment]
See this discussion on the SAM forum: https://sam.nrel.gov/forum/forum-general/2854-text-not-displaying-properly-in-linux.html

Closing as a duplicate: https://github.com/NREL/SAM/issues/153
