### ISSUE TITLE
Improve help docs/UI related to IEC spectral response

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1781]
Based on the interface and Help docs, it isn't clear which spectral response coefficients are which in the IEC61853 model input tab (it looks like SAPM A0-A4, in that order, but I'm not 100% sure).

**Comment by cpaulgilman** [comment]
We'll add this to the list for the second update to SAM 2023.12.17, and also try to improve the description of spectral response built-in assumptions for the other module models.
