### ISSUE TITLE
Third Party Ownership model does not include load download macros

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#18]
Need to decide whether to include "Download Electric Load" macro for residential buildings or commercial buildings, or both.

**Comment by sjanzou** [comment]
Fixed in release branch with commit 8f2660108603d14a3da7647f3ed5209dfdb45d7b

**Comment by cpaulgilman** [comment]
Need to modify download load macro to allow user to choose between residential and commercial building database for third party ownership models.

**Comment by cpaulgilman** [comment]
Fixed in 0ee303ba8b3c27953fb1c9f92525a3ae60e2d193.
