### ISSUE TITLE
Utility bill enhancements for Michigan

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#180]
In Michigan, for net billing with carryover to next month, excess generation credits do not apply to fixed charges. SAM applies the credit to the entire bill, but in this case perhaps should apply it only to the energy charge portion of the bill (not sure about demand charge).

For description:

https://sam.nrel.gov/forum/forum-general/2267-modeling-pv-rate-schedules.html#6783

**Comment by brtietz** [comment]
It looks like we might have solved this in some of the previous utility rates work. In the SAM file below (with a fake rate) the owner receives a $20.44 credit in April of the first year, but still pays the minimum to the utility:

![image](https://user-images.githubusercontent.com/5530592/101197363-41c13800-361f-11eb-81b3-4e8e10c0265a.png)

[net_billing_w_minimum.zip](https://github.com/NREL/SAM/files/5644497/net_billing_w_minimum.zip)

Leaving open for now. @cpaulgilman can you double check this when convenient?
