### ISSUE TITLE
Update depreciation and ITC gross basis based on improved understanding of allowable fees

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1803]
See conversation on https://github.com/NREL/ssc/pull/1178/. We no longer believe reserves and financing fees are allowable costs in the depreciation and ITC basis, but don't  want to remove them in a patch since we have no way to notify users. Remove these expenses from the basis unless we can find cases where they are allowable.

**Comment by brtietz** [comment]
https://www.seia.org/research-resources/cost-basis-itc-and-1603-applications has a good discussion of developer fees for the partnership flip model (the checkbox should also probably apply to these).

**Comment by brtietz** [comment]
For partnership flip, the following are allowable:

![image](https://github.com/user-attachments/assets/3a4f40f7-9989-42eb-aa9e-dbbf68d8c78f)

(from https://www.irs.gov/pub/irs-pdf/p551.pdf, pg 3)

This matches the help description of the equity closing cost and potentially the "other financing cost"

The SEIA article above discourages developers having an ownership stake if the developer fee is to be rolled into the basis. That said, it might be less confusing for users if fees in "project term debt" are excluded from the basis and fees in "cost of acquiring financing" are included (and adjusted on the depreciation page as needed).

**Comment by brtietz** [comment]
Community solar upfront fees https://sepapower.org/knowledge/community-solar-cost-allocation-strategies-lessons-from-six-utilities/ suggests these should be amortized (therefore not depreciated):

![image](https://github.com/user-attachments/assets/9cc80413-7d8c-41e2-8a62-eca213185d3c)

**Comment by cpaulgilman** [comment]
Now that NREL/ssc#1193 is ready:

1. Update the send to Excel files on a new branch from develop.
2. Run test_script_ow.lk for updated SSC results (expecting NPVs to decrease and LCOEs to increase).
