### ISSUE TITLE
Ancillary Services addition to Single Owner PPA Financial Market

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#182]
Add Capacity Payment inputs and output revenue stream to the Single Owner PPA financial market.
Add Curtailment with optional Payment inputs and output revenue stream to the Single Owner PPA financial market.
Add interconnection limit with no compensation to the Single Owner PPA financial market.

**Comment by cpaulgilman** [comment]
https://github.com/NREL/SAM/commit/27a74f854ecccebc0d94275d8103136a97773e2d
