### ISSUE TITLE
Hybrids Depreciation Allocation defaults do not match other models

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1829]
Hybrids depreciation defaults as of the release candidate for 2023-12-17-r2:

![image](https://github.com/user-attachments/assets/eb0a3787-3766-4ebc-a0dc-ad236e1fb8e5)

As compared to PVWatts-Single Owner:

![image](https://github.com/user-attachments/assets/29a6b92a-40cf-4f81-bd79-f7671f204ba2)

Consider updating to match. (PV-Battery-Fuel cell matches the other hybrids)

Additional consideration: anything with "generic system" probably shouldn't have assets qualify. Consider if this case should have different default allocations.

**Comment by cpaulgilman** [comment]
The default allocations are based on a utility-scale PV system (based on work done in 2011). I'm not sure if they would be appropriate for a hybrid system or other types of systems. Assuming 100% 5-yr MACRS allocation is a simplification, but may be appropriate when more information is not available.

**Comment by brtietz** [comment]
My other concern is that the ITC qualification box is unchecked in a case where there are eligible assets. Perhaps the fix is just to check the ITC box?

**Comment by brtietz** [comment]
Consolidated in https://github.com/NREL/SAM/issues/1855
