### ISSUE TITLE
Add Merchant Plant Financial Market to SAM

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#183]
Utility level Merchant Plant financial market to be added to compete in Ancillary Services markets. Utility level financial market with  Capacity Payment, Energy Market, Ancillary Service inputs and output revenue streams and Curtailment with optional Payment inputs and output revenue stream and interconnection limit with no compensation.

**Comment by cpaulgilman** [comment]
Request for AC interconnection limit for Australia

> Firstly, a fixed AC Power limit would be helpful to, in-part, model impositions made upon specific projects by the connection authority - The "transfer capacity", a MW limit that cannot be exceeded.

https://sam.nrel.gov/forum/forum-general/2767-enhancement-request-grid-power-connection-limit.html

**Comment by cpaulgilman** [comment]
Information about New York State capacity payments from [Solar Value Stack Calculator](https://www.nyserda.ny.gov/All-Programs/Programs/NY-Sun/Contractors/Value-of-Distributed-Energy-Resources/Solar-Value-Stack-Calculator) workbook Documentation worksheet Line 7:

> For capacity value Alternative 1, monthly rates derived from ICAP prices are applied to each kWh of solar export all year. Users may select monthly Alt 1 values from a) 2018, b) average of 2018 and 2017, or c) average of 2016 - 2018. Monthly values are calculated by monthly ICAP auction prices multiplied by the proxy capacity factor from a representative solar profile, then divided by the monthly kWh/kW. The value of proxy capacity factor and monthly kWh/kW are obtained from New Order Appendix E.14. The proxy capacity factor was determined based on the period starting with hours beginning 14:00 through hour begging 18:00 on non-holiday weekdays from June 24 to August 31. PSEG-LI applies estimated and actual historical Alt 1 rates, according to current tariff.
>  
> For capacity value Alternative 2, the rate is calculated by dividing the total ICAP $/kW-year value by 240 or 245, based on the number of available hours in the given year. This is allocated across 240 or 245 summer hours (defined as the period starting with hour beginning 14:00 through hour beginning 19:00 on non-holiday weekdays from June 24 to August 31). As of May 31 of each year, the prior 12 months of monthly ICAP auction prices is used to determine the total $/kW-year value. Note that since all times in this tool are in EST, Alt 2 hours (which are defined in EDT) appear as hour beginning 13:00 through hour beginning 18:00. Users may select Alt 2 values from a) 2019, b) average of 2019 and 2018, or c) average of 2017 - 2019. PSEG-LI applies estimated and actual historical Alt 2 rates for 2018 and 2017 only, according to current tariff.
> 
> Alternative 3, the 'Capacity Tag' approach, calculates capacity value as the monthly ICAP capacity prices multiplied by the output at the time of the single hour system peak. The user can select from a single year of monthly ICAP values, or averages from the past 2 or three years. For Long Island, the top 10 hours and specified capacity value are used.
> 
> For all three Capacity Alternatives, the user can also input an annual escalation rate for the ICAP values.
> 
> Source:  NYISO ICAP Auction Prices: https://www.nyiso.com/installed-capacity-market

**Comment by cpaulgilman** [comment]
https://github.com/NREL/SAM/commit/27a74f854ecccebc0d94275d8103136a97773e2d
