### ISSUE TITLE
REopt API call fails with callback error

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1830]
### Describe the bug

REopt API call fails.

### To Reproduce

1. Create a default PV Battery / Commercial case.
2. On Battery Cell and System page, click **Get size and dispatch**.
3. See error.

```
Could not evaluate callback function:call_reopt->on_change
[71]: error in call to 'reopt_size_battery()': access violation: expected hash table, but found null[12]: eval error in statement list
```

### Operating System and Version

 - macOS Sonoma 14.6
 - SAM 2023.12.17 r2 release candidate]

**Comment by cpaulgilman** [comment]
As of the latest Patch branch (8/12/2024), we are seeing this error on macOS, but not Windows or Linux.

**Comment by brtietz** [comment]
Closing since we merged PRs related to this for the patch. @sjanzou and @cpaulgilman please re-open if I've forgotten something that needs to be resolved on our end for this issue.

**Comment by sjanzou** [comment]
> Closing since we merged PRs related to this for the patch. @sjanzou and @cpaulgilman please re-open if I've forgotten something that needs to be resolved on our end for this issue.

I thinks everything works fine with postman but, for curl, the issue remains and the pull request does have the REopt call for loads if the original call fails. 

Finally, the REopt team has been made aware of the problem and SAM will work with any non-API breaking fixes that are donw by the REopt team for curl calls.
