### ISSUE TITLE
Georgia Power PLL-11 Rate does not download tiers properly from URDB

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1848]
### Describe the bug

https://apps.openei.org/IURDB/rate/view/5f73585d5457a3dc0b692d6f#3__Energy is a rate with mixed tiers, some with kWh and some with kWh/kW. SAM's URDB download code fails to pull the tiers for this rate

### To Reproduce

1. Open a behind the meter model such as PVWatts-Commercial
2. Download the rate linked above
3. Max usage tiers do not match the URDB implementation

### Expected behavior

Max usage tiers should match the URDB implementation

### Additional context

Tested on 2023.12.17r2. I expect this would have worked circa 2021 based on previous projects, but haven't tested it.

**Comment by cpaulgilman** [comment]
This is caused by the switch to RapidJSON between SAM 2023.12.17 r1 and SAM 2023.12.17 r2. SAM is only reading tier max values if they are stored as double in the JSON, but the URDB stores the values as integers.

The switch to RapidJSON is also causing a problem loading rates from Arizona Public Service, which I will also address for this issue:

![image](https://github.com/user-attachments/assets/5c33fc05-5d78-4dac-b9be-6cd6726dff13)

**Comment by sjanzou** [comment]
Updated rapidjson::document in urdb.cpp from UTF8 to UTF16 on line 394 and updated all the strings used in the rate retrieval to wchar_t on Windows (using L""). 

The Arizon Public Service Co rates are now retrieved on Windows
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/c463bead-522c-4ddc-b1d9-4113f69fd2ef">

and MacOS
<img width="1096" alt="image" src="https://github.com/user-attachments/assets/eb70c842-65a9-437c-82f4-7c636a4b48b4">

The update has not yet been tested on Linux.

We may want to update to UTF16 throughout SAM.

**Comment by cpaulgilman** [comment]
> The search for rates function crashed SAM when I try to select the Pacific Gas & Electric Co utility. It also happens when I select a few other utilities. 

> The utility rates crash happens when I click the utility name in the left display column after filtering the results with the left filter input field. The crash happens before the specific rate names appear in the right display column.
