### ISSUE TITLE
Consider renaming Generic System model

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1849]
### Is your feature request related to a problem? Please describe.
-Consider renaming generic system model to better capture the ability to input measured plant data or come up with custom energy timeseries data
### Describe the solution you'd like

-'Custom Power Plant' or 'Power Plant Data', etc. 

### Additional context

-Noticed during SAM retreat.

**Comment by janinefreeman** [comment]
Per our 9/25/24 SAM meeting, we've decided to go with the name "Custom generation profile".

Places that this will need to be implemented:
- Technology selection tree
- Startup script (incl hybrids)
- Callbacks
- UI forms
- Macros
- Python example scripts
- Other sample scripts
- Hybrids configs in ssc

@sjanzou @mjprilliman @cpaulgilman @brtietz @dguittet please add any other places this will need to be considered as a comment.

**Comment by mjprilliman** [comment]
On version upgrade from generic system to custom generation profile, it looks like the case reader has issues if there is no Generic System defaults file to point to. So we may have to leave in Generic system default jsons in for one more release to allow for that transition. Other than that it seems straightforward to update variable names and upgrade to the new technology name.

**Comment by cpaulgilman** [comment]
@mjprilliman Camel case isn't ideal here, but works OK. I can't think of a better solution. 

As for the width of the panel, we could slightly widen it or slightly reduce the font size. Also, I think it's OK if the longest name in the list doesn't fit, especially as it's likely one of the least-used configurations and normally hidden under the "Hybrid" heading. (Needs to be checked on Mac and Linux that use different fonts.)
