### ISSUE TITLE
Link to 5-minute Puerto Rico Data

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#185]
Confirm that new 5-minute Puerto Rico data is added to NSRDB API's in such a way that SAM can access automatically.

**Comment by cpaulgilman** [comment]
Addressed in 7635bb5d3f95048f995e1c37d0cc26ea27449c60. For now, the "Puerto Rico Solar Data" macro accesses the data using the API at https://developer.nrel.gov/docs/solar/nsrdb/puerto_rico_data_download/. 

If and when the NSRDB Data Query API (https://developer.nrel.gov/docs/solar/nsrdb/nsrdb_data_query/) returns information about the Puerto Rico SHR API, we can directly download from the Solar Resource UI callback script.

**Comment by brtietz** [comment]
Confirmed that 5 minute data comes down in 2020.11.29's advanced download UI:

![image](https://user-images.githubusercontent.com/5530592/101196684-4df8c580-361e-11eb-8a00-ac7199858b96.png)

**Comment by cpaulgilman** [comment]
@brtietz Should we remove the Puerto Rico Solar Data macro now that it is redundant? We could convert it into a standard LK script and add it to the samples collection at https://github.com/NREL/SAM/tree/develop/samples/LK%20Scripts%20for%20SAM.

**Comment by brtietz** [comment]
That makes sense to me. The macro has four inputs Lat, Lon, interval and names. How should those be represented in the example LK script? The "in" dialogues?

**Comment by cpaulgilman** [comment]
Might be best to make them variables whose values are set in the code. They could be set to sample values with comments explaining how they work.
