### ISSUE TITLE
Add details on subhourly clipping loss correction

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1850]
Two items that could be helpful:
1. Clarify in the UI that the subhourly clipping correction checkbox is for the "Allen method" ![image](https://github.com/user-attachments/assets/487af187-edfc-43b9-82ac-96b1466a2741)
   - this is to avoid confusion with the "Walker method" - I'm not sure of the status of the Walker method in SAM/pysam, but it's been discussed publicly, e.g., https://www.nrel.gov/docs/fy24osti/90054.pdf.

2. Consider adding a reference to [1] in the help docs under "Enable subhourly clipping loss correction" (_note: I'm a co-author on [1], so I have a potential COI with this suggestion..._) 
![image](https://github.com/user-attachments/assets/8a34d865-edf9-4ff2-b8e0-db0142cb6873)

[1] J. O. Allen, R. Dhakal, W. B. Hobbs, and W. Li, “Allen Method for PV Subhourly Clipping Correction,” 2024. [Online]. Available: https://github.com/epri-dev/allen-subhourly-clipping-correction

**Comment by janinefreeman** [comment]
Thanks @williamhobbs ! We're always happy to link to more documentation, so we'll accept the COI. 😛 And that is a helpful suggestion for the UI, as you're right that we've talked about the Walker method publicly. We'll add this for our fall release!

FYI @cpaulgilman  on the documentation addition and @mjprilliman on the UI change.
