### ISSUE TITLE
 Monthly energy naming confusion

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1876]
### Describe the bug

-Several cmods (so far I have checked wind and PVWatts) monthly energy has different monthly AC energy variable names depending on how it is run, due to renaming in the different cmods. Some of these names are incorrect, and ideally the name would be consistent across. 

In hybrids - Host Developer, Wind monthly energy is said to be gross, which is incorrect as the value is based off of gen and adds up to annual energy. This is just a label update. PVWatts is called AC output. 

![image](https://github.com/user-attachments/assets/65c931f1-2cf0-4382-ae28-d5c27dec6f43)

If Single Owner (or Host Developer, seems to be a hybrid fix) is run for wind only case, it is renamed Monthly energy [kWh]. 

![image](https://github.com/user-attachments/assets/8edbc37c-053b-4172-a032-e58c1d8f3525)

BTM Wind (and BTM PVWatts) only is called AC energy (year 1), from cmod_grid.cpp. 

![image](https://github.com/user-attachments/assets/aaba186a-feef-4bf2-b6db-fa5520bc9565)

It would be good if these were more consistent. 

### Additional context

Discovered when evaluating monthly energy outputs for hybrid autograph metrics.

**Comment by cpaulgilman** [comment]
@mjprilliman I took a first cut at this in https://github.com/NREL/ssc/commit/d9c9bddff740d66deefb9c989c15b3fbcc73bbf5. Let me know what you think -- probably worth putting on the SAM meeting agenda to discuss with the team.
