### ISSUE TITLE
Update NSRDB downloads to V4

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1920]
NSRDB V4.0.0 data (1998-2023) is now available from new NREL Developer API endpoints:

https://developer.nrel.gov/docs/solar/nsrdb/nsrdb-GOES-tmy-v4-0-0-download/

https://developer.nrel.gov/docs/solar/nsrdb/nsrdb-GOES-aggregated-v4-0-0-download/

SAM's Advanced Downloads option can access these endpoints, but the direct download from the Location and Resource page still accesses the older V3.2.2 (1998-2022) API endpoint.

Note there is an "aggregated" and "conus" endpoint. The latter seems to be a subset of the former, but need to determine the correct endpoint to use.

To Do:

* Update NSRDB download code to access V4.0.0 endpoint
* Spot-check V4.0.0 files for issues
* Test for locations around the world

**Comment by cpaulgilman** [comment]
Data in weather files from GOES V4 endpoing is offset so that DNI peaks around 8 pm instead of Noon. Awaiting fix from NSRDB team before updating in SAM.

Test URL to download example file:

https://developer.nrel.gov/api/nsrdb/v2/solar/nsrdb-GOES-tmy-v4-0-0-download.csv?api_key=DEMO_KEY&full_name=sam_user&email=test.email@email.org&reason=SAM-test&interval=60&utc=false&leap_day=false&attributes=dni,dhi,ghi,dew_point,air_temperature,surface_pressure,wind_direction,wind_speed,surface_albedo,clearsky_dhi,clearsky_dni,clearsky_ghi&names=tmy&wkt=POINT(-122.676%2045.5118)

**Comment by williamhobbs** [comment]
@cpaulgilman, is this issue with GOES V4 being tracked/reported out somewhere publicly? Or is the SAM team simply communicating directly with the NSRDB team?

It would be nice to get public updates on this from the NSRDB team...

**Comment by cpaulgilman** [comment]
> @cpaulgilman, is this issue with GOES V4 being tracked/reported out somewhere publicly? Or is the SAM team simply communicating directly with the NSRDB team?
> 
> It would be nice to get public updates on this from the NSRDB team...

To be honest, we accidentally stumbled on the update to GOES V4. We discovered the offset issue and reported it to the NSRDB team. I just heard back from them that it's been fixed, and my testing confirms the fix, so we'll proceed with the update in SAM For the December 12, 2024 release.
