### ISSUE TITLE
Remove metering options from IPH commercial models on Electricity Rates page

### ISSUE THREAD

**Issue by taylorbrown75** [NREL/SAM#1934]
### Describe the bug

The IPH trough and IPH Fresnel commercial models allow users to select a metering type on the Electricity Rates page. These models do not produce electricity and the metering type does not seem to have an effect on the simulation.

### To Reproduce

1. Create an IPH Trough commercial model case
2. Go to the Electricity Rates tab
3. See Metering and Billing groupbox

### Expected behavior

'Net energy metering' should be selected and the entire 'Metering and Billing' groupbox disabled. 

### Screenshots

![image](https://github.com/user-attachments/assets/aab25e69-371d-4f7a-bf05-2020c5830a3b)

### Operating System and Version

 - OS: All
 - Version SAM 2024.12.12

**Comment by brtietz** [comment]
I agree disabling the group box might be a good option here, but are you sure net energy metering is the right option? What happens if the system produces more heat than the load in a given timestep? It doesn't seem like the gas utility will allow customers to accrue credits over the course of the month to offset their load for exported heat. I might recommend "net billing" with a sell rate of zero.

**Comment by taylorbrown75** [comment]
I'm not sure which option is best, but this 'Metering and Billing' groupbox is only related to electricity rates. Since we're only buying electricity, I selected 'Net energy metering' because it shows a 'Buy' column and no 'Sell' column in the Energy Charges table. 

For heat production, we set the sell rate to $0 and let the users define the buy rate on the Thermal Rates tab.

**Comment by brtietz** [comment]
Got it, makes sense with the thermal rates being on a different page.

That sounds similar to the convention we use for front of meter losses & battery charging rates which set the metering and billing option to "buy all sell all," hide the sell column, and then set the sell rate to zero in lk. It should be possible to add something to `set_ec_schedule_inputs()` on the Utility Rates - Flat inputs page to accommodate the process heat technologies and make them consistent.

**Comment by taylorbrown75** [comment]
https://github.com/NREL/SAM/pull/1943
