### ISSUE TITLE
Electricity purchases incorrect with hourly buy rate of zero 

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#1964]
The "Electricity Purchases" are incorrectly calculated when hourly buy rates of zero are specified.

To reproduce with the 2024.12.12.ssc.297 release candidate:
1. Create a PV Single Owner case
2. Select "Use retail electricity rate(s)" on the Electricity Purchases page
3. Specify a Buy rate of zero
4. Simulate
5. View the expected "Electricity purchase" O and M value to be zero
6. Change to "Use hourly (subhourly) buy rates instead of TOU rates on the Electricity Purchases page
7. Specify buy rate of 0 for all 8760 values
8. Simulate - get the unexpected non-zero "Electricity purchase" O and M value
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/ba98ffd6-e933-4919-9229-2d9991d20d05">

Test file 
[SAM_1964.sam.zip](https://github.com/user-attachments/files/18076995/SAM_1964.sam.zip)

Expected results in test file
1. "default PV SO" and "hourly default rate" simulation results match - which they do with default buy rate of 4.5 cents/kWh specified as a buy rate and as an hourly value.
2. expect the cash flow line item for "Electricity purchase" Operating Expense value to be zero for both the "zero hourly purchases" and the "zero buy rate" which they are not zero for the "zero hourly purchases" case

**Comment by sjanzou** [comment]
Note this bug is present in all configurations with "Electricity Purchases". Specifically, the IPH / Commercial configurations are also affected.

**Comment by brtietz** [comment]
Good catch! It looks like the issue is that the utility rates code falls back to the energy charges table if the time series rate is zero, rather than looking at the index of the time series rate: https://github.com/NREL/ssc/blob/2daaee8f939eaf349ab58c8047206f1b43fdb7b0/ssc/cmod_utilityrate5.cpp#L2484

I should be able to make a pull request fixing this later this morning.
