### ISSUE TITLE
Bifacial rear irradiance reporting error - rear POA is multiplied by bifaciality coeff.

### ISSUE THREAD

**Issue by cdeline** [NREL/SAM#198]
Hi everyone.  I'd like to report an error in how SAM is reporting rear irradiance which might cause some confusion.  This doesn't cause any errors in the final output of system power, but intermediate parameters are being incorrectly reported.

At the moment, it appears that the value returned in the SAM Data Tables 'Subarray 1 POA rear total irradiance after reflection (IAM) (W/m2)'  is reported as the rear irradiance value *times the bifaciality coefficient*.  This will cause significant under-reporting of the rear irradiance, for the case of people trying to compare measured back POA irradiance with modeled expected values.  

It does appear that the 'Subarray 1 POA total irradiance' is being calculated more or less correctly by adding POA_front + POA_rear * bifaciality coeff.  However, please change the intermediate value reported for POA_rear to not include this bifaciality coefficient.  THANKS!
This may be related to #191, not sure.

-Chris

**Comment by nickdiorio** [comment]
I've corrected this in the `develop` branch, which we are targeting to prepare for an autumn release.  

Example where bificality coefficient is set to 0:
![image](https://user-images.githubusercontent.com/5658281/59631469-2a2d8100-9105-11e9-8e09-7c85af273ea5.png)

And when bifaciality is moved to 1:
![image](https://user-images.githubusercontent.com/5658281/59631508-40d3d800-9105-11e9-8c59-a2e99f3804f0.png)

This should show that the reported POA rear total irradiance is unaffected by the bifaciality coefficient, but that the total panel POA irradiance is.

**Comment by nickdiorio** [comment]
Again, this will be released in autumn 2019
