### ISSUE TITLE
LK to_int() does not return an integer

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#202]
Within a SAM script:

`x = 0;`
`outln(x)`
`outln(to_int(x))`

Output:
`0.000e+00`
`0.000e+00`
`Elapsed time: 0.0 seconds.`

Everything is being represented as a float.

**Comment by sjanzou** [comment]
Fixed in MHK branch of lk and merged into AncillaryServices and develop branches of lk. Updated outln and to_int functions of lk 1d23aebd7e6ed76e7679d4d5905f4864ccf00bc7
