### ISSUE TITLE
LK > operator not working

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#203]
![image](https://user-images.githubusercontent.com/5658281/59384509-9122f280-8d1f-11e9-9716-33119a09649d.png)

I cannot reproduce in an isolate script so far, but I'm seeing the control flow step into a line which should only be accessible if the value is greater than 1.  I'm accessing element 1 of:

`dollars_per_kwh  =  [ 344.3, 0.0, 0.0, 0.0, 0.0, 29.001324357818177, 0.0, 0.0, 0.0, 0.0, 208.09261506533974, 0.0, 0.0, 0.0, 0.0, 19.281026920052778, 0.0, 0.0, 0.0, 0.0, 138.3467618042545, 0.0, 0.0, 0.0, 0.0, 12.818655951881775 ]`

Element 1 is `0.0`.

**Comment by nickdiorio** [comment]
![image](https://user-images.githubusercontent.com/5658281/59385067-caa82d80-8d20-11e9-9a16-950629f3009c.png)

**Comment by nickdiorio** [comment]
To get around this, I had to coerce `cost` to an integer, at which point the inequality was respected:

`cost = to_int(dollars_per_kwh[y])`

**Comment by sjanzou** [comment]
Fixed with the commit in lk that fixed issue #202 

![image](https://user-images.githubusercontent.com/6498311/59550384-512e5c00-8f27-11e9-98f4-d5f628c557d2.png)
