### ISSUE TITLE
Import 3D shade scene data from CAD and other software

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#208]
>When will CAD files be importable to the 3D shade simulator (PVSYST has this and SAM should in order to remain relevant)?

**Comment by janinefreeman** [comment]
We do not have a funded project to add this feature, but this would be a great project for a third party contributor! There are ways to leverage the scripting language within the 3D shading tool to import other file formats. Feel free to contact us if anyone is interested in tackling this!

**Comment by ahk13** [comment]
This issue has been bugging me for a while now. Though I have not been able to figure out how to import a 3D model from a third party CAD program into SAM, I thought the following method would be helpful:

<NOTE: I am most comfortable with SketchUp, and this is what most of my Solar Design Engineer colleagues work with as well. This solution might work with other CAD software as well>

1. Create a 3D model with accurate Geo-location on SketchUp (or other CAD).
2. Enable shadows and create a set of frames or an animation/video file based on tilmesteps (Something like [this](https://www.youtube.com/watch?v=punwn57UhoQ))
3. This data can then be labeled based on shading percentage using Tensorflow
4. An output CSV file can then be generated, which can be imported into SAM in the "month-by-hour beam irradiance shading losses" or "beam irradiance shading losses by tilmestep" sections

I've been working on these lines. If it helps, I'll share the link here once ready.

**Comment by cpaulgilman** [comment]
Yes, please do share a link if/when you get this to work!

Thanks,
Paul.

**Comment by AWABIE** [comment]
In my opinion, the focus here should be on reading and parsing file formats starting with PVCollada files in SAM.
Most layout tools have this xml based file format as export option and it is well documented. 
Being able to combine the capabilities of SAM with the drawing features of Autocad/Sketchup based tools would be pretty amazing. 

[PVCollada.zip](https://github.com/NREL/SAM/files/11892929/PVCollada.zip)
https://www.khronos.org/files/collada_spec_1_5.pdf

**Comment by janinefreeman** [comment]
We could certainly work with something python-based, I think the trick would mostly be making sure it outputs something compatible with one of SAM's current inputs. Is there one that exists that might be adapted to work with SAM?

**Comment by cwhanse** [comment]
None exist but I preparing to write one. The input is clear (PVCollada file), the output is somewhat fungible at this point.

**Comment by janinefreeman** [comment]
Fantastic! Do you want to have a quick call/email to figure out what kinds of outputs might work for a variety of applications?
