### ISSUE TITLE
CEC Single Diode model: gamma_r should be renamed gamma_pmp

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#210]
The temperature coefficient of maximum power is currently titled "gamma_r" in the CEC model. This terminology does not appear to come from anything specific and is confusing, so we'd like to rename to gamma_pmp. The variable in pvsamv1 in SSC will also need to be renamed, which unfortunately could cause some backwards compatibility issues. This is likely a fairly low priority issue, however.

**Comment by toddkarin** [comment]
I agree, I'm trying to get a more uniform parameter labeling for all the CEC values. We have developed a more consistent scheme of parameters in the [pv-terms](https://duramat.github.io/pv-terms/) project. The idea is to use a uniform parameter labeling as much as possible in the various pv analysis software packages.

**Comment by janinefreeman** [comment]
Upon further investigation, the gamma_pmp value is an input to three compute modules:

- `6parsolve`
- `pv6parmod`
- `pvsamv1`

However, it is only used in `6parsolve` . Votes for removing it as an input from the other compute modules? I believe it could still live as a reference value in the GUI for the CEC library page, but I think it's confusing for it to be an input if it's not used.
