### ISSUE TITLE
Check for updates only works for revisions

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#214]
> ...I had clicked “check for updates” on my 2016.3.14, which seems pretty old, but it said I was up to date. I’ll go to the website to dl the latest version instead...

For Version 2017.1.17 and later, Welcome page does display a "new version is available" message in red bar, but users may miss that if they are using the check for updates button:

![image](https://user-images.githubusercontent.com/27711933/61546439-6bfc6080-a9fe-11e9-93ec-918e6812ae5d.png)

For versions before 2017.1.17, Welcome page does not display a message:

![image](https://user-images.githubusercontent.com/27711933/61546811-065ca400-a9ff-11e9-8626-6062425930d5.png)

Welcome page text is populated by `welcome.lk` with path to file defined in `runtime/webapis.conf`.

"Check for updates" code is in `webupd` folder of SAM-private repository.

**Comment by sjanzou** [comment]
![image](https://user-images.githubusercontent.com/6498311/70628347-380c1c80-1be5-11ea-9588-2d55c7cb6a42.png)
Closed with SAM-private commit a37c5b7894f36d30ef19ec66f4419523360e5cd2
