### ISSUE TITLE
Downloading wind data gives wrong hub height in file

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#216]
When I use the download button on the "Wind Resource" page, and change the measurement height to 100m, it downloads a file that says it's 100m in the label, but opening the file reveals the hubheights to be 10m.   I wonder if the hub heights are being updated in the API call?

[lat39.74_lon-104.98__2010_100.zip](https://github.com/NREL/SAM/files/3412732/lat39.74_lon-104.98__2010_100.zip)

@cpaulgilman , have you seen this?

**Comment by cpaulgilman** [comment]
Yes, there's been some discussion on the SAM forum about this issue:

https://sam.nrel.gov/forum/forum-general/2333-problems-downloading-wind-resource-files-by-lat-long.html

**Comment by cpaulgilman** [comment]
Related to https://github.com/NREL/SAM/issues/353

**Comment by cpaulgilman** [comment]
This has been addressed by fixes to the WIND Toolkit web service. Some related code changes in SAM clean up WIND Toolkit data downloads in SAM: c69601b77b0acd52f357762e4535a66c38ba23ec.
