### ISSUE TITLE
Update code generator for PySAM

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#217]
Current code generator options do not provide inputs in the same format as used in PySAM. While conversion is possible, directly producing PySAM formatted input json files would allow for quicker setup as well as direct comparison between python and the GUI.

**Comment by sjanzou** [comment]
@dguittet - what is the PySAM formatted JSON input?

**Comment by dguittet** [comment]
@sjanzou It's nested by SSC group names. Here's an example from GenericSystem:
```
{
	'Plant': {
		'conv_eff': 34.11804962158203,
		'derate': 4.0,
		'energy_output_array': (0.0, ),
		'heat_rate': 10.0,
		'spec_mode': 0.0,
		'system_capacity': 100000.0,
		'user_capacity_factor': 43.6
	},
	'Lifetime': {
		'analysis_period': 25.0,
		'generic_degradation': (0.0, ),
		'system_use_lifetime_output': 0.0
	},
	'AdjustmentFactors': {
		'constant': 0.0
	}
}
```

**Comment by sjanzou** [comment]
From @dguittet, Here’s a short example of importing a SAM case from the JSON exported: https://nrel-pysam.readthedocs.io/en/2.0.2/Import.html

One nice thing that might not be as time-consuming as the original idea but which would be greatly helpful is if the JSON from the code generator could be grouped by compute_modules.

Right now it’s a giant single json, which is why we have to call “dict_to_ssc_table” twice and do an unweidly “so.assign(Singleowner.wrap(so_dat).export())”.

If we could separate the json by compute module, then we can call the “value” function like this, where “filename” is read in from the Pvwatts json.

system_model.value('solar_resource_file', filename)

 Using this method, the nesting by Group names isn’t even required :D

**Comment by sjanzou** [comment]
Updated and separate JSON file for each compute module. However, pySAM value function fails for adjust:constant 
![image](https://user-images.githubusercontent.com/6498311/82890013-c876b900-9f08-11ea-8655-f97f23318efa.png)

Commit and push to SAM_217 branch of SAM and merge into patch and develop branches and close issue

**Comment by dguittet** [comment]
Just a couple of items!

- the “adjust:constant” variable doesn’t work as a PySAM variable since you can’t do `gs.adjust:constant` so I had taken out the “adjust” prefix. Here’s a list of all the adjustment factor variable [names] (https://nrel-pysam.readthedocs.io/en/master/modules/Pvwattsv7.html#adjustmentfactors-group)
 
- “nan” isn’t legit JSON. Could there be a check so that Nan-valued variables aren't printed?

**Comment by sjanzou** [comment]
Update and strip out prefix for now and test several cases. The link provided does not have all the adjustment factors for all of the different technologies. Also, no NaN values encountered in inputs for CSP, PV, Generic generations. Issue with MSPT:
![image](https://user-images.githubusercontent.com/6498311/83007960-ae54dd80-9fd1-11ea-8798-9f6ef0a1442d.png)

**Comment by sjanzou** [comment]
Python code much simpler and running example for generic_system single owner:
![image](https://user-images.githubusercontent.com/6498311/83008045-cc224280-9fd1-11ea-99b2-bc152dba2d26.png)

**Comment by sjanzou** [comment]
Moving out of patch 2 milestone until resolution for all adjustment factors in flat JSON file determined. Fixes and running code checked into SAM_217 branch of SAM and merged into patch and develop branches.

**Comment by sjanzou** [comment]
Working example script for PySAM and generic single owner PySAM JSON code generation:

import json
import PySAM.GenericSystem as GenericSystem
import PySAM.Singleowner as Singleowner
from PySAM.PySSC import *

ssc = PySSC()

dic = json.load(open("untitled_generic_system.json"))
gs = GenericSystem.new()
for key, value in dic.items():
    if key != 'number_inputs' :
        gs.value(key,value) 

#grid compute module here when in PySAM

dic = json.load(open("untitled_singleowner.json"))
so = Singleowner.from_existing(gs)
for key, value in dic.items():
    if key != 'number_inputs' :
        so.value(key,value) 

gs.execute()
so.execute()

print ('\n Annual Energy (year 1) = ', gs.Outputs.annual_energy , ' (kWh)\n PPA price (year 1) = ' , so.Outputs.ppa, '\u00a2/kWh\n')

**Comment by dguittet** [comment]
Script is now working for MSPT
