### ISSUE TITLE
CodeGenerator for json gives invalid Matrixes for one Column

### ISSUE THREAD

**Issue by LucoEldritch** [NREL/SAM#222]
When you try to Generate code using option JSON for inputs, and you have any matrix like Nx1, (with one column and at least two rows), the matrix generated is like
[ [ 1 ], [ 2, [ 3, ... [ N-1, [ N, ] ]
Which is invalid format for JSON.

This is possible in SAM, like for example, when you're using _Photovoltaic (detailed)_ (internally called Pvsamv1 I believe), and you add _Beam irradiance shading losses by time step_ with only one String in Subarray.e

Reproduction steps:
1. Create new project of the type _Photovoltaic (detailed)_, with any Financial Model
1. Go to option _Shading and Layout_
1. In _External Shading_ > _Shade Loss Tables_ > _Subarray 1_, click _Edit shading..._
![image](https://user-images.githubusercontent.com/35275945/63040054-fff50700-be9a-11e9-9a0d-560c4af12e6d.png)
1. Mark the first option, _Enable beam irradiance shading losses by time step_ and press OK (the default option for _Strings in subarray_ is 1, and it'll automatically fill the shading data with zeroes)
_Optionally_: you could change _Strings in subarray_ to 2 or more, to see that the current code works with matrixes having more than one column
1. Select the dropdown in the project tab above and click Generate Code...
1. Select _JSON for inputs_ if it's not already selected, and press OK.
1. Choose folder

Check the field `subarray1_shading:timestep` in the json file. It'll be something like `[ [ 0 ], [ 0, [ 0, ... [ 0, [ 0, ] ]`, and it should be something like `[ [ 0 ], [ 0 ], ... [ 0 ], [ 0 ] ]`

From what I checked, I believe the problem is in this part of the code:
https://github.com/NREL/SAM/blob/f0b6bbb0390e65ca876e8062defeb7557e64c9ca/src/codegenerator.cpp#L7557-L7576
In line 7566, since k % nc will always be 0 when nc is 1 (nc = number of columns), it'll always open new ones after the first one, without ever falling in the else, so, never closing.

The simplest solution, I believe, would be adding an if before line 7566, and changing the if below to else if, like so:
```c
if (nc == 1)
    fprintf(m_fp, " %.17g ], [,", dbl_value);
else if ((k > 0) && (k%nc == 0))
// current code continues
```
Which, since the string is already started with "[ [", would append "val ], [" when the column size is 1, making "[ [ val ], ["

**Important:** I didn't check thoroughly if something like that was present in any other item of CodeGenerator.

**Comment by janinefreeman** [comment]
Hi @LucoEldritch , thanks for submitting the issue, looking through the source code, and finding the possible fix! @sjanzou , can you please take a look?

Thanks both!

**Comment by sjanzou** [comment]
@LucoEldritch, thanks for the detailed analysis. The actual fix was very close to your suggestion with one comma removed. Thanks:
				if (nc == 1)
					fprintf(m_fp, " %.17g ], [", dbl_value);
				else if ((k > 0) && (k%nc == 0))
