### ISSUE TITLE
PV-battery charge/discharge based on SOC

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#226]
> I am trying to model a PV-battery system which is effectively separate from the grid and has discrete power output demands. The power demand on the system is determined by the battery state-of-charge.
>For example, the power output required of the system could be 10 kW for SOC between 10% and 25%, 20 kW between 25% and 50%, 30 kW for SOC between 50% and 75%, etc. Power output demand is only set by battery SOC, not power available.
>In the system, if the PV field exceeds the current power demand, it charges the battery, and if it does not meet it, it discharges the battery. If the battery is full and the PV field still exceeds the power demand, the excess is dumped. If the battery is at the minimum charge state, the output power demand drops to zero.
>I have been using the detailed photovoltaic model with a commercial financial model. I am hoping to find some way to combine a defined load with a manual dispatch to define the load based on battery SOC.

**Comment by janinefreeman** [comment]
From team discussions of this issue:
The thing that makes this particular use case hard is that the state-of-charge is a function of the power of the last time step, so trying to make the power of the next time step a function of the state of charge results in some functional interactions:
P(t) = f(SOC(t-1))
SOC(t-1) = f(P(t-1))

We have a related project to [make the battery model available timestep by timestep](https://github.com/NREL/ssc/issues/288) through the [SAM SDK](https://sam.nrel.gov/software-development-kit-sdk.html), so once that is available, the best path forward is probably to call the battery model timestep by timestep and use current state of charge to determine next timestep charge/discharge.
