### ISSUE TITLE
Lifetime daily DC and AC loss window not showing correct number of rows

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#232]
The lifetime daily DC losses and lifetime daily AC losses page in the UI (in pvsamv1 and in the fuel cell model) are not showing the correct number of rows with no way to change it. @sjanzou do you mind taking a look? Thanks!

![image](https://user-images.githubusercontent.com/12733546/70392625-305b3680-199f-11ea-9ad1-cc8ed8cfef37.png)

**Comment by sjanzou** [comment]
Closes with 66a4374c771858c314d3b028e82fded65fe7a847
