### ISSUE TITLE
PV System Design: Tilt=Latitude checkbox does not work

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#234]
The tilt=latitude checkbox on the System Design page doesn't work- the simulation uses whatever is specified in the tilt input box, even when it is grayed out.

**Comment by cpaulgilman** [comment]
Tilt=latitude causes simulation to fail if latitude in weather file is negative for a southern hemisphere location.

**Comment by cpaulgilman** [comment]
Fixed in https://github.com/NREL/ssc/commit/62121c84eae4dc0e8d4774230befae1a192d2635
