### ISSUE TITLE
PVWatts with net metering, almost no PV and batteries and flat rate, yields LCOE < 0.

### ISSUE THREAD

**Issue by frohro** [NREL/SAM#239]
Hi,
I'm puzzled by the SAM version 2018.11.11's output when I do a PVWatts net metering simulation with batteries and almost no PV.  I get negative LCOE, which seems strange, though my understanding of LCOE may be incorrect.  I'm enclosing a .sam file where I made the rate flat, zeroed incentives, and interest/inflation to simplify things.  In order to upload the .sam file, I'm putting a .log as the extension.  You will need to change it back to .sam.
[negative_LCOE.log](https://github.com/NREL/SAM/files/4132063/negative_LCOE.log)
Is this a bug, or is my understanding incorrect?
Thanks,
Rob

**Comment by GridTechs** [comment]
There is a selection I believe asking, Are the batteries going to be
charged off the grid.

**Comment by frohro** [comment]
This is the simple PVWatts model.  I can't find anything like that.  Any pointers?

Regardless of where the batteries are charged, they should not improve the power bill.  They are lossy, and the best you can do with almost zero PV generation is to disconnect them, so they don't waste energy, when the price of energy is the same at every time.

Thanks for the response!

Rob

**Comment by frohro** [comment]
Thanks to GridTechs, I found in the detailed PV simulation there is a section where you can check where the batteries change from.   I set up a simulation (shared here as .log, which needs to be changed to .sam to run) in the detailed PV model similar to what I did here in the PVWatts model.  When I have only charge the batteries from the PV system checked it acts as I expect, but when I check charge from only the grid, I get negative LCOE, and furthermore, it reduces my electric bill, even though the rates are constant as a function of time.  This should not be, because batteries are lossy, and that means that if I charge from the grid, and then give it back to the grid at the same rate, what I give back is less than what I used to charge the batteries, and it costs me money.  This simulation shows negative energy production, which is expected if you charge and discharge batteries from/to the grid, but it shows the electric bill going down with this negative production (claiming I save money by this).  
[surprising_results.log](https://github.com/NREL/SAM/files/4145963/surprising_results.log)
This may be related to a similar bug in the 2020.1.14 [beta.](https://github.com/NREL/SAM/issues/240) (number 240).

**Comment by frohro** [comment]
Another funny thing with the simulation I uploaded above is that the DC module modeled loss is negative.

**Comment by frohro** [comment]
I think the problem is the AC connected battery loss.  It is -305.82%, which makes it a generator.

**Comment by frohro** [comment]
I should have said that I changed it so it charges from the system instead of the grid to git the -305.82% for the AC connected battery loss.  Maybe that is because the PV array is charging the battery, and that is calculated as a negative loss.  If I swap it back to charging only from the grid, the AC connected battery loss is 1731.22%.  I can't find a definition for AC connected battery loss.

**Comment by GridTechs** [comment]
Hi I am Brent. I haven’t started at the beginning of your discussion please
 Excuse me for chiming In. Not sure how I was included on this thread. what
are you trying to accomplish, maybe I can help?
If you pay a higher rate at night at night during peak hours. The batteries
will allow you to store energy during the day when costing electricity  is
lower. This enables you to take advantage of peak shaving. The  powered you
stored during the day you can use at night for a lower cost and avoid high
peaks demand charges.

Hope this helps

Brent

**Comment by GridTechs** [comment]
Also if you have current transformers In place to monitor energy
consumption and solar production for your home. It is critical to have
these in the correct position. It’s possible the monitoring is reading your
solar production head home consumption.

**Comment by frohro** [comment]
Thanks Brent,
Yes, I understand if the rate is different at some time of the day, then batteries can save you some money, but I have the rate flat.  I only have one rate for every time of the day.  :-)  I want to use SAM to model a system with batteries, and I want to believe the results.  When I started getting what appear to me to be strange things, I started reporting them here, making examples that show the problem better than my actual simulations.  Probably the last thing I wondered about above is ok.  I'm just a little spooked, by what appears to be an error in the simulations I'm doing.  I'm doing a feasibility study and I need to be able to trust these results.  At this point I don't.

Thanks for the reply.  I don't know how you ended up getting these issue reports, but I appreciate your response.  I'm on Guam, and it is Sunday back in the States, though it is Monday here.  So I was surprised to get a response.  :-)  Again, thanks!

Rob

**Comment by dguittet** [comment]
Thanks for your detailed and informative comments. I've been looking at the issues you've mentioned in the last few days, and directed my fixes to the closest appropriate issue.

The bug is that the Utility rate calculator is NOT pricing the energy purchased from the grid. At the moment, the output from the PV simulation that gives a time series of electricity purchased from the grid for the battery is not being added to the load which is how the utility rate calculator determines how much energy has been purchased (as load - gen given load > gen).

**Comment by dguittet** [comment]
Regarding the ac connected battery loss, when the battery operates by adding or reducing power in a single hour, it increases or decreases the system output. The ac connected battery loss is the (annual system output before battery - annual system output after battery). 

In the case where the battery can charge from the grid, the second term will be higher, resulting in a negative loss.

**Comment by frohro** [comment]
Thank you so so much Darice!  It did indeed seem like charging the batteries might just be free.  :-)
