### ISSUE TITLE
Batteries alone generate revenue in beta 2020.1.14!

### ISSUE THREAD

**Issue by frohro** [NREL/SAM#240]
Hi,
We noticed something funny here, in that it didn't seem you needed much PV to recharge your batteries.  I made a limiting case, where the PV was almost zero, and it implies somehow the batteries alone, with flat rate electricity, are lowering the power bill.  I'm enclosing a .sam file showing the behavior, but am changing the extension to .log to be able to upload it.  You will need to change it back.
Thanks,
Rob
[battery_generator.log](https://github.com/NREL/SAM/files/4132085/battery_generator.log)

**Comment by cpaulgilman** [comment]
Hi Rob,

SAM assumes that the grid can charge the battery. In PVWatts, the battery is dispatched to reduce peak demand from the grid. In your file, that ends up reducing the monthly grid power usage by about 100 kWh/month, which you can see in the monthly data on the Data Tables tab. Given the buy rate of $1/kWh, that translates to a monthly savings of about $100, or roughly $1,200/year, as you can see in the Energy Value row of the cash flow.

![image](https://user-images.githubusercontent.com/27711933/73579825-70d3af80-4438-11ea-9e64-834d083beccf.png)

Best regards,
Paul.

**Comment by frohro** [comment]
Hi Paul,
I'm still confused by what you and SAM are telling  me.  Are you and PVWatts truely saying that with flat electricity rates, batteries can reduce your electric bill?  I don't understand.  Batteries require charge from the grid, and that costs the same as the electricity they return to the grid.  But batteries are not 100% efficient, so if you use the grid to charge them, and then sell only a fraction of that back to the grid, how does that reduce your electric bill?  I think I entered the correct data, but I'm a novice with SAM, so maybe I did not get that entered correctly.   Can you check? 
This is the bug that is holding me up the most right now.  I need to know that I can believe the predictions SAM is making, and that I'm not making an error entering data, and that SAM is not making an error simulating it.  So I'm just doing sanity checks, and it failed this one, either because I entered something wrong, or SAM has a bug.  
Thanks,
Rob

**Comment by frohro** [comment]
I don't know if I should open a new bug report for this, or if it is the same bug.  I have been comparing the 2018.11.11 version of SAM to the 2020.1.14 version.  It appears that batteries have a negative loss in the detailed PV model for the 2020.1.14 version.  In my example comparison, I got -27.6155% loss, and in the 2018.11.11 version it was 4.42077%.  Battery loss should not be negative.

I'm enclosing for comparison, the files I am using for each SAM program.  I'm changing the .sam to .log for uploading.  Please change it back for testing.
[batteries_93kW.log](https://github.com/NREL/SAM/files/4145857/batteries_93kW.log)
[2018 positive battery loss.log](https://github.com/NREL/SAM/files/4145860/2018.positive.battery.loss.log)

**Comment by dguittet** [comment]
@frohro Thanks for reporting this! 

The reason for the negative battery loss turns out to be a bug where given a situation where the battery cannot meet the power target (col 1) due to state of charge limits (col 3), it is reporting a non-zero discharge value (col2):

![image](https://user-images.githubusercontent.com/29387736/73673722-63067000-466c-11ea-8544-5fab0268836b.png)

I'll look into this.

**Comment by cpaulgilman** [comment]
Hi Rob,

Regarding the discussion of electricity bill savings, I think the thread on the SAM forum is a better place for it. Hopefully latest post there addresses your concerns:

https://sam.nrel.gov/forum/forum-general/2899-pvwatts-with-almost-no-pv-and-batteries-yields-large-net-savings.html

Thank you for all of your feedback on the battery model!

Thanks,
Paul.
