### ISSUE TITLE
Battery power not the same in 2018.11.11 and 2020.1.14 versions

### ISSUE THREAD

**Issue by frohro** [NREL/SAM#241]
In the detailed PV models included here, the 2018.11.11 version has 100.2 kW as Battery power is the System Costs tab, while the 2020.1.14 version has 96 kW in that spot.  I attempted to make everything else the same.  
[2018 positive battery loss.log](https://github.com/NREL/SAM/files/4145854/2018.positive.battery.loss.log)
[batteries_93kW.log](https://github.com/NREL/SAM/files/4145855/batteries_93kW.log)
You need to change the .log to .sam to run these simulations.
Thanks!
Rob

**Comment by dguittet** [comment]
Thanks for reporting this!

This is due to 2018 version reporting Battery power in DC (as the label says) and the 2020 version reporting Battery power in AC.
