### ISSUE TITLE
SAM crashes when UI widgets set to NaN

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/SAM#244]
SAM will crash if a numeric UI widget is set to either nan() or 1./0. inside of a $MIMO$. Other types of widgets and regular functions instead of $MIMO$s were not tested.

**Comment by janinefreeman** [comment]
@Matthew-Boyd was this fixed in one of our patches? If so, can you close this issue?

**Comment by Matthew-Boyd** [comment]
I don't know. I only vaguely remember the issue, but my guess is that no one has looked into it. I see it as outside my purview, but it can be ignored if you don't think it's a significant problem.

**Comment by janinefreeman** [comment]
I had a vague memory that perhaps @sjanzou looked into this, but perhaps that was a different issue?

**Comment by sjanzou** [comment]
I was not aware of this issue. I have never tried to set a widget to NaN. What is the desired behavior if a value is undefined? Throw or exit?
