### ISSUE TITLE
The number of tiers in the energy table is incorrect.

### ISSUE THREAD

**Issue by chaosinside** [NREL/SAM#248]
__Steps to Reproduce__
- Open a new PVWatts Commercial (distrubuted) project.
- In Electricity Rates, click "Search for rates..."
- Select provider "Georgia Power Co"
- Select rate "TOU-EO-6 (Time-of-Use Small General Service)"
- Click "Download and apply utility rate"
- Click "Simulate"

__Result__
exec fail(utilityrate5): The number of tiers in the energy rate table, 1, is incorrect for Month 5 and Period 2. The correct number of tiers for that month and period is 2.
Simulation utilityrate5 failed.

![image](https://user-images.githubusercontent.com/3937155/74784902-994c0e00-526e-11ea-9d6f-4258f456da4a.png)
![image](https://user-images.githubusercontent.com/3937155/74784997-d2847e00-526e-11ea-8595-7215beb1d834.png)

This error can be reproduced with other rates as well, such as with City of Memphis, Tennessee (Utility Company) -> "GENERAL POWER RATE - PART D" (539fb549ec4f024bc1dbf33d). The result is: "Error: utilityrate5: exec fail(utilityrate5): The number of tiers in the energy rate table, 1, is incorrect for Month 0 and Period 3. The correct number of tiers for that month and period is 3."

**Comment by sjanzou** [comment]
The issue was rate setup in the rate calculator. The bug identified affected rates with Energy Charges with more than one period that had periods with different tiers. Ga Power TOU-EO-6 rate
![image](https://user-images.githubusercontent.com/6498311/75110931-867c6500-55f1-11ea-993b-387a405898ae.png) with results 
![image](https://user-images.githubusercontent.com/6498311/75110934-95631780-55f1-11ea-851a-d0a0d126c77f.png)

**Comment by sjanzou** [comment]
City of Memphis, Tennessee (Utility Company) -> "GENERAL POWER RATE - PART D" (539fb549ec4f024bc1dbf33d) 
![image](https://user-images.githubusercontent.com/6498311/75110960-df4bfd80-55f1-11ea-873a-e4a2e59bf89e.png)
with results
![image](https://user-images.githubusercontent.com/6498311/75110975-f7238180-55f1-11ea-806b-d54d4208f542.png)

**Comment by sjanzou** [comment]
Fixed with ssc commit https://github.com/NREL/ssc/commit/e36a73d12775e0aab15524b538d7658e0bd42bdd

**Comment by chaosinside** [comment]
Thank you! @sjanzou
