### ISSUE TITLE
SAM crashes in Windows when loading weather file

### ISSUE THREAD

**Issue by maximiliaknow** [NREL/SAM#250]
When creating a new Photovoltaic PVWatts Commercial distributed model, the fist thing I tried to do was load the weather file 912120TYA.CSV. As soon as I click on the file in the Solar Resources Library section, SAM crashes. It does this each time it is tried with both version 2018.11.11. and beta version 2020.2.24. I am using Windows 10, and my colleague had the same problem with SAM version 2018.11.11 on Windows 7. 
Attached is a screenshot of the crash and the Windows application log in event viewer. 
Please advise how to get it to run without crashing.
Thank you

![CrashScreenshot](https://user-images.githubusercontent.com/61722666/75742507-8dc21200-5d59-11ea-9dbb-3d905899bc5d.jpg)
![WindowsEvent](https://user-images.githubusercontent.com/61722666/75742514-931f5c80-5d59-11ea-95fe-f975dc8c81b8.JPG)

**Comment by janinefreeman** [comment]
@maximiliaknow , thanks for reporting this issue. Would you be able to attach the weather file in question so that we can replicate this issue to solve it?

**Comment by maximiliaknow** [comment]
Thanks for your reply. I zipped the weather file and attached it here.
[912120TYA.zip](https://github.com/NREL/SAM/files/4284029/912120TYA.zip)

**Comment by maximiliaknow** [comment]
I downloaded the TMY3 data at the link below as a new file and it is working now.
https://rredc.nrel.gov/solar/old_data/nsrdb/1991-2005/tmy3/by_state_and_city.html
