### ISSUE TITLE
Just a typo....

### ISSUE THREAD

**Issue by frohro** [NREL/SAM#251]
Hi All,
The word "input" is spelled "intput".  See the screenshot.
I appreciate the nice report of what changed, and that I can open old files with the new beta.
![SAM_typo](https://user-images.githubusercontent.com/994565/75936642-6fc9ee00-5ece-11ea-96f2-b4ef5d9f5d2d.png)

Thanks,
Rob

**Comment by frohro** [comment]
I did a quick grep in the source, and the problem is quickly found.
`grep -R intput
src/stochastic.cpp:		wxMessageBox("Error retrieving weather file intput distribution");
src/stochastic.cpp:		wxMessageBox("Error with weather file intput distribution count");
deploy/runtime/versions.lk:			value('om_replacement_cost_escal', old_escalation, 'Battery replacement cost escalation moved from Battery Storage to System Costs intput page.');
`

**Comment by janinefreeman** [comment]
Thanks @frohro ! We will put this on our list to fix for the next patch.

**Comment by cpaulgilman** [comment]
Fixed in https://github.com/NREL/SAM/commit/fe023c87f6cf3c3e1c8079b73c662857dd9ec4cc
