### ISSUE TITLE
Linux build improvements

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#26]
Currently the Linux build requires a folder hierarchy looking like:

/workspace
/workspace/lk
/workspace/wex
/workspace/ssc
/workspace/SAM
/workspace/googletest

The Linux build can be improved in the following ways:

1. Require the assignment the following as environment variables:
LKDIR - /path/to/lk
WEXDIR - /path/to/wex
SSCDIR - /path/to/ssc
SAMNTDIR - /path/to/SAM
GTEST - /path/to/googletest

2. Update the Linux Makefiles to use these environment variables rather than forcing a specific folder hierarchy.

**Comment by nickdiorio** [comment]
One caveat is that this will break the existing Travis CI scripts and everyone's Linux build until they define their own environment variables

**Comment by janinefreeman** [comment]
Will @dguittet 's CMake improvements take care of this issue?

**Comment by nickdiorio** [comment]
Yes, the CMake improvements are the most robust way to deal with this for multi-platform support.

**Comment by brtietz** [comment]
Looks like this got done without being closed: https://github.com/NREL/SAM/wiki/Linux-Build-Instructions
