### ISSUE TITLE
Pull Request 259 UI equations reverted.

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#261]
All technologies without batteries with financial markets that use TOD factors fail with UI equations updates from PR 259. The issue that PR 259 was to address remains unresolved.

**Comment by sjanzou** [comment]
With UI forms reset, PB-Battery/Merchant Plant and Generic-battery/Merchant Plant fail. src/invoke.cpp changes remain.

**Comment by janinefreeman** [comment]
@dguittet @sjanzou Can one of you review to check if this issue is still relevant (and if so add some more detail), or if it should be closed (and if so, close it)? Thanks!

**Comment by sjanzou** [comment]
Tested all defaults with latest build - this issue was fixed with Batt fix #262 from Darice
