### ISSUE TITLE
Consider inverter current limits in PV sizing

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#272]
Idcmax is a parameter in the CEC inverter library, but not used in the system sizing messages on the System Design page or in the System Sizing macro. Pvsamv1 limits inverter input voltage to MPPT min and max ratings, but does not limit current.

User request:

> Would it possible to include the inverter input current limitation as this is an important element in the Electrical sizing without it the array configuration is unachievable.

Also:

https://sam.nrel.gov/forum/forum-general/555-max-inverter-current-idcmax.html#1739

**Comment by cwhanse** [comment]
What is the source for Idcmax?  I don't see it in the CEC data files, and the values look like they are calculated rather than taken from e.g. datasheets.

**Comment by cpaulgilman** [comment]
Yes, they are calculated. The script that creates the SAM library file from the CEC Excel workbooks calculates Idcmax = Pdco / Vdco.
