### ISSUE TITLE
Utility Rate Nested Tiers not handled quite correctly

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#275]
There is a minor bug in how SAM treats nested tiers within utility rates that we need to resolve. This is a small bug and affects very few utility rates.

**Comment by sjanzou** [comment]
@janinefreeman Is there an example project file that demonstrates the issue?

**Comment by brtietz** [comment]
Solved in https://github.com/NREL/ssc/pull/536 for net metering. Need to solve https://github.com/NREL/ssc/issues/535 before net billing and buy all/sell all work the same as the documentation.
