### ISSUE TITLE
Request up to 36 TOU periods for electricity rate structures

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#28]
This is for a CFE (Mexico) rate structure:

https://sam.nrel.gov/node/75299, now at https://sam.nrel.gov/forum/forum-general/1856

Note that the rates also change every year, so even with the additional TOU periods, the rate structure data will not match the actual rates.

**Comment by brtietz** [comment]
Link to post on current forum https://sam.nrel.gov/forum/forum-general/1856-comision-federal-de-electricidad-tarifa-h-m.html#5794

It looks like the time series rates got implemented, does that cover this case?

**Comment by cpaulgilman** [comment]
The time series energy buy and sell rates partially addresses this issue, but it does not address rates varying by year, which is another request we get periodically, such as in the following:

https://sam.nrel.gov/forum/forum-general/2891

https://sam.nrel.gov/forum/forum-general/2814

I'm not sure if it makes sense to add that level of complexity to the bill calculator. If we decide not to pursue that, we can close this issue.

Thanks,
Paul.

**Comment by brtietz** [comment]
Adding to patch 2 based on a dGen request for Colombian rates where there is a weekday and a weekend period that varies every month of the year. Initial scope is to add this to SSC for PySAM, we may create a separate issue to add this to the GUI (need to decide if the GUI work is patch or release).

**Comment by cpaulgilman** [comment]
Based on SSC implementation in https://github.com/NREL/ssc/pull/781, need to fix width of first column in Electricity Rate Data by Tier and Period table to fit 2-digit numbers. I would recommend making it adjustable like the other columns in the table:

![image](https://user-images.githubusercontent.com/27711933/158645585-ac777989-1e54-4442-a60a-8fc215638700.png)

![image](https://user-images.githubusercontent.com/27711933/158645736-5d875f24-9bad-4c5f-83af-8522a11d4919.png)

**Comment by brtietz** [comment]
781 has been merged into SSC - leaving this issue open and moving to the fall release so we can discuss implications on the GUI. Areas to test/discuss:

- Copying to/from TOD/Battery Dispatch schedules
- Output sizing as Paul discusses above
- Others?

**Comment by cpaulgilman** [comment]
SAM 2021.11.21 crashes when opening .sam file with 24 rates in https://github.com/NREL/ssc/files/8255563/24_rates_test.zip -- issue is in diurnal.cpp related to `m_colours` having 13 defined colors. Need to handle displaying weekday/weekend schedules with up to 36 values.

**Comment by sjanzou** [comment]
Addressed in wex https://github.com/NREL/wex/pull/158 and SAM https://github.com/NREL/SAM/pull/1357

Test file
[SAM_28.zip](https://github.com/NREL/SAM/files/10776843/SAM_28.zip)

Test 36 period csv to load as rate data
[tou-36-periods_update.zip](https://github.com/NREL/SAM/files/10776842/tou-36-periods_update.zip)

TODO items
1.	Test demand charges
2.	Update to better colors
3.	Review 0 key used for period 10 – other choice is period 36

![image](https://user-images.githubusercontent.com/6498311/219947155-f0441306-833a-4d03-b8e1-b0aa676eab8c.png)

**Comment by brtietz** [comment]
Great work! I tested demand charges this morning, and the following schedule produced the following table, so that looks like it works too!

![image](https://user-images.githubusercontent.com/5530592/220177664-60653bde-e7d9-41bc-9d24-d4a2a1070448.png)

![image](https://user-images.githubusercontent.com/5530592/220177752-d99eaa8b-f730-434d-ad3c-2ece47005054.png)
