### ISSUE TITLE
Codegenerator float to double check 

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#280]
c code has been fixed and lk fixed. All other languages updated  but not tested - see https://github.com/NREL/SAM/issues/222
https://github.com/NREL/SAM/issues/217
https://sam.nrel.gov/forum/forum-general/2958-sam-to-matlab-code-errors-generic-system-and-battery.html
"New SDK library with GCC" user support email chain

**Comment by cpaulgilman** [comment]
There have also been several questions about this issue in MATLAB on the SAM forum, for example:

https://sam.nrel.gov/forum/forum-sdk/2949

**Comment by sjanzou** [comment]
Go through Matlab issues and fix mex libpointer calls for all inputs and outputs. Also, modify code generation to copy the latest sscapi.h which is included in all platforms in the application path. Fix in SAM_280 branch of SAM and update ssc cmakelists for post build events on windows. Build and test and merge into patch and develop branches

**Comment by sjanzou** [comment]
For example, Matlab case for Generic-battery Residential results
![image](https://user-images.githubusercontent.com/6498311/82322270-75928400-9993-11ea-8f64-b47af3a24c0a.png)

Fix will be included in 2020.2.29 Revision 2 ssc version 240
