### ISSUE TITLE
Version upgrade script does not convert ppa_price_input for battery configurations

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#281]
For SAM 2020.2.29 versions, the upgrade script converts the input `ppa_price_input` from a number to an array for PPA financial models. For battery configurations (front-of-meter), the conversion does not work correctly.

1. Download [ppa_price_input_test_2018-11-11.zip](https://github.com/NREL/SAM/files/4477852/ppa_price_input_test_2018-11-11.zip) and extract the .sam file that was created in SAM 2018.11.11 r4.

2. Use SAM 2020.2.29 r1 or built from Patch branch to open the file.

3. On PV SO tab, Revenue page and PV LPF Financial Parameters page, PPA price is correctly converted from a number to an array.

4. On PV Battery SO Revenue page and PV Battery LPF Financial Parameters page, UI callback error:

```
Could not evaluate callback function:Financial Solution Mode Single Owner->on_load
[67]: operand to # ('sizeof') must be a array, string, or table type
[64]: eval error in statement list
[64]: error inside function call
[9]: eval error in statement list
```

Not sure if this is related, but note that `ppa_price_input` appears in two different var_info tables in [common,cpp](https://github.com/NREL/ssc/blob/develop/ssc/common.cpp):

![image](https://user-images.githubusercontent.com/27711933/79275428-04732480-7e5b-11ea-9d4b-d018b7862c16.png)

And:

![image](https://user-images.githubusercontent.com/27711933/79275492-24a2e380-7e5b-11ea-88c7-20a23eeae04e.png)

**Comment by sjanzou** [comment]
The issue was changing the configuration and overwriting new variable types with old variable types and then not being able to change from value to an array.  Fixed in SAM branch SAM_281 and merged into patch and develop.
