### ISSUE TITLE
Merchant Plant Inputs Browser Bug & Lack of Info

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#285]
The `mp_energy_market_revenue` inputs and those similar to it are 2D arrays (nsteps_per_year * analysis_years, 2), as shown in this screenshot from editing the value on its UI page:

![image](https://user-images.githubusercontent.com/29387736/79600247-13004c80-80a4-11ea-9714-ca0c456330f8.png)

But editing this value from the Inputs Browser does not show the 2nd column:

![image](https://user-images.githubusercontent.com/29387736/79600277-1f84a500-80a4-11ea-93ec-05a8372f3a0e.png)

Secondly, the SDKtool shows that Units are missing, making it difficult for users to tell that the input array should be 1) a 2d array, 2) lifetime, 3) cleared capacity & price.

![image](https://user-images.githubusercontent.com/29387736/79600447-65da0400-80a4-11ea-8ed9-39f7ec74e4c4.png)

**Comment by cpaulgilman** [comment]
I've seen a similar issue with other widgets that have a properties like Mode that can be set in the IDE. In this case, the DataLifetimeMatrix widget has properties like Mode, ColumnLabels, etc.

For example, batt_custom_dispatch is a DataArray object with a Mode property with 3 options. Opening the widget from the inputs browser has Mode set to the first option "Fixed 8760 Values", but the property on the Battery Dispatch Behind the Meter UI form is set to "Multiples of 8760 Values."

**Comment by sjanzou** [comment]
The labeling updated in ssc branch SAM_285 and merged into patch and develop branches.

![image](https://user-images.githubusercontent.com/6498311/81671817-a1978d80-9406-11ea-98d9-2b267864ad3a.png)

**Comment by sjanzou** [comment]
The inputs browser being worked on in SAM branch SAM_285 actively.

**Comment by sjanzou** [comment]
Fix first issue with DataLifetimeMatrix column settings in gridsupport.cpp in branch SAM_285
![image](https://user-images.githubusercontent.com/6498311/81801382-93627380-94d1-11ea-8883-943bea40752d.png)

**Comment by sjanzou** [comment]
Fixed in branch SAM_285 of SAM and merged into patch. Pull request created from 285 to develop for review by Paul and Darice.
![image](https://user-images.githubusercontent.com/6498311/81810909-07584800-94e1-11ea-9949-16f4436ec2fc.png)

results 
![image](https://user-images.githubusercontent.com/6498311/81810941-150dcd80-94e1-11ea-96b2-b13bca2c70a9.png)

Update load

**Comment by cpaulgilman** [comment]
Other widgets besides DataArray that have a mode property and may need a similar fix to work with the inputs browser are DataLifetimeArray and DataLifetimeMatrix.

**Comment by dguittet** [comment]
Variable descriptions look great! 

![image](https://user-images.githubusercontent.com/29387736/81871539-431cfd00-9535-11ea-8bd7-86b889ca7be7.png)
