### ISSUE TITLE
Battery state of charge drops suddenly

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#287]
For [this PV-battery / Single Owner case](https://github.com/NREL/SAM/files/4494590/curtailed_energy_bug.zip) with 5-minute simulations dispatching to time series power signal:

> I think it’s impossible to have an instantaneous/sudden energy discharge like that because each instant the battery is discharging power not a sudden block of energy (from the graphs of the 2020 version it looks like we lost 5% of SOC suddenly).

> That is to say, starting discharging from an initial 100% SOC, the SOC must change linearly according to a line whose inclination depends on the power discharged.

> Indeed in the 2018 version the SOC profile for those days is the following:
 
![image](https://user-images.githubusercontent.com/27711933/79602766-f7934280-809f-11ea-8271-dd3e84393eb9.png)

> While for the 2020 version is this:
 
![image](https://user-images.githubusercontent.com/27711933/79602783-fcf08d00-809f-11ea-8745-a27205368b28.png)

**Comment by cpaulgilman** [comment]
Possibly related to this issue, the 5-minute dispatch target data shown in the results is different from the input data. [This CSV file](https://github.com/NREL/SAM/files/4494907/dispatch_signal.txt) has one column of the original input target data and another for the target data as reported in the results.

Here are plots showing the difference between SAM 2020.2.29 and 2018.11.11. The pink line is the target dispatch signal. In 2018.11.11, the signal plot is square:

![image](https://user-images.githubusercontent.com/27711933/79608153-5315fe00-80a9-11ea-918b-e82b5f671178.png)

And in 2020.2.29, the signal plot seems to have been modified:

![image](https://user-images.githubusercontent.com/27711933/79608205-6923be80-80a9-11ea-8465-895b13c89324.png)

**Comment by dguittet** [comment]
Thanks Paul for the information and helpful plots. The target is indeed being modified in the newer SAM versions. This is to allow adjusting the target for constraints, which modify the target until convergence (or the iteration limit is reached). So I think the tapering of the battery charging as SOC reaches 100 makes sense. 

I'll take a look at the SOC instantaneous drop issue.

**Comment by dguittet** [comment]
It looks like the capacity update part is alright in that it's doing what it's supposed to, which is to adjust the SOC to the maximum capacity given the temperature.

The new 2020 default in battery default temperature is 20 C, and this is in a part of the temperature vs capacity curve that results in capacity loss:

![image](https://user-images.githubusercontent.com/29387736/81624667-037ad780-93b4-11ea-9ce0-11ec704e138f.png)

What's causing the sudden drop in SOC is actually that the increased current raises the temperature and the maximum capacity, thereby decreasing SOC very quickly:

![image](https://user-images.githubusercontent.com/29387736/81624651-f52cbb80-93b3-11ea-9921-236992959b47.png)

This effect is canceled when the room temperature is switched to 25 C.

We will be rolling out an updated thermal model in the next release, so I'm inclined to suggest we wait until then to make a lot of modifications, including thermal defaults. For this patch, I think at most we will change the room temperature default to 25.

**Comment by dguittet** [comment]
fixed with PR #303
