### ISSUE TITLE
DView 5-minute lifetime outputs last day is not Dec 31

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#289]
For Generic-Battery case with 5-minute liftime simulation, last day is Dec 27:

![image](https://user-images.githubusercontent.com/27711933/80405104-01bef900-8877-11ea-9d7c-49fc36632110.png)

For PV case with 5-minute lifetime simulation, last day is Dec 25:

![image](https://user-images.githubusercontent.com/27711933/80405747-ddafe780-8877-11ea-894b-c1aca712f2a3.png)

[5-min-lifetime-simulations.zip](https://github.com/NREL/SAM/files/4541357/5-min-lifetime-simulations.zip)

**Comment by cpaulgilman** [comment]
See https://github.com/NREL/SAM/issues/1616

**Comment by mjprilliman** [comment]
Dview is throwing in Feb 29 once every 4 years in the lifetime outputs. The graphs are taking from the default hourly PV case, which also does not end Dec 31st in the time series graph. The weather file has no leap day in the data. 

Year 1 (no leap year): 

![image](https://github.com/user-attachments/assets/74908d8c-095b-43fe-b531-00117df8c4bd)

Year 2 (leap year): 

![image](https://github.com/user-attachments/assets/71df1b55-ec0b-470c-bfc4-89dc286e1039)

Year 3-5 (no leap year)

Year 6: 

![image](https://github.com/user-attachments/assets/7e0dfb21-8c97-4f50-a9e8-25c40421bd1b)

25 year analysis period = leap days in years 2,6,10,14,18,22 = 6 days

Last day of lifetime array = Dec 25; 31 - 25 = 6 days missing. 

![image](https://github.com/user-attachments/assets/ac60e6df-6879-4ce2-b118-8074ac9a2eae)

Now to figure out how to fix that...
