### ISSUE TITLE
Battery calendar degradation rate varies with simulation time step

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#291]
The following graphs are for identical default PV Battery / Single Owner cases with 60-, 15-, and 5-minute simulations using the default 60-minute Phoenix weather file and the same data interpolated to 15- and 5-minute time steps.
 
[battery-calendar-degradation.zip](https://github.com/NREL/SAM/files/4547247/battery-calendar-degradation.zip)

Battery cycle degradation is disabled, and calendar degradation should result in 80% capacity after 10 years, and 50% capacity after 20 years:

![image](https://user-images.githubusercontent.com/27711933/80513102-6a6bab80-8933-11ea-8595-2da83a76f4d3.png)

These graphs of "Battery relative capacity to nameplate (calendar) %" show results results that appear to be correct for 60-minute simulations, but the rate of degradation increases with the number of time steps per hour:

**60 minutes:**
![image](https://user-images.githubusercontent.com/27711933/80513379-d0583300-8933-11ea-84da-74d2f6b969da.png)

**15 minutes:**
![image](https://user-images.githubusercontent.com/27711933/80513457-ef56c500-8933-11ea-8232-edff8a8b05bc.png)

**5 minutes:**
![image](https://user-images.githubusercontent.com/27711933/80513561-16ad9200-8934-11ea-8648-54e7ce445e2a.png)

**Comment by cpaulgilman** [comment]
A workaround solution is to adjust the calendar degradation table. For example, to adjust the table above for 15-minute simulations, multiply the number of days by 4 time steps/hour:

![image](https://user-images.githubusercontent.com/27711933/80514184-05b15080-8935-11ea-88c0-d74b681dbc38.png)

That results in:

![image](https://user-images.githubusercontent.com/27711933/80514329-2f6a7780-8935-11ea-89eb-809f1bab0950.png)

**Comment by brtietz** [comment]
This was an operator precedence issue in SSC. PR is open there, close this when that is merged.

**Comment by cpaulgilman** [comment]
Fixed in https://github.com/NREL/ssc/pull/359

**Comment by cpaulgilman** [comment]
This also appears to be an issue with the Li-ion degradation option. Brian, can you verify and fix if needed?

**Comment by dguittet** [comment]
Thanks for digging through this! I've been making some changes during my refactoring, and I've fixed this one already. Will link to it in a moment.

**Comment by brtietz** [comment]
This one was weird: the calendar model tests out ok in a unit test, but Li-Ion still has issues in the full SAM build. It will chug along normally for most timesteps, and then all of a sudden the calendar lifetime will crater by between 7 and 30% of SOC. I was wondering if the 5 minute resolution has temperature spikes that don't occur in hourly? I haven't had a chance to pin it down, but can easily re-generate the screenshots showing the sudden drops if desired.

**Comment by dguittet** [comment]
It could very well be! The current can be a lot higher in subhourly simulations. The temperature output has not been enabled in develop, but I've enabled first year temp outputs in the refactoring branch. One way to exclude the temperature effect is just to make the h really huge and have constant room temperature.

**Comment by brtietz** [comment]
That worked, if I make h 50,000, the five minute degradation matches hourly with h of 500.

The attached zip has a sam file (battery-calendar-degradation-li-ion_2020-2-29r1) that shows the issue. Are you able to test this on batt_refactor? I can also build batt_refactor if needed.
[battery-calendar-degradation.zip](https://github.com/NREL/SAM/files/4565541/battery-calendar-degradation.zip)

**Comment by dguittet** [comment]
Thanks for checking that! I ran the project on the batt_refactor branch and found the calendar degradation to be the same across the 3 different timesteps.

**Comment by dguittet** [comment]
I ran 1`battery-calendar-degradation-li-ion_2020-2-29r1` on the current patch branch and found the `battery relative capacity to nameplate` to be identical across the 3 time intervals. So closing this.

**Comment by dguittet** [comment]
This screenshot captures the difference between `batt_refactor` (top) and `patch` (bottom):
![image](https://user-images.githubusercontent.com/29387736/81717030-4fbb2b80-9437-11ea-8b20-505cca82797f.png)

The issue in `patch` is that the battery temperature jumps much higher, even with the same user-defined battery thermal parameters. 

Within the `patch` thermal model, I wasn't able to find a set of reasonable thermal parameters that resulted in reasonable temperatures (less than 50C is usually what manufacturers design for). This leads me to believe the issue causing the really high temperatures is the model itself rather than the parameter set... in which case we may just need to tune the Li-Ion degradation model to be less sensitive to temperature. Such as changing defaults (top) to bottom:

![image](https://user-images.githubusercontent.com/29387736/81719596-7dee3a80-943a-11ea-9e41-c999dd42ae4f.png)

Thoughts?

**Comment by brtietz** [comment]
It seems like changing those parameters would change the degradation in the hourly case.

I was able to get realistic looking degradation (matches the original yellow line) at a 5 min timestep with the following parameters:
Cell internal resistance: 0.0014 ohms (from https://www.nrel.gov/docs/fy17osti/67102.pdf)
Heat transfer coefficient: 18.4 watts/(m^2-K) (from https://iopscience.iop.org/article/10.1088/1757-899X/53/1/012014/pdf)

![temperature_degradation](https://user-images.githubusercontent.com/5530592/81723495-24890a00-9440-11ea-9722-c410966fc22e.png)

https://www.nrel.gov/transportation/assets/pdfs/apesaran.pdf implies 35 W/(m^2-K) might even be reasonable

**Comment by brtietz** [comment]
This is still an issue with:
* PV-Battery, Commercial
* Phoenix, 5 minute timestep
* Li-Ion Calendar degradation

Changing the heat transfer coefficient to 18 solves the problem, this basically means we'd be changing the default assumption from passive convection to forced convection.

Do we want to update the default in this patch, or keep this as a user support option until the new thermal model on develop can be released?
