### ISSUE TITLE
Enable self-shading for one-axis tracking systems with backtracking

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#292]
Since NREL/ssc#280 added diffuse shading to multiple self-shading scenarios, the "Shading and Layout" page in the UI needs to be updated to allow for self-shading when single axis backtracking systems are selected. This selection applies only diffuse shading, since there is no beam shading for a backtracking system. There will be no difference between "thin film (linear)" and "standard (non-linear)" options in a backtrack system, since only diffuse shading applies and non-linear shading is from beam shading.

**Comment by cpaulgilman** [comment]
Tested on Linux Ubuntu 18.04.3 LTS

**Comment by cpaulgilman** [comment]
Revised description in Help for [Fall 2022 release](https://github.com/NREL/ssc/milestone/20). (We forgot to revise Help for the SAM 2020.2.29 release when this change was made.)
