### ISSUE TITLE
PV Battery Single Owner to PV Single Owner model change fails

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#293]
Steps to reproduce from patch branch build of SAM:
1. Create Detailed PV-Battery Single Owner case
2. Under the case menu chose "Change model..."
3. Select Detailed PV Model Single Owner configuration
4. Click Simulate
![image](https://user-images.githubusercontent.com/6498311/80591764-790d9d80-89db-11ea-98ca-d17a61e5ae04.png)

The workaround is to click the "System Design" page. Then simulation runs without issue.

**Comment by sjanzou** [comment]
Update Battery Enable page and add equation for non-battery configurations:
![image](https://user-images.githubusercontent.com/6498311/80692376-b4b56f80-8a8e-11ea-9578-fb59b5b11e88.png)

Update and test switching technologies and upgrading 2018.11.11 project files.

**Comment by sjanzou** [comment]
Merge change into patch and develop branches.

**Comment by cpaulgilman** [comment]
Tested on Linux Ubuntu 18.04.3 LTS
