### ISSUE TITLE
Fuel Cell configurations Issues

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#294]
With 2020.2.29.r1 and latest patch branch builds, the Fuel Cell Battery Storage has the following issue:

**Comment by sjanzou** [comment]
Issue 1 with FOM:

Create Fuel Cell / Single Owner configuration
Click on Dispatch page

Receive error:
![image](https://user-images.githubusercontent.com/6498311/80694502-d401cc00-8a91-11ea-9121-302e25ccda85.png)

**Comment by sjanzou** [comment]
Trace issue through and find that toggle_custom_dispatch applies only to behind the meter configurations and update 
![image](https://user-images.githubusercontent.com/6498311/80701982-9014c400-8a9d-11ea-8d56-38080705b198.png)

Build and test for several configurations - working

**Comment by sjanzou** [comment]
Merge fix into both patch and develop branches of SAM

**Comment by cpaulgilman** [comment]
Tested on Linux Ubuntu 18.04.3 LTS
