### ISSUE TITLE
Bifaciality feature is not working on PVwatts v7

### ISSUE THREAD

**Issue by rkj90266** [NREL/SAM#295]
In the release notes it says:
The following new features in PVWatts V7 are in SAM Simulation Core (SSC) (accessible via the SAM SDK) but not in SAM:
•        Stow trackers when wind speed exceeds an upper limit (to avoid wind damage).
•        Bifacial modules.
•        Transformer losses.
•        Soiling loss input as a beam irradiance loss.
In the SDKtool, the variables listing gives the following:
Type | Data | Name | Label | Units | Meta | Group | Require | Constraint
SSC_INPUT | SSC_NUMBER | bifaciality | Module bifaciality factor | 0 or ~0.65 |   | System Design | ?=0 |  

I have tried various values of the bifaciality factor and found that any value other than zero gives the same very small (~0.4%) increase in energy produced, and there seems to be no limit check (setting bifaciality anywhere from 0.1 to 99000 hade no difference.
 
I have verified that the produced energy with bifaciality is increased by increasing the albedo, but again, the performance gain is very small, about 0.4%, much less than the 6-9% being reported in the literature.

**Comment by janinefreeman** [comment]
Confirmed that pvsamv1 implementation produces ~4% greater annual energy with bifacial for a PVWatts-like system, but pvwattsv7 produces ~0.4%. Since pvsamv1 implementation has been validated against other codebases, this is an implementation issue in pvwattsv7.
