### ISSUE TITLE
Rate switching not available for Residential and Commercial financial models

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#301]
Electricity bill calculations calculate bill savings by subtracting a "with system" bill from a "without system" bill. Both bills are calculated using the same rate structure. In rate switching the "with system" bill uses a different rate structure than the "without system" bill. For example, a residence might pay energy charges based on a flat rate, but qualify for TOU rates after a PV system is installed.

The Value of RE macro calculates the electricity bill and NPV for a rate switching scenario, but several users have requested that rate switching be available with a regular simulation.

> independent of CHP considerations, in SCE’s Service AREA, if one installs a significant enough battery system  and or PV system, one can opt for a different version of TOU 8D. Last year, one could go to TOU8 R , and there were other rate switch options. Also, I approximated the Departing Load Charges, these CHP monthly charges I think  are actually (Total Annual Generation/12 x the Departing Load Charge (about .0034/KWH).

This would require that the bill calculator have inputs for two rate schedules and that the user interface allow for two separate sets of electricity rate inputs.

**Comment by brtietz** [comment]
While I was looking for resources on real time prices and net metering, I found this resource from ComEd on what happens if you switch from net metering to real time prices: https://hourlypricing.comed.com/faqs/ Could be useful when we address this issue.

**Comment by brtietz** [comment]
Reopening based on 2025 AOP
