### ISSUE TITLE
Add PDF Report Template for PV Battery Configurations

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#302]

**Comment by cpaulgilman** [comment]
Samples from other tools:

[SCE1.pdf](https://github.com/NREL/SAM/files/5196410/SCE1.pdf)

[HousingVT-RedClover-10-11-2017.pdf](https://github.com/NREL/SAM/files/5196411/HousingVT-RedClover-10-11-2017.pdf)

**Comment by mjprilliman** [comment]
Closed by pull request #402
