### ISSUE TITLE
Release report editor

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#308]
There is a report editor contained within the SAM development environment for internal use that we would like to release publicly as a largely unsupported bonus feature, which will involve moving it in front of the SAM interface password in the public version of SAM. We'll target this for our next release, and hope to accompany it with a short webinar to teach people how to use it.

**Comment by dguittet** [comment]
Update 9/24:

Removing from the 2021 Release milestone, because this requires a lot of documentation and error checking (hard crashes from @mjprilliman) if released as is.

**Comment by janinefreeman** [comment]
If we release a report editor, we need to upgrade it to something more usable. We'll see if we get any requests/funding for that type of thing.
