### ISSUE TITLE
Run LK Script from the Command Line

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#309]
In order to test the configurations on Travis, we needed to be able to run lk scripts from the command line. Other users have requested this feature (see https://sam.nrel.gov/forum/forum-sdk/2999-automating-sam-with-lk-script.html#8200)

Once it’s released the syntax is:

[full path to SAM] [any string (can also be a .sam file)] [full path to lk script]

For example (on Linux):

/home/brian/src/sam/build/deploy/linux_64/SAM.bin no_sam_file /home/brian/src/sam/build/deploy/test_script_ow.lk

Close this issue after https://github.com/NREL/SAM/pull/297 is merged

**Comment by brtietz** [comment]
Added with https://github.com/NREL/SAM/pull/297

**Comment by joel3003** [comment]
Hi, I am wondering if it is possible to use the command line to run an LK script from a particular .sam file. For instance, at the moment I can run an LK script from sam.exe using [path to sam.exe] [any string] [path to .lk script], but I am wondering how I may be able to run the LK script from a particular .sam. For instance, [path to .sam] [path to .lk]. Is this possible?
Thanks!

**Comment by cpaulgilman** [comment]
That's not possible, but is something we could look into implementing. For more discussion on this, see https://sam.nrel.gov/forum/forum-sdk/2999.

**Comment by joel3003** [comment]
If it could be implemented down the track that would be great! I currently want to repetitively run a .LK script from a batch file using Python. However, to run the .LK script I also need to have a particular .sam opened with it. It would be easiest if I could call them together from the batch file, unless there is another way to do this? Thanks!

**Comment by janinefreeman** [comment]
Can the LK script open the SAM file as its first step?
