### ISSUE TITLE
Feature request: REopt size for resilience

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#313]
carrying over request in #310 from @brianschmidly

Let SAM pick the battery size (and solar PV size) based on probability of surviving an outage and then filter the results (in a parametric study) By NPV or savings or simple payback. 

Awaiting response from REopt team on availability of resilience as objective from REopt Lite API.

**Comment by brtietz** [comment]
Some additional issues that I'm going to clean up as a part of the pull request for this issue:

1. The "Get size and dispatch" button _always_ applies the custom dispatch value even if the user selects "no" on the sizing, ask the user about this too.
2. REopt (now?) has inputs to allow for only charging from PV, so we can avoid forcing charge to grid in the API call.
3. The solution to https://github.com/NREL/ssc/issues/923 used "gen" as the variable for the production factor series, but this includes the battery dispatch throwing off the times that the battery should be charging. Swap this over to PV production without battery.
4. https://github.com/NREL/ssc/blob/6c9fda04a7253385ed90b55dab5c3b2788b718d3/ssc/cmod_battery_eqns.cpp#L159 assigns inverter and rectifier efficiencies to the internal efficiency variable, we can reassign these and leave internal efficiency at the default.
