### ISSUE TITLE
Fuel Cell + Battery Error for Subhourly Simulations

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#315]
Bug in the pv-battery-fuel cell module running with:
 
•	Phoenix, interpolated to 5 minute timesteps
•	Battery enabled with Li-Ion degradation
 
The bug is:
 
exec fail(generic): Failed to accumulate time series (hourly or subhourly): gen to monthly: monthly_energy
Simulation pvwattsv7 failed :exec fail(generic): Failed to accumulate time series (hourly or subhourly): gen to monthly: monthly_energy

Exists on both develop and the beta R2 that Steve sent out. Hourly works as expected.

**Comment by janinefreeman** [comment]
Do we know if this is in the current release, or only on our development branches?

**Comment by brtietz** [comment]
Paul confirmed that it was in the beta release yesterday. I don't know if anyone has yet tested 2020.2.29 R1.

**Comment by cpaulgilman** [comment]
I've replicated it in SAM 2020,2.29, 2020.2.29 r1, and 2020.2.29 Patch built this afternoon 5/20/2020.

**Comment by brtietz** [comment]
Solved in SSC MR (linked above)
