### ISSUE TITLE
Create snaps for Linux

### ISSUE THREAD

**Issue by bje-** [NREL/SAM#322]
It would be great if the Linux versions of SAM could be released as snaps. See https://snapcraft.io/docs for details.

**Comment by dguittet** [comment]
Thanks @bje for the suggestion. 

We currently approach the problem of being linux distro agnostic by building on an old distro (Centos 7). This may result in missing out on improvements built into later distros. 

I don't foresee this being a priority soon, but if you were interested in building a snap for SAM, we'd be happy to test it and distribute it.

**Comment by bje-** [comment]
Sure, I can have a go.
