### ISSUE TITLE
Cannot download from NREL Wind toolkit API

### ISSUE THREAD

**Issue by Qunlexie** [NREL/SAM#353]
Hi I have been unable to get wind resource file from the NREL tool kit since Friday. Is this because of the update to the Wind toolkit API by NREL?

**Comment by cpaulgilman** [comment]
Hi,

The WIND Toolkit downloads from the Wind Resource page in SAM should be working more reliably now.

What location name or latitude/longitude pair are you using for the download?

Thanks,
Paul.

**Comment by cpaulgilman** [comment]
Related to https://github.com/NREL/SAM/issues/216

**Comment by cpaulgilman** [comment]
Updates to WIND Toolkit APIs and code revisions in 13e6e38f7ad23b4f1b8810a87b8b0fe130fa3fb7 fix this issue.
