### ISSUE TITLE
Time series buy and sell rates do not apply to net metering with $ credits

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#358]
If you choose the utility rate "Net Energy Metering with $ credits" and check the box for "Use (sub)hourly buy rates" the buy rates are not applied. This is because the time series buy rates are only represented in cmod_utility_rate_5's ur_calc_timestep function, and not ur_calc (which is run for the first two metering options). Time series sell rates have the same problem.

Either a GUI update or a fix in SSC would work for this issue, the former sounds easier.

**Comment by sjanzou** [comment]
We should decide the applicability to all the metering options first and then we can either update the GUI and ssc (to throw an exception as Brian stated in email) or fix ssc. My vote would be to fix ssc to properly handle subhourly buy and sell rates for all applicable net metering options.  Thoughts?

**Comment by brtietz** [comment]
Owen's email from the morning of 7/29 describes why net metering and time series rates are incompatible, specifically: 

> expired generation credits do not have timestamps associated with them, let alone sub-hourly “time-series” timestamps associated with them. 

So the SSC code is correct to have different functions for net metering vs net billing.

One behavior I'd like to clarify is what happens if a user inputs hourly buy/sell rates, and changes to net metering? The current GUI behavior might be confusing:

![net_billing_real_time](https://user-images.githubusercontent.com/5530592/88822673-62fdad80-d181-11ea-93ca-75e70b389545.png)

the user cannot enter TOU rates if the boxes are checked, even if the radio button is switched back to net metering. Should switching to net energy metering (or net energy metering with $ credits) forcibly uncheck the hourly sell rate/buy rate boxes? Note that input buy/sell rates can be recovered (they aren't reset to zero if the box is unchecked).

@dguittet do notices work in PySAM, or is an exception the only way to inform the user of the incompatibility of these variables?
