### ISSUE TITLE
Electricity Rate data on OpenEI is more up to date than data SAM downloads

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#361]
Latest OpenEI Utility Rate APIs are listed at https://openei.org/services/.

See SAM forum: https://sam.nrel.gov/forum/forum-general/3093.

**Comment by brtietz** [comment]
I pinged Jay Huggins about this, and it looks like the only differences between v5 and v7 are in the request, not the response:

```
Version 7 of the API vs v5 has some improvements in geo search and handling date queries, and adds the following query parameters:
•	effective_on_date
•	is_default

There’s also version 8 which dropped demandratchetpercentage in favor of lookbackmonths, lookbackpercent, and lookbackrange.
```

So an upgrade to version 7 could be trivial if we want to use the same request. I wasn't able to find the response parsing code to see if we use demandrachetpercentage, but it sounds like that portion of the rate upgrade might also be able to be deferred until Steve has a chance to work on ratcheting demand charges.

**Comment by cpaulgilman** [comment]
urdb.cpp uses hard-coded urls for API calls. Elsewhere in SAM, the URLs are stored in the runtime/webapis.conf text file (for NREL versions, webapis.conf must be updated in both SAM and SAM-private).

The URDB API calls in urdb.cpp use http instead of https -- I think those should be changed to https.

In urdb.cpp, the API calls from SAM use V3 for the list of utilities and available rates: https://github.com/NREL/SAM/blob/6f4761f962bab659fb1cd0c707d2c5eeb02fbdfe/src/urdb.cpp#L155, https://github.com/NREL/SAM/blob/6f4761f962bab659fb1cd0c707d2c5eeb02fbdfe/src/urdb.cpp#L202, https://github.com/NREL/SAM/blob/6f4761f962bab659fb1cd0c707d2c5eeb02fbdfe/src/urdb.cpp#L385.

And V4 for the rate data itself: https://github.com/NREL/SAM/blob/6f4761f962bab659fb1cd0c707d2c5eeb02fbdfe/src/urdb.cpp#L332.

Should those be updated to V7?

And there are calls to special APIs to manage utility names: https://github.com/NREL/SAM/blob/6f4761f962bab659fb1cd0c707d2c5eeb02fbdfe/src/urdb.cpp#L230, https://github.com/NREL/SAM/blob/6f4761f962bab659fb1cd0c707d2c5eeb02fbdfe/src/urdb.cpp#L285.

If we update to V7, are those special API calls compatible with V7?

According to the API documentation, one difference between the V7 response (https://openei.org/services/doc/rest/util_rates/?version=7) and the V4 response (https://openei.org/services/doc/rest/util_rates/?version=4) is the new `dgrules` that replaces the old `usenetmetering`. If the dgrules data is good, I think we should read that value to set the value of the `ur_metering_option` input. 

Some other v4 response fields have been removed, for example, two that I think SAM reads:
minmonthlycharge
annualmincharge

And other new response fields in v7. If the fixed charge and fuel adjustment fields are charges, they would have to be read into SAM and either added to the monthly fixed charge input or as new input variables:
is_default
servicetype
fueladjustmentsmonthly
fixedchargefirstmeter
fixedchargeeaaddl
fixedchargeunits
mincharge
minchargeunits

**Comment by brtietz** [comment]
Additional upgrades: change as many hardcoded urls in urdb.cpp as possible to use https. The zip code query recently broke because we use http, and the server now requires https.

**Comment by cpaulgilman** [comment]
The different URDB versions seems to be causing an issue with the REopt implementation in SAM. I was able to replicate the UI call back error described here: https://sam.nrel.gov/forum/forum-general/3170

> Hi, I created a PVWatts Battery Commercial case, when I change the electricity rate I got this error: Could not evaluate callback > function:call_reopt->on_change
> [10]: error in call to 'reopt_size_battery()': ElectricityRates_format_as_URDBv7 error. Unit type in ur_ec_tou_mat not allowed.[8]: > eval error in statement list.
> 
> I used this rate Bagley Public Utilities Comm: Commercial Electric Three Phase.

**Comment by dguittet** [comment]
@cpaulgilman Thanks Paul, I'll have to fix that for the next Release

**Comment by cpaulgilman** [comment]
@brtietz I'm working on updating to URDB V7 (https://api.openei.org/utility_rates?version=7) for the rate downloads. Could you share a link to the new rate data you added for my tests?

**Comment by brtietz** [comment]
Closed in https://github.com/NREL/SAM/pull/423 ?
