### ISSUE TITLE
Net Billing results do not show $ credits

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#372]
For the Net Billing option, monthly bill is calculated correctly based on credits earned, but dollar credit amount not reported correctly. See https://sam.nrel.gov/forum/forum-general/3122.

**Comment by brtietz** [comment]
It looks like it could be more of a naming issue than a code issue. Here's what I see running the SAM file from that issue with a different weather file (Blythe, CA):

![image](https://user-images.githubusercontent.com/5530592/94735164-8ed71400-0327-11eb-8976-a1d70d7ea6b7.png)

The credits are being applied immediately during the month when they are earned. "Excess generation $ credit earned" is reserved for months where the credit rolls over to the next month (Net billing with carryover to next month):

![image](https://user-images.githubusercontent.com/5530592/94735337-d5c50980-0327-11eb-8507-38c85b1a0fdc.png)

![image](https://user-images.githubusercontent.com/5530592/94735371-e5dce900-0327-11eb-801c-1086db6b173a.png)

Thoughts on name changes that might make this more clear? Or am I missing something about the bug?

**Comment by cpaulgilman** [comment]
I agree there is a labeling problem, and also think it would be helpful to modify some of the monthly output variables to help people understand how SAM calculates the monthly bill for he different billing options:

**Excess generation** (kWh) for both net energy metering options: 
 
    * sum(generation[h]) - sum(load[h]) for net energy metering options

    * sum(generation[h] - load[h]) for net billing options

    * set to zero for buy all / sell all

**Net metering credit** (kWh), for *net metering* only, kWh credit that applies to current month (includes this month's excess generation and any credits rolled over from previous months).

**Net metering credit** ($), for *net metering with $ credits* only, shows $ credit that applies in current month. 

**Net billing credit** ($), for two net billing options, shows $ credit that applies in current month, regardless of when it was earned. Or, use that for *net billing* only, with a separate **Net billing carryover credit** ($) for *net billing with carryover to next month*.

**Comment by brtietz** [comment]
Finally had some time to dig into this. I like these categories, are these generally additions or replacements? Some notes are below:

With net metering **Excess generation** only fits that calculation when there is one TOU period. For example, for the SAM default rates, if sum(generation[period_3]) > sum(load[period_3]) but sum(generation[period_1]) < sum(load[period_1]) at the end of the year, the customer would still receive true-up credits for the excess generation in period 3. I would favor reporting those credits in the **Excess generation (kWh)** column.

Are there any differences (besides the name) between the **Net metering credit** column and the existing **Excess generation cumulative kWh credit earned** column? Or is this closer to **Excess generation kWh credit applied**?

With **Net metering credit** ($) I think it makes sense to include the end of year true-up credits in that column for the net metering option, similar to the existing behavior of Excess generation $ credit earned.

**Comment by cpaulgilman** [comment]
@brtietz I agree with your suggestion for **Excess generation** -- my examples show equations for a simple flat rate.

**Excess generation cumulative kWh credit earned**, **Excess generation kWh credit applied**, and **Excess generation kWh credit earned** were an attempt to make the excess generation credit calculation transparent, but are confusing. What would be useful is to replace those with one **Net metering credit** column that shows the kWh that are applied in a given month, and perhaps an **Excess generation** column that shows the excess generation in each month (although that can easily be calculated by subtracting **Electricity load** from **Monthly energy**, so maybe not necessary).

I agree with **Net metering credit** ($) and true-up credit.

**Comment by brtietz** [comment]
Some clarifications on the above for net metering based on Paul and my meeting this morning:

- **Excess generation kWh applied** will be removed. The numbers currently in this category have some errors, and determining how many credits are "applied" in one month can be ambigious
- Rename **Excess generation cumulative kWh credit earned** to more clearly indicate that this shows the annual credits used in the true-up (exact name TBD)
- Add a variable showing the cumulative monthly rollover credits, the variable in ur_month.ec_energy_surplus. Users can go to the existing "electricity rate data by tier and period" variables to see more about how these numbers are computed.

Net billing will be updated as outlined above.

**Comment by sjanzou** [comment]
@brtietz, are the ur_month.ec_energy_surplus restricted to rollovers in the same periods?

**Comment by brtietz** [comment]
Within a month, yes. Between months, if the period times change, the credits can be shifted between periods using the code in https://github.com/NREL/ssc/blob/c1a40c53f91bca6949dee63df9ed6aae672fbe71/shared/lib_utility_rate_equations.cpp#L837

I was thinking that having a sum of the hours available in ur_month.ec_energy_surplus would be a useful indicator to tell the user whether they needed to dig into the "electricity rate data by tier and period" outputs for a given month.

**Comment by brtietz** [comment]
@cpaulgilman For net billing, does it make sense to make Excess generation

sum((generation[h] - load[h]) > 0) ?

This equation above ensures that:
(excess generation) * (sell rate) = (excess $ earned)
for a flat sell rate. (I still need to make the updates for net billing $, just reporting the odd hybrid in front of me)

SAM 2020.2.29 reports net monthly kWh in this category for both net metering and net billing.  It's worth noting that your equation above has the same result for net metering and net billing due to the associative property, and I want to make sure that's what we want.

Changing reporting the sum of the surplus credits would mean excess generation changes based on the utility rate option, so I'm open to adding a new variable for the above output instead.

**Comment by brtietz** [comment]
Additional bug found while developing these changes: In the help, "net billing with carryover to the next month" says "For months with excess generation, the dollar value of the excess is credited to next month's bill." and "Any credit remaining at the end of December is credited to the December electricity bill."

However, in develop and SAM 2020.2.29 credits earned in December are never applied. Should these be applied in December or January?

**Comment by brtietz** [comment]
https://github.com/NREL/SAM-documentation/blob/master/UtilityRates/NetBilling/Updates_2016.7.28/Workbooks/Tiered%20TOU%20single%20meter%20Net%20Billing%20%24%20rollover.xlsx row 8764 column AG suggests credits earned in December should be applied to the "December year end payout"

**Comment by cpaulgilman** [comment]
@brtietz I think it makes sense to show the same excess generation (kWh) value regardless of the billing option.

I think the December credits should be applied to January now that we can do that, although that would mean January in Year 1 starts with a credit.

Was the "December year end payout" required before we could apply the December credits to January?

Finally, should the "Month for credit rollover" option be available for the Net billing with carryover to next month option?

**Comment by brtietz** [comment]
@cpaulgilman Do you have an example of a utility that does continuous rollover like that? The only one I could find on this topic was Arizona Public Service: https://www.sunrun.com/utility/az/aps/how-to-read-your-aps-nem-bill
https://www.aps.com/en/Residential/Service-Plans/Compare-Service-Plans/Renewable-Energy-Riders#RCPExportRider

It looks like they'll roll over Dec to Jan if the credit is < $25, and cut a check if it's >= $25.

I think the "Month for credit rollover" option should be available if we go with the code in #483, but we should take it away if we decide to do continuous rollover.

**Comment by brtietz** [comment]
Ah, got it! Yes, "End of true-up period" or "month of annual surplus compensation" would be better names, and that is used by the net billing with rollover credits code. Swap "December" in all of my comments above with the month selected in that drop-down.

Merged in f94e504
