### ISSUE TITLE
Welcome page displays parse error when SAM not connected to internet

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#376]
Welcome page should load a special local version of welcome.lk like this one, [welcome_local.zip](https://github.com/NREL/SAM/files/5158123/welcome_local.zip), from the runtime folder if SAM is not connected to the internet.

**Comment by sjanzou** [comment]
Fixed with SAM-private commit 7b261ac95bde3ad06acae8f058b6c526dcae4bf9

Available for testing in SAM 2020.11.17 ssc 247 beta

Details in attached document
[SAM_376.docx](https://github.com/NREL/SAM/files/5553244/SAM_376.docx)
