### ISSUE TITLE
URDB issue with the REopt implementation in SAM

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#388]
The different URDB versions seems to be causing an issue with the REopt implementation in SAM. I was able to replicate the UI call back error described here: https://sam.nrel.gov/forum/forum-general/3170

> Hi, I created a PVWatts Battery Commercial case, when I change the electricity rate I got this error: Could not evaluate callback > function:call_reopt->on_change
> [10]: error in call to 'reopt_size_battery()': ElectricityRates_format_as_URDBv7 error. Unit type in ur_ec_tou_mat not allowed.[8]: > eval error in statement list.
> 
> I used this rate Bagley Public Utilities Comm: Commercial Electric Three Phase.

_Originally posted by @cpaulgilman in https://github.com/NREL/SAM/issues/361#issuecomment-699224070_

**Comment by dguittet** [comment]
@cpaulgilman This is actually an issue with the rate not having Max. Usage Units:

![image](https://user-images.githubusercontent.com/29387736/98843839-ba5e1b80-2408-11eb-8822-c22b0b4adb00.png)

from https://openei.org/apps/USURDB/rate/view/539f7306ec4f024411ecf833#3__Energy
![image](https://user-images.githubusercontent.com/29387736/98843861-c2b65680-2408-11eb-8bc4-33f6128b7ddf.png)

Looks like it still simulates in utilityrate5 which assumes that if there are no units, there are no tiers; Is this a safe assumption that I should build into the REopt sizing fxn in SAM?

**Comment by cpaulgilman** [comment]
I think it is safe to assume that if there is only one tier, the max usage and max usage units are not required because they do not apply. 

I don't know if there are any rates in the URDB that have more than one tier with no units -- I will see if I can find any in case that is a database error we need to handle.
