### ISSUE TITLE
Marine energy summary page enhancements

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#390]
Add requested output metrics to ME wave and tidal model summary pages. Allow for more than one table on the summary page, with tables being able to have more than 2 columns. Add sector plotting to autographs.lk. 

This work is in marine_cost_UI branch for SAM, ssc, and wex.

**Comment by mjprilliman** [comment]
@sjanzou a potential future improvement for agraphs is in issue #382. I haven't figured out a way to do this yet but maybe in a future patch.

**Comment by sjanzou** [comment]
@mjprilliman, do you need anything from me for this?

**Comment by mjprilliman** [comment]
@sjanzou I think I am just in UI cleanup at this point so most likely no. No substance changes for the summary page or output reporting. I need to determine why the Travis build failed.

**Comment by sjanzou** [comment]
@mjprilliman, everything looks good to me... No rush, I will make a beta 11/3/2020.

**Comment by GridTechs** [comment]
Great work team
