### ISSUE TITLE
Add support for PV-battery with DC-connected battery and multiple MPPT inputs:

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#396]
Add support for PV-battery with DC-connected battery and multiple MPPT inputs:

https://sam.nrel.gov/forum/forum-general/3160

_Originally posted by @cpaulgilman in https://github.com/NREL/SAM/issues/215#issuecomment-693702967_

**Comment by dguittet** [comment]
From https://github.com/NREL/ssc/issues/250 about DC-Connected batteries, we have the configuration for a single-MPPT inverter:
![image](https://user-images.githubusercontent.com/29387736/95630726-91302100-0a3f-11eb-9427-e4ca065a4fc7.png)

![image](https://user-images.githubusercontent.com/29387736/95630195-a3f62600-0a3e-11eb-9239-934118a30887.png)

The simplest way to support DC-connected battery with multiple MPPT inputs may be to assume charge controllers for each PV array are connected to the battery, which can then charge from both PV arrays. Each PV array's power can charge the battery or be inverted. The power inverted is the sum of the PV arrays and battery. The rectifier shown in the first diagram is not explicitly modeled currently, but the power passing from the AC bus to the BMS is netted out of the power inverted.

Thoughts and suggestions welcome.

Mermaid markdown code for diagram:
```
graph LR
A[PV Array]-->C[DC/DC Power Optimizer]
B[PV Array]-->D[DC/DC Power Optimizer]
C-->E[Inverter]
D-->E
C-->F[DC/DC Battery Management System]
D-->F
F-->G[Battery]
G-->F
```

**Comment by cpaulgilman** [comment]
Some additional context:

This revised diagram [from help](https://samrepo.nrelcloud.org/help/battery_storage_btm.htm) shows how SAM models BTM PV-battery DC-connected systems in a way that is more consistent with SAM's inputs than the older version of the diagram:

![image](https://user-images.githubusercontent.com/27711933/164757135-b3b2c3e3-49fd-433b-a980-044019f22387.png)

Feedback from a user (with diagram):

> Most residential battery based DC Coupled systems have the DC/DC converter that steps down the 600V to 24-48V and the inverter is then 24-48V based. It would be great to be able to model these types of systems in the future more accurately. Do you think this could be a future possibility?

![image](https://user-images.githubusercontent.com/27711933/164757321-2b992d5d-10b4-4129-832c-2239b087d6f5.png)

**Comment by cpaulgilman** [comment]
See also https://github.com/NREL/SAM/issues/215
