### ISSUE TITLE
Battery replacement percentage does not change cost

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#399]
Triggering a battery replacement in the "Replace at specified schedule" option triggers 100% of the battery replacement cost, regardless of the percentage specified in "Battery bank replacement percent." In the attached SAM file, both cases see the same expenses, but "replace 100%" gets a larger capacity boost.

Cost should be based on % replacement.

[battery_replacement_bug.zip](https://github.com/NREL/SAM/files/5372862/battery_replacement_bug.zip)

**Comment by brtietz** [comment]
Additional decisions made during the SAM meeting:

- Remove the replacement schedule table - replacements must be specified in the % schedule
- @cpaulgilman will need to make these adjustments in the version upgrade script, and was considering adding help messages if the user specifies a replacement cost schedule (costs need to be specified in replacement years)

**Comment by brtietz** [comment]
@cpaulgilman and @dguittet - I started ripping out some of the replacement code, and realized that a feature of the replacement schedule input was to allow multiple replacements per year. For example, if the user specified "2" then this code in battery_t::runReplacement would schedule a replacement in the middle of the year:

![image](https://user-images.githubusercontent.com/5530592/96755894-860ab880-1390-11eb-8940-0450733f2cdb.png)

Is that a feature we want to maintain? If so, is there a not-confusing way to get it in the percent input, or do we need two inputs?

**Comment by dguittet** [comment]
I can't think of a reason to have more than 1 replacement in a single year. 

As an aside, I think there was originally some consideration about battery augmentation (increasing capacity for increased future load) but that could be covered by a percent > 100%.
