### ISSUE TITLE
Scroll bars on long input pages don't always work

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#405]
For long input pages and results pages, especially ones with expanding panels, the scroll bar does not always show the bottom of the page. Workaround is to switch to a different page and back.

Some examples:

Financial Parameters page for Single Owner:

![image](https://user-images.githubusercontent.com/27711933/96650962-ae3edc80-12e8-11eb-8ba8-9d42075dfc30.png)

Battery Storage page for PV Battery:

![image](https://user-images.githubusercontent.com/27711933/96651131-01189400-12e9-11eb-9a0d-1bb345c8994e.png)

Cash Flow tab on Results page:

![image](https://user-images.githubusercontent.com/27711933/96651247-43da6c00-12e9-11eb-8526-b2683876f0d3.png)

**Comment by sjanzou** [comment]
Steps to reproduce effect:

1. Create generic battery, sales leaseback configuration
![image](https://user-images.githubusercontent.com/6498311/96835170-73c86300-1400-11eb-9c77-ffd2eb2d0e87.png)

2. Open Battery Cell and System page
![image](https://user-images.githubusercontent.com/6498311/96835241-8cd11400-1400-11eb-97de-c4434d56c255.png)

3. Scroll down
![image](https://user-images.githubusercontent.com/6498311/96835291-9fe3e400-1400-11eb-9be6-4ce7e34c3c95.png)

4. Return to Power Plant page
![image](https://user-images.githubusercontent.com/6498311/96835347-b427e100-1400-11eb-9280-e4a8f5f291e2.png)

All widgets moved down on page...

**Comment by sjanzou** [comment]
PR #408 fixed input page scrollbar issue but cash flow scrollbar issue remains
![image](https://user-images.githubusercontent.com/6498311/96950849-7aaab080-14a8-11eb-874e-b939f39085a0.png)
