### ISSUE TITLE
DNI spikes 

### ISSUE THREAD

**Issue by mr1001v** [NREL/SAM#414]
SAM 2020. 2.29
It looks like that with high resolution weather data (e.g. 1min data), SAM internally calculating very high DNI spikes. The associated weather file should not give any reason for that, see picture.
![grafik](https://user-images.githubusercontent.com/46873057/97592179-aa097200-1a00-11eb-882b-b6e92a50e164.png)

**Comment by dguittet** [comment]
Thanks for bringing this up. Could you send the weather file you are using?

**Comment by mr1001v** [comment]
Dear Darice,

 

I tested several weather files and system configurations with the same effect. 

 

I send you two weather files based on the same data:

-original one downloaded from JRC as EPW file. The 1h resolution works w/o any issue

-1min weather file interpolated by SAM macro: This file shows the problem with “Irradiance DNI calculated”. The Irradiance DNI from weather file looks good. I think this triggers a peak the “Inverter clipping loss DC MPPT voltage limits”. I’m wondering that this clipping loss occurs at sunset, while the calculated DNI irradiance peak is at sunrise.

The first time I discovered this issue at a satellite 1min weather file, but until now, all 1min weather files (1min from satellite or 1min interpolated from 1h data) generating this effect.

 

 

Can you send me your direct e-mail? Because I have a 18 MB zip file and like to send via wetransfer to you  (1h and interpolated 1min from this file and the corresponding SAM project file). Or should I send it to notifications@github.com <mailto:notifications@github.com>  ?

 

Best regards

Andre

 

 

Von: Darice L Guittet <notifications@github.com> 
Gesendet: Dienstag, 3. November 2020 19:05
An: NREL/SAM <SAM@noreply.github.com>
Cc: mr1001v <richter08@web.de>; Author <author@noreply.github.com>
Betreff: Re: [NREL/SAM] DNI spikes (#414)

 

Thanks for bringing this up. Could you send the weather file you are using?

**Comment by dguittet** [comment]
Thanks Andre. Could you send it to samsupport@nrel.gov?

**Comment by mr1001v** [comment]
File just send to you

 

 

Von: Darice L Guittet <notifications@github.com> 
Gesendet: Mittwoch, 4. November 2020 18:37
An: NREL/SAM <SAM@noreply.github.com>
Cc: mr1001v <richter08@web.de>; Author <author@noreply.github.com>
Betreff: Re: [NREL/SAM] DNI spikes (#414)

 

Thanks Andre. Could you send it to samsupport@nrel.gov <mailto:samsupport@nrel.gov> ?

**Comment by cpaulgilman** [comment]
[Uploading SAM_DNI_spikes.zip…]()
