### ISSUE TITLE
Error messages during simulation

### ISSUE THREAD

**Issue by mr1001v** [NREL/SAM#416]
Some weather files generate DNI spikes or other small trouble during simulation. If the weather files have many timesteps or parametric simulation with many sub-simulations are activated, displaying error messages delay the simulation and need user response ("click button ok"). 
Maybe adding a check-box in HMI to "supress error messages" with confirmation will improve simulation speed.

**Comment by cpaulgilman** [comment]
Related issue: https://github.com/NREL/SAM/issues/610
