### ISSUE TITLE
LK script does not set om_production

### ISSUE THREAD

**Issue by bje-** [NREL/SAM#42]
An LK script that sets an Excel cell to the value of `om_production` ("Variable cost by generation") has no effect. It works for other variables such as `om_fixedmodulecost`, `om_fuel_cost`, etc.

**Comment by bje-** [comment]
Here is a reduced test case:

    active_case('test');
    set('bos_equip_fixed', 10); // this gets updated
    set('om_production', 55); // this does not get updated
    simulate("", 1);

**Comment by janinefreeman** [comment]
Ben, I don't believe this is a bug. The variable "om_production" is type array, and therefore passing a scalar from the scripting language will not work. If you modify script to set('om_production', [55]); it should correctly update the variable. This is true for all variables that have the blue/gray "input/schedule" button next to the value in the user interface. The single value option is not a scalar, but an array of length 1.

Please try it and let me know. Thanks!

**Comment by bje-** [comment]
Ah, thanks!
