### ISSUE TITLE
Net surplus compensation may be taxable

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#441]
A possible change noted by Paul for when compensation for distributed generation drives the bill negative: The negative bill is technically treated as savings in the cash flow, not income. Income would be subject to income tax, but savings are not. For the residential and commercial financial models, the only taxable income is from cash incentives that are marked as taxable.

Collect any negative bills as taxable income in the cashloan financial module.

**Comment by brtietz** [comment]
@cpaulgilman I'm looking at this as a possible issue for patch 1, and I think I'll need to add a variable to cashloan in order to compute the tax. Cases where there is a net payment to the utility over the year, but a payment from the utility in one month wouldn't show up in annual_energy_value. 

I see two options: (1) add utility_bill_w_sys_ym as an input to cashloan and have cashloan compute based on any negative numbers. (2) Have utilityrate5 collect the total payments from the utility over each year, and pass that as a new variable to cashloan.

Preferences? Other ideas?

**Comment by cpaulgilman** [comment]
@brtietz Do we have documentation of the tax treatment of cash payments received by a residential or commercial system owner by the utility?

It looks like `elec_cost_with_system` and `elec_cost_without_system` are already inputs to the cashloan module. Is `utility_bill_w_sys_ym` a different variable? I guess the former are Year 1 arrays, and the latter is a matrix over the entire analysis period? Seems confusing to have both `utility_bill_w_sys_ym` and `elec_cost_with_system` as inputs.

I'm not sure I can think of any offhand, but are there other items that might be considered as taxable income to a residential or commercial system owner? Maybe salvage value?

@sjanzou may have some thoughts.

**Comment by brtietz** [comment]
Annoyingly, the clearest answers on this are TurboTax forum posts, which suggest it's "other income" reported on a 1099:

https://ttlc.intuit.com/community/taxes/discussion/yes-you-are-required-to-report-all-income-unless-specifi/01/663742#M267867

Some more reputable sources that point in the same direction less clearly:

https://www.energy.gov/sites/prod/files/2020/01/f70/Guide%20to%20Federal%20Tax%20Credit%20for%20Residential%20Solar%20PV.pdf

https://www.puc.nh.gov/regulatory/Docketbk/2016/16-576/MOTIONS-OBJECTIONS/16-576_2017-03-24_LEBANON_ATT_RESPONSE_CFL_MOTION_FOCUS_OCA_MOTION_IN_LIMINE.PDF

https://www.greentechmedia.com/articles/read/Solar-Policy-Battle-IRS-Now-Part-of-Fierce-Debate-on-How-to-Value-Solar-Po

Yes `utility_bill_w_sys_ym` is a different variable, `elec_cost_with_system` is annual, so we may not be able to determine the payment amounts.

I also realized this morning that any input/output changes are better left for a major version, so I'll tag this for the fall 2021 release.

**Comment by cpaulgilman** [comment]
I agree this is probably best left to a major version. I'm not sure if the debate described in the 2014 GTM article has been resolved, but if this is a policy issue currently under debate, it might make most sense in SAM to make the utility cash payments optionally taxable so policy analysts can explore the impact of different tax rules. Also, this is probably handled differently in different countries, so we should use an approach that works around the world.

**Comment by brtietz** [comment]
Response from Owen on this:

> I did some asking around, and there is definitely some serious ambiguity about this question. This is a pretty rare occurrence, usually a small dollar amount, and certainly not income that utilities are reporting to the IRS (i.e., issuing a 1099, etc.) even if the income is in fact taxable. I think having a checkbox for this would be useful, but it should probably be default off, and I wouldn’t necessarily place this high on the list compared to other more pressing tariff-related upgrades! 
> 
> My father lives outside of NYC, is served by ConEd for electric/gas, and has solar. His excess NEM credits are actually used to pay for his natural gas bill!

Taking this off the list for the release since other utility rate upgrades are higher priority.
