### ISSUE TITLE
Can't parse "CEC Inverters.csv" library - what does "C2=-1.#IND" mean ?

### ISSUE THREAD

**Issue by mikofski** [NREL/SAM#45]
In the latest `CEC Inverters.csv` library, the very first entry, on L4, for "AAA Perfect Tech A-1 Perfect Inverter 500V [CEC 2016]" has the value in the `C2` column set to `-1.#IND` which doesn't parse to a float or any numeric. What is it supposed to mean? Is this special to SAM?

https://github.com/NREL/SAM/blob/e3ec5ff752d27826099220775ade8e4c5218187e/deploy/libraries/CEC%20Inverters.csv#L4

**Comment by nickdiorio** [comment]
@sjanzou , do you know what this is from?  Did the CEC Inverters.csv come like that, or is that a result of our own parsing?

**Comment by mikofski** [comment]
OK. that makes sense. I guess I should have figured that out for myself. Should we close this issue, or is there anything I can do? I can submit a PR with those inverters removed from the csv file, that's easy enough.

**Comment by cpaulgilman** [comment]
We will remove those and some other inverters when we next update the library. That update will also add a lot of new inverters.
