### ISSUE TITLE
SAM Release Candidate on Linux always goes to /index instead of the proper help page

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#456]
When pressing the help button on Linux, the url sent to the default browser always goes to /index.html, rather than the help page associated with the page where the button is pressed. Paul said the correct behavior is closer to what happens on Windows where it goes to the specific page, just using the browser.

This occurs both on the open source version, and the 2020.11.23 release candidate.

**Comment by sjanzou** [comment]
Same issue on 2018.11.11, 2020.2.29 and 2020.11.29 using Chrome or FireFox as default browser - opens to index:
![image](https://user-images.githubusercontent.com/6498311/100201515-639f1a00-2ebd-11eb-9398-05f5821cf18e.png)

**Comment by sjanzou** [comment]
One potential issue is noted here: https://github.com/clearlinux/distribution/issues/1843

In the terminal window from starting 2020.11.29 with Chrome as default browser:
[9020:9020:1125/010455.479777:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id
[9020:9020:1125/010508.954255:ERROR:browser_switcher_service.cc(238)] XXX Init()
[9438:9438:1125/010534.435651:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id
Opening in existing browser session.

**Comment by sjanzou** [comment]
Also, Linux is set to open index.html and has been for some time:
![image](https://user-images.githubusercontent.com/6498311/100204666-5e43ce80-2ec1-11eb-9781-7ce3dc451adc.png)

**Comment by sjanzou** [comment]
Note https://docs.wxwidgets.org/3.0/classwx_web_view.html
wxWEBVIEW_WEBKIT (GTK)
Under GTK the WebKit backend uses WebKitGTK+. The current minimum version required is 1.3.1 which ships by default with Ubuntu Natty and Debian Wheezy and has the package name libwebkitgtk-dev. Custom schemes and virtual files systems are supported under this backend, however embedded resources such as images and stylesheets are currently loaded using the data:// scheme.
