### ISSUE TITLE
LK small numbers turned to zeros

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#458]
In LK callbacks, anything after 6 decimal places is not being included when writing the variable from ssc_exec().

https://github.com/NREL/SAM/pull/454

**Comment by mjprilliman** [comment]
I believe this issue also affects very large numbers as well. We seem to be losing for 9 digits (hundred million) in front of the decimal point. And the printed number is not matching up with what is being used for calculations

**Comment by dguittet** [comment]
Could you please post a sample LK script?

**Comment by cpaulgilman** [comment]
```
x = 1.0834e-19;
outln(x);

x = 1.0834e-7;
outln(x);

x = 1.0834e-6;
outln(x);
```

**Comment by mjprilliman** [comment]
![image](https://user-images.githubusercontent.com/54449384/100682977-98372980-3334-11eb-9115-9b5a316bd786.png)
![image](https://user-images.githubusercontent.com/54449384/100683014-aab16300-3334-11eb-8331-fc712130043b.png)
![image](https://user-images.githubusercontent.com/54449384/100683056-c3ba1400-3334-11eb-86c5-4be06aa12a71.png)






You can mess around with the numbers on that. Comment out the lines on two and unselect the checkmark on 'Override cost structure' to only focus on 1. I can try to come up with better use cases tomorrow. 
[LK_number_testing.zip](https://github.com/NREL/SAM/files/5619583/LK_number_testing.zip)
The number that is printed seems to vary based on what the last two digits are with no clear pattern. Not entirely sure what is going on it may be a different issue. I tried the different number formats on the UI object and it didn't work outside of 
[LK_number_testing.zip](https://github.com/NREL/SAM/files/5619580/LK_number_testing.zip)

**Comment by sjanzou** [comment]
Issue with the lkscript "set" function fixed in SAM_458 branch of SAM - pull request #763 

Issue with small numbers in "outln" lkscript is fixed in SAM_458 branch of lk - pull request https://github.com/NREL/lk/pull/25

Issue with values from numeric control passed through ssc_exec in SAM_458 branch of wex - pull request https://github.com/NREL/wex/pull/125

**Comment by sjanzou** [comment]
This is a time intensive task that will be reolved manually by changing all calculated variables to Real with fixed decimals per discussion at https://github.com/NREL/SAM/pull/763#issuecomment-969394134
