### ISSUE TITLE
Mac Graphs Text Blurriness

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#462]
In the latest candidate built from develop, the text on graphs look blurrier than before, for Mac. This is for all graphs in the UI, including Module, Inverter, and all Results graphs.

New:
![image](https://user-images.githubusercontent.com/29387736/100257349-10e85100-2f03-11eb-842b-b9001106b26f.png)

Old:
![image](https://user-images.githubusercontent.com/29387736/100257749-82280400-2f03-11eb-9de8-647d242b94ed.png)

**Comment by sjanzou** [comment]
Fixed with wex pull request https://github.com/NREL/wex/pull/112
