### ISSUE TITLE
Generic-Battery Costs page does not update power units

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#469]
The number for costs on the generic-battery costs page are pulled directly from the battery cell and system page, rather than being converted for DC. This appears to only affect the generic battery, not pv-battery:

From 2020.11.29:

![image](https://user-images.githubusercontent.com/5530592/100655491-98213480-3308-11eb-860d-e510a3272a38.png)

Costs:

![image](https://user-images.githubusercontent.com/5530592/100655524-a53e2380-3308-11eb-9b7e-5a9ee27b01a0.png)

@cpaulgilman also suggested capitalizing "dc" on the costs page.

**Comment by cpaulgilman** [comment]
My capitalization suggestion is to use uppercase when the "AC" or "DC" abbreviation is spelled as a separate word, like kW DC, kWh AC. Use lowercase if the abbreviation is spelled as one word like kWdc, kWhac.

**Comment by brtietz** [comment]
Closed in PR SAM 469, merged into patch and develop
