### ISSUE TITLE
Value of RE macro uses en_batt

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#487]
## Background

In SAM versions before 2020.2.29, when the battery model was part of the Detailed PV and Generic System configurations `en_batt` was a user input to enable or disable the battery. In 2020.2.29 and later, `en_batt` is set in a UI equation for the battery configurations.

## Issue

Value of RE macro sets `en_batt=0` to disable the battery to calculate metrics for the PV-only scenario, but user cannot access that input without LK. Need to test that this is working properly, and that the `en_batt` is set back to 1. Consider modeling the PV-only scenario by setting the battery capacity kWh and kW inputs to zero so that the macro does it in a way that can be replicated manually in the user interface without LK.

## Test

[value-of-re-macro-tests.zip](https://github.com/NREL/SAM/files/5718487/value-of-re-macro-tests.zip)

1. Open value-of-re-macro-tests.sam.
2. Run Value of RE macro on "battery 10 kWh 2.5 kW" case.
3. Open and run en_batt-tests.lk script.

NPV for RE-only scenario from macro should match 3 NPV values from LK script.

**Comment by cpaulgilman** [comment]
When `en_batt=0` and battery capacity in kWh/kW is not zero, total installed cost includes battery cost, so Value of RE macro incorrectly includes battery cost in PV-only scenario. To verify, run script on SAM file in attached zip archive and note that NPV for "en_batt = 0" case is different than NPV for other cases.

[en_batt-tests.zip](https://github.com/NREL/SAM/files/5717365/en_batt-tests.zip)

**Comment by cpaulgilman** [comment]
@brtietz Are there any situations in SSC where setting `en_batt` to zero is expected to set battery costs to zero?

**Comment by brtietz** [comment]
I don't think SSC is directly aware of the battery installation costs, only the replacement costs. The installation costs get wrapped up in total_installed_cost. If possible, I think it would be best to fix this in the UI calculations.

**Comment by cpaulgilman** [comment]
The PV Battery Capital Costs UI form sets the battery kWh capacity to zero when en_batt = 0, but not the kW capacity, I will fix that as part of this issue.
