### ISSUE TITLE
Solar Resource File Converter Macro for SolarAnywhere V3.4 Files 

### ISSUE THREAD

**Issue by KWagnerCPR** [NREL/SAM#491]
**Describe the bug**
SolarAnywhere V3.4 file downloads have 9 columns in the first row. This is the case when the metadata in cell H1 spills over into cell I1. The SAM solar resource file converter macro is currently designed to only accept files with 8 columns in row 1 so attempting to convert a SolarAnywhere V3.4 file breaks the macro. 

**To Reproduce**
1. Obtain a SolarAnywhere V3.4 TMY3 format or SA format file. 
2. Open a new project in SAM. 
3. In the bottom left corner, select Macros. Select Solar Resource File Converter from the list, then select SolarAnywhere from the 
Weather file format drop down in the top right corner.
4. Select Run macro and choose your SolarAnywhere V3.4 file. 

**Expected behavior**
I would expect the converter to successfully convert the SolarAnywhere format file to a samcsv format file as it has in the past when converting SolarAnywhere V3.3 files. But instead you receive an error saying the file does not appear to be in SolarAnywhere format. 

**Screenshots**

![image](https://user-images.githubusercontent.com/76822471/103422223-33e6d000-4b55-11eb-91be-58daae83da33.png)

**Operating System and Version**
 - OS: Windows
 - Version: SAM 2020.11.29

**Additional context**

**Comment by cpaulgilman** [comment]
@KWagnerCPR, would you mind attaching an example of a file in the both the TMY3 and SA format generated by SolarAnywhere V3.4 that we can use as a basis for updating the macro?

**Comment by KWagnerCPR** [comment]
@cpaulgilman Sure thing! I'm going to email you examples of a time series, TGY, and TDY files in both TMY3 and SolarAnywhere output formats. We also provide probability of exceedance files in both formats. Do you need examples of those? The header information in cell H1 would be slightly different.

**Comment by cpaulgilman** [comment]
Sample files for testing:

[SolarAnywhere_SA_and_TMY3 format_examples.zip](https://github.com/NREL/SAM/files/6013729/SolarAnywhere_SA_and_TMY3.format_examples.zip)
