### ISSUE TITLE
PVWatts-battery ReOpt sets battery capacity inputs to zero before dispaying user prompt

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#495]
**Describe the bug**
Battery capacity and power inputs are set to zero even if user chooses not to override inputs:

![image](https://user-images.githubusercontent.com/27711933/104245380-ffa6c580-5418-11eb-8bd3-a2bf3591f8b9.png)

**To Reproduce**
1. Create a PVWatts-battery / Commercial case.
2. On System Design page, click *Get size and dispatch*.

**Expected behavior**
Battery capacity inputs should only be overridden when user clicks Yes in popup.

**Operating System and Version**
2020.11.29

**Additional context**
Need to also test this for Detailed PV-battery.

**Comment by dguittet** [comment]
The battery sizes are set to 0 before the ReOpt call in order to recalculate the system cost without battery. I could save the battery sizes which existed before and replace those if the user decides to not Override.
