### ISSUE TITLE
Power tower heliostat availability not used in simulations

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#50]
Heliostat availability is used in design calculations but not during performance simulations. Workaround solution is to use the Constant loss in the Edit Losses window to represent heliostat availability.

**Comment by dguittet** [comment]
@cpaulgilman will confirm with @mjwagner2 whether or it's still an issue.

**Comment by cpaulgilman** [comment]
Ok to remove as input in UI.

From Mike 3/16/2021:

> The availability is a holdover, and I think we should eliminate it. By default, the constant losses would then be set to 1%.

**Comment by cpaulgilman** [comment]
From Mark 3/17/2021:

> Sounds good but would be nice to see the constant loss term available for a sensitivity or stochastic analysis.

**Comment by cpaulgilman** [comment]
Heliostat Availability is a design parameter that is an input to SolarPilot, but not used in the SSC simulation, so this issue needs more consideration.

A proposed solution from Ty:

* Keep the single availability design-point UI value as is (and maybe update the labeling to emphasize design-point). I want to avoid passing calculated values or making SolarPILOT interpret the availability widget to get a design point value.

* Create a radio button for the “operational” availability that toggles between “use constant design-point” and “timeseries”. This removes the redundant constant value from the current widget, but requires new UI development (and maybe a “heliostat_availability_mode” input corresponding to the radio button).

Changing the milestone to the Fall 2021 release.

**Comment by tyneises** [comment]
Heliostat Availability is used in the SSC simulation if option is selected for layout optimization before the annual simulation.

**Comment by cpaulgilman** [comment]
@tyneises Is it OK to consider this fixed with https://github.com/NREL/SAM/pull/717?

**Comment by tyneises** [comment]
@cpaulgilman I think the UI is fixed. Your comment from March 16 notes that to be consistent with the design-point availability, we should change the time-series default value to 1% constant loss. Should we make that change after some of the current pull requests are merged (to make it easier to update test results)?
