### ISSUE TITLE
For the graphics related to DView, I would like default selections in all cases so that the results do not open up blank. 

### ISSUE THREAD

**Issue by n8blair** [NREL/SAM#513]
**Is your feature request related to a problem? Please describe.**
The problem is that for new users and demonstrations, it's not clear what these capabilities will do and the number of choices and options (particularly all the various energy outputs for the heat map) are extensive and overwhelming. 

**Describe the solution you'd like**
For every graphic and every combination, select an appropriate "start" variable to display and have taht selected and updated when the user first goes there. For teh bulk of these, the default should be really clear (hourly AC energy out for example).

**Describe alternatives you've considered**
Planning how to select those for demonstration.

**Additional context**

**Comment by sjanzou** [comment]
@mjprilliman, is this issue fixed in patch and develop? Can you close this issue now? Thanks!
