### ISSUE TITLE
Enabling battery in Fuel Cell causes simulation progress to count to 133%

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#522]
**Describe the bug**
See title. Progress bar counts to 133% before resetting to 100%. 

Also, for new Hybrid configurations, progress bar sits at 0% while first model runs, so looks like nothing is happening at the beginning of the simulation.

**To Reproduce**
1. Open Fuel Cell Case
2. Enable battery on the Battery Storage page
3. Simulate

**Expected behavior**
Simulation bar should go to 100%. 

![image](https://user-images.githubusercontent.com/54449384/106626507-04046100-6535-11eb-902d-9e7d317a6ace.png)

**Comment by brtietz** [comment]
Duplicate with https://github.com/NREL/SAM/issues/435 - I'll close that one since this one is better documented.

**Comment by mjprilliman** [comment]
> Duplicate with #435 - I'll close that one since this one is better documented.

I should've checked the issues list first. Thanks for organizing.

**Comment by cpaulgilman** [comment]
This one's above my paygrade. Maybe @sjanzou can fix? Also, I think we can put off for later, unless it's a quick fix for 2020.11.29 Patch 1.

**Comment by mjprilliman** [comment]
> This one's above my paygrade. Maybe @sjanzou can fix? Also, I think we can put off for later, unless it's a quick fix for 2020.11.29 Patch 1.

Wasn't sure who the right person was. I'll take it off of Patch 1 I just thought I had noticed something new but it was already on our radar.

**Comment by mjprilliman** [comment]
@sjanzou let me know if this is easily fixable. If not I can take it off the milestone.

**Comment by sjanzou** [comment]
> @sjanzou let me know if this is easily fixable. If not I can take it off the milestone.

@mjprilliman, we can leave for the fall release, this issue has been "addressed" several times but not fixed because the progress bar is based on a single compute module and the loop goes through both the battery and fuel cell technology modules and ends up over 100%.

**Comment by cpaulgilman** [comment]
@sjanzou Assigning this to the Fall 2023 milestone to fix for Hybrid configurations -- no need for the new issue we discussed today.
