### ISSUE TITLE
PDF report template for PV-battery / Single Owner broken

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#524]
**Describe the bug**
Page 2 of PDF report for PV-battery with PPA financial models has LK error messages:

```
[173]: operand to # ('sizeof') must be a array, string, or table type
[173]: eval error in statement list
[173]: error inside function call
[508]: eval error in statement list
[3]: eval error in statement list
```

**To Reproduce**
1. Create default PV-battery / Single Owner case.
2. Click **Generate report** on Case menu.

**Comment by mjprilliman** [comment]
@cpaulgilman I can take a look at this if you'd like.

**Comment by cpaulgilman** [comment]
Thanks! Need to test with both PPA price and retail rate options  for battery charge power, and for the other PPA financial models.

**Comment by mjprilliman** [comment]
I needed to take out the variables energy delivered to load for the PPA models as there is no load data. PR is up for review.
