### ISSUE TITLE
NSRDB download intermittent error

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#531]
**Describe the bug**

When NSRDB API service is down, attempt to download a weather file from Solar Resource page results in:

```
Could not evaluate callback function:btn_download->on_change
[507]: error: _s
[507]: failed to evaluate function call argument _d to '_s()'
[507]: failed to evaluate function call argument _d to '_s()'
[507]: eval error in statement list
[497]: eval error in statement list
[468]: eval error in statement list
[468]: error inside function call
[644]: eval error in statement list
[609]: eval error in statement list
[609]: error inside function call
[115]: eval error in statement list
```

**To Reproduce**

1. Modify UI callback in Solar Resource Data UI form to force error from API:

![image](https://user-images.githubusercontent.com/27711933/107103470-97a68d80-67d2-11eb-9c27-ad74a569fd30.png)

2. Try to download a weather file.

**Expected behavior**

Callback should gracefully handle API errors with a useful message.

**Comment by cpaulgilman** [comment]
Also check with "advanced download."

**Comment by janinefreeman** [comment]
I happened to be working with advanced download today, and I'm getting the error: "The required 'email' parameter must be a valid email address". Probably a different error, but I'm assuming the fix is in the same area of the code.

**Comment by cpaulgilman** [comment]
Is this happening consistently for you in the release version of SAM 2020.11.29?

**Comment by janinefreeman** [comment]
Yes, seems to be. Just tried a fresh start with a different location, same error for every single file I'm attempting to download through the "advanced" window.

**Comment by cpaulgilman** [comment]
I can't seem to replicate that. What location are you trying?

**Comment by janinefreeman** [comment]
I tried a couple locations in CO- try "Arvada, CO"

**Comment by cpaulgilman** [comment]
Is this the error you are seeing? I got it by starting SAM and skipping the registration process. I assume you registered with email and key?

![image](https://user-images.githubusercontent.com/27711933/107825061-4e58bf80-6d37-11eb-93fd-1afb40c61361.png)

**Comment by janinefreeman** [comment]
Hmmm interesting- no, I believe I have the developer override in my registry. That's never stopped a past version from working, but seems it's on my end! I should have thought of that. Thank you!

**Comment by cpaulgilman** [comment]
Part of the issue is that the NSRDB API requires the email parameter, and we recently changed SAM to send the registration email address instead of the hard-coded SAM support email address. I'm going through the code to make sure SAM is being consistent about what email address it uses for this purpose.

Can you try registering SAM to see if the downloads work when you register with an email address?

**Comment by janinefreeman** [comment]
Yes, it fixes the issue for me! Thanks!

**Comment by cpaulgilman** [comment]
See also https://sam.nrel.gov/forum/forum-general/4288-issues-downloading-weather-files.html#12344
