### ISSUE TITLE
Negative LPPA and LCOE for storage projects

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#532]
SAM 2020.11.29 uses net energy to grid to calculate the LCOE and LPPA. For stand alone batteries which charge from the grid, this can lead to negative LCOE and LPPA values. Determine what kWh values should be used for these calculations in cases where the net energy is negative.

**Comment by cpaulgilman** [comment]
To replicate:

1. In SAM 2020.2.29, open [storage-negative-lcoe-issue-SAM-2020-2-29.zip](https://github.com/NREL/SAM/files/5967448/storage-negative-lcoe-issue-SAM-2020-2-29.zip).

2. Run simulation.

3. Open the same file in SAM 2020.11.29.

4. Run simulation.

SAM 2020.2.29 reports negative NPV and positive LCOE. SAM 2020.11.29 reports negative NPV and negative LCOE.

**Comment by brtietz** [comment]
Determination in meeting on 2/26 is that the gross kWh delivered to the grid (sum of positive gen values) can be used for the denominator within LCOE and LPPA. This matches the convention in LCOSS - where energy generated by PV and sent directly to the grid, energy generated by PV and sent through the battery, and energy purchased from the grid and returned through the battery are all summed into the denominator.

This may gloss over some subtle issues like where inverter power comes from during the day, but we would have to increase the detail in our power flow calculations in order to handle this, which means its out of scope for this bug.

**Comment by brtietz** [comment]
Related issues: https://github.com/NREL/ssc/issues/546 https://github.com/NREL/ssc/issues/539
