### ISSUE TITLE
Wind uncertainty language should indicate you can likely ignore the inputs.

### ISSUE THREAD

**Issue by n8blair** [NREL/SAM#533]
I must have been daydreaming when we talked about Wind Uncertainties. I was tracking down something else and ran across the Uncertainties page on the Wind model. Coming in cold, I don’t think that the text at the top of the page really explained what the hell all of this is. The help was more helpful with the statement below. I might propose adding something else to the top of the page (just before the sentence “All uncertainty components and subcomponents…” such as “This page contains the inputs that calculate probability distributions displayed on the Uncertainties Tab of the results page.  If you are not interested in viewing uncertainties, you may ignore these inputs.”  Otherwise, it’s a pretty scary page.

The Uncertainties inputs allow you to specify uncertainties for different input parameters to calculate the probability distributions displayed on the Uncertainties tab of the Results page.
The uncertainty model is draws from the IEC 61400-15 uncertainty framework as described in Damiani, R. (2018). Uncertainty and Risk Assessment in the Design Process for Wind. National Renewable Energy Laboratory, NREL/TP-5000-67499 (PDF 8.9 MB).

**Comment by janinefreeman** [comment]
Additional thought from @cpaulgilman :
We also could hide the inputs unless you expand a hidden panel, like the battery page for the fuel cell model. That provides a space for a text description to warn you what you're getting into. I think that would make it possible to only show the P90 metric if you enable the inputs:
