### ISSUE TITLE
MSLF hard crashing in develop

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#538]
**Describe the bug**
Running MSLF with any financial model hard crashes at 0% simulation status. But the model runs all the way through in the debugger. 

**To Reproduce**
1. Open SAM with a MSLF model
2. Click Simulate

**Expected behavior**

**Additional Context**
As far as I can tell everything still works in patch

**Comment by tyneises** [comment]
@mjprilliman The default Linear Fresnel Molten Salt case solves for me in develop. Are you still getting the hard crash?

**Comment by mjprilliman** [comment]
> @mjprilliman The default Linear Fresnel Molten Salt case solves for me in develop. Are you still getting the hard crash?

Yes I am still getting the hard crash. Must be something on my end I guess...

**Comment by sjanzou** [comment]
I just pulled all of the develop branches and clean and build and run and just get notices - simulation runs
![image](https://user-images.githubusercontent.com/6498311/108125321-83318300-7065-11eb-8baf-a1f3fd1e1560.png)

Testing debug build and running in VS2019 debug mode:
![image](https://user-images.githubusercontent.com/6498311/108125981-7bbea980-7066-11eb-8b8d-98ff4b9a84fd.png)

**Comment by mjprilliman** [comment]
I'm not sure what I originally did but I'm not getting this issue anymore. Sorry for the false alarm!
