### ISSUE TITLE
Retire PV India Wizard

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#549]
**Background**

This feature was introduced in SAM 2017.9.5 as part of the Weather Data and Project Finance Models work described here: https://sam.nrel.gov/international.html. In addition to the wizard, this work added a set of weather files for selected locations in India to SAM's default weather file collection, and the following features to SAM's PPA financial models:

* Fixed principal declining interest debt option

* Debt moratorium option

* A "return on equity" calculator, which simply reports a percentage of the equity portion of the project cost.

The weather files are superseded by data now available for download from the NSRDB directly from the Location and Resource page. The India weather files add 42 MB to the SAM installation package.

We are considering adding a new return on equity metric that is calculated from project revenues and want to avoid having two different metrics with the same name.

There is no longer funding to support maintenance of the PV India wizard.

**Tasks**

* Remove the runtime/quickstart/pv_india_weather folder and its contents.

* Remove PV India.lk, PV_for_India.sam, pvforindiawizard.samreport from the runtime/quickstart folder.

* Remove the Return on Equity UI form and the calculation and output from the PPA financial models.

* Remove Return on Equity description from Help.

* Make a note on the SAM website page for SAM 2020.11.29 that it is the last version to include the PV India Wizard so people can find it if they want to use the wizard.

**Comment by sjanzou** [comment]
Completed first three tasks in SAM_549 branches of ssc and SAM - pull request coming soon.

**Comment by sjanzou** [comment]
SAM Pull request #732 and ssc pull request 642
