### ISSUE TITLE
Issue errors when PPA model results are out of range

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#551]
**Background**

PPA financial model metrics should be considered as a set: PPA price, IRR, NPV, Size of Debt, and LCOE. For example, in some cases the NPV may be positive indicating an economically feasible project, but some other metric like size of debt, IRR, or PPA price may be unreasonable, indicating the project is not feasible.

SAM does not provide an user feedback when a financial metric is unreasonable, so it is easy to be unaware that there might be a problem with the results.

**Task**

Add error/warning messages to SSC outputs when PPA metrics are out of predefined ranges, such as NPV < 0, Debt Percent > 100. Get feedback from Finance folks on what those ranges should be -- is there a way to identify an IRR value that might be too high?

**Comment by janinefreeman** [comment]
This would be a nice fit with some of the financial model upgrades that are on @sjanzou 's project list this year.

**Comment by sjanzou** [comment]
Using Fuel Cell / single Owner defaults as an example to start with
[SAM_551.zip](https://github.com/NREL/SAM/files/9495417/SAM_551.zip)

![image](https://user-images.githubusercontent.com/6498311/188601504-bd0cb015-df0d-4164-8b60-db6f6410fa2f.png)

**Comment by sjanzou** [comment]
SSC_NOTICE appears too subtle:
![image](https://user-images.githubusercontent.com/6498311/188614130-d1ef7c5e-d386-421b-976a-590ad6b61f2f.png)

**Comment by sjanzou** [comment]
SSC_WARNING seems more noticeable
![image](https://user-images.githubusercontent.com/6498311/188614752-7fb09dfa-affc-4d09-9f02-d662531163e0.png)

**Comment by sjanzou** [comment]
@cpaulgilman, what do you think about notices and warnings?

**Comment by cpaulgilman** [comment]
@sjanzou I think warnings would be best, but might annoy people who are ignoring the financial model results. 

Is this in a remote branch where I can edit the text?

**Comment by sjanzou** [comment]
> @sjanzou I think warnings would be best, but might annoy people who are ignoring the financial model results.
> 
> Is this in a remote branch where I can edit the text?

551-issue-errors-when-ppa-model-results-are-out-of-range branches of ssc and SAM (probably the last time I let Github name the branches for an issue!)
