### ISSUE TITLE
Update defaults for PPA financial models to be consistent with ATB

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#553]
SAM's current annual debt interest rate default is 7% compared to 4% in ATB.

SAM uses DSCR sizing option by default, so the resulting debt percent is likely to be different than the ATB debt percent. We could change the default to debt sizing option to Debt percent. (This would also minimize confusion for users who don't understand debt sizing based on cash available for debt service, but be less realistic for project studies.)

Default Debt closing cost is $450,000 (about 0.9% of total installed cost for PV / Single Owner). This is a fixed cost that does not scale with system size. We could leave it as is, or set it to zero and account it a $/Wdc overhead cost on the System Costs page. For project-level analysis, this may be appropriate because that cost is not likely to scale with project size if it is to account for costs like legal fees that do not depend on the system size. However, for high-level analysis where it is more important to have all costs scale with system size, this fixed cost could distort results if someone forgets to set it to zero.

In general, need to consider whether defaults should be values appropriate for high-level analysis like ATB, or project-level analysis. SAM Is widely used for both, so not clear what defaults should be based on.

**Comment by brtietz** [comment]
Two notes on this issue: First: Janine filed a duplicate issue here: https://github.com/NREL/SAM/issues/548 Should we close that one since this one is more descriptive?

Second: the ATB debt fractions are based on DSCR calculations:

![image](https://user-images.githubusercontent.com/5530592/109992087-28846200-7cc8-11eb-9f47-b032231e7da5.png)

from https://atb.nrel.gov/electricity/2020/finance-impact.php

**Comment by brtietz** [comment]
Proposed changes:

**PPA, merchant plant, host developer**
- Annual interest rate for term debt: change from 7% to 4%, source: ATB
- Interest during construction: change from 4% to 3.5%, source: ATB
- Interest on reserves: change from 1.75% to 1.25% - mirroring the reduction in interest during construction. I don't have a source here and could imagine it's lower

**Cash loan**
- Loan rate: change from 5% to 4%, source ATB

**LCOE Calculator**
- Nominal interest rate: change from 8% to 4%, source: ATB
- Effective tax rate: reduce from 40% to match other techs

The ATB uses a combined tax rate of 25.7% - but https://en.wikipedia.org/wiki/State_income_tax#Corporate_income_tax_2 implies that 7% is still pretty close to the median, so I'm inclined to leave that alone.

Are there other financial metrics we want to change in this round?

**Comment by cpaulgilman** [comment]
I recommend using the same defaults for the new Community Solar model as PV PPA/merchant/third party host-dev.

Not noted here that we've discussed elsewhere is major equipment replacement reserve:

* For PV configurations (Flat Plate PV, PVWatts, Fuel Cell, PV Battery), choose value to be consistent with O&M cost that represents inverter replacement. 
* Replacement reserve default is inconsistent across other technologies. For example Wind has default replacement reserve 1 of  $0.25/W (based on PV inverter replacement cost?) with an O&M cost of $42/kW. CSP techs have replacement reserve set to zero. Perhaps set it to zero for all except PV configs.

**Comment by brtietz** [comment]
Good catch on the replacement reserves in other techs. According to https://www.nrel.gov/docs/fy19osti/73822.pdf, the inverter replacement cost should be estimated at 2x the factory cost, so for utility scale systems I'm leaning towards 0.10/Wdc.

I also [have an Excel with raw numbers](https://github.com/NREL/SAM-documentation/blob/master/Defaults%20References%20and%20Tools/Fall%202021/Copy%20of%20OandM%20TabularForm_Graphic.xlsx) of the cost breakdown in Figure 10 of https://www.nrel.gov/docs/fy21osti/77324.pdf, so we can use that to remove inverter replacement. Do you prefer insurance in fixed O&M or on the financial parameters page? Insurance is lumped in with "Insurance, asset management, and security," so it might be hard to accurately pull out just that line item.

We also appear to have been double counting land costs in 2020.11.29.

**Comment by brtietz** [comment]
One more thing, the ATB assumes that the inverter replacement occurs in yr 15: https://public.tableau.com/shared/GMFMJPTH8?:toolbar=n&:display_count=n&:origin=viz_share_link&:embed=y

Should we update the replacement frequency on that reserve account to match?

**Comment by cpaulgilman** [comment]
> Do you prefer insurance in fixed O&M or on the financial parameters page? Insurance is lumped in with "Insurance, asset management, and security," so it might be hard to accurately pull out just that line item.

Would be idea to pull it out, but it would also be fine to include it in the O&M cost and set the insurance cost to zero on the Financial Parameters page.

> One more thing, the ATB assumes that the inverter replacement occurs in yr 15: https://public.tableau.com/shared/GMFMJPTH8?:toolbar=n&:display_count=n&:origin=viz_share_link&:embed=y
> 
> Should we update the replacement frequency on that reserve account to match?

Yes, I think so.

**Comment by brtietz** [comment]
I'm still running test_script_ow.lk so we can have a robust discussion of this on the pull request, but the dramatic reduction in interest rates isn't playing well with the other defaults. Here's the current state of detailed PV single owner:

![image](https://user-images.githubusercontent.com/5530592/142515653-0597b265-37a2-486c-9e2a-b29be9cddd0c.png)

This is because the high PPA price ($0.1/kWh) is enabling a ton of revenue, which means the DSCR allows for taking out more debt than the total installed cost.

I could think of a few things to fix this, and we need to decide how many technologies to apply them to:

1. Reduce the default PPA price
2. Change to a debt fraction
3. Change to IRR target mode by default

Preferences on one or a combination of those?

**Comment by cpaulgilman** [comment]
From this cool LBL graph, I'd say $0.10/kWh is probably a bit high: https://emp.lbl.gov/pv-ppa-prices.

Note their use of "levelized PPA price"!

**Comment by brtietz** [comment]
$0.045/kWh produces the following results:

![image](https://user-images.githubusercontent.com/5530592/142517526-26e43ed0-973b-4209-8ff5-fd732c29d630.png)

So that's a little higher than the PPAs reported by LBNL, but a lot closer than we were before!

**Comment by brtietz** [comment]
$0.045/kWh works well for single owner, but produces negative NPVs for the other three FOM financial models. The LCOE is higher for those models (especially equity flip and sale leasback) so that makes sense.

Other things to adjust could be the TOD factors - this is all with a flat TOD.

**Comment by cpaulgilman** [comment]
> $0.045/kWh works well for single owner, but produces negative NPVs for the other three FOM financial models. The LCOE is higher for those models (especially equity flip and sale leasback) so that makes sense.
> 
> Other things to adjust could be the TOD factors - this is all with a flat TOD.

I think default TOD should be flat because it is easy to miss for new users, and they are only available in some markets.

**Comment by cpaulgilman** [comment]
> 

Following up on default TOD factors, TOD multipliers make sense for FOM Battery defaults, but perhaps not for the non-storage technologies.
