### ISSUE TITLE
SAM crashes with TOU rates

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#563]
**Describe the bug**
PVWatts-Residential case with tiered TOU energy and demand rates crashes.

**To Reproduce**

1. Open the tou-outputs.sam file [tou-outputs.zip](https://github.com/NREL/SAM/files/6143262/tou-outputs.zip).

2. Run a simulation.

**Operating System and Version**
 - OS: Windows
 - Version: SAM 2020.11.29 r1

**Comment by brtietz** [comment]
It looks like the issue here is that the TOU periods have different tiers, all periods need to have the same tier. Fix for the crash will be to catch the exception or index error and provide an error message to the user.

**Comment by drevastation** [comment]
Still not fixed, in 2020.11.29r2 and 2021.12.2. Using a Time-of-Day rate from Public Service company of Oklahoma
GUID: 5dae1b2f5457a3cc62d2ae4f
This crashes both versions.

**Comment by brtietz** [comment]
@drevastation thanks for reporting! The root cause of your issue is different from what was reported and fixed here, so I've opened a new issue: https://github.com/NREL/SAM/issues/857 and put it on the list for patch 1. Thanks for helping us expand the number of rates that SAM supports!
