### ISSUE TITLE
File PySSC.py generated from SAM have the variable "double" not declared.

### ISSUE THREAD

**Issue by leo-smi** [NREL/SAM#588]
There's three functions that uses the variable "double":

![image](https://user-images.githubusercontent.com/20663547/113347913-43201a00-930c-11eb-8515-745c426ca50d.png)

```
	def data_set_array_from_csv(self, p_data, name, fn) :
		f = open(fn, 'rb'); 
		data = []; 
		for line in f : 
			data.extend([n for n in map(double, line.split(b','))])
		f.close(); 
		return self.data_set_array(p_data, name, data); 

	def data_set_matrix_from_csv(self, p_data, name, fn) :
		f = open(fn, 'rb'); 
		data = []; 
		for line in f : 
			lst = ([n for n in map(double, line.split(b','))])
			data.append(lst);
		f.close(); 
		return self.data_set_matrix(p_data, name, data); 

	def data_get_matrix(self,p_data,name):
		nrows = c_int()
		ncols = c_int()
		self.pdll.ssc_data_get_matrix.restype = POINTER(c_number)
		parr = self.pdll.ssc_data_get_matrix( c_void_p(p_data), c_char_p(name), byref(nrows), byref(ncols) )
		idx = 0
		mat = []
		for r in range(nrows.value):
			row = []
			for c in range(ncols.value):
				row.append( double(parr[idx]) )
				idx = idx + 1
			mat.append(row)
		return mat

```

**Comment by leo-smi** [comment]
After changing double to float in the functions mentioned, occurred anothers errors, it seems problem reading integer instead of a float number inside the pysam lib:
![image](https://user-images.githubusercontent.com/20663547/114955180-6d0c2d00-9e32-11eb-9bce-e82efb8e68fe.png)

**Comment by sjanzou** [comment]
Fixed with PR #590

**Comment by dguittet** [comment]
@leo-smi Can you check what value is being read in for `system_use_lifetime_output` ? Sending the files you're working with would be helpful also.

Assuming you've used the Python 3 code generator, it should say 

`ssc.data_set_number( data, b'system_use_lifetime_output', 0 )`

**Comment by sjanzou** [comment]
Merged into patch PR 590 and merged into develop PR 596

**Comment by leo-smi** [comment]
There it is the files, just run "SMI.py", I think the path will work automatically...

[sim_python.zip](https://github.com/NREL/SAM/files/6368911/sim_python.zip)

**Comment by dguittet** [comment]
@leo-smi Thanks for sending. I was able to identify the error. In PySSC.py, please change line 4 to `c_number = c_double`.
