### ISSUE TITLE
Add support for Mac M1 chip

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#599]
SAM does not run on new Mac computers with the ARM-based M1 chip.

Solution is to build installation image file to support both older Intel-based and new ARM-based Mac computers.

**Comment by cpaulgilman** [comment]
Mac users are reporting an intermittent crash on macOS (sometimes happens every 3 tries or so). To replicate:

1. Open SAM.
2. Start new project: Photovoltaic > Detailed PV Model > Distributed > Residential Owner
3. Click **Simulate**.
4. When the simulation finishes, click **Simulate** again. SAM crashes.

**Comment by pat-githubber** [comment]
I frequently receive this graphical bug on my MacBook with the M1 Chip (macOS Big Sir: Version 11.4). When I hover over the black areas, SAM restores the UI.

https://user-images.githubusercontent.com/87087327/124797213-50bfee00-df52-11eb-975a-1a06275092e8.mp4
