### ISSUE TITLE
modules for hydrogen electrolysis 

### ISSUE THREAD

**Issue by yassineennassiri** [NREL/SAM#60]
Hi ! I would like to add new modules to SSC library in ordre to build model for production of hydrogen using eletrolysis (The eletricity needed in electrolysis of water will be generated from PV/CSP system). I'm not sure how to get started, so wanted to touch base with your team to plan how I can add this new feature.

**Comment by nickdiorio** [comment]
Hi @yassineennassiri , sorry we didn't respond to you initially.  Is this still an interest you have?

**Comment by yassineennassiri** [comment]
Hello @nickdiorio  !

Thank you for your response ! Yes I m always interested.

As a first step, may I have just an overview about how could this be done ? 


Kind Regards,

**Comment by nickdiorio** [comment]
Hi @yassineennassiri,

Certainly, as an overview, we have a couple of options:

1.  You fork the relevant repositories and add your features, and we can link to your fork with a note of it's capabilities.
2. As an optional step, you can submit a pull request with your work to see if we can include it in SAM directly.

What is the scope of the work you are considering?  Are you interested in creating a model which takes electricity as an input and produces hydrogen as an output?  Do you envision any other capabilities you would need to develop along with that, and integration with any financial models?

Best,
Nick

**Comment by yassineennassiri** [comment]
Hi @nickdiorio,

My idea is to create a model that takes electricity as an input and produce hydrogen as an ouput. Two technologies that I want to integrate into this model for hydrogen electrolysis: 

The Proton Exchange Membrane (PEM) Electrolyzer and/or high temperature steam electrolyzer.

As an additional capability that I think must be considered also is the storage of hydrogen produced which can be stored in the three phases: gaz, liquid or solid using absorber material.

This model could also be linked to another model "cell fuel" for electricity generation based on hydrogen stored, depending on peak demand or to cover intermittence in PV production.

Is all these features could be implemented into one or two modules and then into SSC library ? 

Regards,

Yassine

**Comment by nickdiorio** [comment]
@yassineennassiri , thanks for providing the details.  To me this sounds broadly useful.  I think the path forward would be to create a new compute modules `cmod_hydrogen`.  The compute modules in the SSC project are described here: https://github.com/NREL/ssc/wiki/SSC-Compute-Modules. 

I've recently written a fuel compute module, which is a generic fuel cell that could conceivably be more robustly developed to incorporate hydrogen directly. https://github.com/NREL/ssc/blob/develop/ssc/cmod_fuelcell.cpp.  You can download a beta version of SAM to try out the fuel_cell if you'd like: https://sam.nrel.gov/sites/default/files/content/public_releases/sam-beta-windows-2019-1-21.exe .

I'll confirm with the team on next steps, but you're certainly welcome to start looking at this.  We could provide some limited support in getting started and potentially integrating with SSC.

**Comment by nickdiorio** [comment]
Maybe we can setup a time to talk as well, feel free to email `nicholas.diorio@nrel.gov`.  Thanks again for you interest!
