### ISSUE TITLE
PV POA as input generates multiple errors

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#610]
### Describe the bug

When running the Detailed PV model in "POA as input" mode, SAM often generates multiple error messages about DNI being set to zero because the decomposition model calculated a value less than zero or out of range.

### To Reproduce

1. Create a Detailed PV / No Financial case.

2. On the Location and Resource page, click **Add/remove weather file folders** to add the "Fake POA" file to the solar resource library: [phoenix_az_fake_poa.zip](https://github.com/NREL/SAM/files/6436233/phoenix_az_fake_poa.zip).

3. Choose the phoenix_az_fake_poa,csv file from the solar resource library.

4. Expand the **Albedo - Sky Diffuse Model - Irradiance Data (Advanced) panel** and choose **POA from reference cell**.
 
5. Run a simulation.

### Expected behavior

Either calculate valid DNI values at low sun angles and/or limit the number of error messages that are displayed during the simulation.

### Additional context

These errors tend to occur during time steps with low sun angles, so simulation results using the resulting DNI data are usually reasonable, at least on a total monthly and annual output basis because the output is typically low during those time steps.

**Comment by cpaulgilman** [comment]
Related issue: https://github.com/NREL/SAM/issues/416

**Comment by cpaulgilman** [comment]
Also happens with some weather files from NSRDB, such as Clover, VA 2020 single year file.

**Comment by GabrielSimoes1** [comment]
Good morning

I've read your solution, but where I have to change my weather file? I tried to set to zero values under 200, it didn't work. I did the same thing to time steps with low sun angles, but also didn't work.

I got the same problem. I have a weather file with POA as input, but SAM are not decomposing this data to DHI and DNI. My POA data is from a pyranometer.

As result I get a negative energy production 

Could you help me?

Thks

**Comment by janinefreeman** [comment]
Hi @GabrielSimoes1 , this issue was specifically to turn off the warnings for POA as an input, but if you have a weather file that is producing negative generation, can you please email it to sam.support@nrel.gov for us to take a look at? Thanks!
