### ISSUE TITLE
3D Shade Calculator on macOS crashes when using mouse to move or resize objects.

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#620]
See https://sam.nrel.gov/forum/forum-general/3437.

Screenshots and detailed error log:  [Mac Resize and hard crash SAM 2020.docx](https://github.com/NREL/SAM/files/6475446/Mac.Resize.and.hard.crash.SAM.2020.docx)

**Comment by sjanzou** [comment]
Works without crashing on Windows 10 with 2020.11.29.r2 and crashes on MacOS 11.1 per 
[Uploading Mac Resize and hard crash SAM 2020.docx…]()

**Comment by cpaulgilman** [comment]
One more person reported this with system information:

System Advisor Model
Version 2020.11.29, 64 bit, updated to revision 2
SSC Version 256: OS X 64 bit GNU/C++ May 12 2021 02:59:59
wxWidgets 3.1.1 on macOS Version 11.4 (Build 20F71)
Internet connection method: default
Display: 1440 x 900, magnification 1x

Model Name:    MacBook Air
Model Identifier:    MacBookAir10,1
macOS Big Sir:    Version 11.4
Chip:    Apple M1
Total Number of Cores:    8 (4 performance and 4 efficiency)
Memory:    8 GB

**Comment by sjanzou** [comment]
wex pull request 128 https://github.com/NREL/wex/pull/128 and ssc pull request 661 https://github.com/NREL/ssc/pull/661 are applied to fix broken MacOS build.

No longer crashes with pull request #775 
[GitHubIssuesSAM_620.docx](https://github.com/NREL/SAM/files/7546089/GitHubIssuesSAM_620.docx)
