### ISSUE TITLE
Pie Chart export as PDF not using correct color scale

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#622]
### Describe the bug

Export to PDF option for Pie charts on summary page seem to display the wrong colors in the output .pdf file if the 3rd or fourth values in the graph are 0. 

### To Reproduce

1. Open a MEwave or tidal case. 
2. Got to the Capital Costs: Financial tab
3. Check the override cost structure box, then make sure financial costs is $0
4. Simulate
5. Right click pie chart in summary page and export as PDF

### Expected behavior

Colors on pie chart should match that of summary page and other export methods (.jpg, .png)

### Screenshots

![image](https://user-images.githubusercontent.com/54449384/119053426-48e8c200-b983-11eb-930f-57e87957449f.png)
![image](https://user-images.githubusercontent.com/54449384/119053476-5736de00-b983-11eb-940f-1639e1805ba3.png)

**Comment by mjprilliman** [comment]
@sjanzou Do you mind taking a look at this before the next release?

**Comment by sjanzou** [comment]
wex branch SAM_622. wex pull request 124 https://github.com/NREL/wex/pull/124
![image](https://user-images.githubusercontent.com/6498311/141465665-da7b5c27-6cc4-4e82-9abe-e4d64d6fe8f7.png)

**Comment by sjanzou** [comment]
Closed with wex pull request 124 https://github.com/NREL/wex/pull/124
