### ISSUE TITLE
Report Generator Crashes SAM on MacOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#626]
Issue reported to SAM support mailbox in May 2021:

[MacOSReportGeneration.docx](https://github.com/NREL/SAM/files/6548197/MacOSReportGeneration.docx)

[report.pdf](https://github.com/NREL/SAM/files/6548200/report.pdf)

[Apple_crash_report.txt](https://github.com/NREL/SAM/files/6548201/Apple_crash_report.txt)

**Comment by brianschmidly** [comment]
Paul, I'm detecting this issue on macOS Big Sur version 11.4, too.  FYI.

**Comment by cpaulgilman** [comment]
Potentially related, LK browse() function results in error on macOS Big Sur when trying to open either a file or folder: SAM Error, Failed to open URL "/Users/[user]/path/to/file/or/folder".
