### ISSUE TITLE
Give users notice when the URDB rate download is unsupported in SAM

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#629]
Right now SAM only supports four types of utility rate units: kWh, kWh/kW, kWh daily, and kWh/kW daily. However, URDB supports additional rate units such as kVA and hp: https://openei.org/services/doc/rest/util_rates/?version=8

If the user attempts to download one of these rates, provide a notice that they may need to do the conversion themselves.

An example rate: https://openei.org/apps/IURDB/rate/view/539fbce2ec4f024c27d8756d#1__Basic_Information

A comment from Steve on a previous PR with more possible examples: https://github.com/NREL/ssc/pull/580#pullrequestreview-671111045

**Comment by cpaulgilman** [comment]
One note about this particular example is that it's an irrigation rate (hence the kWh/hp units) so good to handle in SAM, but maybe not as high a priority as a commercial or residential rate to implement a complete solution.
