### ISSUE TITLE
Geothermal output issues

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#630]
User reported issues: https://sam.nrel.gov/forum/forum-general/3451

* Capacity factor is always 100%. Most recent version to calculate it correctly is SAM 2017.9.5.

* System Availability losses `adjust` do not affect outputs.

**Comment by mjprilliman** [comment]
These issues have both been addressed in previous PR's. I will add new issues with Geothermal fixes for the next release. Closing this issue now.
