### ISSUE TITLE
Add UI function that auto-populates cmod inputs

### ISSUE THREAD

**Issue by tyneises** [NREL/SAM#634]
It can be helpful to call the technology compute module from a UI page script to calculate design parameters from the same SSC code that the annual simulation will use. Currently this is possible by defining each compute module input with its matching UI variable (e.g., ssc_var(obj, "tshours", ${tshours});). However, this is tedious and causes opaque ui crashes when a new input is added to the compute module but not assigned in the UI script.

Proposed modification:
A new function that
1) Automatically populates the SSC object by assigning ui variables to compute module inputs with the same name
2) Passes a flag to the compute module indicating the type of simulation. I'm currently using an optional compute module input 'sim_type' and setting it to 2 in the ui script when I want to call the compute module for design-point calcs and not an annual simulation. This variable can't exist in the UI, because it will affect normal SAM simulations
3) Runs the specified compute module and returns compute module outputs the same as the existing 'ssc_exec' function, (e.g., ${total_installed_cost} = ssc_var(obj, "total_installed_cost");)

The function might look something like:
ssc_auto_exec(obj_solved, 'cmod_name', sim_type)

**Comment by tyneises** [comment]
You can see how I'm calling the technology compute module in UI scripts the Tedious Way by:
- checking out the etes_dispatch SSC branch: https://github.com/NREL/ssc/tree/etes_dispatch
- checking out the etes_dispatch SAM branch: https://github.com/NREL/SAM/tree/etes_dispatch
- use the UI editor to review any of the "ETES_..." ui pages
- run the ETES technology model, which is available under the CSP technology drop-down

**Comment by sjanzou** [comment]
@tyneises , that is tedious! I will try to have a pull request for you soon!

**Comment by tyneises** [comment]
@sjanzou I modified the UI pages to call the cmod once in the System Design page equations. Then, the System Design page stores all relevant cmod outputs. The remaining UI pages use a distinct variable name for its UI object, which it sets to the corresponding System Design output via equation{'name'} = define() {......} https://github.com/NREL/SAM/commit/c95bf3e3de51ffcc29dd3f3be7b9cbfff7510161

**Comment by sjanzou** [comment]
Closed with pull request #687 into etes_dispatch which was later merged into develop
