### ISSUE TITLE
Defaults manager writes small values instead of 0

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#642]
### Describe the bug

When creating a new variable, I attempted to write a new SSC number of 0, but the defaults manager wrote 3.33e-317 instead. Modifying the variable successfully changed it to zero.

### To Reproduce

1. Go to defaults manager
2. Create a new number
3. Use git diff to see what the defaults manager actually wrote

### Expected behavior

Expect 0 to write 0 instead of a very small number.

**Comment by janinefreeman** [comment]
Is this related to #458 ?

**Comment by mjprilliman** [comment]
When modifying an existing variable in the Defaults Manager, trying to change a variable attached to a Choice object from 1 to 0 changed the variable to 3e-317. Re-modifying did not fix the issue. The default was only written to 0 when I modified the value to 0.0 rather than 0.

**Comment by sjanzou** [comment]
Fixed with wex pull request https://github.com/NREL/wex/pull/120

**Comment by sjanzou** [comment]
Merged into wex PR#120
