### ISSUE TITLE
How to import a module or an inverter from sam's library to pysam?

### ISSUE THREAD

**Issue by danige10** [NREL/SAM#647]
Hi everyone, Could someone explain to me what is the code to import a module from the sam library to python?
It would be a great help, thank you.

**Comment by cwhanse** [comment]
I don't know how to use pysam to do that. You could use pvlib-python:

```
import pvlib


CECmodules = pvlib.pvsystem.retrieve_sam('CECMod')
```

returns the CEC module database as a Dataframe.

**Comment by brtietz** [comment]
@danige10 Unfortunately there isn't yet code to directly import the libraries that the SAM GUI uses. A workaround is to set up the PV system in the SAM GUI, use "shift-F5" to export the JSON files with the module and inverter data, and import it into PySAM. An example for the last step using PVWatts is available here, this also works with the detailed PV model: https://github.com/NREL/pysam/blob/master/Examples/SAMsimPVWattsCommercialExample.py
