### ISSUE TITLE
SHW model: no way to get cost of auxiliary energy

### ISSUE THREAD

**Issue by bje-** [NREL/SAM#65]
It seems that there is no way to get an output variable in SAM for the dollars per year spent on auxiliary energy in the solar hot water model. You can get cost with system, cost without system, etc., but these include pumping energy, etc. All I want to know is how much money is being spent on auxiliary boosting of the tank?

**Comment by nickdiorio** [comment]
Hi Ben, it's been some time since I've looked at this module.  But I think the "electricity bill" with system is essentially equal to the money spent on auxiliary boosting of the tank. You could set the pumping efficiency to 100% and a very low power as well.
