### ISSUE TITLE
Defaults for PV & Battery Divergence

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#665]
The defaults for FlatPlatePV Single Owner were updated recently in https://github.com/NREL/SAM/commit/992c6bdf6b2d4d9c6d69ba5e5cce947d56186a5c#diff-2c4938936666acfae618b1684ecfd2241a9bbd5fd82590de67c32a207f900c07 changing the cost defaults for many of the PV & Battery models such as the total installed cost and construction financing cost, while the system_capacity remained the same:

For example, in Flat Plate PV_All Equity Partnership Flip.txt, total_installed_cost increased from 51384528 to 5.40779e+12.

In the GUI, these values are overwritten from a callback or equation, so that total_installed_cost is around 51384528 again.

The problem is that for these files, the PySAM modules use the defaults from the .txt file (5.40779e+12) and due to these costs being different between the GUI and the .txt file (while the system config is the same), the PySAM and SAM default simulations have extremely different results. 

-------

I went and did F10 on all the PV and/or Battery configs and found a lot of the defaults to be out of date with the GUI... Is there something systematic we can do to assure the defaults file reflects the GUI as well as possible?

**Comment by dguittet** [comment]
@sjanzou mentioned a script to check all the Ui forms for all the configurations will trigger all the calculations (equations and callbacks). And an option to overwrite the defaults after checking all ui forms for each configuration. I think a option for each UI variable to be excluded from being overwritten would also be helpful

**Comment by sjanzou** [comment]
@dguittet, @mjprilliman is this still an issue? 

There is a "Test_UI" branch of SAM that has an additional invoke.cpp "check_configuration" that is supposed to run through a configuration's pages and open each one to test the callbacks and equations. 

I never had a chance to finish testing... would this be the desired function here? 

There is currently no option for each variable (UI or ssc) to be excluded from being overwritten.

**Comment by mjprilliman** [comment]
> @dguittet, @mjprilliman is this still an issue?
> 
> There is a "Test_UI" branch of SAM that has an additional invoke.cpp "check_configuration" that is supposed to run through a configuration's pages and open each one to test the callbacks and equations.
> 
> I never had a chance to finish testing... would this be the desired function here?
> 
> There is currently no option for each variable (UI or ssc) to be excluded from being overwritten.

We pushed a PR fixing the inconsistencies for the release but there might still be a desire for that function. @dguittet could speak to that more than me.
