### ISSUE TITLE
Text Appears Jumbled

### ISSUE THREAD

**Issue by minimenchmuncher** [NREL/SAM#672]
### Describe the bug

The text appears jumbled on my computer, making the tool somewhat less usable. Screen Shot included.

I would expect this to affect Linux Desktop (GNOME) only, probably something to do with the gtk setup or the like.

### To Reproduce

1. Use x11 session (not tested in wayland)
2. turn on "Large Text" in Accessibility Settings
3. Open SAM

### Expected behavior
I would expect the text to be legible, not jumbled.

### Screenshots
![image](https://user-images.githubusercontent.com/3420931/127659054-cec93838-acbc-4ab1-ad47-296544cf5bb3.png)

### Operating System and Version

 - OS: Ubuntu 21.04 x64_64 5.11.0-25-generic running GNOME 3.38.4 and x11
 - Version 2020.11.29

### Additional context

In the screen shot I see the input fields are dark with dark blue text-- that's not the issue (my GTK theme here is Nordic-darker). The problem is that the text boxes all appear to be too small so it's tough to see what I'm doing.

I can also report the logs often say things like:

```
Gtk-CRITICAL **: 09:18:41.596: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
```
![image](https://user-images.githubusercontent.com/3420931/127659862-2394fd69-82a0-4e7b-93ab-d1b016135f3f.png)
which might have something to do with the problem.

Additionally, I habitually use "Large Text" in the GNOME Accessibility settings -- given the fact I'm currently stuck with a hidpi display, an nvidia graphics card (hence x11), for which fractional scaling is terrible, this is usually a sensible workaround where I can still see what I'm doing. Turning off this setting in GNOME causes everything to render properly.

**Comment by sakvaua** [comment]
Same on Linux Mint 19.2 but with no Large Text enabled but Hi-DPI User interface scaling enabled in display options. Returning to normal size makes everything very small but the fonts in SAM become properly scaled

**Comment by cpaulgilman** [comment]
@minimenchmuncher and @sakvaua Thank you for this feedback and for describing the workaround. We are unlikely to have resources to address this but would welcome someone contributing a fix for this.
