### ISSUE TITLE
Code generator outputs no longer align with metrics table

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#685]
![image](https://user-images.githubusercontent.com/6498311/129694138-37a891c6-487e-4e3a-8504-5b6771b9e17a.png)

Discovered while fixing issue #673

**Comment by mjprilliman** [comment]
@sjanzou #558 May fit here as well?

**Comment by sjanzou** [comment]
With pull request #768 the code generator outputs now align
![image](https://user-images.githubusercontent.com/6498311/141780410-9a835121-ed4c-45ae-bb88-1da739d23e66.png)

SAM project file used to test both #558 and #685 
[test_SAM_558.zip](https://github.com/NREL/SAM/files/7538591/test_SAM_558.zip)
