### ISSUE TITLE
CEC module library has duplicate entries

### ISSUE THREAD

**Issue by cwhanse** [NREL/SAM#69]
For the following modules:

['Silevo_Triex_U310_Black', 'Solartec_S72MC6_290', 'Solartec_S72MC6_295',
       'Solartec_S72MC6_305', 'Solartec_S72MC6_310', 'Solartec_S72MC6_315']

It looks like the parameter values and date are different, although the module names are the same.  It would be useful to clarify if the duplicates result from two separate test evolutions reported to the CEC, or from re-analysis of a single test report but using a different process.

**Comment by cpaulgilman** [comment]
We're generating a new CEC module library for SAM, and I wanted to address this issue, but I'm not seeing duplicate entries for these modules either in SAM 2018.11.11 or in the Excel workbook from the CEC.
