### ISSUE TITLE
SAM Photovoltaic,residential 

### ISSUE THREAD

**Issue by curry830** [NREL/SAM#697]
Can I adjust "Module aspect ratio" in Shading and Layout mode casually?
Can I adjust "Active surface's length and width" in 3D shading calculator casually?
We are Taiwanese students,we need your help, we are studying hard.

**Comment by janinefreeman** [comment]
Hi @curry830 ! It appears that your question is more about model usage, which is better suited to the SAM user support forum: https://sam.nrel.gov/forum.html. Thank you!
