### ISSUE TITLE
Sales Tax typo on PVWatts 'Installation Costs' page

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/SAM#699]

**Comment by Matthew-Boyd** [comment]
![image](https://user-images.githubusercontent.com/30417543/133470954-8e1cbfc8-3723-43ac-a809-3f75b0503aad.png)

**Comment by cpaulgilman** [comment]
Fixing this may cause conflict between develop and community-solar branches, so may want to fix in develop after community-solar is merged.

**Comment by cpaulgilman** [comment]
This should be fixed in Develop as of https://github.com/NREL/SAM/pull/730
