### ISSUE TITLE
Develop Environment User Interface search missing instances

### ISSUE THREAD

**Issue by tyneises** [NREL/SAM#705]
The search button in the User Interface page in the SAM Development Environment appears to miss instances of the searched text that exist in the Callbacks.

![ui_search](https://user-images.githubusercontent.com/27820293/134689559-3f3aa49a-5f62-4a1c-84c6-2db64116d420.png)

**Comment by sjanzou** [comment]
Fixed with SAM pull request #764 
![image](https://user-images.githubusercontent.com/6498311/141680296-b07d8ba1-b04f-452e-b68e-ec7d53a18ad0.png)
