### ISSUE TITLE
Fix combine cases combined operating costs and keep nameplate input

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/SAM#709]
- Fixed annual cost, in the Generic Model Operating Costs, is off by ~1000 when brought over
- Keep Nameplate capacity input (don't hide it)

@cpaulgilman I will iterate with you on the UI element organization, for the second bullet point

**Comment by Matthew-Boyd** [comment]
@cpaulgilman I don't think there's an issue with the Operating Costs, as it initially seemed. The default column width is just cutting off the exponent.

![image](https://user-images.githubusercontent.com/30417543/141850786-5c949bec-04bf-48f6-8178-5700509c6449.png)

**Comment by Matthew-Boyd** [comment]
@cpaulgilman @janinefreeman How does this look for keeping the nameplate capacity when combining cases? It will initially be 0, but will update to the sum of the nameplate capacities after the cases are chosen.

![image](https://user-images.githubusercontent.com/30417543/141851964-74ec57e5-763b-49aa-9012-e2c52584af32.png)

**Comment by cpaulgilman** [comment]
I agree with showing the nameplate capacity because it is used for various $/kW calculations. It is also useful to be able to compare the nameplate to the peak generation shown under "Calculated Values." 

Should the nameplate capacity be editable? The time series generation data is editable after SAM calculates the combined data, and I think it is reasonable for a user to want to edit either.

Also, maybe change the radio button label "Generate production profiles from open cases" to "Generate production profiles and nameplate capacity from open cases."

**Comment by Matthew-Boyd** [comment]
I'll make that change to the radio button label.

I can also make the nameplate capacity editable, but I think I recall @janinefreeman maybe having an opinion on that?

@cpaulgilman , what would a use-case be for editing the combined nameplate capacity instead of editing one or more of the case nameplate capacities? I vaguely remembering you describing one.

**Comment by cpaulgilman** [comment]
I don't have a specific use case, but also can't predict the different ways people might use this combine cases capability. Given that "nameplate capacity" can be a subjective value, I'm guessing there may be situations where the user might want to change it.

I'm also fine with leaving it as a calculated value that cannot be edited.

Thanks,
Paul.

**Comment by janinefreeman** [comment]
Remind me, does the combination happen when a user clicks "Select cases" or when they click simulate? If the former, then Paul is probably right that it should be editable. If the latter, then it probably shouldn't be. Thanks Matt!

**Comment by Matthew-Boyd** [comment]
The combination happens after the user clicks "Select cases", selects their desired cases to combine, presses 'OK' and the individual cases are simulated. At this point the "Nameplate capacity" is combined and set. This all of course happens before the generic case is simulated with the resulting production profile.

I assume you mean 'simulate' in regards to the generic case; therefore, the combined nameplate capacity should be editable after the individual cases are simulated and before the generic case is simulated? (Which is inline with what Paul is suggesting.)

**Comment by janinefreeman** [comment]
Yes, that is what I mean, so there's my vote for Paul's suggestion. :)

**Comment by Matthew-Boyd** [comment]
Thanks! I'll make it editable as described, per Paul's suggestion.

**Comment by Matthew-Boyd** [comment]
Resolved Issue via commit ac747b6c5cbbe4ca50b52c1e78ffa85f66eb6d5d
