### ISSUE TITLE
Requests for ratcheting demand rates

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#71]
Demand ratchets: https://sam.nrel.gov/forum/forum-general/1164

Topic on old forum not on Wayback Machine: https://sam.nrel.gov/node/75891

Australia kVA with rolling capacity demand charges: https://sam.nrel.gov/forum/forum-general/1341

From Owen Z 5/11/2021:

> Demand Ratchets / Minimum Billing Demands – These are already ubiquitous among commercial and industrial customers, but not currently represented in SAM (although you can sometimes calculate a workaround using the minimum bill function, but not in a super streamlined manner). If I define “Billing Demand” as the amount of kW that are billed (and thus gets multiplied by the demand charge), these are usually not as simple as just the peak 15- or 30-minute demand during the month. Usually, they are specified as something like this:
> 
> The Billing Demand shall be the highest of the following:
> (a) Actual maximum demand measured during the month
> (b) 75% percent of maximum demand over the previous 12 months
> (c) 30 kW 
> 
> This is just an example, but you get the point. Option (b) is referred to as a Demand Ratchet, and it’s a way to make sure that distribution utilities recover their costs! There are some more nuances to this whole area, but this is the general gist.

**Comment by brtietz** [comment]
A discussion of how the lookback_months field was defined:
 

> Currently the URDB provides an array of 12 percentages. See discussion below why this doesn't work.
>  
> What we do need is an array of 1/0 values for which months are included in the lookback period, a scaler value for the percent, and a scaler value for the number of lookback months. The 12 month 1/0 array applies for rates that are calculated over the past summer months for example. Other lookback rates are calculated over the past X months. So in most, maybe all cases only the 12 month 1/0 array would apply or the scaler lookback months would apply.
>  
> For example, a summer lookback rate from the URDB would look like:
>  
> "lookback_months": [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
> "lookback_percent": 50
> "lookback_range": 0
>  
> And a lookback rate with a constant 9 month lookback range would look like:
>  
> "lookback_months": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
> "lookback_percent": 80
> "lookback_range": 9
>  
> It seems like the current array of 12 percentages will translate to this new framework for the first example, as long as the percentage array contains the same value for each month. For example, this rate has Demand Ratchet Percentages as [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25], which would be:
>  
>  
> "lookback_months": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
> "lookback_percent": 25
> "lookback_range": 0
>  

I can forward the entire thread to folks as desired, since it also has implications for the upgrade to URDB version 8.
