### ISSUE TITLE
latitude-comma-space-longitude has unspecified behavior

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#710]
### Describe the bug

SAM's solar resource download accepts latitude-comma-longitude successfully, but adding a space (the default when you copy from Google Maps) converts the lat-lon pair to a different lat-lon or an arbitrary address.

### To Reproduce

1. Open a version of SAM with api-keys (2020.11.29 r2 or a beta)
2. Go to the location and resource page
3. Enter (for example) "39.71, -105.1", select "choose year"
4. See that the lat and lon in the "header data from weather file" do not match what was wntered

### Expected behavior

The lk script responsible for the conversion should strip the spaces for ease of use

### Screenshots

![image](https://user-images.githubusercontent.com/5530592/136408360-f18b4271-ed95-4601-a45b-8440f11fa73d.png)

**Comment by cpaulgilman** [comment]
UI callback error when lat/lon pair accidentally doesn't include a comma:

![image](https://user-images.githubusercontent.com/27711933/145908859-fd6dcf41-8976-4b28-8410-5d84818f64ed.png)
