### ISSUE TITLE
DView values not present in "Time series" after "Save with hourly results"

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/SAM#713]
Is it possible to have the values saved via "Save with hourly results" present in the "Time series" pane like they are in "Data tables"? And, potentially, have the same plots showing at the prior close?

**Comment by tyneises** [comment]
This would be very helpful for some of our slower (CSP) models.

**Comment by cpaulgilman** [comment]
User request for this feature: https://sam.nrel.gov/forum/forum-general/4294
