### ISSUE TITLE
Parametrics interface does not properly sizing batteries for duration

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#716]
### Describe the bug

When attempting to do parametric run on battery duration in hours, the battery strings and cells are not updated appropriately.

### To Reproduce

1. Set up a detailed pv-battery model
2. Select "hours" for the duration input on the cell and system page
3. Set up a parametrics run varying the number of hours with battery back installed capacity as an output
4. See that installed capacity is the same regardless of the input hrs

### Expected behavior

The parameteric runs should vary based on the input hours

### Screenshots

![image](https://user-images.githubusercontent.com/5530592/138768910-fd1e150d-9c8d-4990-bb3e-6a2fe2014110.png)

### Operating System and Version

Occurs in 2020.11.29 r2 and on develop

**Comment by sjanzou** [comment]
Still failing in latest develop branches
![image](https://user-images.githubusercontent.com/6498311/140262116-d2d300aa-3e42-402b-899d-463fb54e1e3d.png)

**Comment by mjprilliman** [comment]
> Still failing in latest develop branches ![image](https://user-images.githubusercontent.com/6498311/140262116-d2d300aa-3e42-402b-899d-463fb54e1e3d.png)
> 
> This is a subtle failure and may require another issue or handled with message boxes
> 
> If the units are changed to hours on the page: ![image](https://user-images.githubusercontent.com/6498311/140262516-4cfc4262-ba1d-47c2-9f75-9e3621a42b89.png)
> 
> then the parametrics work correctly (first failing graph was when units were initially kWh) ![image](https://user-images.githubusercontent.com/6498311/140262326-a60085b9-891d-4eba-8626-d8c315ccda39.png)

Is this not the intended behavior? If you choice in the dropdown is 'kWh' shouldn't changing the hours then have no effect on the computed kWh capacity?

**Comment by brtietz** [comment]
https://github.com/NREL/SAM/issues/741 has a more comprehensive take on this issue.
