### ISSUE TITLE
Remove iOS and Android from code generator

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#718]
The Code Generator options "Android Studio (Android)" and "XCode Swift (iOS)" are based on SAM 2017.9.5 and out of date.

We don't have resources to maintain these option, so best solution is to remove them.

Workaround solution is to build libraries from GitHub repositories as described here: https://sam.nrel.gov/forum/forum-sdk/3605

**Comment by sjanzou** [comment]
SAM pull request 738 should close this issue
