### ISSUE TITLE
SAM crashes on macOS

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#723]
### Describe the bug

SAM crashes after clicking Simulate twice.

### To Reproduce

1. Create new Detailed PV / No Financials case.
2. Click Simulate.
3. Click Simulate, repeat until crashes.

Error log: [macos-error.txt](https://github.com/NREL/SAM/files/7437297/macos-error.txt)

Notes:

* SAM crashes pretty reliably immediately after clicking Simulate the second or third time. 
* Number of cases in file seems to affect how many times it takes for SAM to crash (maybe): More cases takes more clicks to crash. 
* Note that SAM only crashes for some configurations. For example, PVWatts / No Financials does not crash.

### Operating System and Version

 - Tested in macOS Catalina 10.15.7 and observed in macOS Mojave 10.14.6
 - SAM 2020.11.29 r2

**Comment by sjanzou** [comment]
Note that this crash does not happen on macOS 12.0.1 using a MacBook Air with an Apple M1 chip running SAM under Rosetta. 

The crash is reproducable on Intel based MacBooks and is related to the heat map. The issue does not occur for PVWatts / No Financial configuration and is currently under review and testing in the SAM_723 branch of SAM.

**Comment by sjanzou** [comment]
wxWidgets 3.1.5 fixes UI editor crash and all heatmap refreshing issues. However, the PV / No financial configuration (among others) runs and does not crash unless the heat map is selected and then Simulate clicked again. 

Additional updates will be posted in this thread and in the macOS_wx3.1.5 branches of all repos.

**Comment by sjanzou** [comment]
Fixed with pull request #865
