### ISSUE TITLE
PVWatts-Battery "Adjust" Bug

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#727]
There appears to be a bug in the PVWatts-Battery model with the "adjust" input:

1. Open a PVWatts-Battery Residential case
2. Click "simulate"- note that annual energy is 8023
3. Open the "adjust" factor on the System Design page, enter 25% in a constant loss
4. Click "simulate"- annual energy is still 8023

This does not appear to be happening in the normal PVWatts case. This bug is present in 2020.11.29 r2 as well as develop.

**Comment by janinefreeman** [comment]
@sjanzou  do you have time to add this to your list? If not I can take a look next week

**Comment by sjanzou** [comment]
Addressed in ssc pull reqeust 672 https://github.com/NREL/ssc/pull/672
<img width="893" alt="image" src="https://user-images.githubusercontent.com/6498311/143675432-53df6eec-77d0-4602-9590-6015dca857f5.png">

With test project file
[SAM_727_test.zip](https://github.com/NREL/SAM/files/7611501/SAM_727_test.zip)

**Comment by sjanzou** [comment]
Closed with https://github.com/NREL/ssc/pull/672
