### ISSUE TITLE
Electricity Purchases hourly buy rates option bug

### ISSUE THREAD

**Issue by tyneises** [NREL/SAM#736]
When the user selects "Use hourly (subhourly) buy rates instead of TOU rates" on the Electricity Purchases page, the Single Owner financial model instead uses the buy rate from the table in the Energy Charges section. This happens at least for the Buy all / sell all configuration. 

To Reproduce (In 2010 release and at least 11/2/21 version of LPPA branch)
1. Open default case of Detailed PV-Battery, PPA Single Owner
2. Go to Battery Dispatch page. Deselect "charge from system" in Period 1 and select "charge from grid" in Period 1.
3. Go to Electricity Purchases page
4. Select "Use Retail Rates" in drop-down
5. Run default case that we expect to use the 0.06 $/kWh buy rate from the table in the Energy Charges section. 
6. Go to Cash Flow results. Get OPERATING EXPENSES: Electricity purchase ($) = 78,478
7. Go to Electricity Purchases page
8. Add 8760 buy rate prices at 0.2 $/kWh and select 'Use subhourly buy rates instead of TOU rates'
9. Run the modified case. Expect to see higher cost of Electricity purchase due to the higher buy rate in the 8760 data, but instead see the same value as in Step 6.

**Comment by mjprilliman** [comment]
@cpaulgilman @brtietz @tyneises It looks like the tier_charge variable was not being assigned in the hourly buy rates section which was causing the code to fall back to the TOU rates. Adding the fix changes Electricity purchase to $261,594 for hourly buy rates of $0.2/kWh

![image](https://user-images.githubusercontent.com/54449384/140836403-5eabc338-14ff-4c6a-8a4f-3542b986726b.png)
