### ISSUE TITLE
Transition PV smoothing algorithm to the "timestep method"

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#744]
Right now, the pv smoothing battery dispatch method uses forecasts of PV in order to compute a battery dispatch profile for the entire year. Due to differences in the efficiency assumptions, this means the predicted SOC can drift from the actual SOC during the year. Refactor the pv smoothing implementation such that it is run at the ramp interval and can get feedback from the actual battery SOC.

**Comment by mjprilliman** [comment]
@sjanzou You can send the review my way on Monday.

**Comment by sjanzou** [comment]
closed with ssc pull request 758 https://github.com/NREL/ssc/pull/758 into patch and ssc pull request 764 https://github.com/NREL/ssc/pull/764 into develop
