### ISSUE TITLE
Improve piping heat loss in molten salt power tower model

### ISSUE THREAD

**Issue by tyneises** [NREL/SAM#746]
The Molten Salt Power Tower Model now uses a piping heat loss coefficient in units of W/m2-K to calculate piping thermal losses which replaces units of W/m in the previous versions. This new convention allows the performance model to calculate new piping losses as the receiver thermal power and design temperatures vary. We found that the old W/m default value, 10200, in the default case corresponded to a W/m2-K value of around 13, which we think is likely too high for insulated piping, so we set the new W/m default value to 2. This change results in 0.76% increase in annual energy for the default case. The change will be smaller as temperatures increase relative to the default case, and the change will be larger as the receiver thermal power decreases relative to the default case.

In the Version Upgrade, we do not attempt to convert the W/m value from the old file to the new W/m2-K input, and instead set it to the default value and instruct the user to review the input on the Tower and Receiver page and modify it as necessary for their design.

**Comment by cpaulgilman** [comment]
Looks good and works well. I revised the message a little:

We have changed the units for the piping heat loss coefficient for the Molten Salt Power Tower Model from W/m to W/m2-K.This new convention allows the performance model to calculate piping thermal losses as the receiver thermal power and design temperatures vary. We found that the old default value of 10,200 W/m corresponds to about 13 W/m2-K, which we think is too high for insulated piping, so we chose a new default value of 2 W/m2-K. We are changing the piping heat loss coefficient value in your file of 10200 W/m to the default value of 2 W/m2-K. Please review this input on the Tower and Receiver page and modify it as necessary for your design.

**Comment by tyneises** [comment]
In the SSC repository, I created a new tcsmolten_salt cmod input for the W/m2-K input, and I attempted to deprecate the old W/m input. Both inputs are optional in the var table, and then checked at the beginning of exec(). If the old is provided but not the new, then the code throws an exception explaining the change. If both are provided, then the code prints a notice that the old input is not used. You can see this behavior by using Shift+F5 to generate a script of the default MSPT case in SAM 2020 and then running that script in the SDKtool.

https://github.com/NREL/ssc/commit/41fdaf10c22fe049cd1a7dc7e40d13544b47b332

**Comment by tyneises** [comment]
FYI, this issue will affect your old MSPT scripts, old MSPT SAM files, and MSPT in pysam. Let me know if you have any thoughts on the piping loss change or recommendations for deprecating cmod variables.

@jannamartinek @Matthew-Boyd @qualand @mjwagner2 @dguittet
