### ISSUE TITLE
Increase maximum inverter efficiency in PvWattsv7 to 100% for modeling using AC capacities

### ISSUE THREAD

**Issue by grgmiller** [NREL/SAM#747]
### Is your feature request related to a problem? Please describe.

I know that this is more of a PvWatts issue than a SAM issue, but I wasn't able to easily find a forum for requesting feature updates to PvWatts. Currently, PvWatts limits the inverter efficiency parameter to a maximum of 99.5%. However, for some applications, we are trying to simulate solar output based on a given AC system capacity, ignoring any losses on the DC side of the system. To do this, I am entering the system capacity in kWac, setting a DC-to-AC ratio = 1, removing any DC-side losses from the losses parameter, and attempting to set the inverter efficiency to 100%. However, the current constraint only allows the inverter efficiency to be 99.5% maximum. 

### Describe the solution you'd like

Increase the inverter efficiency parameter limit from 99.5% to 100%. I'm not sure if this can be done in SAM, or if this request needs to be passed to the PvWatts team. 

### Describe alternatives you've considered

An alternative could be to take the hourly system generation data that I get using an inverter efficiency = 0.995 and divide that value by 0.995 to scale it.

### Additional context

For my specific context, I'm only interested in the hourly generation output, not in any financial or other parameters. I'm not sure if increasing the limit to 100% would have any impact on the way that the model performs or the other outputs.

**Comment by cpaulgilman** [comment]
Thank you for posting this issue. PVWatts is part of SSC and SAM, so this is a good place to report issues and request features for PVWatts.

The version of SSC used by the PVWatts web API (https://developer.nrel.gov/docs/solar/pvwatts/v6/) and online PVWatts Calculator (pvwatts.nrel.gov) is generally older than the version of SSC available in SAM, so updates we make to SSC will not be reflected in the web API or online calculator until those services are updated.

**Comment by grgmiller** [comment]
Thank you, Paul. I should have mentioned that I'm currently using the PVWattsv7 module as part of PySAM, rather than the online calculator, so it would definitely be helpful to have this updated in the SSC for SAM.
