### ISSUE TITLE
DC Degradation Schedule Confusing

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#755]
In the Detailed PV model, the DC Degradation "schedule" mode is confusing because users can enter a value of degradation for Year 1, but it is not used. @cpaulgilman what do you think of me adding red text that shows up on the UI page if the Year 1 value is something other than 0, to alert users that the Year 1 value isn't used? Or should we modify SSC such that the Year 1 value is actually used?

**Comment by cpaulgilman** [comment]
I think the red text approach is best. I think it makes sense for degradation to start in Year 2 because, limited to modeling annual degradation, we assume the modules and system perform as designed in the first year.
