### ISSUE TITLE
Improvements to sloped terrain UI feature

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#759]
For future improvements:

* Consider enabling slope inputs for combinations that have no effect. For example, disable when self shading is enabled but backtracking is disabled.
* Consider moving to "Shading and Layout" page.

_Originally posted by @cpaulgilman in https://github.com/NREL/SAM/issues/742#issuecomment-965967070_

**Comment by mjprilliman** [comment]
@cpaulgilman Let's discuss these changes when looking at system design / land area pieces of the user interface

**Comment by cpaulgilman** [comment]
@mjprilliman I think we decided to 1) enable slope inputs based on their applicability, and 2) leave the slope inputs on the System Design page because they are linked to inputs on both the System Design and Shading and Layout pages, so there is not a perfect place to put them.
