### ISSUE TITLE
No default value found for 'user_capacity_factor'

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/SAM#777]
A new notice when opening a Generic Battery model:

"No default value found for 'user_capacity_factor' in external file (Generic Battery/Single Owner), using internal default"

(Assigning Matt and Brian since it sounds like you're handling general default updating?)

**Comment by brtietz** [comment]
I'm pretty sure I fixed this issue on the standalone battery branch. I'd vote for merging that branch in first, and then I'll take a look and see if the issue persists on develop.

**Comment by brtietz** [comment]
This was fixed by yesterday's merges.
