### ISSUE TITLE
Support time series buy and sell rates as input for electricity bill calculations

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#78]
For example, ComED hourly pricing:

https://www.comed.com/WaysToSave/ForYourHome/Pages/HourlyPricing.aspx

**Comment by cpaulgilman** [comment]
Would be useful to have both hourly buy and sell rates, and to have an option to allow hourly rates to be added to month-by-hour rates.

For example, Denmark has a rate structure that combines an hourly buy rate with a month-by-hour buy rate:

> The electricity price is a price based on the current balance on the market (traded similar to a stock market once every day - production vs. consumption), it varies a lot but is around 0.30 DKK/kWh in average. It is really the clean price for the electricity produced.

> But as normal household user you pay around 2 DKK/kWh, because there are grid tariffs, for use of the electrical grid, and taxes on top of the electricity price. (Companies typically pay much less in tariffs and taxes).

> The electricity price varies every hour, the grid tariffs vary on seasonal and TOU basis. These costs for electricity consumption can of cause be added together to a total cost per kWh – but still varying on an hourly basis.

> The page ”Energy charges” fits the consumption ”grid tariffs” perfectly as they are now (in the near future they will maybe also be on hourly basis). But to really cover the total electricity cost we need to be able to make a sum of the TOU-based grid tariffs and the hourly electricity buy rates. One total cost for each hour (like the hourly/subhourly sell rates) in the year would solve the issue.

> Do you think it is something you could implement?

**Comment by frohro** [comment]
When addressing this, it would be really nice to be able to have electric rates that can be changed over the years by other than a linear factor.  For example, here on Guam, there is a LEAC (fuel) surcharge, and that is projected to drop precipitously once when 200 MW of solar comes online in 2022.

**Comment by cpaulgilman** [comment]
As of SAM 2020.2.29, time series retail buy and sell rates are available for all metering options except net metering with an optional escalation rate that applies in addition to inflation. 

It is not possible to input a table of hourly buy and/or sell rates by year.

In general, for financial modeling that involves a change in an out-year of the cash flow, it may be possible to approximate the effect my modeling each period as a separate case, and using the resulting cash flows from SAM to create a cash flow outside of SAM to calculate NPV and other fianancial metrics. Another example like this is a PPA project switching to merchant at the end of the PPA period.
