### ISSUE TITLE
Fuel Cell / Commercial Configuration UI and Defaults Issues

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#801]
Defaults need updating 

```
No default value found for 'compute_as_cube' in external file (Fuel Cell/Commercial), using internal default
No default value found for 'batt_unit_capacity' in external file (Fuel Cell/Commercial), using internal default
No default value found for 'batt_unit_surface_area' in external file (Fuel Cell/Commercial), using internal default
```

Default simulation fail. Fix by changing default dispatch from input battery power targets to peaks shaving or manual dispatch:

```
exec fail(battery): Invalid custom dispatch, must be 8760 * steps_per_hour.
Simulation battery failed :exec fail(battery): Invalid custom dispatch, must be 8760 * steps_per_hour.
monthly_grid_to_batt not assigned
Simulation cashloan failed :monthly_grid_to_batt not assigned
```

Grid outage and critical load inputs are available, but Outage Discharge Limits form is missing from Dispatch page. Should it be added?

**Comment by dguittet** [comment]
The first 3 fuel cell battery defaults existed in develop for me. For example, here's `compute_as_cube`: https://github.com/NREL/SAM/blob/229e2ec84c324d20e8e640370319998fb61d3ae7/deploy/runtime/defaults/Fuel%20Cell_Commercial.txt#L1427

**Comment by brtietz** [comment]
The defaults were added here: https://github.com/NREL/SAM/commit/e28ad03e3eb238ccc6dc64aa4806e128d9fe18b9#diff-2c4938936666acfae618b1684ecfd2241a9bbd5fd82590de67c32a207f900c07

The outage discharge limits are on the battery storage page, to match the location of the "charge limits and priority" box. If we want to move outage discharge limits, we should move both.

I did not get the LCOS error (in Steve's beta from Saturday or on develop)

**Comment by mjprilliman** [comment]
So is this only the LCOS issue now? I think I've resolved that issue but I haven't run into anything on develop with the defaults

**Comment by brtietz** [comment]
Yes, that was the only issue remaining. Thanks for making a PR!
