### ISSUE TITLE
BTM Battery Input Power Target Error

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#802]
To replicate:

1. Choose peak shaving with custom forecast.

2. Switch to input grid power targets.

3. Click simulate.

Tested with PV battery and standalone battery.

```
exec fail(battery): batt_pv_clipping_forecast forecast length is 1 when custom weather file forecast is selected. Change batt_dispatch_wf_forecast_choice or provide a forecast of at least length 8760.000000
Simulation battery failed :exec fail(battery): batt_pv_clipping_forecast forecast length is 1 when custom weather file forecast is selected. Change batt_dispatch_wf_forecast_choice or provide a forecast of at least length 8760.000000
monthly_grid_to_batt not assigned
Simulation cashloan failed :monthly_grid_to_batt not assigned
```

**Comment by brtietz** [comment]
This one is tricky. First, note that this issue also occurs for all other dispatch types, so the error in SSC needs to consider whether or not the forecast is relevant to the chosen dispatch.

Upon further inspection the forecast variables are relevant to the grid power targets option:

![image](https://user-images.githubusercontent.com/5530592/143958162-603db6c9-3a94-48a0-8f5c-9b209953e34b.png)

grid[i].Grid() is computed based on the PV and load forecasts, not the actual values.

You can test this by comparing input grid power targets run with a custom forecast (set on the peak shaving page as above) with perfect lookahead. Using a different weather file for the forecast decreases the NPV by ~20% for input grid power targets.

I think we have two options for a fix:

(1) Expose the forecast options for grid power targets (perhaps confusing)
(2) Refactor the dispatch to compare the actual values to the target, not just the forecasts.

If we do (2) I think it would make sense to apply that change to peak shaving as well - peak shaving would still use the forecasts when choosing targets, but the targets would be compared to the actual dispatch at each timestep, not just the forecast values.

**Comment by brtietz** [comment]
In SAM meeting on 11/30 we decided option 2 (refactor the dispatch) is the correct option.

**Comment by brtietz** [comment]
Additional issue: If one selects grid power target dispatch but does not define the targets (by clicking on the edit values option), the default array does not have the length required and the code throws an index out of bounds exception. For whatever reason this causes the release (as opposed to debug) version of SAM to plod along with whatever happens to be in memory for the array, leading to undefined behavior.

I'm inclined to add an exception if the array "batt_target_power_monthly" has a length != 12, but I'm open to other (complementary) options like defining a length 12 array in the defaults.

**Comment by cpaulgilman** [comment]
Sorry I didn't get to this sooner. The SSC exception is good.

As for defaults, a couple of questions:

1. Is our intention to set the defaults for large time series arrays  (8760 or greater) to a length of 1 to make the defaults files smaller? If so, we have not applied that consistently. For example `batt_target_power` is an 8760 array of ones for some configurations (PV Battery / Residential, etc.), and an array of a single zero for others (Standalone Battery / Third Party, etc.). For `batt_custom_dispatch`, the default for all configurations is an array of a single zero.

2. For the smaller monthly arrays, I think it's better to set the defaults to an array of 12 values. Otherwise the SSC error message is confusing if you click Edit Values to look at the monthly table and close the window without clicking **OK** because the widget makes it looks like the variable has 12 values.

**Comment by brtietz** [comment]
(1) Agreed that this is good practice and inconsistently implemented. If I made an issue to encourage us to audit this, should it be tagged for the patch or the 2022 release?

(2) Sounds good, I'll make a paired SAM PR with that change.

**Comment by brtietz** [comment]
Solved in the two PRs, above.
