### ISSUE TITLE
UI Editor crashing on MacOS 11.6.1 when editing forms

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#811]
Open UI Editor

Open any form

Move a control

Crash

**Comment by dguittet** [comment]
As background info, this has been the case for as long as I've been developing on Mac, so at least 2 years.

**Comment by sjanzou** [comment]
Fixed with wxWidgets 3.1.5 and in branches macOS_wx3.1.5 branches of all repos and tested on M1 Mac running macOS 12.0.1 and Intel based Mac running macOS 11.6.1

**Comment by sjanzou** [comment]
Closed with pull request #865
