### ISSUE TITLE
Help issues in 2021.11.30

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#816]
"Battery cell and system" directs to "Battery storage: behind the meter" regardless of financial model:

![image](https://user-images.githubusercontent.com/5530592/144108808-4fe87483-75f8-4634-b0c8-1c423167cfc2.png)

Should go to "battery storage: front of meter"

"Battery storage" page on fuel cell configurations does not have an associated help page:

![image](https://user-images.githubusercontent.com/5530592/144108999-74941ed9-5bec-461f-b8c7-987f987ec14b.png)

should direct to the BTM or FOM storage page as appropriate.

**Comment by cpaulgilman** [comment]
Good catches!

Item 1 is addressed in 7c43d37dc

Item 2 is addressed in 46489aa94
