### ISSUE TITLE
Generic Battery Upgrade to RC Crashes SAM

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#818]
Steps to reproduce:
1. Create a Generic-Battery/Single Owner case in SAM 2020.11.29
2. Save the case and open it in the current release candidate or on develop
3. Click simulate
4. SAM crashes

Note that the simulation does NOT crash when created new in the current release candidate or on develop, it's only with an upgrade.

**Comment by sjanzou** [comment]
Closed with pull request #825 
Issue with upgrading batt_dispatch_choice for all FOM battery configuration.
Details in attached document
[SAM issue 818.docx](https://github.com/NREL/SAM/files/7633067/SAM.issue.818.docx)
