### ISSUE TITLE
PV land area estimate should account for tilt angle and GCR

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#826]
PV land area estimate currently based on module surface area:

    Land Area Estimate = Total Module Area * Land Area Multiplier + Additional Land Area

This requires that the user adjust the land area multiplier when they change the GCR or tilt angle.

A more accurate estimate would take into account tilt angle and ground coverage ratio (GCR):

    Adjusted Module Area = Total Module Area / GCR * COSINE( Tilt Angle )

   Land Area Estimate = Adjusted Module Area * Land Area Multiplier + Additional Land Area

Note that PVWatts module area estimate currently includes GCR while Detailed PV does not.

Missing UI group label for PVWatts:

![image](https://user-images.githubusercontent.com/27711933/148848299-95606502-0412-4652-be39-0aa66faeea1b.png)

**Comment by cpaulgilman** [comment]
https://sam.nrel.gov/forum/forum-general/3721

**Comment by mjprilliman** [comment]
@cpaulgilman Just to clarify what is the order of operations on this?

`Adjusted Module Area = Total Module Area / GCR * COSINE( Tilt Angle )`
