### ISSUE TITLE
Allow custom forecasts for generic system

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#839]
Right now, if one attempts to select "custom weather file forecast" for generic system, SAM pops up an error, below:

![image](https://user-images.githubusercontent.com/5530592/144656471-0e3947d0-edbe-44bc-8ddc-b92cf8c1690b.png)

While this is strictly true, it could be useful to compare uncertainty in the generation input for generic systems as well (ex: a different wind generation profile than the one provided on the power plant page). The forecast input provided to ssc is the time series of ac powers, so there's no reason we couldn't provide that for generic system.

This would require creating a new input that takes a time series of powers, similar to the load input array. Discuss whether this is better to do a show/hide on the existing page or create a new page.

This doesn't require any changes to ssc, so it is an option for patch 1. No rush though.

**Comment by cpaulgilman** [comment]
The forecast based on custom weather file options for FOM and BTM battery dispatch is done in the run_forecast() function in the Battery Dispatch Common UI callback, which calls ssc_exec() on pvsamv1 to generate the time series forecast array for AC output and PV clipping. These forecast options currently only work for PV Battery configurations that have all the inputs necessary to run pvsamv1.

**Comment by cpaulgilman** [comment]
Revise Help description of FOM Look ahead to custom weather file when this gets addressed.

**Comment by brtietz** [comment]
Note typo in UI:

![image](https://user-images.githubusercontent.com/5530592/158273342-659741d4-a2a5-478f-9db1-a97cfdc549b2.png)

As Paul indicates above, we'll need a UI that specifies an 8760 of powers rather than a weather file to address this.

**Comment by cpaulgilman** [comment]
@brtietz We are using "production profile" on the Battery Dispatch page and "generation profile" on the generic system Power Plant page. I think we should use the same term for both -- I have a slight preference for "generation". Do you have a preference?

(We are also inconsistent in results with variable names like "System power generated," "Electricity generated without storage," "Energy produced in Year...," "Power produced without the battery or curtailment," etc. But that's something to address separately.)

**Comment by cpaulgilman** [comment]
I've made local changes to Help. I'll push those to this branch after I compare them to your UI changes.

**Comment by brtietz** [comment]
👍🏻 Just pushed the UI changes.
