### ISSUE TITLE
Add PV option to specify tilt angle as time series data

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#850]
SAM's PV models currently model fixed arrays with a constant tilt angle, and tracking arrays with surface angles calculated by the model in each time step based on the tilt and azimuth inputs and sun position.

For some modeling applications, it would be useful to be able to provide time series surface angles as input, for example to model advanced "smart" trackers, or misaligned trackers. The latter would make it possible to compare a system with misaligned trackers to one with "ideal" trackers, which would be useful for PV O&M teams to evaluate the impact of tracker problems on project economics.

Another approach would be to make the angle of incidence an input as suggested here: https://sam.nrel.gov/forum/forum-general/3702

See this feature request from June 2022: https://sam.nrel.gov/forum/forum-general/3914

**Comment by williamhobbs** [comment]
I'll add some additional thoughts on this. I've come across three specific cases related to misaligned trackers:

1. Trackers with a fixed angle offset, e.g., the tracker is consistently off of the ideal position by +3 degrees.
2. Trackers with a fixed time offset, e.g., the tracker control clock is 20 minutes behind. This is similar to a -5 degree fixed angle offset, but I think it would deviate from that, especially with backtracking.
3. Temporarily stuck trackers. 

I think all of these could be covered pretty easily through a time series surface angle input, for example, by running SAM once, exporting modeled or ideal surface tilt (`subarray1_axisrot` or `subarray1_idealrot`, I think), adjusting in an external tool (e.g., a spreadsheet), and the pasting the adjusted values back into SAM.

**Comment by mjprilliman** [comment]
Adding pvlib perspective on tracking capabilities from @kanderso-nrel: 
https://github.com/pvlib/pvlib-python/discussions/1581#discussioncomment-4060499

**Comment by mjprilliman** [comment]
@janinefreeman I think minimum viable product here is to use functionality for seasonal tilt (monthly inputs) applied to nrecords per year array of user-specified tilt angles. This treats user-specified tilt angles as fixed tilt category for shading and other downstream calculations. This would essentially extend track_mode options by 1, or allow for flexibility in array size for seasonal tilt input.

**Comment by mjprilliman** [comment]
Closing per https://github.com/NREL/ssc/pull/1071, outstanding work moved to #1543
