### ISSUE TITLE
How to tell SAM to load all the years downloaded at once?

### ISSUE THREAD

**Issue by leo-smi** [NREL/SAM#851]
I want to use all the files from 1998 to 2020 in my simulation, but I guess SAM only uses the selected one.
The files are download all in a separated folder, I thought SAM was using all, but when I click to see the data only shows one year at time.
Am I loosing something?
I'm asking because when I choose automatic download SAM downloads a file with many "random" years, some years are like 2020 or 2019 are not in the file...

1 - Image from the separated folder
![image](https://user-images.githubusercontent.com/20663547/145497804-81f7c33d-1b2b-4a2e-b5fa-8f7f5b2287ec.png)

2 - Image from the files
![image](https://user-images.githubusercontent.com/20663547/145497877-46a1a83e-d114-40ab-9456-1c4f47dacdf0.png)

3 - Image from SAM
![image](https://user-images.githubusercontent.com/20663547/145498027-a2693545-6fcc-41a8-aff8-0705949d9e49.png)

**Comment by cpaulgilman** [comment]
@leo-smi Thanks for posting your question here. This is the way SAM is designed to work. I have posted a reply to the [question you posted on the SAM forum](https://sam.nrel.gov/forum/forum-general/3699) and am closing this issue.
