### ISSUE TITLE
Transformer loss incorrectly calculated for DC-connected battery

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#856]
### Describe the bug

For PV-battery configurations with DC-connected batteries, with transformer losses specified, SAM calculates very large loss values.

![image](https://user-images.githubusercontent.com/27711933/145628107-deb47cef-3db1-4099-987f-0e01f5b53553.png)

A workaround is to assign the transformer loss input to the AC wiring loss category and set transformer loss inputs to zero.

https://sam.nrel.gov/forum/forum-general/3700

### To Reproduce

1. Create a default PV-Battery / Single Owner case.
2. On the Losses page set both the transformer load and no load loss values to 0.2%.
3. On the Battery Cell and System page, choose the DC Connected option.
4. Run.

### Expected behavior

Annual transformer loss percentage in results should be of similar magnitude as input percentages.

### Operating System and Version

SAM 2021.12.02, tested in Windows

**Comment by brtietz** [comment]
Closed with ssc 728
