### ISSUE TITLE
Default PPA price for CSP models too high

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#862]
In the process of switching from default Specify IRR target mode to Specify PPA price mode for SAM 2021.12.02, we forgot to change the default PPA price for CSP models. The default PPA price should be approximately equivalent to the PPA price that would result from the defaut IRR target.

@tyneises will check with the CSP team to see what an appropriate PPA price would be. Note LBL's "Utility-scale Research" page has a spreadsheet with trough and tower PPA prices over 2008 - 2021 on the "PPA Price for CSP Plants" worksheet, see the link to Utility-Scale Solar 2021 Edition Data File (XLSM) at the bottom of the page: https://emp.lbl.gov/utility-scale-solar

![image](https://user-images.githubusercontent.com/27711933/146579056-f27ea0be-7397-4724-a700-77361fc19a6e.png)

**Comment by tyneises** [comment]
closed in #904
