### ISSUE TITLE
Specifying a critical load on stand alone battery produces a callback error

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#864]
The grid page used by stand alone battery doesn't have the grid outage input, and the resiliency calculations variable is fixed to "calculate resiliency only for outage time steps," so specifying a critical load does not result in any change to the simulation outputs. This is case 5 in the help file.

Additionally, if one attempts to specify a critical load, one gets the error:

Could not evaluate callback function:crit_load_pct->on_change

> [45]: reference to unassigned variable:is_grid_outage
> [45]: error: _s
> [45]: error: _s
> [45]: error: _s
> [44]: eval error in statement list
> [44]: error inside function call
> [19]: eval error in statement list

There are three options to remedy this:

1. Add the grid outage input and enable the resiliency calculations, bringing the code in line with pv-battery and generic battery
2. Fix the resiliency calculations to "calculate for all timesteps" so that specifying a critical load triggers the resiliency runner
3. Disable the inputs for critical load

**Comment by mjprilliman** [comment]
I started taking steps toward option 1 in a patch branch but I was not sure if those type of changes could be included in a patch.
