### ISSUE TITLE
Allow pvlib column labels for solar weather files

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#866]
The variable name convention in the Python pvlib documentation is here:

https://pvlib-python.readthedocs.io/en/stable/variables_style_rules.html

SAM's weather file reader column names are defined here:

https://github.com/NREL/ssc/blob/632217258303cdbb77f471b517187b701f56d08e/shared/lib_weatherfile.cpp#L948

Modify lib_weatherfile.cpp to accept pvlib variable names.

**Comment by cpaulgilman** [comment]
[SSC PR 754](https://github.com/NREL/ssc/pull/754)  should resolve this issue.

@williamhobbs, let me know if you know of other labels to add to this list:

poa_global, temp_air, temp_dew, wind_speed, wind_direction, relative_humidity

**Comment by williamhobbs** [comment]
That looks like a complete list to me. Other variables (ghi, pressure, etc.) seem to already be covered. 

Thanks!
