### ISSUE TITLE
Monthly albedo error message unclear

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#868]
See https://sam.nrel.gov/forum/forum-general/3724 for a description and example file.

**Comment by dguittet** [comment]
@cpaulgilman What's the desired behavior or fix here? It seems like the original issue was that the values in the albedo widget weren't stored by using the "Ok" button. The file posted by the user also results in a Simulation error:

![image](https://user-images.githubusercontent.com/29387736/152009525-5e12d88f-4789-4d13-a778-0ff40eb60712.png)

**Comment by cpaulgilman** [comment]
@dguittet You are correct that this is an issue with the albedo input, not with the call to REopt. 

SAM displays this confusing SSC error message when an albedo value in the monthly input array is invalid (albedo <=0 or albedo >=1): "exec fail(pvsamv1): Error retrieving albedo value: Invalid month in weather file or invalid albedo value in weather file"

The message should say something like "Invalid albedo value x in monthly input array or weather file." I will make that change and do some additional testing.

**Comment by cpaulgilman** [comment]
@janinefreeman In the https://github.com/NREL/ssc/tree/pvsam_albedo_errors branch of SSC, I modifed pvsamv1 albedo errors to address this issue. I also changed the behavior for the weather file albedo option to throw an error if an albedo value is invalid instead of setting it to whatever the value in the monthly array is for that month because I think that behavior is not transparent. Do you agree with this change?
