### ISSUE TITLE
Unable to read data using SAM script

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#87]
It was reported in June 2017 that the user could not open an xslx file using a SAM lk script 
[Charac_aSiTriple28325.zip](https://github.com/NREL/SAM/files/2116694/Charac_aSiTriple28325.zip)

**Comment by dguittet** [comment]
The script should be changed from:

`xl_charac = xl_create();`	
`xl_open(xl_charac, filepath);`

to:

`xl_charac = xl_create(filepath);`

Then the rest of the script works as intended.
