### ISSUE TITLE
Location and Resource page layout and labels

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#874]
### Describe the bug

![image](https://user-images.githubusercontent.com/54449384/148427679-1e564ce1-28ea-4b61-9382-2eff5e4d5f57.png)
Seen in patch and 2021.12.2 release

**Comment by cpaulgilman** [comment]
Also:

1. Change "Station ID" to "Location" to avoid confusion that NSRDB grids are associated with a WMO weather station. See https://sam.nrel.gov/forum/forum-general/3004

2. Make Source text box wider so longer descriptions are more visible:

![image](https://user-images.githubusercontent.com/27711933/150237434-b8c01cec-1aa5-41b8-b196-516cf63ed166.png)
