### ISSUE TITLE
Invalid energy charge table with different numbers of tiers causes exec fail

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#875]
See email conversation below for description.

Example file:
[billing-demand-no-demand-charges.zip](https://github.com/NREL/SAM/files/7825302/billing-demand-no-demand-charges.zip)

Notes:

* Note that this issue about kWh/kW rates in only some months touches some of the same code: https://github.com/NREL/SAM/issues/857

* Workaround: Enable demand charges and set them all to 0.

* Check Help descriptions of the behavior of kWh/kW units for energy charges when this is ready.

> Paul,
> 
> The issue there is exclusively confined to the energy charge table, if I uncheck the billing demand options I still get the error. With the way SAM handles TOU rates and tiers (and likely the way that these are handled generally) the rate you’ve sent is invalid due to periods 1 and 2 having different numbers of tiers. I reformatted the rate to trigger the error I think you’re thinking about, below:
> 
> exec fail(utilityrate5): The ur_dc_billing_demand_periods matrix should have 0 rows, to match the number of TOU periods. Instead it has 2 rows.
> Simulation utilityrate5 failed :exec fail(utilityrate5): The ur_dc_billing_demand_periods matrix should have 0 rows, to match the number of TOU periods. Instead it has 2 rows.
> SSC requires input 'year1_hourly_ec_with_system', but was not found in the SAM UI or from previous simulations
> Simulation cashloan failed :precheck input: variable 'year1_hourly_ec_with_system' (Energy charge with system (year 1 hourly)) required but not assigned
> 
> I took a look at the code, and unfortunately the ur_dc_billing_demand_periods matrix is tied up in the billing demand calculations (which is a bug), so simply not throwing the error is not an option. Please file an issue, and I’ll add this to my list for patch 1 to fix.
> 
> Brian
> 
>
> Hi Brian,
> 
> The attached file uses kWh/kW units for a tiered energy rate. It causes an SSC error because the billing demand by TOU period table has a different number of periods than the TOU demand rate table for demand charges. However, demand charges are disabled.
> 
> Should this error be disabled when demand charges are disabled? If so, I can create an issue.
> 
> I could also make the UI text dynamic to suggest the correct number of rows and period numbers based on the demand charge table
> 
> Thanks,
> Paul.

**Comment by brtietz** [comment]
A question on solving this is what to do about the "ur_dc_billing_demand_periods" matrix in the case where only kWh/kW energy charges reference billing demand and there are no demand charges. Based on this PSO rate from the related issue: https://www.psoklahoma.com/lib/docs/ratesandtariffs/Oklahoma/PSO%20Commercial%20&%20Small%20Industrial%20April%202019.pdf it looks like it should be safe to assume the peak consumption during the month for the billing demand.

"The  Monthly  Maximum  demand  (kW)  and  the  monthly  maximum  kVAR  requirements  are  the  
highest  metered  kW  and  kVAR  occurring  during  the  month.    Metered  data  is  based  on  thirty  minute  
integrated periods measured by demand indicating meters. "

If there is a rate where peak consumption is only calculated off of certain energy charge periods, we can wait to add that feature after a user requests it. That addition would require a new input and is not appropriate for a patch, I don't want to repurpose  ur_dc_billing_demand_periods to look at energy charge periods.

**Comment by brtietz** [comment]
Closed in #889
