### ISSUE TITLE
Version upgrade script displays messages twice

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#876]
It looks like the version upgrader is listing the same message twice when it opens on old file?

[mpst-default-sam-2020-11-29r2.zip](https://github.com/NREL/SAM/files/7825379/mpst-default-sam-2020-11-29r2.zip)

Looking at the Version Control script, it’s not immediately obvious to me why this is happening.

![image](https://user-images.githubusercontent.com/27711933/148469427-8c023edf-d08e-4139-8b4a-e6e46f8ac796.png)

**Comment by cpaulgilman** [comment]
@sjanzou Could you look into this?

**Comment by sjanzou** [comment]
@cpaulgilman, one for dochub... duplicate version numbers in main.cpp cause duplicate messages in version upgrade script:
<img width="997" alt="image" src="https://user-images.githubusercontent.com/6498311/151942216-c298c2b4-bd90-4bfe-a227-1c3f0f026ac8.png">
