### ISSUE TITLE
Wind "Define Turbine Design Characteristics" option causes UI callback error

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#877]
### Describe the bug

For the Wind model, choosing the define turbine design characteristics option and changing some values causes a callback error.

https://sam.nrel.gov/forum/forum-general/3731

### To Reproduce

1. Create a Wind / Single Owner case.
2. On the Wind Turbine page, choose **Define turbine characteristics**.
3. Change **Maximum tip-speed ratio** to 6.8.
4. Press Enter or switch between **Select a turbine from library** and **Define turbine design characteristics**.

> equation engine: [32]: eval error in statement list\
> 
> fail: [wind_turbine_powercurve_windspeeds,wind_turbine_powercurve_powerout,wind_turbine_rated_wind_speed,wind_turbine_powercurve_err_msg,wind_turbine_powercurve_hub_efficiency] = f( wind.turbine.radio_list_or_design,wind_turbine_powercurve_windspeeds_from_lib,wind_turbine_powercurve_powerout_from_lib,wind_turbine_kw_rating_from_lib,wind_turbine_kw_rating_input,wind_turbine_rotor_diameter_input,wind_turbine_hub_ht,wind.turbine.elevation,wind_resource_model_choice,wind_turbine_max_cp,wind.turbine.max_tip_speed,wind.turbine.max_tspeed_ratio,wind_turbine_cutin,wind_turbine_cut_out,wind.turbine.drive_train )
> no variables calculated in a single iteration, cannot make progress!
> eqn not evaluated: [wind_turbine_powercurve_windspeeds,wind_turbine_powercurve_powerout,wind_turbine_rated_wind_speed,wind_turbine_powercurve_err_msg,wind_turbine_powercurve_hub_efficiency] = f( wind.turbine.radio_list_or_design,wind_turbine_powercurve_windspeeds_from_lib,wind_turbine_powercurve_powerout_from_lib,wind_turbine_kw_rating_from_lib,wind_turbine_kw_rating_input,wind_turbine_rotor_diameter_input,wind_turbine_hub_ht,wind.turbine.elevation,wind_resource_model_choice,wind_turbine_max_cp,wind.turbine.max_tip_speed,wind.turbine.max_tspeed_ratio,wind_turbine_cutin,wind_turbine_cut_out,wind.turbine.drive_train)

### Expected behavior

SAM should accept different values for parameters, and return a message if there are problems with the value.

### Screenshots

![image](https://user-images.githubusercontent.com/27711933/148609216-7cfb5c7a-a2ed-4a34-a962-86756565ade0.png)

### Operating System and Version

Tested in SAM 2021.12.02 on Windows 10

**Comment by grgmiller** [comment]
Just wanted to tag this issue: https://github.com/NREL/pysam/issues/107

This error seems to propagate through to PySAM and is causing the jupyter kernel to die, making PySAM unusable for certain wind turbine configurations. In my specific case, it was a value of rotor diameter that was raising this error.

**Comment by janinefreeman** [comment]
What if we throw a warning from the compute module if the power curve is zero? I don't think it necessarily needs to fail, but a warning that the power curve doesn't contain any values greater than zero could be helpful. Open to other suggestions.

**Comment by cpaulgilman** [comment]
That solution is partly helpful, but without digging into the code its hard to know what parameters are causing the problem. 

In his post on the SAM forum, Marc suggests that the parameters he entered are for a valid turbine design (Siemens SWT-6.0-154). I notice in the code that these equations calculate the air density from the elevation, which I think would come from the weather file. The default weather file is the "Southern WY" one with an elevation of 2,088 meters -- could that be the culprit if the equations are intended to work with a design air density value?

**Comment by mjprilliman** [comment]
> That solution is partly helpful, but without digging into the code its hard to know what parameters are causing the problem.
> 
> In his post on the SAM forum, Marc suggests that the parameters he entered are for a valid turbine design (Siemens SWT-6.0-154). I notice in the code that these equations calculate the air density from the elevation, which I think would come from the weather file. The default weather file is the "Southern WY" one with an elevation of 2,088 meters -- could that be the culprit if the equations are intended to work with a design air density value?

@cpaulgilman @janinefreeman Right now if the wind_resource_model_choice is not set to the Weibull distribution on the Wind Resource tab the elevation is passed as 0 (ignoring the hub height and turbine elevation inputs on the Wind Turbine page). Unless I'm missing something there's currently no link between the weather file elevation and the elevation that is passed to the equation. I can try to modify that behavior.

**Comment by dguittet** [comment]
The behavior of this equation has changed, making the `if ( omegaT > omega_m ) ` return early whereas in the past, it added the error but continued onward to make the power curve. I'm honestly not sure we need to keep this early-exit error if it's failing for reasonable inputs. I think instead of making it an error, we can make it just a warning.

**Comment by mjprilliman** [comment]
> The behavior of this equation has changed, making the `if ( omegaT > omega_m ) ` return early whereas in the past, it added the error but continued onward to make the power curve. I'm honestly not sure we need to keep this early-exit error if it's failing for reasonable inputs. I think instead of making it an error, we can make it just a warning:
> 
> ```
> if ( omegaT > omega_m ) {
>     sprintf( errmsg, "Warning: Turbine inputs may not be valid, please check the inputs. omegaT: %f, omegaM: %f", omegaT, omega_m );
>     vt->assign( "error", std::string(errmsg ));
> }
> ```

That's a good note, and I'm fine with removing the early-exit. I guess my concern was more if we are passing reasonable inputs as the elevation is being passed as 0 in a lot of cases which seems wrong but I'm not very familiar with the model.

**Comment by dguittet** [comment]
I think that was just the way it was done before, so I'm not sure why elevation was always 0. I'm not sure otherwise where to get an elevation number. I guess at the minimum, the elevation could be the hub height.

I can create an SSC PR.

**Comment by dguittet** [comment]
I just tried with a non-zero elevation, 100m, and it didn't fix the issue. So it may not be related to the elevation value.
