### ISSUE TITLE
Sometimes scrollbar in cash flow disappears

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#88]
When toggling between pages, the page scrollbars on the cashflow don't always appear.  To make them reappear, you can unmaximize and remaximize the window, which indicates this is probably an event issue.

**Comment by cpaulgilman** [comment]
Related issue from a user:

> I’m in PV, Detailed, Commercial Distributed and sometimes am not be able to see the bottom of the System Costs tab. I just clicked around to check other tabs, and when I returned to System Costs I could see the bottom. Just a heads up that it’s buggy I suppose. Thanks for all your work!

**Comment by cpaulgilman** [comment]
This is fixed. See https://github.com/NREL/SAM/issues/405.
