### ISSUE TITLE
Power Tower Cavity Receiver in Southern hemisphere optimizes heliostat field incorrectly

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#898]
### Describe the bug

For Southern Hemisphere locations, MSPT with cavity receiver optimizes heliostat field with more heliostats north of the tower than south. Note that external receiver works correctly.

### To Reproduce

1. Create a default MSPT / Single Owner case.
2. Use the Advanced Download option on the Location and Resource page to download a 60-min 2009 weather file for -28.3,23.07 (a location in Northern Cape Province in South Africa).
3. On the Heliostat Field page, click **Calculate** for **Optimize heliostat layout and tower dimensions** to optimize the field layout. 
4. When the optimization finishes, click **Yes** to update inputs and note distribution of heliostats south of the tower in the diagram.
5. On the Tower and Receiver page, change MSPT Receiver External to MSPT Receiver Cavity.
6. Repeat Steps 3 and 4, noting distribution of heliostats north of tower.

### Expected behavior

Cavity receiver option should work correctly for Southern Hemisphere locations.

### Screenshots

**Heliostat distribution for Southern Hemisphere location with cavity receiver:**
![image](https://user-images.githubusercontent.com/27711933/150886166-e51faaa2-8808-4cf3-bff7-4d61318e017b.png)

**External receiver:**
![image](https://user-images.githubusercontent.com/27711933/150886400-b5c1e403-2b6f-41b9-978b-89fb2397ff89.png)

**Comment by tyneises** [comment]
@qualand (can't figure out how to assign this to you...)
