### ISSUE TITLE
Stochastic simulations do not work in macOS

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#90]
For the default PV residential system, computing samples on module cost with NPV as output results in a notice like:

```
An error occured while computing the samples using LHS:

Could not read output file /var/folders/42/s5f72dmd16qdns9c1dcc_r_80000gn/T/SAMLHS.LSP
```

Tested on a Mid 2012 MacBook Pro running macOS High Sierra 10.13.14

**Comment by sjanzou** [comment]
Working with the latest release branch updates.
<img width="1099" alt="sam_issue_90" src="https://user-images.githubusercontent.com/6498311/47643735-f54aca80-db31-11e8-86f5-d19cf8767707.png">

**Comment by cpaulgilman** [comment]
Version 2018.11.11, 64 bit
SSC Version 200: OS X 64 bit GNU/C++ Nov 11 2018 01:54:20
wxWidgets 3.1.0 on OS X Version 10.13.6 (Build 17G3025)
Internet connection method: default
Display: 1366 x 768, magnification 1x

SAM was copied in the Application folder after opening the image and then registered.  The directory /var/folders/6n/rqvwszcd4t3gvn3dxhn2ccrw0000gn/T/ exists and is writable from my user.  The file SAMLHS.LSP don’t exist instead.

macOS generates a crash report every time I press “Run simulations” for the Stochastic option.

Contents of .crash file from a MacBook Air:

```
Process:               lhs.bin [25268]
Path:                  /Applications/SAM.app/Contents/runtime/bin/lhs.bin
Identifier:            lhs.bin
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        SAM [25254]
Responsible:           lhs.bin [25268]
User ID:               501

Date/Time:             2018-11-22 16:17:58.307 +0800
OS Version:            Mac OS X 10.13.6 (17G3025)
Report Version:        12
Anonymous UUID:        21726BC5-ADC9-7F58-8832-B2EBB75DD571

Sleep/Wake UUID:       3E239547-1FEC-4147-B83D-80E4EED1C1F2

Time Awake Since Boot: 58000 seconds
Time Since Wake:       310 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/gfortran/lib/libquadmath.0.dylib
  Referenced from: /Applications/SAM.app/Contents/runtime//bin/lhs.bin
  Reason: image not found

Binary Images:
       0x1040f2000 -        0x104159fef +lhs.bin (0) <97C22BC2-D2BD-3C91-9137-8F9DA558C018> /Applications/SAM.app/Contents/runtime/bin/lhs.bin
       0x1101b6000 -        0x110200acf  dyld (551.5) <30B355CB-35BA-3112-AA76-4E46CD45F699> /usr/lib/dyld
```

**Comment by WuMingIT** [comment]
Probably related: https://github.com/NREL/EnergyPlus/pull/6042#issuecomment-303450108

**Comment by sjanzou** [comment]
The issue is that the stochastic simulations require gfortran libraries. The gfortran is installed with gcc and is available at http://hpc.sourceforge.net/#fortran We hope to have more detailed information with the macOS installation instructions soon.

**Comment by cpaulgilman** [comment]
Updated installation instructions for Mac on SAM website: https://sam.nrel.gov/download/61-sam-2020-2-29-for-mac.html
