### ISSUE TITLE
Allow simulations including leap days

### ISSUE THREAD

**Issue by danielolsen** [NREL/SAM#917]
### Describe the solution you'd like

It would be great if SAM could produce outputs including leap days, if provided with input weather files that include leap days. Currently, it seems that SAM can accept weather files that include leap days (at least via PySAM, as of PySAM version 2.2.2), but that the outputs never have them. The following forum post seems to confirm this: https://sam.nrel.gov/forum/forum-general/3722-accounting-for-daylight-saving-time-dst-in-electricity-rates.html#10448

**Comment by janinefreeman** [comment]
Hi @danielolsen ! Thanks for the issue! This is definitely on our wishlist. We currently have it posted on the SSC repo, where the underlying algorithm lives: https://github.com/NREL/ssc/issues/604 . I'm closing this issue but will copy your comment over to the other issue to make note of the multiple requests for the feature!
