### ISSUE TITLE
Battery for Generic System missing battery cost input and lifetime simulation option

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#94]
I tried Generic system with Battery storage option.
- Enabling Battery bank replacement prompts to enable "PV simulation over analysis period"

![image](https://user-images.githubusercontent.com/27711933/44376602-2497e800-a4ae-11e8-8cc1-b27357127d3c.png)

One other thing I noticed, didn't see a way to enter Battery Bank costs for storage in system costs - is the Nameplate capacity intended for battery bank or the power plant capacity?  Maybe I'm missing something.

![image](https://user-images.githubusercontent.com/27711933/44376582-0fbb5480-a4ae-11e8-8a09-501a16902cfe.png)

**Comment by sjanzou** [comment]
Updated and checked into develop branches of ssc and SAM. Pending review from Nick and Paul.

**Comment by nickdiorio** [comment]
Verified that this works and is behaving as expected.
