### ISSUE TITLE
Problems to build SAM with Visual Studio 2013/2017

### ISSUE THREAD

**Issue by LudoGTA** [NREL/SAM#95]
Hello,

I would like to run SAM Open Source.
I have some problems for the following builds with VS 2013 :
- **Google Test** (gtest_unittest.cc)
4>..\..\test\gtest_unittest.cc(7600): fatal error C1903: unable to recover from previous error(s); stopping compilation
- **SSC** (lib_wind_obos.h)
'' 8>LINK : fatal error LNK1104: cannot open file 'C:\sam_dev\ssc\build_vs2013\x64\Debug\shared.lib'
9>LINK : fatal error LNK1104: cannot open file 'shared.lib' ''

With VS 2017 I have a single error with sam which is the last step of the build : MSB3073 Robocopy.
'' 1>Done building project "SAMnt_vs2017.vcxproj" -- FAILED. ''

Please find in attachment some screenshots and log of theses different problems.

Thank you in advance for your help,
Respectfully,

Ludovic

[SAM Errors with VS.zip](https://github.com/NREL/SAM/files/2311076/SAM.Errors.with.VS.zip)

**Comment by nickdiorio** [comment]
Hi @LudoGTA , thanks for reaching out, and sorry to hear you are having trouble.  We will be investigating additional ways to make the build process easier.

To address your issues, I'd say let's concentrate on VS2017, as that's the version that we support the most.

The errors you are seeing in VS2017 result from a post build event trying to copy libcurl libraries from the `wex` project into `sam`.  Can you confirm whether or not files exist within `C:\sam_dev\wex\build_vs2017\libcurl_ssl_x64\bin` and whether the directory `C:\sam_dev\sam\deploy\x64\ ` exists?  If both locations exist, you can verify whether the contexts of the libcurl directory has indeed been copied to the sam directory.  If not, try manually copying the files.

I will see if I can reproduce on my local environment, the issue may be with the timing of certain build events, as described in: [https://stackoverflow.com/questions/17075279/how-do-i-fix-msb3073-error-in-my-post-build-event](url)
