### ISSUE TITLE
Add Capacity Payment Defaults to More Technologies?

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#955]
We should consider updating the capacity payment defaults from zero for a variety of technologies, based on current industry trends. See spreadsheet in sam-documentation/Defaults References and Tools/Capacity_value_methods.xlsx for additional thoughts.

**Comment by cpaulgilman** [comment]
See also https://github.com/NREL/SAM/issues/955

**Comment by brtietz** [comment]
I would love to use an NREL source for this, but the Cambium data defines the capacity costs at a system level, not at a plant level: https://www.nrel.gov/docs/fy22osti/81611.pdf, and the spreadsheet in developer tools includes a lot of references that predate the deployment of Li-Ion batteries for this purpose.

This EIA source seems reasonable, and would suggest a value of $54,000 /MW-yr for batteries: https://www.eia.gov/outlooks/aeo/IIF_battery/

Thoughts on whether this year's update should be for just batteries or more technologies?

**Comment by brtietz** [comment]
https://github.com/NREL/SAM/pull/1258 added capacity payment defaults to relevant stand alone batteries. Closing this issue for this release. We should continue to review capacity payment defaults along with other revenue defaults, especially after https://github.com/NREL/SAM/issues/635 is completed.
