### ISSUE TITLE
Add options for sub-hourly data in WIND Toolkit downloads

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#962]
### Is your feature request related to a problem? Please describe.

The WIND Toolkit includes data in 5, 15, 30, and 60 minute intervals, but only 60 minute data is available through the SAM GUI download utility. 

### Describe the solution you'd like

Adding the option to download 5, 15, and 30 minute interval wind resource data through the SAM download GUI.

### Describe alternatives you've considered

Users can manually download sub-hourly data, reformat it, and import it into SAM.

### Additional context

The solar NSRDB download options are more robust and have the type of functionality that is being requested here for the wind portion of SAM.

This data is available through the ["regular" API](https://developer.nrel.gov/docs/wind/wind-toolkit/wtk-download/), but not the [SAM format API](https://developer.nrel.gov/docs/wind/wind-toolkit/wtk-srw-download/). So, I think data reformatting may be required.

**Comment by cpaulgilman** [comment]
This is related to https://github.com/NREL/SAM/issues/815

**Comment by cpaulgilman** [comment]
Would also be helpful for wind data files to include time stamp data (year,month,day,hour,minute) similar to NSRDB files.

**Comment by williamhobbs** [comment]
I've realized that this issue applies to PySAM as well since it also uses .srw files for wind projects.

**Comment by cpaulgilman** [comment]
Any changes to WIND Toolkit downloads also requires updating sample LK script and PySAM resource tools script.
