### ISSUE TITLE
Enable albedo in parametric simulations

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#97]
Per request at Bifacial workshop, we should enable the albedo variables for parametric analysis.

**Comment by cpaulgilman** [comment]
Note that albedo is an array of monthly values, so tricky to work with as parametric input.

Also need to investigate albedo data available with NSRDB PSM V3 data. If data is available, we could move "use albedo from weather file if available" checkbox to be more visible, and check it by default if albedo data is available in weather file. User can clear checkbox to use monthly values instead, although that will be tricky with parametrics, and require redesigning the monthly albedo input user interface a bit.

**Comment by nickdiorio** [comment]
Should be done, need to test
