### ISSUE TITLE
Change in battery charging from fuel cell in 2021.12.02 r1

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#977]
### Describe the bug

In the 2021.12.02 revision 1 release, there appears to be a bug where batteries do not charge correctly from fuel cells. _Electricity to battery from fuel cell_ is almost zero in all hours, where it is frequently very high (as expected) in the original 2021.12.02 release.

### To Reproduce

1. In 2021.12.2 (original, rev 0) Create a new *Fuel Cell, Commercial* case
2. Enable the battery
3. Change fuel cell unit nameplate to 50 kW (probably not necessary)
4. Set fuel cell annual degradation to 0% (probably not necessary)
5. Start simulation with fuel cell operating = true (probably not necessary)
6. Set battery dispatch to "input grid power targets" with monthly values all set to 0
7. Enable "battery can charge from fuel cell"
8. Simulate
9. View _Electricity to battery from fuel cell_ in Time series results (looks as expected):
![image](https://user-images.githubusercontent.com/45701090/157149534-e2700dba-c7b8-4102-bde9-b547686bb1e4.png)

10. Repeat 1-9 in 2021.12.2 r1 (note small y axis):
![image](https://user-images.githubusercontent.com/45701090/157149589-f853fd30-339e-4d50-861f-d7bfec3ff0c1.png)

11. (optional) Save project file from step 9, open in 2021.12.2 r1, and see that results are slightly different from step 10 (not sure if this is a second bug, since there were no notices that something was changed when opening the file):
![image](https://user-images.githubusercontent.com/45701090/157149776-48bb979b-5b62-459f-b01a-ef23e35b9f35.png)

### Expected behavior

See step 9 output above. It is expected that the battery will get meaningful amounts of electricity from the fuel cell. 

### Screenshots

See above.

### Operating System and Version

 - OS: Windows
 - Version: SAM 2021.12.2 r1 (compared with 2021.12.2)

### Additional context

I was originally trying to use the new Grid Outage functionality when I came across this issue. Results in 2021.12.2 r1 using Grid Outage (critical load 100% of electric load, Grid outage array = 1 in all timesteps) were substantially different from results in 2021.12.2 with battery dispatch set to "input grid power targets" with monthly values all set to 0, even these should have similar dispath objectives.

**Comment by brtietz** [comment]
@williamhobbs Thanks for reporting this! We had a pretty significant change to the peak shaving/grid power target family of dispatch modes in the patch - they now use the actual grid power at each timestep instead of the forecast grid power. You can see more details here: https://github.com/NREL/ssc/pull/683/

It looks like I missed the fuel cell power in a key equation - that'll be fixed for patch 2.

**Comment by brtietz** [comment]
Closed in https://github.com/NREL/ssc/pull/780
