### ISSUE TITLE
Report Year 1 hourly 1 outputs as lifetime hourly to facilitate intepreting time series results in out years

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#978]
### Is your feature request related to a problem? Please describe.

For models with lifetime simulations, such as Detailed PV and PV Battery, some outputs are reported as "Hourly Data" for Year 1 only, and others are reported as "Lifetime Hourly Data" over the analysis period. This can make it difficult to interpret or troubleshoot results in out years (Years 2 and greater). 

At a minimum, changing the following from Year 1 to lifetime would help address the question in https://sam.nrel.gov/forum/forum-general/3782:

* Battery capacity percent for temperature
* Battery temperature

Additional variables to consider as a partial solution would be

* Irradiance data (particularly DHI and DNI)
* Ambient temperature

See also this post on the SAM forum regarding "system power generated" and "electricity from grid" in lifetime vs year 1 outputs: 

https://sam.nrel.gov/forum/forum-general/3795

### Describe the solution you'd like

Show all time series outputs as lifetime variables.

### Additional context

Need to consider potential memory or graph display issues.

"Hourly Data" includes time stamps when viewed on Data Tables tab. "Lifetime Hourly Data" shows row number. Would be nice to show time stamps for lifetime hourly data.

On Time Series graph, there is no indication of year in x-axis labels, so it can be difficult to tell where you are in the time series when the graph is zoomed in.

### Related issues

https://github.com/NREL/SAM/issues/289

https://github.com/NREL/SAM/issues/99

https://github.com/NREL/SAM/issues/204

**Comment by brtietz** [comment]
Closed in ssc 791
