### ISSUE TITLE
Ensure all techs with a time series have availablity losses

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#985]
We noticed on 3/15/22 that the wind losses page is missing the hourly availability input. Check the other techs to see if it is missing elsewhere, and add it to the appropriate categories.

**Comment by janinefreeman** [comment]
This input is also missing from: standalone battery; marine wave, wave+battery, and tidal (have a flat rate availability input instead).

Fuel cell and battery both don't have their own availability loss, which is true of all hybrid configs containing these two.

For further discussion at the next SAM meeting.

**Comment by janinefreeman** [comment]
Discussed creating a specific UI page for the availability losses, and allowing them to be applied to each component of a system (i.e. PV would have a separate availability loss than batteries).

**Comment by brtietz** [comment]
A note on the availability losses in batteries: Essentially, the availability loss puts a giant resistor between the battery and the load, and burns a percentage of the energy in each timestep. In reality, an availability loss for the battery would knock out part of the battery’s power or energy capacity, but if the battery discharged 3 kW for an hour, 3 kWh from the storage would be depleted. Right now a 10% availability loss would discharge an additional 0.3 kWh.

Clean this up as a part of this issue.

**Comment by janinefreeman** [comment]
Related #1247

**Comment by mjprilliman** [comment]
https://github.com/NREL/SAM/issues/1247 tracking for wave, tidal, wave battery.

**Comment by brtietz** [comment]
https://github.com/NREL/SAM/issues/1868 for wind
https://github.com/NREL/SAM/issues/1869 for batteries (may include adjustments to PVsamv1)
https://github.com/NREL/SAM/issues/1870 for fuel cells
