### ISSUE TITLE
First install NSRDB download fails

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#995]
1. Download and install a version of SAM that has not been registered on your computer
2. Register SAM, click "Confirm"
3. Go to Solar Resource page and try to download a weather file

error "The required 'email' parameter must be a valid email address."

The workaround is to close SAM after registering and then download a weather file.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/6498311/161019841-c731c0a2-6bd9-4f6e-8f84-3e1425c488de.png">

**Comment by sjanzou** [comment]
Related forum post https://sam.nrel.gov/forum/forum-sdk/3816

**Comment by sjanzou** [comment]
Fixed in SAM-private pull request 66 https://github.com/NREL/SAM-private/pull/66

**Comment by janinefreeman** [comment]
Closed in sam-private

**Comment by williamhobbs** [comment]
I just had this occur with a fresh install of the latest version (2022.11.21). I got the error when trying to download from NSRDB the first time I opened SAM, then it worked fine after restarting the program. Is that a new issue?

![image](https://user-images.githubusercontent.com/45701090/210900820-8f1d5c6e-dcae-4303-9936-eec130a15d03.png)

**Comment by sjanzou** [comment]
> I just had this occur with a fresh install of the latest version (2022.11.21). I got the error when trying to download from NSRDB the first time I opened SAM, then it worked fine after restarting the program. Is that a new issue?
> 
> ![image](https://user-images.githubusercontent.com/45701090/210900820-8f1d5c6e-dcae-4303-9936-eec130a15d03.png)

@williamhobbs, this is the same issue that was fixed and then reintroduced when the build process on Windows was simplified for building the open source and release version of SAM. The issue is reopened and will be fixed in patch 1 coming out by mid February.

**Comment by sjanzou** [comment]
Fixed in SAM-private pull request https://github.com/NREL/SAM-private/pull/81
