### ISSUE TITLE
Storage media selection in IPH Trough model 

### ISSUE THREAD

**Issue by joeyhu1985** [NREL/SAM#998]
is it possible to add a function that allow users to select storage media in IPH Trough model? this function already been implemented in Trough(phys) model, sometimes we want to simulate cases which HTF in solar field wiil not be the same as in storage for some reasons.

**Comment by cpaulgilman** [comment]
The current implementation of the parabolic trough model for industrial process heat applications includes thermal energy storage (TES), but only for a TES system that uses the same heat transfer fluid (HTF) as the solar field. This request is to add an option to choose a different storage fluid than the solar field HTF.

**Comment by Matthew-Boyd** [comment]
This wasn't on our to-do list but I'll see if we can get to it in the coming months. Thanks for pointing this out.

**Comment by cpaulgilman** [comment]
IPH Trough with storage is available in SAM 2023.12.17
